import {
	HUMAN_RESOURCES_COMPENSATION_BENEFITS_COMMANDS,
	HUMAN_RESOURCES_COMPENSATION_BENEFITS_QUERIES,
} from "../compensation-benefits/operation-registry";
import {
	HUMAN_RESOURCES_COMPLIANCE_COMMANDS,
	HUMAN_RESOURCES_COMPLIANCE_QUERIES,
} from "../compliance/operation-registry";
import {
	HUMAN_RESOURCES_EMPLOYEE_RELATIONS_COMMANDS,
	HUMAN_RESOURCES_EMPLOYEE_RELATIONS_QUERIES,
} from "../employee-relations/operation-registry";
import {
	HUMAN_RESOURCES_EMPLOYMENT_LIFECYCLE_COMMANDS,
	HUMAN_RESOURCES_EMPLOYMENT_LIFECYCLE_QUERIES,
} from "../employment-lifecycle/operation-registry";
import { HUMAN_RESOURCES_PAYROLL_HANDOFF_QUERIES } from "../handoff/operation-registry";
import { HUMAN_RESOURCES_HIRE_ORCHESTRATION_COMMANDS } from "../hire-orchestration/operation-registry";
import {
	HUMAN_RESOURCES_LEARNING_COMMANDS,
	HUMAN_RESOURCES_LEARNING_QUERIES,
} from "../learning/operation-registry";
import {
	HUMAN_RESOURCES_LEAVE_COMMANDS,
	HUMAN_RESOURCES_LEAVE_QUERIES,
} from "../leave/operation-registry";
import {
	HUMAN_RESOURCES_ORGANIZATION_COMMANDS,
	HUMAN_RESOURCES_ORGANIZATION_QUERIES,
} from "../organization/operation-registry";
import {
	HUMAN_RESOURCES_PERFORMANCE_COMMANDS,
	HUMAN_RESOURCES_PERFORMANCE_QUERIES,
} from "../performance/operation-registry";
import {
	HUMAN_RESOURCES_PRIVACY_COMMANDS,
	HUMAN_RESOURCES_PRIVACY_QUERIES,
} from "../privacy/operation-registry";
import {
	HUMAN_RESOURCES_RECRUITMENT_COMMANDS,
	HUMAN_RESOURCES_RECRUITMENT_QUERIES,
} from "../recruitment/operation-registry";
import {
	HUMAN_RESOURCES_TALENT_COMMANDS,
	HUMAN_RESOURCES_TALENT_QUERIES,
} from "../talent/operation-registry";
import {
	HUMAN_RESOURCES_ATTENDANCE_COMMANDS,
	HUMAN_RESOURCES_ATTENDANCE_QUERIES,
	HUMAN_RESOURCES_OVERTIME_COMMANDS,
	HUMAN_RESOURCES_OVERTIME_HANDOFF_QUERIES,
	HUMAN_RESOURCES_SHIFT_SCHEDULING_COMMANDS,
	HUMAN_RESOURCES_SHIFT_SCHEDULING_QUERIES,
	HUMAN_RESOURCES_TIME_POLICY_COMMANDS,
	HUMAN_RESOURCES_TIME_POLICY_QUERIES,
	HUMAN_RESOURCES_TIMESHEET_COMMANDS,
	HUMAN_RESOURCES_TIMESHEET_QUERIES,
	HUMAN_RESOURCES_WORK_CALENDAR_COMMANDS,
	HUMAN_RESOURCES_WORK_CALENDAR_QUERIES,
} from "../time/operation-registry";
import {
	HUMAN_RESOURCES_WORKFORCE_FOUNDATION_COMMANDS,
	HUMAN_RESOURCES_WORKFORCE_FOUNDATION_QUERIES,
} from "../workforce-foundation/operation-registry";
import {
	HUMAN_RESOURCES_WORKFORCE_PLANNING_COMMANDS,
	HUMAN_RESOURCES_WORKFORCE_PLANNING_QUERIES,
} from "../workforce-planning/operation-registry";
import { composeHumanResourcesOperationRegistries } from "./define-registry";
import type { HumanResourcesOperationDefinition } from "./types";

export const HUMAN_RESOURCES_REGISTERED_OPERATION_DEFINITIONS =
	composeHumanResourcesOperationRegistries(
		HUMAN_RESOURCES_WORKFORCE_FOUNDATION_COMMANDS,
		HUMAN_RESOURCES_WORKFORCE_FOUNDATION_QUERIES,
		HUMAN_RESOURCES_EMPLOYMENT_LIFECYCLE_COMMANDS,
		HUMAN_RESOURCES_EMPLOYMENT_LIFECYCLE_QUERIES,
		HUMAN_RESOURCES_EMPLOYEE_RELATIONS_COMMANDS,
		HUMAN_RESOURCES_EMPLOYEE_RELATIONS_QUERIES,
		HUMAN_RESOURCES_COMPLIANCE_COMMANDS,
		HUMAN_RESOURCES_COMPLIANCE_QUERIES,
		HUMAN_RESOURCES_LEAVE_COMMANDS,
		HUMAN_RESOURCES_LEAVE_QUERIES,
		HUMAN_RESOURCES_LEARNING_COMMANDS,
		HUMAN_RESOURCES_LEARNING_QUERIES,
		HUMAN_RESOURCES_COMPENSATION_BENEFITS_COMMANDS,
		HUMAN_RESOURCES_COMPENSATION_BENEFITS_QUERIES,
		HUMAN_RESOURCES_PAYROLL_HANDOFF_QUERIES,
		HUMAN_RESOURCES_HIRE_ORCHESTRATION_COMMANDS,
		HUMAN_RESOURCES_ORGANIZATION_COMMANDS,
		HUMAN_RESOURCES_ORGANIZATION_QUERIES,
		HUMAN_RESOURCES_PERFORMANCE_COMMANDS,
		HUMAN_RESOURCES_PERFORMANCE_QUERIES,
		HUMAN_RESOURCES_PRIVACY_COMMANDS,
		HUMAN_RESOURCES_PRIVACY_QUERIES,
		HUMAN_RESOURCES_TALENT_COMMANDS,
		HUMAN_RESOURCES_TALENT_QUERIES,
		HUMAN_RESOURCES_RECRUITMENT_COMMANDS,
		HUMAN_RESOURCES_RECRUITMENT_QUERIES,
		HUMAN_RESOURCES_WORK_CALENDAR_COMMANDS,
		HUMAN_RESOURCES_WORK_CALENDAR_QUERIES,
		HUMAN_RESOURCES_TIME_POLICY_COMMANDS,
		HUMAN_RESOURCES_TIME_POLICY_QUERIES,
		HUMAN_RESOURCES_SHIFT_SCHEDULING_COMMANDS,
		HUMAN_RESOURCES_SHIFT_SCHEDULING_QUERIES,
		HUMAN_RESOURCES_ATTENDANCE_COMMANDS,
		HUMAN_RESOURCES_ATTENDANCE_QUERIES,
		HUMAN_RESOURCES_TIMESHEET_COMMANDS,
		HUMAN_RESOURCES_TIMESHEET_QUERIES,
		HUMAN_RESOURCES_OVERTIME_COMMANDS,
		HUMAN_RESOURCES_OVERTIME_HANDOFF_QUERIES,
		HUMAN_RESOURCES_WORKFORCE_PLANNING_COMMANDS,
		HUMAN_RESOURCES_WORKFORCE_PLANNING_QUERIES,
	);

export const HUMAN_RESOURCES_REGISTERED_OPERATION_DEFINITION_RECORD =
	Object.freeze(
		Object.fromEntries(
			HUMAN_RESOURCES_REGISTERED_OPERATION_DEFINITIONS.map((definition) => [
				definition.id,
				definition,
			]),
		),
	) as Readonly<
		Record<
			HumanResourcesOperationDefinition["id"],
			HumanResourcesOperationDefinition
		>
	>;

export function getHumanResourcesOperationDefinition(
	operationId: HumanResourcesOperationDefinition["id"],
): HumanResourcesOperationDefinition {
	const definition =
		HUMAN_RESOURCES_REGISTERED_OPERATION_DEFINITION_RECORD[operationId];
	if (definition === undefined) {
		throw new Error(`Unknown Human Resources operation: ${operationId}`);
	}
	return definition;
}
