import {
	HUMAN_RESOURCES_EMPLOYMENT_LIFECYCLE_COMMANDS,
	HUMAN_RESOURCES_EMPLOYMENT_LIFECYCLE_QUERIES,
} from "../employment-lifecycle/operation-registry";
import {
	HUMAN_RESOURCES_ORGANIZATION_COMMANDS,
	HUMAN_RESOURCES_ORGANIZATION_QUERIES,
} from "../organization/operation-registry";
import {
	HUMAN_RESOURCES_WORKFORCE_FOUNDATION_COMMANDS,
	HUMAN_RESOURCES_WORKFORCE_FOUNDATION_QUERIES,
} from "../workforce-foundation/operation-registry";
import { composeHumanResourcesOperationRegistries } from "./define-registry";

export const HUMAN_RESOURCES_REGISTERED_OPERATION_DEFINITIONS =
	composeHumanResourcesOperationRegistries(
		HUMAN_RESOURCES_WORKFORCE_FOUNDATION_COMMANDS,
		HUMAN_RESOURCES_WORKFORCE_FOUNDATION_QUERIES,
		HUMAN_RESOURCES_EMPLOYMENT_LIFECYCLE_COMMANDS,
		HUMAN_RESOURCES_EMPLOYMENT_LIFECYCLE_QUERIES,
		HUMAN_RESOURCES_ORGANIZATION_COMMANDS,
		HUMAN_RESOURCES_ORGANIZATION_QUERIES,
	);
