import "server-only";

export {
	type MasterAuthorizationPort,
	type MasterPermission,
	requireMasterCommandPermission,
	requireMasterQueryPermission,
} from "./authorization";
export {
	type ChangeRequestId,
	changeRequestIdSchema,
	type ItemGroupId,
	type ItemId,
	type ItemTemplateAttributeId,
	type ItemTemplateAttributeOptionId,
	type ItemTemplateId,
	type ItemVariantId,
	itemGroupIdSchema,
	itemIdSchema,
	itemTemplateAttributeIdSchema,
	itemTemplateAttributeOptionIdSchema,
	itemTemplateIdSchema,
	itemVariantIdSchema,
	type PartyId,
	type PaymentTermId,
	partyIdSchema,
	paymentTermIdSchema,
	type TaxRegistrationId,
	taxRegistrationIdSchema,
	type WarehouseId,
	warehouseIdSchema,
} from "./brands";
export {
	coreMasterDependencyBlocked,
	coreMasterNotFound,
} from "./capabilities/core-organization-masters/core-master-errors";
export type {
	ItemGroupLifecycleEventSuffix,
	ItemLifecycleEventSuffix,
	ItemTemplateLifecycleEventSuffix,
	PartyLifecycleEventSuffix,
	PaymentTermLifecycleEventSuffix,
	TaxRegistrationLifecycleEventSuffix,
	WarehouseLifecycleEventSuffix,
} from "./capabilities/core-organization-masters/core-master-events";
export {
	type CoreMasterUsability,
	evaluateItemTemplateUsability,
	evaluateItemUsability,
	evaluateItemVariantUsability,
	evaluateMasterStatus,
	evaluatePartyUsability,
	evaluatePaymentTermUsability,
	evaluateTaxRegistrationUsability,
	evaluateWarehouseUsability,
} from "./capabilities/core-organization-masters/core-master-policy";
export {
	existsItemByCode,
	getItemByCode,
	getItemById,
	listActiveItems,
	listItems,
	listItemsByGroup,
	listItemsByStatus,
	listItemsUpdatedSince,
} from "./capabilities/core-organization-masters/item";
export type { ItemGroupPath } from "./capabilities/core-organization-masters/item-group";
export {
	existsItemGroupByCode,
	getItemGroupByCode,
	getItemGroupById,
	listActiveItemGroups,
	listItemGroups,
	listItemGroupsByStatus,
	listItemGroupsUpdatedSince,
	resolveItemGroupPath,
} from "./capabilities/core-organization-masters/item-group";
export {
	assertLifecycleTransition,
	assertRestoreTransition,
	assertTaxRegistrationLifecycleTransition,
} from "./capabilities/core-organization-masters/lifecycle";
export {
	MAX_MASTER_CODE_LENGTH,
	normalizeEmail,
	normalizeExternalIdValue,
	normalizeMasterCode,
	normalizePhone,
	normalizeSearchText,
} from "./capabilities/core-organization-masters/normalized-code";
export {
	createOrganizationDimensionInputSchema,
	getOrganizationDimensionByCodeInputSchema,
	getOrganizationDimensionByIdInputSchema,
	getOrganizationDimensionEffectiveInputSchema,
	listOrganizationDimensionsInputSchema,
	ORGANIZATION_DIMENSION_KINDS,
	type OrganizationDimension,
	type OrganizationDimensionKind,
	type OrganizationDimensionReference,
	organizationDimensionLifecycleInputSchema,
	resolveOrganizationDimensionsAsOfInputSchema,
	updateOrganizationDimensionInputSchema,
} from "./capabilities/core-organization-masters/organization-dimension";
export {
	existsPartyByCode,
	findPartyByTaxRegistration,
	getParty,
	getPartyByCode,
	getPartyById,
	listActiveParties,
	listParties,
	listPartiesByRole,
	listPartiesByStatus,
	listPartiesUpdatedSince,
	searchParties,
} from "./capabilities/core-organization-masters/party";
export {
	existsPaymentTermByCode,
	getPaymentTermByCode,
	getPaymentTermById,
	listActivePaymentTerms,
	listPaymentTerms,
	listPaymentTermsByStatus,
	listPaymentTermsUpdatedSince,
} from "./capabilities/core-organization-masters/payment-term";
export {
	activatePartyInputSchema,
	addItemTemplateAttributeInputSchema,
	addItemTemplateAttributeOptionInputSchema,
	type CreateItemGroupInput,
	type CreateItemInput,
	type CreateItemTemplateInput,
	type CreateItemVariantInput,
	type CreatePartyInput,
	type CreatePaymentTermInput,
	type CreateTaxRegistrationInput,
	type CreateWarehouseInput,
	createItemGroupInputSchema,
	createItemInputSchema,
	createItemTemplateInputSchema,
	createItemVariantInputSchema,
	createPartyInputSchema,
	createPaymentTermInputSchema,
	createTaxRegistrationInputSchema,
	createWarehouseInputSchema,
	DEFAULT_MASTER_PAGE,
	DEFAULT_MASTER_PAGE_SIZE,
	findPartyByTaxRegistrationInputSchema,
	findTaxRegistrationsByPartyInputSchema,
	getByCodeInputSchema,
	getByIdInputSchema,
	itemGroupLifecycleInputSchema,
	itemLifecycleInputSchema,
	itemTemplateLifecycleInputSchema,
	listByStatusInputSchema,
	listItemsByGroupInputSchema,
	listItemTemplateAttributeOptionsInputSchema,
	listItemTemplateAttributesInputSchema,
	listItemVariantsByTemplateInputSchema,
	listPartiesByRoleInputSchema,
	listTaxRegistrationsInputSchema,
	listUpdatedSinceInputSchema,
	MAX_MASTER_PAGE_SIZE,
	type MasterListQuery,
	type MoveWarehouseInput,
	masterListOptionsSchema,
	moveWarehouseInputSchema,
	partyLifecycleInputSchema,
	paymentTermLifecycleInputSchema,
	retireItemVariantInputSchema,
	searchPartiesInputSchema,
	taxRegistrationLifecycleInputSchema,
	type UpdateItemGroupInput,
	type UpdateItemInput,
	type UpdateItemTemplateInput,
	type UpdatePartyInput,
	type UpdatePaymentTermInput,
	type UpdateTaxRegistrationInput,
	type UpdateWarehouseInput,
	updateItemGroupInputSchema,
	updateItemInputSchema,
	updateItemTemplateInputSchema,
	updatePartyInputSchema,
	updatePaymentTermInputSchema,
	updateTaxRegistrationInputSchema,
	updateWarehouseInputSchema,
	warehouseLifecycleInputSchema,
} from "./capabilities/core-organization-masters/schemas";
export {
	findSensitiveTaxRegistrationsByParty,
	findTaxRegistrationsByParty,
	getSensitiveTaxRegistration,
	getTaxRegistration,
	listSensitiveTaxRegistrations,
	listTaxRegistrations,
	listTaxRegistrationsUpdatedSince,
} from "./capabilities/core-organization-masters/tax-registration";
export {
	maskTaxRegistrationNumber,
	normalizeTaxRegistrationNumber,
	projectTaxRegistrationLifecycleStatus,
	type SensitiveTaxRegistrationProjection,
	TAX_REGISTRATION_LIFECYCLE_STATUSES,
	type TaxRegistrationLifecycleStatus,
	type TaxRegistrationProjection,
	type TaxRegistrationStatus,
	toSensitiveTaxRegistrationProjection,
	toTaxRegistrationProjection,
} from "./capabilities/core-organization-masters/tax-registration-number";
export {
	isInvalidValidityRange,
	validityRangesOverlap,
} from "./capabilities/core-organization-masters/validity-overlap";
export {
	buildCombinationKey,
	normalizeAttributeValueText,
} from "./capabilities/core-organization-masters/variant-signature";
export {
	assertExpectedVersion,
	nextMasterVersion,
	type VersionedMaster,
} from "./capabilities/core-organization-masters/version-cas";
export {
	existsWarehouseByCode,
	getWarehouseByCode,
	getWarehouseById,
	listActiveWarehouses,
	listWarehouses,
	listWarehousesByStatus,
	listWarehousesUpdatedSince,
} from "./capabilities/core-organization-masters/warehouse";
export * from "./capabilities/data-governance-workflows";
export { normalizePartyContactValue } from "./capabilities/extensions/contact-normalization";
export type {
	ExtensionDependencyBehavior,
	ExtensionLifecycleTransition,
	ExtensionParentStateRequirement,
} from "./capabilities/extensions/extension-lifecycle";
export {
	assertExtensionTransitionReason,
	assertStandardChildLifecycleStatus,
	EXTENSION_LIFECYCLE_FAMILY_BY_KIND,
	EXTENSION_LIFECYCLE_PERMISSION_BY_KIND,
	EXTENSION_LIFECYCLE_TRANSITIONS,
	isStandardChildLifecycleStatus,
	parseStandardChildLifecycleStatus,
	resolveExtensionLifecycleTransition,
} from "./capabilities/extensions/extension-lifecycle";
export {
	EXTENSION_EVENT_TYPES,
	type ExtensionEventPayload,
	type ExtensionEventType,
} from "./capabilities/extensions/extension-transaction-contract";
export {
	assertExpectedExtensionVersion,
	nextExtensionVersion,
	type VersionedExtension,
} from "./capabilities/extensions/extension-version-cas";
export {
	MAX_EXTERNAL_ID_QUALIFIER_LENGTH,
	MAX_EXTERNAL_ID_VALUE_LENGTH,
	type NormalizedExternalId,
	normalizeExternalId,
	normalizeExternalIdQualifier,
} from "./capabilities/extensions/external-id-normalization";
export {
	ITEM_ALIAS_TYPES,
	type ItemAliasType,
	MAX_ITEM_ALIAS_SOURCE_LENGTH,
	MAX_ITEM_ALIAS_VALUE_LENGTH,
	normalizeItemAlias,
	normalizeItemAliasSource,
} from "./capabilities/extensions/item-alias-policy";
export {
	ITEM_BARCODE_SYMBOLOGIES,
	type ItemBarcodeSymbology,
	MAX_ITEM_BARCODE_PACK_QUANTITY_SCALE,
	MAX_ITEM_BARCODE_VALUE_LENGTH,
	normalizeBarcode,
	normalizeBarcodePackQuantity,
} from "./capabilities/extensions/item-barcode-policy";
export {
	assertItemUomCompatibility,
	ITEM_UOM_COMPATIBILITY_MODES,
	ITEM_UOM_FACTOR_PRECISION,
	ITEM_UOM_FACTOR_SCALE,
	ITEM_UOM_MAX_INTEGER_DIGITS,
	type ItemUomCompatibilityMode,
	normalizeItemUomConversionFactor,
} from "./capabilities/extensions/item-uom-policy";
export type {
	PartyContactProjection,
	SensitivePartyContactProjection,
} from "./capabilities/extensions/party-contact-projection";
export {
	isSameNullablePrimaryScope,
	PRIMARY_RECORD_REPLACEMENT_POLICY,
	PRIMARY_RECORD_SCOPES,
} from "./capabilities/extensions/primary-record-policy";
export * from "./capabilities/integration-projections";
export {
	MASTER_SEARCH_ENTITY,
	MASTER_SEARCH_ENTITY_VALUES,
	type MasterSearchEntity,
	projectMasterRoot,
	type RebuildMasterDataSearchResult,
	shouldIndexMasterStatus,
	syncMasterRootProjection,
} from "./capabilities/integration-projections/search-projector-commands";
export * from "./capabilities/lifecycle-governance";
export {
	getRefCountryByCode,
	getRefCurrencyByCode,
	getRefLanguageByCode,
	getRefTimeZoneByIana,
	getRefUomByCode,
	getRefUomById,
	getRefUomDimensionByCode,
	listRefUoms,
} from "./capabilities/platform-references/authorized-queries";
export * from "./capabilities/platform-references/schemas";
export * from "./capabilities/platform-references/types";
export type { MasterDataCapabilityOptions } from "./command-options";
export {
	actorUserIdSchema,
	type CorrelationId,
	correlationIdSchema,
	expectedVersionSchema,
	type IdempotencyKey,
	idempotencyKeySchema,
	type MasterDataMutationContext,
	masterDataMutationContextSchema,
	type OrganizationId,
	type OrgQueryActor,
	organizationIdSchema,
	orgQueryActorSchema,
	type UserId,
	type VersionedMutationContext,
	versionedMutationContextSchema,
} from "./contracts/context";
export {
	MASTER_DATA_ERROR_CODES,
	MASTER_REASON_TO_ERROR_CODE,
	MASTER_REASONS,
	type MasterDataErrorCode,
	type MasterFailureDetails,
	type MasterReason,
	masterDataErrorCodeForFailureDetails,
	masterDataErrorCodeForReason,
} from "./contracts/reasons";
export {
	MASTER_DATA_DATABASE_CONSTRAINT_REQUIREMENTS,
	type MasterDataDatabaseConstraintKind,
	type MasterDataDatabaseConstraintRequirement,
} from "./database-constraints";
export {
	type Page,
	type PageRequest,
	pageRequestSchema,
} from "./pagination";
export * from "./permissions";
export {
	activateItem,
	activateItemGroup,
	activateItemTemplate,
	activateOrganizationDimension,
	activateParty,
	activatePartyRole,
	activatePaymentTerm,
	activateTaxRegistration,
	activateWarehouse,
	addItemTemplateAttribute,
	addItemTemplateAttributeOption,
	approveChangeRequest,
	archiveItem,
	archiveItemTemplate,
	archiveOrganizationDimension,
	archiveParty,
	archivePartyRole,
	archiveTaxRegistration,
	archiveWarehouse,
	assertApprovedChangeRequestForApply,
	blockParty,
	blockTaxRegistration,
	createItem,
	createItemAlias,
	createItemBarcode,
	createItemExternalId,
	createItemGroup,
	createItemTemplate,
	createItemUom,
	createItemVariant,
	createOrganizationDimension,
	createParty,
	createPartyAddress,
	createPartyContact,
	createPartyExternalId,
	createPartyRelationship,
	createPartyRole,
	createPaymentTerm,
	createTaxRegistration,
	createWarehouse,
	createWarehouseExternalId,
	deactivateOrganizationDimension,
	deactivatePartyRole,
	findItemByAlias,
	findItemByBarcode,
	findItemByExternalId,
	findPartyByExternalId,
	findPartyDuplicateWarnings,
	findWarehouseByExternalId,
	getChangeRequestById,
	getDefaultItemPurchaseUom,
	getDefaultItemSalesUom,
	getItemTemplateByCode,
	getItemTemplateById,
	getItemVariantById,
	getOrganizationDimensionByCode,
	getOrganizationDimensionById,
	getOrganizationDimensionEffective,
	getPartyAddressById,
	getPartyRoleById,
	getPrimaryPartyAddress,
	getPrimaryPartyContact,
	getSensitivePrimaryPartyContact,
	getVariantConfiguration,
	inactiveItem,
	inactiveItemGroup,
	inactiveItemTemplate,
	inactiveParty,
	inactivePaymentTerm,
	inactiveWarehouse,
	listActivePartyRoles,
	listChangeRequests,
	listItemAliases,
	listItemsByAlias,
	listItemTemplateAttributeOptions,
	listItemTemplateAttributes,
	listItemTemplates,
	listItemUoms,
	listItemVariantsByTemplate,
	listOrganizationDimensions,
	listPartyAddresses,
	listPartyContacts,
	listPartyRelationships,
	listPartyRoles,
	listSensitivePartyContacts,
	listVariantAttributeValues,
	mergeParties,
	moveWarehouse,
	rebuildMasterDataSearchIndex,
	rejectChangeRequest,
	resolveCanonicalPartyId,
	resolveOrganizationDimensionsAsOf,
	restoreItem,
	restoreParty,
	restoreTaxRegistration,
	retireItem,
	retireItemGroup,
	retireItemTemplate,
	retireItemVariant,
	retireParty,
	retirePartyRole,
	retirePaymentTerm,
	retireTaxRegistration,
	retireWarehouse,
	revokeTaxRegistration,
	searchMasterDataDocuments,
	submitChangeRequest,
	suspendItem,
	suspendParty,
	suspendWarehouse,
	updateItem,
	updateItemGroup,
	updateItemTemplate,
	updateOrganizationDimension,
	updateParty,
	updatePartyAddress,
	updatePartyContact,
	updatePartyContactVerification,
	updatePartyRole,
	updatePaymentTerm,
	updateTaxRegistration,
	updateWarehouse,
	upsertItemGroupsByCode,
	upsertItemsByCode,
	upsertPartiesByCode,
	upsertWarehousesByCode,
	validatePartyImportBatch,
} from "./public-capabilities";
export {
	MASTER_DATA_COMPLETION_GATE_COMMANDS,
	MASTER_DATA_MUTABLE_AGGREGATE_PARITY_REQUIREMENTS,
	MASTER_DATA_REQUIRED_AGGREGATE_PARITY_CASES,
	MASTER_DATA_REQUIRED_TEST_LAYERS,
	type MasterDataAggregateParityCase,
	type MasterDataAggregateParityRequirement,
	type MasterDataCompletionEvidence,
	type MasterDataCompletionGate,
	type MasterDataTestLayerId,
} from "./testing-completeness";
export {
	type ActivatePartyChangePayload,
	CHANGE_REQUEST_COMMAND_KINDS,
	CHANGE_REQUEST_STATUSES,
	type ChangeRequest,
	type ChangeRequestCommandKind,
	type ChangeRequestPayload,
	type ChangeRequestStatus,
	EXTENSION_STATUSES,
	EXTERNAL_ID_CASE_SENSITIVITIES,
	type ExtensionLifecycleFamily,
	type ExtensionLifecycleStatus,
	type ExtensionStatus,
	type ExternalIdCaseSensitivity,
	IDENTITY_REGISTRATION_LIFECYCLE_STATUSES,
	type IdentityRegistrationLifecycleStatus,
	ITEM_TEMPLATE_ATTRIBUTE_DATA_TYPES,
	ITEM_TRACKING_POLICIES,
	ITEM_TYPES,
	type Item,
	type ItemAlias,
	type ItemBarcode,
	type ItemExternalId,
	type ItemGroup,
	type ItemTemplate,
	type ItemTemplateAttribute,
	type ItemTemplateAttributeDataType,
	type ItemTemplateAttributeOption,
	type ItemTemplateAttributeValidationRules,
	type ItemTrackingPolicy,
	type ItemType,
	type ItemUom,
	type ItemVariant,
	type ItemVariantAttributeValue,
	MASTER_STATUSES,
	MAX_PAYMENT_TERM_NET_DAYS,
	type MasterDependency,
	type MasterStatus,
	type MergePartiesChangePayload,
	OPTION_COMPATIBLE_ATTRIBUTE_DATA_TYPES,
	PARTY_ADDRESS_PURPOSES,
	PARTY_ADDRESS_TYPES,
	PARTY_ADDRESS_VALIDATION_STATUSES,
	PARTY_CONTACT_TYPES,
	PARTY_CONTACT_VERIFICATION_STATUSES,
	PARTY_KINDS,
	PARTY_RELATIONSHIP_DIRECTIONS,
	PARTY_RELATIONSHIP_TYPES,
	PARTY_ROLE_CODES,
	PAYMENT_TERM_DUE_DAY_RULES,
	PAYMENT_TERM_INSTALLMENT_POLICIES,
	type Party,
	type PartyAddress,
	type PartyAddressPurpose,
	type PartyAddressType,
	type PartyAddressValidationStatus,
	type PartyContactType,
	type PartyContactVerificationStatus,
	type PartyExternalId,
	type PartyKind,
	type PartyRelationship,
	type PartyRelationshipDirection,
	type PartyRelationshipType,
	type PartyRole,
	type PartyRoleCode,
	type PaymentTerm,
	type PaymentTermDueDayRule,
	type PaymentTermInstallmentPolicy,
	RELATIONSHIP_LIFECYCLE_STATUSES,
	type RelationshipLifecycleStatus,
	STANDARD_CHILD_LIFECYCLE_STATUSES,
	type StandardChildLifecycleStatus,
	TAX_REGISTRATION_TYPES,
	type TaxRegistrationType,
	WAREHOUSE_LOCATION_TYPES,
	type Warehouse,
	type WarehouseExternalId,
	type WarehouseLocationType,
} from "./types";
