import { z } from "zod";

const IDENTIFIER_MAX_LENGTH = 128;

function identifierSchema<const T extends string>(brand: T) {
	return z
		.string()
		.trim()
		.min(1, `${brand} must not be empty`)
		.max(
			IDENTIFIER_MAX_LENGTH,
			`${brand} must not exceed ${IDENTIFIER_MAX_LENGTH} characters`,
		)
		.brand<T>();
}

function uuidIdentifierSchema<const T extends string>(brand: T) {
	return z
		.uuid({
			error: `${brand} must be a valid UUID`,
		})
		.brand<T>();
}

export const organizationIdSchema = identifierSchema("OrganizationId");
export type OrganizationId = z.infer<typeof organizationIdSchema>;

export const userIdSchema = identifierSchema("UserId");
export type UserId = z.infer<typeof userIdSchema>;

/**
 * Domain event identity for Corporate Administration envelopes.
 *
 * Representation matches platform event-payload `eventId` fields: an opaque,
 * non-empty trimmed string bounded to 128 characters. This is not the
 * `platform_domain_event.id` column — that UUID is generated by the outbox
 * store and must not be assumed by this brand.
 *
 * Validates and brands only. Callers must supply an already-generated value
 * from the application composition boundary or an ID-generator port.
 */
export const eventIdSchema = identifierSchema("CorporateAdministrationEventId");
export type CorporateAdministrationEventId = z.infer<typeof eventIdSchema>;

export const legalCompanyIdSchema = uuidIdentifierSchema("LegalCompanyId");
export type LegalCompanyId = z.infer<typeof legalCompanyIdSchema>;

export const companyNameIdSchema = uuidIdentifierSchema("CompanyNameId");
export type CompanyNameId = z.infer<typeof companyNameIdSchema>;

export const companyLegalFormHistoryIdSchema = uuidIdentifierSchema(
	"CompanyLegalFormHistoryId",
);
export type CompanyLegalFormHistoryId = z.infer<
	typeof companyLegalFormHistoryIdSchema
>;

export const companyIdentifierIdSchema = uuidIdentifierSchema(
	"CompanyIdentifierId",
);
export type CompanyIdentifierId = z.infer<typeof companyIdentifierIdSchema>;

export const companyFinancialYearIdSchema = uuidIdentifierSchema(
	"CompanyFinancialYearId",
);
export type CompanyFinancialYearId = z.infer<
	typeof companyFinancialYearIdSchema
>;

export const companyActivityIdSchema =
	uuidIdentifierSchema("CompanyActivityId");
export type CompanyActivityId = z.infer<typeof companyActivityIdSchema>;

export const legalEstablishmentIdSchema = uuidIdentifierSchema(
	"LegalEstablishmentId",
);
export type LegalEstablishmentId = z.infer<typeof legalEstablishmentIdSchema>;

export const establishmentStatusHistoryIdSchema = uuidIdentifierSchema(
	"EstablishmentStatusHistoryId",
);
export type EstablishmentStatusHistoryId = z.infer<
	typeof establishmentStatusHistoryIdSchema
>;

export const registeredAddressIdSchema = uuidIdentifierSchema(
	"RegisteredAddressId",
);
export type RegisteredAddressId = z.infer<typeof registeredAddressIdSchema>;

export const premiseIdSchema = uuidIdentifierSchema("PremiseId");
export type PremiseId = z.infer<typeof premiseIdSchema>;

export const correlationIdSchema = identifierSchema("CorrelationId");
export type CorrelationId = z.infer<typeof correlationIdSchema>;

export const causationIdSchema = identifierSchema("CausationId");
export type CausationId = z.infer<typeof causationIdSchema>;

export const idempotencyKeySchema = identifierSchema("IdempotencyKey");
export type IdempotencyKey = z.infer<typeof idempotencyKeySchema>;

export const idempotencyReservationTokenSchema = identifierSchema(
	"IdempotencyReservationToken",
);
export type IdempotencyReservationToken = z.infer<
	typeof idempotencyReservationTokenSchema
>;

export const approvalRequestIdSchema =
	uuidIdentifierSchema("ApprovalRequestId");
export type ApprovalRequestId = z.infer<typeof approvalRequestIdSchema>;

export const approvalDecisionIdSchema =
	uuidIdentifierSchema("ApprovalDecisionId");
export type ApprovalDecisionId = z.infer<typeof approvalDecisionIdSchema>;

export const documentObjectRefSchema = identifierSchema("DocumentObjectRef");
export type DocumentObjectRef = z.infer<typeof documentObjectRefSchema>;

export const commandFingerprintSchema = z
	.string()
	.regex(
		/^[0-9a-f]{64}$/,
		"CommandFingerprint must be a lowercase SHA-256 hexadecimal value",
	)
	.brand<"CommandFingerprint">();

export type CommandFingerprint = z.infer<typeof commandFingerprintSchema>;
