export {
	CORPORATE_ADMINISTRATION_COMMAND_AUTHORIZATION,
	CORPORATE_ADMINISTRATION_COMMAND_IDS,
	CORPORATE_ADMINISTRATION_EMITTED_EVENT_IDS,
	CORPORATE_ADMINISTRATION_QUERY_AUTHORIZATION,
	CORPORATE_ADMINISTRATION_QUERY_IDS,
} from "./operations/registry";
export { CORPORATE_ADMINISTRATION_PERMISSION_CODES } from "./permissions";
