export type {
	CompanyIdentifierCreateRecord,
	CompanyIdentifierStore,
	CompanyIdentifierUpdatePatch,
	CompanyNameCreateRecord,
	CompanyNameListFilter,
	CompanyNameStore,
	CompanyStatusHistoryListFilter,
	CompanyStatusHistoryStore,
	CorporateAdministrationCompanyStore,
	CorporateAdministrationMutationMeta,
	CorporateAdministrationMutationReceipt,
	LegalCompanyActivationFacts,
	LegalCompanyCreateRecord,
	LegalCompanyListFilter,
	LegalCompanyMutationStore,
	LegalCompanyQueryStore,
	LegalCompanyStatusTransitionRecord,
	LegalCompanyTransitionPatch,
	LegalCompanyUpdatePatch,
} from "./company-store";
export {
	CORPORATE_ADMINISTRATION_STORE_ERROR_CODES,
	CorporateAdministrationIdempotencyConflictError,
	CorporateAdministrationStoreError,
	type CorporateAdministrationStoreErrorCode,
	CorporateAdministrationVersionConflictError,
	isCorporateAdministrationStoreError,
	mapCorporateAdministrationStoreError,
} from "./store-errors";
