import {
	PAYROLL_FINAL_SETTLEMENT_CALCULATED_EVENT,
	PAYROLL_FINAL_SETTLEMENT_FINALIZED_EVENT,
	PAYROLL_FINAL_SETTLEMENT_INITIATED_EVENT,
	PAYROLL_PAYMENT_CORRECTION_REQUESTED_EVENT,
	PAYROLL_PAYMENT_REQUESTED_EVENT,
	PAYROLL_POSTING_CORRECTION_REQUESTED_EVENT,
	PAYROLL_POSTING_REQUESTED_EVENT,
	PAYROLL_RUN_CALCULATED_EVENT,
	PAYROLL_RUN_FINALIZED_EVENT,
	PAYROLL_RUN_REVERSED_EVENT,
	PAYROLL_RUN_STARTED_EVENT,
	type PayrollEventType,
} from "@afenda/events/schemas";

import {
	PAYROLL_COMMAND_FINAL_SETTLEMENT_CALCULATE,
	PAYROLL_COMMAND_FINAL_SETTLEMENT_FINALIZE,
	PAYROLL_COMMAND_FINAL_SETTLEMENT_INITIATE,
	PAYROLL_COMMAND_RUN_CALCULATE,
	PAYROLL_COMMAND_RUN_CREATE,
	PAYROLL_COMMAND_RUN_FINALIZE,
	PAYROLL_COMMAND_RUN_REVERSE,
	type PayrollCommandId,
} from "../operations/module-ids";

/**
 * Canonical Payroll emission registry (bridging B4).
 *
 * Event name strings are owned by `@afenda/events/schemas`. This registry owns
 * the payroll-local mapping from each emitted event to the command that
 * produces it and the registered dispatcher drained by `apps/web` (B6).
 */
export const PAYROLL_PLATFORM_EVENT_DISPATCHER_ID =
	"apps/web:payroll-platform-events" as const;

export type PayrollEmissionEntry = Readonly<{
	dispatcher: string | null;
	emittedBy: PayrollCommandId;
	event: PayrollEventType;
}>;

export const PAYROLL_EMISSION_REGISTRY = [
	{
		event: PAYROLL_RUN_STARTED_EVENT,
		emittedBy: PAYROLL_COMMAND_RUN_CREATE,
		dispatcher: PAYROLL_PLATFORM_EVENT_DISPATCHER_ID,
	},
	{
		event: PAYROLL_RUN_CALCULATED_EVENT,
		emittedBy: PAYROLL_COMMAND_RUN_CALCULATE,
		dispatcher: PAYROLL_PLATFORM_EVENT_DISPATCHER_ID,
	},
	{
		event: PAYROLL_RUN_FINALIZED_EVENT,
		emittedBy: PAYROLL_COMMAND_RUN_FINALIZE,
		dispatcher: PAYROLL_PLATFORM_EVENT_DISPATCHER_ID,
	},
	{
		event: PAYROLL_PAYMENT_REQUESTED_EVENT,
		emittedBy: PAYROLL_COMMAND_RUN_FINALIZE,
		dispatcher: PAYROLL_PLATFORM_EVENT_DISPATCHER_ID,
	},
	{
		event: PAYROLL_POSTING_REQUESTED_EVENT,
		emittedBy: PAYROLL_COMMAND_RUN_FINALIZE,
		dispatcher: PAYROLL_PLATFORM_EVENT_DISPATCHER_ID,
	},
	{
		event: PAYROLL_RUN_REVERSED_EVENT,
		emittedBy: PAYROLL_COMMAND_RUN_REVERSE,
		dispatcher: PAYROLL_PLATFORM_EVENT_DISPATCHER_ID,
	},
	{
		event: PAYROLL_PAYMENT_CORRECTION_REQUESTED_EVENT,
		emittedBy: PAYROLL_COMMAND_RUN_REVERSE,
		dispatcher: PAYROLL_PLATFORM_EVENT_DISPATCHER_ID,
	},
	{
		event: PAYROLL_POSTING_CORRECTION_REQUESTED_EVENT,
		emittedBy: PAYROLL_COMMAND_RUN_REVERSE,
		dispatcher: PAYROLL_PLATFORM_EVENT_DISPATCHER_ID,
	},
	{
		event: PAYROLL_FINAL_SETTLEMENT_INITIATED_EVENT,
		emittedBy: PAYROLL_COMMAND_FINAL_SETTLEMENT_INITIATE,
		dispatcher: PAYROLL_PLATFORM_EVENT_DISPATCHER_ID,
	},
	{
		event: PAYROLL_FINAL_SETTLEMENT_CALCULATED_EVENT,
		emittedBy: PAYROLL_COMMAND_FINAL_SETTLEMENT_CALCULATE,
		dispatcher: PAYROLL_PLATFORM_EVENT_DISPATCHER_ID,
	},
	{
		event: PAYROLL_FINAL_SETTLEMENT_FINALIZED_EVENT,
		emittedBy: PAYROLL_COMMAND_FINAL_SETTLEMENT_FINALIZE,
		dispatcher: PAYROLL_PLATFORM_EVENT_DISPATCHER_ID,
	},
] as const satisfies readonly PayrollEmissionEntry[];

export const PAYROLL_EMITTED_EVENTS = PAYROLL_EMISSION_REGISTRY.map(
	({ event }) => event,
);
