import type { AfendaModuleManifest } from "@afenda/db/module-manifest";
import {
	PAYABLES_ALLOCATION_POSTED_EVENT,
	PAYABLES_CREDIT_NOTE_POSTED_EVENT,
	PAYABLES_INVOICE_CANCELLED_EVENT,
	PAYABLES_INVOICE_CREATED_EVENT,
	PAYABLES_INVOICE_MATCHED_EVENT,
	PAYABLES_INVOICE_POSTED_EVENT,
	PAYABLES_PAYMENT_APPLICATION_REVERSED_EVENT,
} from "@afenda/events/schemas";

export const payablesModuleManifest = {
	activationMode: "organization_toggle",
	authorization: {
		commands: {
			"payables.credit_note.create": "payables.manage",
			"payables.credit_note.issue": "payables.manage",
			"payables.credit_note.line.add": "payables.manage",
			"payables.credit_note.post": "payables.manage",
			"payables.credit.apply": "payables.manage",
			"payables.invoice.cancel": "payables.manage",
			"payables.invoice.create": "payables.manage",
			"payables.invoice.line.add": "payables.manage",
			"payables.invoice.match": "payables.manage",
			"payables.invoice.post": "payables.manage",
			"payables.payment_application.reverse": "payables.manage",
			"payables.payment.apply": "payables.manage",
		},
		queries: {
			"payables.balance.get": "payables.read",
			"payables.invoice.get": "payables.read",
			"payables.invoice.list": "payables.read",
		},
	},
	band: "R1-F",
	category: "commercial",
	events: {
		consumes: [],
		emits: [
			PAYABLES_INVOICE_CREATED_EVENT,
			PAYABLES_INVOICE_MATCHED_EVENT,
			PAYABLES_INVOICE_POSTED_EVENT,
			PAYABLES_CREDIT_NOTE_POSTED_EVENT,
			PAYABLES_ALLOCATION_POSTED_EVENT,
			PAYABLES_INVOICE_CANCELLED_EVENT,
			PAYABLES_PAYMENT_APPLICATION_REVERSED_EVENT,
		],
		namespace: "payables",
	},
	id: "payables",
	lifecycle: "active",
	moduleDependencies: {
		required: ["master-data"],
	},
	optionalIntegratesWith: [
		{ moduleId: "purchasing", style: "ports" },
		{ moduleId: "receiving", style: "ports" },
		{ moduleId: "payments", style: "ports" },
		{ moduleId: "accounting", style: "events" },
	],
	owns: {
		aggregates: [
			"supplier_invoice",
			"supplier_allocation",
			"supplier_balance_projection",
			"three_way_match_result",
		],
		commandNamespace: "payables",
		commands: [
			"payables.invoice.create",
			"payables.invoice.line.add",
			"payables.invoice.match",
			"payables.invoice.post",
			"payables.credit_note.issue",
			"payables.credit_note.create",
			"payables.credit_note.line.add",
			"payables.credit_note.post",
			"payables.payment.apply",
			"payables.credit.apply",
			"payables.payment_application.reverse",
			"payables.invoice.cancel",
		],
		queries: [
			"payables.invoice.get",
			"payables.invoice.list",
			"payables.balance.get",
		],
		queryNamespace: "payables",
	},
	packageName: "@afenda/payables",
	permissions: {
		codes: ["payables.read", "payables.manage"],
		namespace: "payables",
	},
	persistence: {
		mutationTables: [
			"supplier_invoice",
			"supplier_invoice_line",
			"supplier_credit_note",
			"supplier_credit_note_line",
			"supplier_allocation",
			"supplier_balance_projection",
			"three_way_match_result",
		],
		schemaOwner: "@afenda/db",
	},
} as const satisfies AfendaModuleManifest;
