export const RECEIVABLES_PERMISSION_INVOICE_READ =
	"receivables.invoice.read" as const;
export const RECEIVABLES_PERMISSION_INVOICE_CREATE =
	"receivables.invoice.create" as const;
export const RECEIVABLES_PERMISSION_INVOICE_UPDATE =
	"receivables.invoice.update" as const;
export const RECEIVABLES_PERMISSION_INVOICE_POST =
	"receivables.invoice.post" as const;
export const RECEIVABLES_PERMISSION_INVOICE_CANCEL =
	"receivables.invoice.cancel" as const;
export const RECEIVABLES_PERMISSION_INVOICE_CLOSE =
	"receivables.invoice.close" as const;
export const RECEIVABLES_PERMISSION_CREDIT_NOTE_ISSUE =
	"receivables.credit_note.issue" as const;
export const RECEIVABLES_PERMISSION_RECEIPT_APPLY =
	"receivables.receipt.apply" as const;
export const RECEIVABLES_PERMISSION_RECEIPT_APPLICATION_REVERSE =
	"receivables.receipt_application.reverse" as const;
export const RECEIVABLES_PERMISSION_BALANCE_READ =
	"receivables.balance.read" as const;
export const RECEIVABLES_PERMISSION_AGING_READ =
	"receivables.aging.read" as const;

export const RECEIVABLES_PERMISSION_CODES = [
	RECEIVABLES_PERMISSION_INVOICE_READ,
	RECEIVABLES_PERMISSION_INVOICE_CREATE,
	RECEIVABLES_PERMISSION_INVOICE_UPDATE,
	RECEIVABLES_PERMISSION_INVOICE_POST,
	RECEIVABLES_PERMISSION_INVOICE_CANCEL,
	RECEIVABLES_PERMISSION_INVOICE_CLOSE,
	RECEIVABLES_PERMISSION_CREDIT_NOTE_ISSUE,
	RECEIVABLES_PERMISSION_RECEIPT_APPLY,
	RECEIVABLES_PERMISSION_RECEIPT_APPLICATION_REVERSE,
	RECEIVABLES_PERMISSION_BALANCE_READ,
	RECEIVABLES_PERMISSION_AGING_READ,
] as const;

export const receivablesPermissions = {
	invoiceRead: RECEIVABLES_PERMISSION_INVOICE_READ,
	invoiceCreate: RECEIVABLES_PERMISSION_INVOICE_CREATE,
	invoiceUpdate: RECEIVABLES_PERMISSION_INVOICE_UPDATE,
	invoicePost: RECEIVABLES_PERMISSION_INVOICE_POST,
	invoiceCancel: RECEIVABLES_PERMISSION_INVOICE_CANCEL,
	invoiceClose: RECEIVABLES_PERMISSION_INVOICE_CLOSE,
	creditNoteIssue: RECEIVABLES_PERMISSION_CREDIT_NOTE_ISSUE,
	receiptApply: RECEIVABLES_PERMISSION_RECEIPT_APPLY,
	receiptApplicationReverse: RECEIVABLES_PERMISSION_RECEIPT_APPLICATION_REVERSE,
	balanceRead: RECEIVABLES_PERMISSION_BALANCE_READ,
	agingRead: RECEIVABLES_PERMISSION_AGING_READ,
} as const;
