import {
	HUMAN_RESOURCES_EMPLOYEE_DOCUMENT_EXPIRED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_DOCUMENT_NEARING_EXPIRY_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_DOCUMENT_REGISTERED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_DOCUMENT_REJECTED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_DOCUMENT_VERIFIED_EVENT,
	HUMAN_RESOURCES_POLICY_ACKNOWLEDGEMENT_ACKNOWLEDGED_EVENT,
	HUMAN_RESOURCES_POLICY_ACKNOWLEDGEMENT_OUTSTANDING_EVENT,
	HUMAN_RESOURCES_WORK_ELIGIBILITY_EXPIRED_EVENT,
	HUMAN_RESOURCES_WORK_ELIGIBILITY_RENEWED_EVENT,
	HUMAN_RESOURCES_WORK_ELIGIBILITY_SUSPENDED_EVENT,
	HUMAN_RESOURCES_WORK_ELIGIBILITY_VERIFIED_EVENT,
} from "@afenda/events/schemas";

import {
	HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_CREATE,
	HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_PUBLISH,
	HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_RETIRE,
	HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_UPDATE,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_MARK_EXPIRED,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_REGISTER,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_REJECT,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_REVOKE_VERIFICATION,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_UPDATE_METADATA,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_VERIFY,
	HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_ACKNOWLEDGE,
	HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_ISSUE,
	HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_REVOKE,
	HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_SUPERSEDE,
	HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_CLOSE,
	HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_RECORD,
	HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_RENEW,
	HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_SUSPEND,
	HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_VERIFY,
	type HumanResourcesComplianceCommandId,
} from "../../operations/module-ids";

import {
	defineAuditOnlyEmission,
	defineDomainEventEmission,
} from "../define-emission";
import type { HumanResourcesMutationEmissionDefinition } from "../types";

export const HUMAN_RESOURCES_COMPLIANCE_EMISSIONS = {
	[HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_CREATE]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_CREATE,
			{
				domain: "compliance",
				aggregateType: "document_requirement",
			},
		),
	[HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_UPDATE]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_UPDATE,
			{
				domain: "compliance",
				aggregateType: "document_requirement",
			},
		),
	[HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_PUBLISH]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_PUBLISH,
			{
				domain: "compliance",
				aggregateType: "document_requirement",
			},
		),
	[HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_RETIRE]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_RETIRE,
			{
				domain: "compliance",
				aggregateType: "document_requirement",
			},
		),
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_REGISTER]:
		defineDomainEventEmission(
			HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_REGISTER,
			{
				domain: "compliance",
				aggregateType: "employee_document",
				eventTypes: [
					HUMAN_RESOURCES_EMPLOYEE_DOCUMENT_REGISTERED_EVENT,
					HUMAN_RESOURCES_EMPLOYEE_DOCUMENT_NEARING_EXPIRY_EVENT,
				] as const,
			},
		),
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_UPDATE_METADATA]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_UPDATE_METADATA,
			{
				domain: "compliance",
				aggregateType: "employee_document",
			},
		),
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_VERIFY]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_VERIFY,
		{
			domain: "compliance",
			aggregateType: "employee_document",
			eventTypes: [HUMAN_RESOURCES_EMPLOYEE_DOCUMENT_VERIFIED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_REJECT]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_REJECT,
		{
			domain: "compliance",
			aggregateType: "employee_document",
			eventTypes: [HUMAN_RESOURCES_EMPLOYEE_DOCUMENT_REJECTED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_REVOKE_VERIFICATION]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_REVOKE_VERIFICATION,
			{
				domain: "compliance",
				aggregateType: "employee_document",
			},
		),
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_MARK_EXPIRED]:
		defineDomainEventEmission(
			HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_MARK_EXPIRED,
			{
				domain: "compliance",
				aggregateType: "employee_document",
				eventTypes: [HUMAN_RESOURCES_EMPLOYEE_DOCUMENT_EXPIRED_EVENT] as const,
			},
		),
	[HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_RECORD]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_RECORD,
		{
			domain: "compliance",
			aggregateType: "work_eligibility",
		},
	),
	[HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_VERIFY]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_VERIFY,
		{
			domain: "compliance",
			aggregateType: "work_eligibility",
			eventTypes: [HUMAN_RESOURCES_WORK_ELIGIBILITY_VERIFIED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_SUSPEND]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_SUSPEND,
		{
			domain: "compliance",
			aggregateType: "work_eligibility",
			eventTypes: [HUMAN_RESOURCES_WORK_ELIGIBILITY_SUSPENDED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_RENEW]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_RENEW,
		{
			domain: "compliance",
			aggregateType: "work_eligibility",
			eventTypes: [HUMAN_RESOURCES_WORK_ELIGIBILITY_RENEWED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_CLOSE]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_CLOSE,
		{
			domain: "compliance",
			aggregateType: "work_eligibility",
			eventTypes: [HUMAN_RESOURCES_WORK_ELIGIBILITY_EXPIRED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_ISSUE]:
		defineDomainEventEmission(
			HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_ISSUE,
			{
				domain: "compliance",
				aggregateType: "policy_acknowledgement",
				eventTypes: [
					HUMAN_RESOURCES_POLICY_ACKNOWLEDGEMENT_OUTSTANDING_EVENT,
				] as const,
			},
		),
	[HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_ACKNOWLEDGE]:
		defineDomainEventEmission(
			HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_ACKNOWLEDGE,
			{
				domain: "compliance",
				aggregateType: "policy_acknowledgement",
				eventTypes: [
					HUMAN_RESOURCES_POLICY_ACKNOWLEDGEMENT_ACKNOWLEDGED_EVENT,
				] as const,
			},
		),
	[HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_REVOKE]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_REVOKE,
			{
				domain: "compliance",
				aggregateType: "policy_acknowledgement",
			},
		),
	[HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_SUPERSEDE]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_SUPERSEDE,
			{
				domain: "compliance",
				aggregateType: "policy_acknowledgement",
			},
		),
} satisfies Record<
	HumanResourcesComplianceCommandId,
	HumanResourcesMutationEmissionDefinition
>;
