import {
	MASTER_COMMAND_ITEM_ALIAS_CREATE,
	MASTER_COMMAND_ITEM_BARCODE_CREATE,
	MASTER_COMMAND_ITEM_EXTERNAL_ID_CREATE,
	MASTER_COMMAND_ITEM_TEMPLATE_ATTRIBUTE_CREATE,
	MASTER_COMMAND_ITEM_TEMPLATE_ATTRIBUTE_CREATE_VARIANT_DEFINING,
	MASTER_COMMAND_ITEM_TEMPLATE_ATTRIBUTE_OPTION_CREATE,
	MASTER_COMMAND_ITEM_UOM_CREATE,
	MASTER_COMMAND_ITEM_VARIANT_CREATE,
	MASTER_COMMAND_PARTY_ADDRESS_CREATE,
	MASTER_COMMAND_PARTY_ADDRESS_UPDATE,
	MASTER_COMMAND_PARTY_CONTACT_CREATE,
	MASTER_COMMAND_PARTY_CONTACT_UPDATE,
	MASTER_COMMAND_PARTY_CONTACT_VERIFY,
	MASTER_COMMAND_PARTY_EXTERNAL_ID_CREATE,
	MASTER_COMMAND_PARTY_EXTERNAL_ID_CREATE_REGULATORY,
	MASTER_COMMAND_PARTY_RELATIONSHIP_CREATE,
	MASTER_COMMAND_PARTY_RELATIONSHIP_CREATE_CONTROL,
	MASTER_COMMAND_PARTY_ROLE_ACTIVATE,
	MASTER_COMMAND_PARTY_ROLE_ARCHIVE,
	MASTER_COMMAND_PARTY_ROLE_CREATE,
	MASTER_COMMAND_PARTY_ROLE_INACTIVE,
	MASTER_COMMAND_PARTY_ROLE_RETIRE,
	MASTER_COMMAND_PARTY_ROLE_UPDATE,
	MASTER_COMMAND_WAREHOUSE_EXTERNAL_ID_CREATE,
	type MasterCommandId,
} from "../../module-ids";
import {
	type MASTER_DATA_PERMISSION_CODES,
	MASTER_DATA_PERMISSION_ITEM_EXTENSION_MANAGE,
	MASTER_DATA_PERMISSION_PARTY_ADDRESS_MANAGE,
	MASTER_DATA_PERMISSION_PARTY_CONTACT_MANAGE,
	MASTER_DATA_PERMISSION_PARTY_EXTERNAL_ID_MANAGE,
	MASTER_DATA_PERMISSION_PARTY_RELATIONSHIP_MANAGE,
	MASTER_DATA_PERMISSION_PARTY_ROLE_MANAGE,
	MASTER_DATA_PERMISSION_TEMPLATE_MANAGE,
	MASTER_DATA_PERMISSION_VARIANT_MANAGE,
	MASTER_DATA_PERMISSION_WAREHOUSE_MANAGE,
} from "../../permissions";
import type { PartyRelationshipType } from "../../types";

type MasterPermission = (typeof MASTER_DATA_PERMISSION_CODES)[number];

type ExtensionCommandId =
	| typeof MASTER_COMMAND_PARTY_ROLE_CREATE
	| typeof MASTER_COMMAND_PARTY_ROLE_UPDATE
	| typeof MASTER_COMMAND_PARTY_ROLE_ACTIVATE
	| typeof MASTER_COMMAND_PARTY_ROLE_INACTIVE
	| typeof MASTER_COMMAND_PARTY_ROLE_ARCHIVE
	| typeof MASTER_COMMAND_PARTY_ROLE_RETIRE
	| typeof MASTER_COMMAND_PARTY_ADDRESS_CREATE
	| typeof MASTER_COMMAND_PARTY_ADDRESS_UPDATE
	| typeof MASTER_COMMAND_PARTY_CONTACT_CREATE
	| typeof MASTER_COMMAND_PARTY_CONTACT_UPDATE
	| typeof MASTER_COMMAND_PARTY_CONTACT_VERIFY
	| typeof MASTER_COMMAND_PARTY_EXTERNAL_ID_CREATE
	| typeof MASTER_COMMAND_PARTY_EXTERNAL_ID_CREATE_REGULATORY
	| typeof MASTER_COMMAND_PARTY_RELATIONSHIP_CREATE
	| typeof MASTER_COMMAND_PARTY_RELATIONSHIP_CREATE_CONTROL
	| typeof MASTER_COMMAND_ITEM_UOM_CREATE
	| typeof MASTER_COMMAND_ITEM_BARCODE_CREATE
	| typeof MASTER_COMMAND_ITEM_EXTERNAL_ID_CREATE
	| typeof MASTER_COMMAND_ITEM_ALIAS_CREATE
	| typeof MASTER_COMMAND_WAREHOUSE_EXTERNAL_ID_CREATE
	| typeof MASTER_COMMAND_ITEM_TEMPLATE_ATTRIBUTE_CREATE
	| typeof MASTER_COMMAND_ITEM_TEMPLATE_ATTRIBUTE_CREATE_VARIANT_DEFINING
	| typeof MASTER_COMMAND_ITEM_TEMPLATE_ATTRIBUTE_OPTION_CREATE
	| typeof MASTER_COMMAND_ITEM_VARIANT_CREATE;

/**
 * Complete command-to-permission authority for subordinate extension mutations.
 *
 * Adding an ExtensionCommandId without adding its permission mapping is a
 * compile-time error.
 */
export const EXTENSION_COMMAND_PERMISSION = {
	[MASTER_COMMAND_PARTY_ROLE_CREATE]: MASTER_DATA_PERMISSION_PARTY_ROLE_MANAGE,
	[MASTER_COMMAND_PARTY_ROLE_UPDATE]: MASTER_DATA_PERMISSION_PARTY_ROLE_MANAGE,
	[MASTER_COMMAND_PARTY_ROLE_ACTIVATE]:
		MASTER_DATA_PERMISSION_PARTY_ROLE_MANAGE,
	[MASTER_COMMAND_PARTY_ROLE_INACTIVE]:
		MASTER_DATA_PERMISSION_PARTY_ROLE_MANAGE,
	[MASTER_COMMAND_PARTY_ROLE_ARCHIVE]: MASTER_DATA_PERMISSION_PARTY_ROLE_MANAGE,
	[MASTER_COMMAND_PARTY_ROLE_RETIRE]: MASTER_DATA_PERMISSION_PARTY_ROLE_MANAGE,
	[MASTER_COMMAND_PARTY_ADDRESS_CREATE]:
		MASTER_DATA_PERMISSION_PARTY_ADDRESS_MANAGE,
	[MASTER_COMMAND_PARTY_ADDRESS_UPDATE]:
		MASTER_DATA_PERMISSION_PARTY_ADDRESS_MANAGE,
	[MASTER_COMMAND_PARTY_CONTACT_CREATE]:
		MASTER_DATA_PERMISSION_PARTY_CONTACT_MANAGE,
	[MASTER_COMMAND_PARTY_CONTACT_UPDATE]:
		MASTER_DATA_PERMISSION_PARTY_CONTACT_MANAGE,
	[MASTER_COMMAND_PARTY_CONTACT_VERIFY]:
		MASTER_DATA_PERMISSION_PARTY_CONTACT_MANAGE,
	[MASTER_COMMAND_PARTY_EXTERNAL_ID_CREATE]:
		MASTER_DATA_PERMISSION_PARTY_EXTERNAL_ID_MANAGE,
	[MASTER_COMMAND_PARTY_EXTERNAL_ID_CREATE_REGULATORY]:
		MASTER_DATA_PERMISSION_PARTY_EXTERNAL_ID_MANAGE,
	[MASTER_COMMAND_PARTY_RELATIONSHIP_CREATE]:
		MASTER_DATA_PERMISSION_PARTY_RELATIONSHIP_MANAGE,
	[MASTER_COMMAND_PARTY_RELATIONSHIP_CREATE_CONTROL]:
		MASTER_DATA_PERMISSION_PARTY_RELATIONSHIP_MANAGE,
	[MASTER_COMMAND_ITEM_UOM_CREATE]:
		MASTER_DATA_PERMISSION_ITEM_EXTENSION_MANAGE,
	[MASTER_COMMAND_ITEM_BARCODE_CREATE]:
		MASTER_DATA_PERMISSION_ITEM_EXTENSION_MANAGE,
	[MASTER_COMMAND_ITEM_EXTERNAL_ID_CREATE]:
		MASTER_DATA_PERMISSION_ITEM_EXTENSION_MANAGE,
	[MASTER_COMMAND_ITEM_ALIAS_CREATE]:
		MASTER_DATA_PERMISSION_ITEM_EXTENSION_MANAGE,
	[MASTER_COMMAND_WAREHOUSE_EXTERNAL_ID_CREATE]:
		MASTER_DATA_PERMISSION_WAREHOUSE_MANAGE,
	[MASTER_COMMAND_ITEM_TEMPLATE_ATTRIBUTE_CREATE]:
		MASTER_DATA_PERMISSION_TEMPLATE_MANAGE,
	[MASTER_COMMAND_ITEM_TEMPLATE_ATTRIBUTE_CREATE_VARIANT_DEFINING]:
		MASTER_DATA_PERMISSION_VARIANT_MANAGE,
	[MASTER_COMMAND_ITEM_TEMPLATE_ATTRIBUTE_OPTION_CREATE]:
		MASTER_DATA_PERMISSION_TEMPLATE_MANAGE,
	[MASTER_COMMAND_ITEM_VARIANT_CREATE]: MASTER_DATA_PERMISSION_VARIANT_MANAGE,
} as const satisfies Record<ExtensionCommandId, MasterPermission>;

function isExtensionCommandId(
	command: MasterCommandId,
): command is ExtensionCommandId {
	return Object.hasOwn(EXTENSION_COMMAND_PERMISSION, command);
}

/**
 * Returns the extension-policy permission for a command.
 *
 * Null means the command is outside the extension-command authority map.
 * It must not be interpreted as permission-free.
 */
export function extensionPermissionForCommand(
	command: MasterCommandId,
): MasterPermission | null {
	return isExtensionCommandId(command)
		? EXTENSION_COMMAND_PERMISSION[command]
		: null;
}

const REGULATORY_EXTERNAL_ID_TOKENS: ReadonlySet<string> = new Set([
	"government",
	"national",
	"registration",
	"regulatory",
	"tax",
	"vat",
]);

/**
 * Provides a conservative fallback classification for external-ID type codes.
 *
 * Governed external-ID type metadata should remain the primary authority.
 */
export function isRegulatoryExternalIdType(externalIdType: string): boolean {
	const normalizedType = externalIdType
		.normalize("NFC")
		.trim()
		.replace(/([a-z])([A-Z])/gu, "$1_$2")
		.toLowerCase()
		.replace(/[\s/]+/gu, "_");

	if (normalizedType.length === 0) {
		return false;
	}

	return normalizedType
		.split(/[._-]+/u)
		.some((token) => REGULATORY_EXTERNAL_ID_TOKENS.has(token));
}

const CONTROL_RELATIONSHIP_TYPES: ReadonlySet<PartyRelationshipType> = new Set([
	"parent_of",
	"subsidiary_of",
	"owned_by",
]);

/** Ownership and corporate-control relationships require elevated authority. */
export function isControlRelationshipType(
	relationshipType: PartyRelationshipType,
): boolean {
	return CONTROL_RELATIONSHIP_TYPES.has(relationshipType);
}
