export const SALES_PERMISSION_CODES = [
	"sales.pricing.read",
	"sales.pricing.manage",
	"sales.quotation.read",
	"sales.quotation.create",
	"sales.quotation.update",
	"sales.quotation.approve",
	"sales.order.read",
	"sales.order.list",
	"sales.order.create",
	"sales.order.update",
	"sales.order.approve",
	"sales.order.post",
	"sales.order.release",
	"sales.order.hold",
	"sales.order.cancel",
	"sales.order.close",
	"sales.return.read",
	"sales.return.create",
	"sales.return.approve",
	"sales.return.cancel",
] as const;
export type SalesPermission = (typeof SALES_PERMISSION_CODES)[number];
