import { PAYROLL_PERMISSION_SETUP_MANAGE } from "../../kernel/execution/permissions";
import { definePayrollOperationRegistry } from "../../kernel/operations/define-registry";

const OWNER = "payroll-setup" as const;

export const PAYROLL_SETUP_COMMANDS = definePayrollOperationRegistry({
	createCalendar: {
		id: "payroll.setup.calendar.create",
		kind: "command",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "createCalendar",
	},
	updateCalendar: {
		id: "payroll.setup.calendar.update",
		kind: "command",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "updateCalendar",
	},
	archiveCalendar: {
		id: "payroll.setup.calendar.archive",
		kind: "command",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "archiveCalendar",
	},
	createPayGroup: {
		id: "payroll.setup.pay-group.create",
		kind: "command",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "createPayGroup",
	},
	updatePayGroup: {
		id: "payroll.setup.pay-group.update",
		kind: "command",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "updatePayGroup",
	},
	archivePayGroup: {
		id: "payroll.setup.pay-group.archive",
		kind: "command",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "archivePayGroup",
	},
	createPeriod: {
		id: "payroll.setup.period.create",
		kind: "command",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "createPeriod",
	},
	updatePeriod: {
		id: "payroll.setup.period.update",
		kind: "command",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "updatePeriod",
	},
	closePeriod: {
		id: "payroll.setup.period.close",
		kind: "command",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "closePeriod",
	},
	createEarningRule: {
		id: "payroll.setup.earning-rule.create",
		kind: "command",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "createEarningRule",
	},
	updateEarningRule: {
		id: "payroll.setup.earning-rule.update",
		kind: "command",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "updateEarningRule",
	},
	archiveEarningRule: {
		id: "payroll.setup.earning-rule.archive",
		kind: "command",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "archiveEarningRule",
	},
	supersedeEarningRule: {
		id: "payroll.setup.earning-rule.supersede",
		kind: "command",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "supersedeEarningRule",
	},
	createDeductionRule: {
		id: "payroll.setup.deduction-rule.create",
		kind: "command",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "createDeductionRule",
	},
	updateDeductionRule: {
		id: "payroll.setup.deduction-rule.update",
		kind: "command",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "updateDeductionRule",
	},
	archiveDeductionRule: {
		id: "payroll.setup.deduction-rule.archive",
		kind: "command",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "archiveDeductionRule",
	},
	supersedeDeductionRule: {
		id: "payroll.setup.deduction-rule.supersede",
		kind: "command",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "supersedeDeductionRule",
	},
	createStatutoryRule: {
		id: "payroll.setup.statutory-rule.create",
		kind: "command",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "createStatutoryRule",
	},
	updateStatutoryRule: {
		id: "payroll.setup.statutory-rule.update",
		kind: "command",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "updateStatutoryRule",
	},
	archiveStatutoryRule: {
		id: "payroll.setup.statutory-rule.archive",
		kind: "command",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "archiveStatutoryRule",
	},
	supersedeStatutoryRule: {
		id: "payroll.setup.statutory-rule.supersede",
		kind: "command",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "supersedeStatutoryRule",
	},
});

export const PAYROLL_SETUP_QUERIES = definePayrollOperationRegistry({
	getCalendar: {
		id: "payroll.setup.calendar.get",
		kind: "query",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "getCalendar",
	},
	listCalendars: {
		id: "payroll.setup.calendar.list",
		kind: "query",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "listCalendars",
	},
	getPayGroup: {
		id: "payroll.setup.pay-group.get",
		kind: "query",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "getPayGroup",
	},
	listPayGroups: {
		id: "payroll.setup.pay-group.list",
		kind: "query",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "listPayGroups",
	},
	getPeriod: {
		id: "payroll.setup.period.get",
		kind: "query",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "getPeriod",
	},
	listPeriods: {
		id: "payroll.setup.period.list",
		kind: "query",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "listPeriods",
	},
	getEarningRule: {
		id: "payroll.setup.earning-rule.get",
		kind: "query",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "getEarningRule",
	},
	getDeductionRule: {
		id: "payroll.setup.deduction-rule.get",
		kind: "query",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "getDeductionRule",
	},
	getStatutoryRule: {
		id: "payroll.setup.statutory-rule.get",
		kind: "query",
		owner: OWNER,
		permission: PAYROLL_PERMISSION_SETUP_MANAGE,
		publicName: "getStatutoryRule",
	},
});
