import {
	HUMAN_RESOURCES_CAREER_PLAN_ACKNOWLEDGED_EVENT,
	HUMAN_RESOURCES_COMPETENCY_ASSESSED_EVENT,
	HUMAN_RESOURCES_COMPETENCY_ASSESSMENT_EXPIRED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_CASE_ACTION_APPROVED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_CASE_APPEAL_RESOLVED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_CASE_APPEALED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_CASE_ASSIGNED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_CASE_CLOSED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_CASE_FINDING_RECORDED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_CASE_INTERIM_MEASURE_ISSUED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_CASE_OPENED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_CASE_REOPENED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_DOCUMENT_EXPIRED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_DOCUMENT_NEARING_EXPIRY_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_DOCUMENT_REGISTERED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_DOCUMENT_REJECTED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_DOCUMENT_VERIFIED_EVENT,
	HUMAN_RESOURCES_HEADCOUNT_PLAN_APPROVED_EVENT,
	HUMAN_RESOURCES_HEADCOUNT_RESERVATION_CONSUMED_EVENT,
	HUMAN_RESOURCES_HEADCOUNT_RESERVATION_RELEASED_EVENT,
	HUMAN_RESOURCES_HEADCOUNT_RESERVED_EVENT,
	HUMAN_RESOURCES_POLICY_ACKNOWLEDGEMENT_ACKNOWLEDGED_EVENT,
	HUMAN_RESOURCES_POLICY_ACKNOWLEDGEMENT_OUTSTANDING_EVENT,
	HUMAN_RESOURCES_SUCCESSION_CANDIDATE_APPROVED_EVENT,
	HUMAN_RESOURCES_SUCCESSION_READINESS_CHANGED_EVENT,
	HUMAN_RESOURCES_TALENT_POOL_MEMBER_REMOVED_EVENT,
	HUMAN_RESOURCES_TALENT_POOL_MEMBERSHIP_APPROVED_EVENT,
	HUMAN_RESOURCES_TALENT_PROFILE_UPDATED_EVENT,
	HUMAN_RESOURCES_WORK_ELIGIBILITY_EXPIRED_EVENT,
	HUMAN_RESOURCES_WORK_ELIGIBILITY_RENEWED_EVENT,
	HUMAN_RESOURCES_WORK_ELIGIBILITY_SUSPENDED_EVENT,
	HUMAN_RESOURCES_WORK_ELIGIBILITY_VERIFIED_EVENT,
} from "@afenda/events/schemas";
import { describe, expect, it } from "vitest";
import { HUMAN_RESOURCES_COMPLIANCE_EMISSIONS } from "../src/kernel/emissions/domains/compliance";
import { HUMAN_RESOURCES_EMPLOYEE_RELATIONS_EMISSIONS } from "../src/kernel/emissions/domains/employee-relations";
import { HUMAN_RESOURCES_TALENT_EMISSIONS } from "../src/kernel/emissions/domains/talent";
import { HUMAN_RESOURCES_WORKFORCE_PLANNING_EMISSIONS } from "../src/kernel/emissions/domains/workforce-planning";
import { HUMAN_RESOURCES_MUTATION_EMISSION_REGISTRY_RECORD } from "../src/kernel/emissions/registry";
import {
	HUMAN_RESOURCES_COMMAND_CAREER_PLAN_ACKNOWLEDGE,
	HUMAN_RESOURCES_COMMAND_CAREER_PLAN_ACTION_ADD,
	HUMAN_RESOURCES_COMMAND_CAREER_PLAN_ACTION_COMPLETE,
	HUMAN_RESOURCES_COMMAND_CAREER_PLAN_CLOSE,
	HUMAN_RESOURCES_COMMAND_CAREER_PLAN_CREATE,
	HUMAN_RESOURCES_COMMAND_CAREER_PLAN_UPDATE,
	HUMAN_RESOURCES_COMMAND_COMPETENCY_ASSESSMENT_EXPIRE,
	HUMAN_RESOURCES_COMMAND_COMPETENCY_ASSESSMENT_RECORD,
	HUMAN_RESOURCES_COMMAND_COMPETENCY_ASSESSMENT_SUPERSEDE,
	HUMAN_RESOURCES_COMMAND_COMPETENCY_CREATE,
	HUMAN_RESOURCES_COMMAND_COMPETENCY_RETIRE,
	HUMAN_RESOURCES_COMMAND_COMPETENCY_UPDATE,
	HUMAN_RESOURCES_COMMAND_CRITICAL_ROLE_READINESS_RECORD,
	HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_CREATE,
	HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_PUBLISH,
	HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_RETIRE,
	HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_UPDATE,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_ADD_EVIDENCE_REFERENCE,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_ADD_PARTICIPANT,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_APPROVE_ACTION,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_ASSIGN_OWNER,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_CLOSE,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_ISSUE_INTERIM_MEASURE,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_OPEN,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_RECOMMEND_ACTION,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_RECORD_APPEAL,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_RECORD_EVENT,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_RECORD_FINDING,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_REDACT_EVIDENCE_REFERENCE,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_REOPEN,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_RESOLVE_APPEAL,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_UPDATE_CLASSIFICATION,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_MARK_EXPIRED,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_REGISTER,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_REJECT,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_REVOKE_VERIFICATION,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_UPDATE_METADATA,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_VERIFY,
	HUMAN_RESOURCES_COMMAND_HEADCOUNT_PLAN_APPROVE,
	HUMAN_RESOURCES_COMMAND_HEADCOUNT_PLAN_CLOSE,
	HUMAN_RESOURCES_COMMAND_HEADCOUNT_PLAN_CREATE,
	HUMAN_RESOURCES_COMMAND_HEADCOUNT_PLAN_LINE_ADD,
	HUMAN_RESOURCES_COMMAND_HEADCOUNT_PLAN_LINE_REMOVE,
	HUMAN_RESOURCES_COMMAND_HEADCOUNT_PLAN_LINE_UPDATE,
	HUMAN_RESOURCES_COMMAND_HEADCOUNT_PLAN_REJECT,
	HUMAN_RESOURCES_COMMAND_HEADCOUNT_PLAN_SUBMIT,
	HUMAN_RESOURCES_COMMAND_HEADCOUNT_PLAN_SUPERSEDE,
	HUMAN_RESOURCES_COMMAND_HEADCOUNT_PLAN_UPDATE,
	HUMAN_RESOURCES_COMMAND_HEADCOUNT_RESERVATION_CONSUME,
	HUMAN_RESOURCES_COMMAND_HEADCOUNT_RESERVATION_RELEASE,
	HUMAN_RESOURCES_COMMAND_HEADCOUNT_RESERVE,
	HUMAN_RESOURCES_COMMAND_JOB_COMPETENCY_MAP,
	HUMAN_RESOURCES_COMMAND_JOB_COMPETENCY_REMOVE,
	HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_ACKNOWLEDGE,
	HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_ISSUE,
	HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_REVOKE,
	HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_SUPERSEDE,
	HUMAN_RESOURCES_COMMAND_SUCCESSION_CANDIDATE_APPROVE,
	HUMAN_RESOURCES_COMMAND_SUCCESSION_CANDIDATE_ASSESS_READINESS,
	HUMAN_RESOURCES_COMMAND_SUCCESSION_CANDIDATE_NOMINATE,
	HUMAN_RESOURCES_COMMAND_SUCCESSION_CANDIDATE_REMOVE,
	HUMAN_RESOURCES_COMMAND_SUCCESSION_PLAN_CLOSE,
	HUMAN_RESOURCES_COMMAND_SUCCESSION_PLAN_CREATE,
	HUMAN_RESOURCES_COMMAND_SUCCESSION_PLAN_UPDATE,
	HUMAN_RESOURCES_COMMAND_TALENT_POOL_CLOSE,
	HUMAN_RESOURCES_COMMAND_TALENT_POOL_CREATE,
	HUMAN_RESOURCES_COMMAND_TALENT_POOL_MEMBER_APPROVE,
	HUMAN_RESOURCES_COMMAND_TALENT_POOL_MEMBER_NOMINATE,
	HUMAN_RESOURCES_COMMAND_TALENT_POOL_MEMBER_REMOVE,
	HUMAN_RESOURCES_COMMAND_TALENT_POOL_UPDATE,
	HUMAN_RESOURCES_COMMAND_TALENT_PROFILE_ARCHIVE,
	HUMAN_RESOURCES_COMMAND_TALENT_PROFILE_ASSESSMENT_CONFIRM,
	HUMAN_RESOURCES_COMMAND_TALENT_PROFILE_ASSESSMENT_RECORD,
	HUMAN_RESOURCES_COMMAND_TALENT_PROFILE_CREATE,
	HUMAN_RESOURCES_COMMAND_TALENT_PROFILE_MOBILITY_RECORD,
	HUMAN_RESOURCES_COMMAND_TALENT_PROFILE_UPDATE,
	HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_CLOSE,
	HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_RECORD,
	HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_RENEW,
	HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_SUSPEND,
	HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_VERIFY,
	HUMAN_RESOURCES_COMPLIANCE_COMMAND_IDS,
	HUMAN_RESOURCES_EMPLOYEE_RELATIONS_COMMAND_IDS,
	HUMAN_RESOURCES_TALENT_COMMAND_IDS,
	HUMAN_RESOURCES_WORKFORCE_PLANNING_COMMAND_IDS,
} from "../src/kernel/operations/module-ids";
import { helperAssert as assert } from "./helpers/helper-assert";

interface EmissionExpectation {
	emission: "audit_only" | "domain_event";
	eventTypes?: readonly string[];
}

const EMPLOYEE_RELATIONS_MATRIX: Record<string, EmissionExpectation> = {
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_OPEN]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_EMPLOYEE_CASE_OPENED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_UPDATE_CLASSIFICATION]: {
		emission: "audit_only",
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_ASSIGN_OWNER]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_EMPLOYEE_CASE_ASSIGNED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_ADD_PARTICIPANT]: {
		emission: "audit_only",
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_RECORD_EVENT]: {
		emission: "audit_only",
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_ADD_EVIDENCE_REFERENCE]: {
		emission: "audit_only",
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_REDACT_EVIDENCE_REFERENCE]: {
		emission: "audit_only",
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_ISSUE_INTERIM_MEASURE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_EMPLOYEE_CASE_INTERIM_MEASURE_ISSUED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_RECORD_FINDING]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_EMPLOYEE_CASE_FINDING_RECORDED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_RECOMMEND_ACTION]: {
		emission: "audit_only",
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_APPROVE_ACTION]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_EMPLOYEE_CASE_ACTION_APPROVED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_RECORD_APPEAL]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_EMPLOYEE_CASE_APPEALED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_RESOLVE_APPEAL]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_EMPLOYEE_CASE_APPEAL_RESOLVED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_CLOSE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_EMPLOYEE_CASE_CLOSED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_CASE_REOPEN]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_EMPLOYEE_CASE_REOPENED_EVENT],
	},
};

const COMPLIANCE_MATRIX: Record<string, EmissionExpectation> = {
	[HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_CREATE]: {
		emission: "audit_only",
	},
	[HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_UPDATE]: {
		emission: "audit_only",
	},
	[HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_PUBLISH]: {
		emission: "audit_only",
	},
	[HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_RETIRE]: {
		emission: "audit_only",
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_REGISTER]: {
		emission: "domain_event",
		eventTypes: [
			HUMAN_RESOURCES_EMPLOYEE_DOCUMENT_REGISTERED_EVENT,
			HUMAN_RESOURCES_EMPLOYEE_DOCUMENT_NEARING_EXPIRY_EVENT,
		],
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_UPDATE_METADATA]: {
		emission: "audit_only",
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_VERIFY]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_EMPLOYEE_DOCUMENT_VERIFIED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_REJECT]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_EMPLOYEE_DOCUMENT_REJECTED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_REVOKE_VERIFICATION]: {
		emission: "audit_only",
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_MARK_EXPIRED]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_EMPLOYEE_DOCUMENT_EXPIRED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_RECORD]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_VERIFY]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_WORK_ELIGIBILITY_VERIFIED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_SUSPEND]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_WORK_ELIGIBILITY_SUSPENDED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_RENEW]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_WORK_ELIGIBILITY_RENEWED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_CLOSE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_WORK_ELIGIBILITY_EXPIRED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_ISSUE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_POLICY_ACKNOWLEDGEMENT_OUTSTANDING_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_ACKNOWLEDGE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_POLICY_ACKNOWLEDGEMENT_ACKNOWLEDGED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_REVOKE]: {
		emission: "audit_only",
	},
	[HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_SUPERSEDE]: {
		emission: "audit_only",
	},
};

const TALENT_MATRIX: Record<string, EmissionExpectation> = {
	[HUMAN_RESOURCES_COMMAND_COMPETENCY_CREATE]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_COMPETENCY_UPDATE]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_COMPETENCY_RETIRE]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_JOB_COMPETENCY_MAP]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_JOB_COMPETENCY_REMOVE]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_COMPETENCY_ASSESSMENT_RECORD]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_COMPETENCY_ASSESSED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_COMPETENCY_ASSESSMENT_SUPERSEDE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_COMPETENCY_ASSESSED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_COMPETENCY_ASSESSMENT_EXPIRE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_COMPETENCY_ASSESSMENT_EXPIRED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_TALENT_PROFILE_CREATE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_TALENT_PROFILE_UPDATED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_TALENT_PROFILE_UPDATE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_TALENT_PROFILE_UPDATED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_TALENT_PROFILE_ASSESSMENT_RECORD]: {
		emission: "audit_only",
	},
	[HUMAN_RESOURCES_COMMAND_TALENT_PROFILE_ASSESSMENT_CONFIRM]: {
		emission: "audit_only",
	},
	[HUMAN_RESOURCES_COMMAND_TALENT_PROFILE_ARCHIVE]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_TALENT_PROFILE_MOBILITY_RECORD]: {
		emission: "audit_only",
	},
	[HUMAN_RESOURCES_COMMAND_CRITICAL_ROLE_READINESS_RECORD]: {
		emission: "audit_only",
	},
	[HUMAN_RESOURCES_COMMAND_TALENT_POOL_CREATE]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_TALENT_POOL_UPDATE]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_TALENT_POOL_CLOSE]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_TALENT_POOL_MEMBER_NOMINATE]: {
		emission: "audit_only",
	},
	[HUMAN_RESOURCES_COMMAND_TALENT_POOL_MEMBER_APPROVE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_TALENT_POOL_MEMBERSHIP_APPROVED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_TALENT_POOL_MEMBER_REMOVE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_TALENT_POOL_MEMBER_REMOVED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_CAREER_PLAN_CREATE]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_CAREER_PLAN_UPDATE]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_CAREER_PLAN_ACKNOWLEDGE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_CAREER_PLAN_ACKNOWLEDGED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_CAREER_PLAN_ACTION_ADD]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_CAREER_PLAN_ACTION_COMPLETE]: {
		emission: "audit_only",
	},
	[HUMAN_RESOURCES_COMMAND_CAREER_PLAN_CLOSE]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_SUCCESSION_PLAN_CREATE]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_SUCCESSION_PLAN_UPDATE]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_SUCCESSION_CANDIDATE_NOMINATE]: {
		emission: "audit_only",
	},
	[HUMAN_RESOURCES_COMMAND_SUCCESSION_CANDIDATE_ASSESS_READINESS]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_SUCCESSION_READINESS_CHANGED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_SUCCESSION_CANDIDATE_APPROVE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_SUCCESSION_CANDIDATE_APPROVED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_SUCCESSION_CANDIDATE_REMOVE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_SUCCESSION_READINESS_CHANGED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_SUCCESSION_PLAN_CLOSE]: { emission: "audit_only" },
};

const WORKFORCE_PLANNING_MATRIX: Record<string, EmissionExpectation> = {
	[HUMAN_RESOURCES_COMMAND_HEADCOUNT_PLAN_CREATE]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_HEADCOUNT_PLAN_UPDATE]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_HEADCOUNT_PLAN_LINE_ADD]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_HEADCOUNT_PLAN_LINE_UPDATE]: {
		emission: "audit_only",
	},
	[HUMAN_RESOURCES_COMMAND_HEADCOUNT_PLAN_LINE_REMOVE]: {
		emission: "audit_only",
	},
	[HUMAN_RESOURCES_COMMAND_HEADCOUNT_PLAN_SUBMIT]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_HEADCOUNT_PLAN_APPROVE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_HEADCOUNT_PLAN_APPROVED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_HEADCOUNT_PLAN_REJECT]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_HEADCOUNT_PLAN_SUPERSEDE]: {
		emission: "audit_only",
	},
	[HUMAN_RESOURCES_COMMAND_HEADCOUNT_PLAN_CLOSE]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_HEADCOUNT_RESERVE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_HEADCOUNT_RESERVED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_HEADCOUNT_RESERVATION_RELEASE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_HEADCOUNT_RESERVATION_RELEASED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_HEADCOUNT_RESERVATION_CONSUME]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_HEADCOUNT_RESERVATION_CONSUMED_EVENT],
	},
};

function assertLockedMatrix(
	commandIds: readonly string[],
	expectedMatrix: Record<string, EmissionExpectation>,
) {
	for (const commandId of commandIds) {
		const expected = expectedMatrix[commandId];
		assert.isDefined(expected);

		const definition =
			HUMAN_RESOURCES_MUTATION_EMISSION_REGISTRY_RECORD[commandId];
		assert.isDefined(definition);
		assert.strictEqual(definition?.emissionMode, expected.emission);
		assert.strictEqual(definition?.auditRequired, true);
		assert.strictEqual(definition?.correlationRequired, true);

		if (expected.emission === "audit_only") {
			assert.deepEqual(definition?.eventTypes, []);
			continue;
		}

		assert.deepEqual(definition?.eventTypes, expected.eventTypes);
	}
}

describe("employee-relations emission registry", () => {
	it("registers every employee-relations command exactly once in domain file", () => {
		expect(Object.keys(HUMAN_RESOURCES_EMPLOYEE_RELATIONS_EMISSIONS)).toEqual([
			...HUMAN_RESOURCES_EMPLOYEE_RELATIONS_COMMAND_IDS,
		]);
	});

	it("matches the locked 15-row mode/eventType matrix", () => {
		assertLockedMatrix(
			HUMAN_RESOURCES_EMPLOYEE_RELATIONS_COMMAND_IDS,
			EMPLOYEE_RELATIONS_MATRIX,
		);
	});
});

describe("compliance emission registry", () => {
	it("registers every compliance command exactly once in domain file", () => {
		expect(Object.keys(HUMAN_RESOURCES_COMPLIANCE_EMISSIONS)).toEqual([
			...HUMAN_RESOURCES_COMPLIANCE_COMMAND_IDS,
		]);
	});

	it("matches the locked 20-row mode/eventType matrix", () => {
		assertLockedMatrix(
			HUMAN_RESOURCES_COMPLIANCE_COMMAND_IDS,
			COMPLIANCE_MATRIX,
		);
	});
});

describe("talent emission registry", () => {
	it("registers every talent command exactly once in domain file", () => {
		expect(Object.keys(HUMAN_RESOURCES_TALENT_EMISSIONS)).toEqual([
			...HUMAN_RESOURCES_TALENT_COMMAND_IDS,
		]);
	});

	it("matches the locked 34-row mode/eventType matrix", () => {
		assertLockedMatrix(HUMAN_RESOURCES_TALENT_COMMAND_IDS, TALENT_MATRIX);
	});
});

describe("workforce-planning emission registry", () => {
	it("registers every workforce-planning command exactly once in domain file", () => {
		expect(Object.keys(HUMAN_RESOURCES_WORKFORCE_PLANNING_EMISSIONS)).toEqual([
			...HUMAN_RESOURCES_WORKFORCE_PLANNING_COMMAND_IDS,
		]);
	});

	it("matches the locked 13-row mode/eventType matrix", () => {
		assertLockedMatrix(
			HUMAN_RESOURCES_WORKFORCE_PLANNING_COMMAND_IDS,
			WORKFORCE_PLANNING_MATRIX,
		);
	});
});
