import {
	HUMAN_RESOURCES_APPLICATION_REJECTED_EVENT,
	HUMAN_RESOURCES_APPLICATION_STAGE_CHANGED_EVENT,
	HUMAN_RESOURCES_APPLICATION_SUBMITTED_EVENT,
	HUMAN_RESOURCES_APPLICATION_WITHDRAWN_EVENT,
	HUMAN_RESOURCES_APPLICATION_REOPENED_EVENT,
	HUMAN_RESOURCES_CANDIDATE_ANONYMIZED_EVENT,
	HUMAN_RESOURCES_CANDIDATE_CONSENT_WITHDRAWN_EVENT,
	HUMAN_RESOURCES_CANDIDATE_CREATED_EVENT,
	HUMAN_RESOURCES_CANDIDATE_RETENTION_CHANGED_EVENT,
	HUMAN_RESOURCES_INTERVIEW_COMPLETED_EVENT,
	HUMAN_RESOURCES_INTERVIEW_SCHEDULED_EVENT,
	HUMAN_RESOURCES_OFFER_ACCEPTED_EVENT,
	HUMAN_RESOURCES_OFFER_APPROVED_EVENT,
	HUMAN_RESOURCES_OFFER_EXPIRED_EVENT,
	HUMAN_RESOURCES_OFFER_ISSUED_EVENT,
	HUMAN_RESOURCES_OFFER_REJECTED_EVENT,
	HUMAN_RESOURCES_OFFER_WITHDRAWN_EVENT,
	HUMAN_RESOURCES_REQUISITION_APPROVED_EVENT,
	HUMAN_RESOURCES_REQUISITION_CLOSED_EVENT,
	HUMAN_RESOURCES_REQUISITION_OPENED_EVENT,
} from "@afenda/events/schemas";
import { describe, expect, it } from "vitest";

import { HUMAN_RESOURCES_RECRUITMENT_EMISSIONS } from "../src/emissions/domains/recruitment";
import { HUMAN_RESOURCES_MUTATION_EMISSION_REGISTRY_RECORD } from "../src/emissions/registry";
import {
	HUMAN_RESOURCES_COMMAND_APPLICATION_CREATE,
	HUMAN_RESOURCES_COMMAND_APPLICATION_MOVE_TO_IN_REVIEW,
	HUMAN_RESOURCES_COMMAND_APPLICATION_MOVE_TO_INTERVIEWING,
	HUMAN_RESOURCES_COMMAND_APPLICATION_REJECT,
	HUMAN_RESOURCES_COMMAND_APPLICATION_WITHDRAW,
	HUMAN_RESOURCES_COMMAND_APPLICATION_REOPEN,
	HUMAN_RESOURCES_COMMAND_CANDIDATE_ANONYMIZE,
	HUMAN_RESOURCES_COMMAND_CANDIDATE_CHANGE_RETENTION,
	HUMAN_RESOURCES_COMMAND_CANDIDATE_CREATE,
	HUMAN_RESOURCES_COMMAND_CANDIDATE_UPDATE_PROFILE,
	HUMAN_RESOURCES_COMMAND_CANDIDATE_WITHDRAW_CONSENT,
	HUMAN_RESOURCES_COMMAND_INTERVIEW_CANCEL,
	HUMAN_RESOURCES_COMMAND_INTERVIEW_ASSIGN_INTERVIEWER,
	HUMAN_RESOURCES_COMMAND_INTERVIEW_RECORD_EVALUATION,
	HUMAN_RESOURCES_COMMAND_INTERVIEW_SCHEDULE,
	HUMAN_RESOURCES_COMMAND_OFFER_ACCEPT,
	HUMAN_RESOURCES_COMMAND_OFFER_AMEND_DRAFT,
	HUMAN_RESOURCES_COMMAND_OFFER_CREATE,
	HUMAN_RESOURCES_COMMAND_OFFER_DECLINE,
	HUMAN_RESOURCES_COMMAND_OFFER_EXPIRE,
	HUMAN_RESOURCES_COMMAND_OFFER_ISSUE,
	HUMAN_RESOURCES_COMMAND_OFFER_WITHDRAW,
	HUMAN_RESOURCES_COMMAND_OFFER_APPROVE,
	HUMAN_RESOURCES_COMMAND_REQUISITION_AMEND,
	HUMAN_RESOURCES_COMMAND_REQUISITION_APPROVE,
	HUMAN_RESOURCES_COMMAND_REQUISITION_ASSIGN_HIRING_MANAGER,
	HUMAN_RESOURCES_COMMAND_REQUISITION_CANCEL,
	HUMAN_RESOURCES_COMMAND_REQUISITION_CLOSE,
	HUMAN_RESOURCES_COMMAND_REQUISITION_CREATE_DRAFT,
	HUMAN_RESOURCES_COMMAND_REQUISITION_OPEN,
	HUMAN_RESOURCES_COMMAND_REQUISITION_PLACE_ON_HOLD,
	HUMAN_RESOURCES_COMMAND_REQUISITION_SUBMIT,
	HUMAN_RESOURCES_RECRUITMENT_COMMAND_IDS,
} from "../src/module-ids";

const EXPECTED_MATRIX: Record<
	string,
	{ emission: "audit_only" | "domain_event"; eventTypes?: readonly string[] }
> = {
	[HUMAN_RESOURCES_COMMAND_REQUISITION_CREATE_DRAFT]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_REQUISITION_AMEND]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_REQUISITION_SUBMIT]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_REQUISITION_APPROVE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_REQUISITION_APPROVED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_REQUISITION_OPEN]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_REQUISITION_OPENED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_REQUISITION_PLACE_ON_HOLD]: {
		emission: "audit_only",
	},
	[HUMAN_RESOURCES_COMMAND_REQUISITION_CLOSE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_REQUISITION_CLOSED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_REQUISITION_CANCEL]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_REQUISITION_ASSIGN_HIRING_MANAGER]: {
		emission: "audit_only",
	},
	[HUMAN_RESOURCES_COMMAND_CANDIDATE_CREATE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_CANDIDATE_CREATED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_CANDIDATE_UPDATE_PROFILE]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_CANDIDATE_WITHDRAW_CONSENT]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_CANDIDATE_CONSENT_WITHDRAWN_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_CANDIDATE_CHANGE_RETENTION]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_CANDIDATE_RETENTION_CHANGED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_CANDIDATE_ANONYMIZE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_CANDIDATE_ANONYMIZED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_APPLICATION_CREATE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_APPLICATION_SUBMITTED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_APPLICATION_MOVE_TO_IN_REVIEW]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_APPLICATION_STAGE_CHANGED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_APPLICATION_MOVE_TO_INTERVIEWING]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_APPLICATION_STAGE_CHANGED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_APPLICATION_REJECT]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_APPLICATION_REJECTED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_APPLICATION_WITHDRAW]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_APPLICATION_WITHDRAWN_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_APPLICATION_REOPEN]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_APPLICATION_REOPENED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_INTERVIEW_SCHEDULE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_INTERVIEW_SCHEDULED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_INTERVIEW_ASSIGN_INTERVIEWER]: {
		emission: "audit_only",
	},
	[HUMAN_RESOURCES_COMMAND_INTERVIEW_CANCEL]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_INTERVIEW_RECORD_EVALUATION]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_INTERVIEW_COMPLETED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_OFFER_CREATE]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_OFFER_AMEND_DRAFT]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_OFFER_ISSUE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_OFFER_ISSUED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_OFFER_ACCEPT]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_OFFER_ACCEPTED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_OFFER_DECLINE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_OFFER_REJECTED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_OFFER_EXPIRE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_OFFER_EXPIRED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_OFFER_WITHDRAW]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_OFFER_WITHDRAWN_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_OFFER_APPROVE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_OFFER_APPROVED_EVENT],
	},
};

describe("recruitment emission registry", () => {
	it("registers every recruitment command exactly once in domain file", () => {
		expect(Object.keys(HUMAN_RESOURCES_RECRUITMENT_EMISSIONS)).toEqual([
			...HUMAN_RESOURCES_RECRUITMENT_COMMAND_IDS,
		]);
	});

	it("matches the locked 30-row mode/eventType matrix", () => {
		for (const commandId of HUMAN_RESOURCES_RECRUITMENT_COMMAND_IDS) {
			const expected = EXPECTED_MATRIX[commandId];
			expect(expected).toBeDefined();

			const definition =
				HUMAN_RESOURCES_MUTATION_EMISSION_REGISTRY_RECORD[commandId];
			expect(definition).toBeDefined();
			expect(definition.emissionMode).toBe(expected.emission);
			expect(definition.auditRequired).toBe(true);
			expect(definition.correlationRequired).toBe(true);

			if (expected.emission === "audit_only") {
				expect(definition.eventTypes).toEqual([]);
				continue;
			}

			expect(definition.eventTypes).toEqual(expected.eventTypes);
		}
	});
});
