import {
	HUMAN_RESOURCES_ASSIGNMENT_CREATED_EVENT,
	HUMAN_RESOURCES_ASSIGNMENT_ENDED_EVENT,
	HUMAN_RESOURCES_DEPARTMENT_ACTIVATED_EVENT,
	HUMAN_RESOURCES_DEPARTMENT_ARCHIVED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_CREATED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_REHIRED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_TERMINATED_EVENT,
	HUMAN_RESOURCES_EMPLOYMENT_CHANGED_EVENT,
	HUMAN_RESOURCES_EMPLOYMENT_CONTRACT_CREATED_EVENT,
	HUMAN_RESOURCES_EMPLOYMENT_CONTRACT_CHANGED_EVENT,
	HUMAN_RESOURCES_EMPLOYMENT_CONTRACT_SUPERSEDED_EVENT,
	HUMAN_RESOURCES_EMPLOYMENT_STARTED_EVENT,
	HUMAN_RESOURCES_JOB_ACTIVATED_EVENT,
	HUMAN_RESOURCES_JOB_ARCHIVED_EVENT,
	HUMAN_RESOURCES_PERSON_CHANGED_EVENT,
	HUMAN_RESOURCES_PERSON_CONTACT_ADDED_EVENT,
	HUMAN_RESOURCES_PERSON_CONTACT_CHANGED_EVENT,
	HUMAN_RESOURCES_PERSON_CONTACT_RETIRED_EVENT,
	HUMAN_RESOURCES_PERSON_CREATED_EVENT,
	HUMAN_RESOURCES_PERSON_IDENTIFIER_ADDED_EVENT,
	HUMAN_RESOURCES_PERSON_IDENTIFIER_RETIRED_EVENT,
	HUMAN_RESOURCES_POSITION_ACTIVATED_EVENT,
	HUMAN_RESOURCES_POSITION_CLOSED_EVENT,
	HUMAN_RESOURCES_POSITION_FROZEN_EVENT,
	HUMAN_RESOURCES_REPORTING_LINE_ASSIGNED_EVENT,
	HUMAN_RESOURCES_REPORTING_LINE_CLOSED_EVENT,
	HUMAN_RESOURCES_REPORTING_LINE_REPLACED_EVENT,
	HUMAN_RESOURCES_WORKER_CHANGED_EVENT,
	HUMAN_RESOURCES_WORKER_CREATED_EVENT,
} from "@afenda/events/schemas";
import { describe, expect, it } from "vitest";

import { HUMAN_RESOURCES_CORE_ORGANIZATION_EMISSIONS } from "../src/emissions/domains/core-organization";
import { HUMAN_RESOURCES_WORKFORCE_FOUNDATION_EMISSIONS } from "../src/emissions/domains/workforce-foundation";
import { HUMAN_RESOURCES_LEGACY_EMISSION_CLASSIFICATIONS } from "../src/emissions/legacy-classifications";
import { HUMAN_RESOURCES_MUTATION_EMISSION_REGISTRY_RECORD } from "../src/emissions/registry";
import {
	HUMAN_RESOURCES_COMMAND_ASSIGNMENT_CREATE,
	HUMAN_RESOURCES_COMMAND_ASSIGNMENT_END,
	HUMAN_RESOURCES_COMMAND_DEPARTMENT_ACTIVATE,
	HUMAN_RESOURCES_COMMAND_DEPARTMENT_ARCHIVE,
	HUMAN_RESOURCES_COMMAND_DEPARTMENT_CREATE,
	HUMAN_RESOURCES_COMMAND_DEPARTMENT_UPDATE,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_CREATE,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_UPDATE,
	HUMAN_RESOURCES_COMMAND_EMPLOYMENT_AMEND,
	HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CORRECT,
	HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CONTRACT_CREATE,
	HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CONTRACT_CORRECT,
	HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CONTRACT_SUPERSEDE,
	HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CREATE,
	HUMAN_RESOURCES_COMMAND_JOB_ACTIVATE,
	HUMAN_RESOURCES_COMMAND_JOB_ARCHIVE,
	HUMAN_RESOURCES_COMMAND_JOB_CREATE,
	HUMAN_RESOURCES_COMMAND_JOB_UPDATE,
	HUMAN_RESOURCES_COMMAND_PERSON_CONTACT_ADD,
	HUMAN_RESOURCES_COMMAND_PERSON_CONTACT_RETIRE,
	HUMAN_RESOURCES_COMMAND_PERSON_CONTACT_UPDATE,
	HUMAN_RESOURCES_COMMAND_PERSON_CREATE,
	HUMAN_RESOURCES_COMMAND_PERSON_IDENTIFIER_ADD,
	HUMAN_RESOURCES_COMMAND_PERSON_IDENTIFIER_RETIRE,
	HUMAN_RESOURCES_COMMAND_PERSON_PREFERRED_NAME_UPDATE,
	HUMAN_RESOURCES_COMMAND_PERSON_PRIVACY_CLASSIFICATION_SET,
	HUMAN_RESOURCES_COMMAND_PERSON_UPDATE,
	HUMAN_RESOURCES_COMMAND_POSITION_ACTIVATE,
	HUMAN_RESOURCES_COMMAND_POSITION_CLOSE,
	HUMAN_RESOURCES_COMMAND_POSITION_CREATE,
	HUMAN_RESOURCES_COMMAND_POSITION_FREEZE,
	HUMAN_RESOURCES_COMMAND_POSITION_UPDATE,
	HUMAN_RESOURCES_COMMAND_REPORTING_LINE_ASSIGN_PRIMARY,
	HUMAN_RESOURCES_COMMAND_REPORTING_LINE_CLOSE,
	HUMAN_RESOURCES_COMMAND_REPORTING_LINE_REPLACE_PRIMARY,
	HUMAN_RESOURCES_COMMAND_WORKER_CHANGE_STATUS,
	HUMAN_RESOURCES_COMMAND_WORKER_CHANGE_TYPE,
	HUMAN_RESOURCES_COMMAND_WORKER_CREATE,
	HUMAN_RESOURCES_CORE_ORGANIZATION_COMMAND_IDS,
	HUMAN_RESOURCES_WORKFORCE_FOUNDATION_COMMAND_IDS,
} from "../src/module-ids";

const DRAINED_FROM_LEGACY = [
	HUMAN_RESOURCES_COMMAND_PERSON_CREATE,
	HUMAN_RESOURCES_COMMAND_PERSON_UPDATE,
	HUMAN_RESOURCES_COMMAND_WORKER_CREATE,
	HUMAN_RESOURCES_COMMAND_WORKER_CHANGE_TYPE,
	HUMAN_RESOURCES_COMMAND_WORKER_CHANGE_STATUS,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_CREATE,
] as const;

const EXPECTED_MATRIX: Record<
	string,
	{ emission: "audit_only" | "domain_event"; eventTypes?: readonly string[] }
> = {
	[HUMAN_RESOURCES_COMMAND_PERSON_CREATE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_PERSON_CREATED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_PERSON_UPDATE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_PERSON_CHANGED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_PERSON_PREFERRED_NAME_UPDATE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_PERSON_CHANGED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_PERSON_PRIVACY_CLASSIFICATION_SET]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_PERSON_CHANGED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_PERSON_CONTACT_ADD]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_PERSON_CONTACT_ADDED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_PERSON_CONTACT_UPDATE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_PERSON_CONTACT_CHANGED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_PERSON_CONTACT_RETIRE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_PERSON_CONTACT_RETIRED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_PERSON_IDENTIFIER_ADD]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_PERSON_IDENTIFIER_ADDED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_PERSON_IDENTIFIER_RETIRE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_PERSON_IDENTIFIER_RETIRED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_WORKER_CREATE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_WORKER_CREATED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_WORKER_CHANGE_TYPE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_WORKER_CHANGED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_WORKER_CHANGE_STATUS]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_WORKER_CHANGED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_CREATE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_EMPLOYEE_CREATED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYEE_UPDATE]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CREATE]: {
		emission: "domain_event",
		eventTypes: [
			HUMAN_RESOURCES_EMPLOYMENT_STARTED_EVENT,
			HUMAN_RESOURCES_EMPLOYEE_REHIRED_EVENT,
		],
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYMENT_AMEND]: {
		emission: "domain_event",
		eventTypes: [
			HUMAN_RESOURCES_EMPLOYMENT_CHANGED_EVENT,
			HUMAN_RESOURCES_EMPLOYEE_TERMINATED_EVENT,
		],
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CORRECT]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_EMPLOYMENT_CHANGED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CONTRACT_CREATE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_EMPLOYMENT_CONTRACT_CREATED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CONTRACT_CORRECT]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_EMPLOYMENT_CONTRACT_CHANGED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CONTRACT_SUPERSEDE]: {
		emission: "domain_event",
		eventTypes: [
			HUMAN_RESOURCES_EMPLOYMENT_CONTRACT_SUPERSEDED_EVENT,
			HUMAN_RESOURCES_EMPLOYMENT_CONTRACT_CREATED_EVENT,
		],
	},
	[HUMAN_RESOURCES_COMMAND_ASSIGNMENT_CREATE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_ASSIGNMENT_CREATED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_ASSIGNMENT_END]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_ASSIGNMENT_ENDED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_DEPARTMENT_CREATE]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_DEPARTMENT_UPDATE]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_DEPARTMENT_ACTIVATE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_DEPARTMENT_ACTIVATED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_DEPARTMENT_ARCHIVE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_DEPARTMENT_ARCHIVED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_JOB_CREATE]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_JOB_UPDATE]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_JOB_ACTIVATE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_JOB_ACTIVATED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_JOB_ARCHIVE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_JOB_ARCHIVED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_POSITION_CREATE]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_POSITION_UPDATE]: { emission: "audit_only" },
	[HUMAN_RESOURCES_COMMAND_POSITION_ACTIVATE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_POSITION_ACTIVATED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_POSITION_FREEZE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_POSITION_FROZEN_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_POSITION_CLOSE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_POSITION_CLOSED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_REPORTING_LINE_ASSIGN_PRIMARY]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_REPORTING_LINE_ASSIGNED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_REPORTING_LINE_CLOSE]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_REPORTING_LINE_CLOSED_EVENT],
	},
	[HUMAN_RESOURCES_COMMAND_REPORTING_LINE_REPLACE_PRIMARY]: {
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_REPORTING_LINE_REPLACED_EVENT],
	},
};

describe("workforce-foundation + core-organization emission registry", () => {
	it("registers every workforce-foundation command exactly once in domain file", () => {
		expect(Object.keys(HUMAN_RESOURCES_WORKFORCE_FOUNDATION_EMISSIONS)).toEqual(
			[...HUMAN_RESOURCES_WORKFORCE_FOUNDATION_COMMAND_IDS],
		);
	});

	it("registers every core-organization command exactly once in domain file", () => {
		expect(Object.keys(HUMAN_RESOURCES_CORE_ORGANIZATION_EMISSIONS)).toEqual([
			...HUMAN_RESOURCES_CORE_ORGANIZATION_COMMAND_IDS,
		]);
	});

	it("keeps drained commands out of legacy classifications", () => {
		for (const commandId of DRAINED_FROM_LEGACY) {
			expect(
				HUMAN_RESOURCES_LEGACY_EMISSION_CLASSIFICATIONS[
					commandId as keyof typeof HUMAN_RESOURCES_LEGACY_EMISSION_CLASSIFICATIONS
				],
			).toBeUndefined();
		}
	});

	it("matches the locked mode/eventType matrix with audit + correlation flags", () => {
		const sliceCommands = [
			...HUMAN_RESOURCES_WORKFORCE_FOUNDATION_COMMAND_IDS,
			...HUMAN_RESOURCES_CORE_ORGANIZATION_COMMAND_IDS,
		];

		for (const commandId of sliceCommands) {
			const expected = EXPECTED_MATRIX[commandId];
			expect(expected).toBeDefined();

			const definition =
				HUMAN_RESOURCES_MUTATION_EMISSION_REGISTRY_RECORD[commandId];
			expect(definition).toBeDefined();
			expect(definition.emissionMode).toBe(expected.emission);
			expect(definition.auditRequired).toBe(true);
			expect(definition.correlationRequired).toBe(true);

			if (expected.emission === "audit_only") {
				expect(definition.eventTypes).toEqual([]);
				continue;
			}

			expect(definition.eventTypes).toEqual(expected.eventTypes);
		}
	});
});
