import {
	HUMAN_RESOURCES_IMPROVEMENT_PLAN_COMPLETED_EVENT,
	HUMAN_RESOURCES_IMPROVEMENT_PLAN_STARTED_EVENT,
	HUMAN_RESOURCES_PERFORMANCE_CYCLE_OPENED_EVENT,
	HUMAN_RESOURCES_PERFORMANCE_GOAL_APPROVED_EVENT,
	HUMAN_RESOURCES_PERFORMANCE_REVIEW_FINALIZED_EVENT,
	HUMAN_RESOURCES_PERFORMANCE_REVIEW_REOPENED_EVENT,
} from "@afenda/events/schemas";

import {
	HUMAN_RESOURCES_COMMAND_IMPROVEMENT_PLAN_ACKNOWLEDGE,
	HUMAN_RESOURCES_COMMAND_IMPROVEMENT_PLAN_AMEND,
	HUMAN_RESOURCES_COMMAND_IMPROVEMENT_PLAN_CANCEL,
	HUMAN_RESOURCES_COMMAND_IMPROVEMENT_PLAN_CLOSE_UNSUCCESSFUL,
	HUMAN_RESOURCES_COMMAND_IMPROVEMENT_PLAN_COMPLETE,
	HUMAN_RESOURCES_COMMAND_IMPROVEMENT_PLAN_CREATE,
	HUMAN_RESOURCES_COMMAND_IMPROVEMENT_PLAN_OPEN,
	HUMAN_RESOURCES_COMMAND_IMPROVEMENT_PLAN_RECORD_CHECKPOINT,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_ADD_PARTICIPANT,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_CANCEL,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_CLOSE,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_CREATE,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_ENROLL_ELIGIBLE,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_OPEN,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_PUBLISH,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_REMOVE_PARTICIPANT,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_SET_ELIGIBILITY,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_SET_REVIEW_PERIODS,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_UPDATE,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_ACTIVATE,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_ALIGN,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_APPROVE,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_CANCEL,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_CLOSE,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_CREATE,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_RECORD_PROGRESS,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_REJECT,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_SUBMIT,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_UPDATE,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_ACKNOWLEDGE,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_ADD_DELEGATED_REVIEWER,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_CALIBRATE,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_FINALIZE,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_REOPEN,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_RETURN_FOR_CORRECTION,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_START,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_SUBMIT_DELEGATED_ASSESSMENT,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_SUBMIT_MANAGER_ASSESSMENT,
	HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_SUBMIT_SELF_ASSESSMENT,
	type HumanResourcesPerformanceCommandId,
} from "../../module-ids";

import {
	defineAuditOnlyEmission,
	defineDomainEventEmission,
} from "../define-emission";
import type { HumanResourcesMutationEmissionDefinition } from "../types";

export const HUMAN_RESOURCES_PERFORMANCE_EMISSIONS = {
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_CREATE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_CREATE,
		{
			domain: "performance",
			aggregateType: "performance_cycle",
		},
	),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_UPDATE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_UPDATE,
		{
			domain: "performance",
			aggregateType: "performance_cycle",
		},
	),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_OPEN]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_OPEN,
		{
			domain: "performance",
			aggregateType: "performance_cycle",
			eventTypes: [HUMAN_RESOURCES_PERFORMANCE_CYCLE_OPENED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_CLOSE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_CLOSE,
		{
			domain: "performance",
			aggregateType: "performance_cycle",
		},
	),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_CANCEL]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_CANCEL,
		{
			domain: "performance",
			aggregateType: "performance_cycle",
		},
	),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_PUBLISH]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_PUBLISH,
		{
			domain: "performance",
			aggregateType: "performance_cycle",
		},
	),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_SET_REVIEW_PERIODS]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_SET_REVIEW_PERIODS,
			{
				domain: "performance",
				aggregateType: "performance_cycle",
			},
		),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_SET_ELIGIBILITY]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_SET_ELIGIBILITY,
			{
				domain: "performance",
				aggregateType: "performance_cycle",
			},
		),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_ENROLL_ELIGIBLE]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_ENROLL_ELIGIBLE,
			{
				domain: "performance",
				aggregateType: "performance_cycle_participant",
			},
		),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_ADD_PARTICIPANT]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_ADD_PARTICIPANT,
			{
				domain: "performance",
				aggregateType: "performance_cycle_participant",
			},
		),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_REMOVE_PARTICIPANT]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_PERFORMANCE_CYCLE_REMOVE_PARTICIPANT,
			{
				domain: "performance",
				aggregateType: "performance_cycle_participant",
			},
		),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_CREATE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_CREATE,
		{
			domain: "performance",
			aggregateType: "performance_goal",
		},
	),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_UPDATE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_UPDATE,
		{
			domain: "performance",
			aggregateType: "performance_goal",
		},
	),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_SUBMIT]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_SUBMIT,
		{
			domain: "performance",
			aggregateType: "performance_goal",
		},
	),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_APPROVE]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_APPROVE,
		{
			domain: "performance",
			aggregateType: "performance_goal",
			eventTypes: [HUMAN_RESOURCES_PERFORMANCE_GOAL_APPROVED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_REJECT]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_REJECT,
		{
			domain: "performance",
			aggregateType: "performance_goal",
		},
	),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_RECORD_PROGRESS]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_RECORD_PROGRESS,
			{
				domain: "performance",
				aggregateType: "performance_goal",
			},
		),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_CLOSE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_CLOSE,
		{
			domain: "performance",
			aggregateType: "performance_goal",
		},
	),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_CANCEL]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_CANCEL,
		{
			domain: "performance",
			aggregateType: "performance_goal",
		},
	),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_ACTIVATE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_ACTIVATE,
		{
			domain: "performance",
			aggregateType: "performance_goal",
		},
	),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_ALIGN]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_PERFORMANCE_GOAL_ALIGN,
		{
			domain: "performance",
			aggregateType: "performance_goal",
		},
	),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_START]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_START,
		{
			domain: "performance",
			aggregateType: "performance_review",
		},
	),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_SUBMIT_SELF_ASSESSMENT]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_SUBMIT_SELF_ASSESSMENT,
			{
				domain: "performance",
				aggregateType: "performance_review",
			},
		),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_SUBMIT_MANAGER_ASSESSMENT]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_SUBMIT_MANAGER_ASSESSMENT,
			{
				domain: "performance",
				aggregateType: "performance_review",
			},
		),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_ADD_DELEGATED_REVIEWER]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_ADD_DELEGATED_REVIEWER,
			{
				domain: "performance",
				aggregateType: "performance_review",
			},
		),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_SUBMIT_DELEGATED_ASSESSMENT]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_SUBMIT_DELEGATED_ASSESSMENT,
			{
				domain: "performance",
				aggregateType: "performance_review",
			},
		),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_CALIBRATE]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_CALIBRATE,
			{
				domain: "performance",
				aggregateType: "performance_review",
			},
		),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_RETURN_FOR_CORRECTION]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_RETURN_FOR_CORRECTION,
			{
				domain: "performance",
				aggregateType: "performance_review",
			},
		),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_ACKNOWLEDGE]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_ACKNOWLEDGE,
			{
				domain: "performance",
				aggregateType: "performance_review",
			},
		),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_FINALIZE]:
		defineDomainEventEmission(
			HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_FINALIZE,
			{
				domain: "performance",
				aggregateType: "performance_review",
				eventTypes: [
					HUMAN_RESOURCES_PERFORMANCE_REVIEW_FINALIZED_EVENT,
				] as const,
			},
		),
	[HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_REOPEN]:
		defineDomainEventEmission(
			HUMAN_RESOURCES_COMMAND_PERFORMANCE_REVIEW_REOPEN,
			{
				domain: "performance",
				aggregateType: "performance_review",
				eventTypes: [
					HUMAN_RESOURCES_PERFORMANCE_REVIEW_REOPENED_EVENT,
				] as const,
			},
		),
	[HUMAN_RESOURCES_COMMAND_IMPROVEMENT_PLAN_CREATE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_IMPROVEMENT_PLAN_CREATE,
		{
			domain: "performance",
			aggregateType: "improvement_plan",
		},
	),
	[HUMAN_RESOURCES_COMMAND_IMPROVEMENT_PLAN_OPEN]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_IMPROVEMENT_PLAN_OPEN,
		{
			domain: "performance",
			aggregateType: "improvement_plan",
			eventTypes: [HUMAN_RESOURCES_IMPROVEMENT_PLAN_STARTED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_IMPROVEMENT_PLAN_ACKNOWLEDGE]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_IMPROVEMENT_PLAN_ACKNOWLEDGE,
			{
				domain: "performance",
				aggregateType: "improvement_plan",
			},
		),
	[HUMAN_RESOURCES_COMMAND_IMPROVEMENT_PLAN_RECORD_CHECKPOINT]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_IMPROVEMENT_PLAN_RECORD_CHECKPOINT,
			{
				domain: "performance",
				aggregateType: "improvement_plan",
			},
		),
	[HUMAN_RESOURCES_COMMAND_IMPROVEMENT_PLAN_AMEND]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_IMPROVEMENT_PLAN_AMEND,
		{
			domain: "performance",
			aggregateType: "improvement_plan",
		},
	),
	[HUMAN_RESOURCES_COMMAND_IMPROVEMENT_PLAN_COMPLETE]:
		defineDomainEventEmission(
			HUMAN_RESOURCES_COMMAND_IMPROVEMENT_PLAN_COMPLETE,
			{
				domain: "performance",
				aggregateType: "improvement_plan",
				eventTypes: [HUMAN_RESOURCES_IMPROVEMENT_PLAN_COMPLETED_EVENT] as const,
			},
		),
	[HUMAN_RESOURCES_COMMAND_IMPROVEMENT_PLAN_CLOSE_UNSUCCESSFUL]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_IMPROVEMENT_PLAN_CLOSE_UNSUCCESSFUL,
			{
				domain: "performance",
				aggregateType: "improvement_plan",
			},
		),
	[HUMAN_RESOURCES_COMMAND_IMPROVEMENT_PLAN_CANCEL]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_IMPROVEMENT_PLAN_CANCEL,
		{
			domain: "performance",
			aggregateType: "improvement_plan",
		},
	),
} satisfies Record<
	HumanResourcesPerformanceCommandId,
	HumanResourcesMutationEmissionDefinition
>;
