import {
	HUMAN_RESOURCES_APPLICATION_REJECTED_EVENT,
	HUMAN_RESOURCES_APPLICATION_STAGE_CHANGED_EVENT,
	HUMAN_RESOURCES_APPLICATION_SUBMITTED_EVENT,
	HUMAN_RESOURCES_APPLICATION_WITHDRAWN_EVENT,
	HUMAN_RESOURCES_CANDIDATE_CONSENT_WITHDRAWN_EVENT,
	HUMAN_RESOURCES_CANDIDATE_CREATED_EVENT,
	HUMAN_RESOURCES_CANDIDATE_RETENTION_CHANGED_EVENT,
	HUMAN_RESOURCES_INTERVIEW_COMPLETED_EVENT,
	HUMAN_RESOURCES_INTERVIEW_SCHEDULED_EVENT,
	HUMAN_RESOURCES_OFFER_ACCEPTED_EVENT,
	HUMAN_RESOURCES_OFFER_EXPIRED_EVENT,
	HUMAN_RESOURCES_OFFER_ISSUED_EVENT,
	HUMAN_RESOURCES_OFFER_REJECTED_EVENT,
	HUMAN_RESOURCES_OFFER_WITHDRAWN_EVENT,
	HUMAN_RESOURCES_REQUISITION_APPROVED_EVENT,
	HUMAN_RESOURCES_REQUISITION_CLOSED_EVENT,
	HUMAN_RESOURCES_REQUISITION_OPENED_EVENT,
} from "@afenda/events/schemas";

import {
	HUMAN_RESOURCES_COMMAND_APPLICATION_CREATE,
	HUMAN_RESOURCES_COMMAND_APPLICATION_MOVE_TO_IN_REVIEW,
	HUMAN_RESOURCES_COMMAND_APPLICATION_MOVE_TO_INTERVIEWING,
	HUMAN_RESOURCES_COMMAND_APPLICATION_REJECT,
	HUMAN_RESOURCES_COMMAND_APPLICATION_WITHDRAW,
	HUMAN_RESOURCES_COMMAND_CANDIDATE_CHANGE_RETENTION,
	HUMAN_RESOURCES_COMMAND_CANDIDATE_CREATE,
	HUMAN_RESOURCES_COMMAND_CANDIDATE_UPDATE_PROFILE,
	HUMAN_RESOURCES_COMMAND_CANDIDATE_WITHDRAW_CONSENT,
	HUMAN_RESOURCES_COMMAND_INTERVIEW_CANCEL,
	HUMAN_RESOURCES_COMMAND_INTERVIEW_RECORD_EVALUATION,
	HUMAN_RESOURCES_COMMAND_INTERVIEW_SCHEDULE,
	HUMAN_RESOURCES_COMMAND_OFFER_ACCEPT,
	HUMAN_RESOURCES_COMMAND_OFFER_AMEND_DRAFT,
	HUMAN_RESOURCES_COMMAND_OFFER_CREATE,
	HUMAN_RESOURCES_COMMAND_OFFER_DECLINE,
	HUMAN_RESOURCES_COMMAND_OFFER_EXPIRE,
	HUMAN_RESOURCES_COMMAND_OFFER_ISSUE,
	HUMAN_RESOURCES_COMMAND_OFFER_WITHDRAW,
	HUMAN_RESOURCES_COMMAND_REQUISITION_AMEND,
	HUMAN_RESOURCES_COMMAND_REQUISITION_APPROVE,
	HUMAN_RESOURCES_COMMAND_REQUISITION_CANCEL,
	HUMAN_RESOURCES_COMMAND_REQUISITION_CLOSE,
	HUMAN_RESOURCES_COMMAND_REQUISITION_CREATE_DRAFT,
	HUMAN_RESOURCES_COMMAND_REQUISITION_OPEN,
	HUMAN_RESOURCES_COMMAND_REQUISITION_PLACE_ON_HOLD,
	HUMAN_RESOURCES_COMMAND_REQUISITION_SUBMIT,
	type HumanResourcesRecruitmentCommandId,
} from "../../module-ids";

import {
	defineAuditOnlyEmission,
	defineDomainEventEmission,
} from "../define-emission";
import type { HumanResourcesMutationEmissionDefinition } from "../types";

export const HUMAN_RESOURCES_RECRUITMENT_EMISSIONS = {
	[HUMAN_RESOURCES_COMMAND_REQUISITION_CREATE_DRAFT]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_REQUISITION_CREATE_DRAFT,
		{
			domain: "recruitment",
			aggregateType: "requisition",
		},
	),
	[HUMAN_RESOURCES_COMMAND_REQUISITION_AMEND]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_REQUISITION_AMEND,
		{
			domain: "recruitment",
			aggregateType: "requisition",
		},
	),
	[HUMAN_RESOURCES_COMMAND_REQUISITION_SUBMIT]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_REQUISITION_SUBMIT,
		{
			domain: "recruitment",
			aggregateType: "requisition",
		},
	),
	[HUMAN_RESOURCES_COMMAND_REQUISITION_APPROVE]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_REQUISITION_APPROVE,
		{
			domain: "recruitment",
			aggregateType: "requisition",
			eventTypes: [HUMAN_RESOURCES_REQUISITION_APPROVED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_REQUISITION_OPEN]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_REQUISITION_OPEN,
		{
			domain: "recruitment",
			aggregateType: "requisition",
			eventTypes: [HUMAN_RESOURCES_REQUISITION_OPENED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_REQUISITION_PLACE_ON_HOLD]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_REQUISITION_PLACE_ON_HOLD,
		{
			domain: "recruitment",
			aggregateType: "requisition",
		},
	),
	[HUMAN_RESOURCES_COMMAND_REQUISITION_CLOSE]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_REQUISITION_CLOSE,
		{
			domain: "recruitment",
			aggregateType: "requisition",
			eventTypes: [HUMAN_RESOURCES_REQUISITION_CLOSED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_REQUISITION_CANCEL]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_REQUISITION_CANCEL,
		{
			domain: "recruitment",
			aggregateType: "requisition",
		},
	),
	[HUMAN_RESOURCES_COMMAND_CANDIDATE_CREATE]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_CANDIDATE_CREATE,
		{
			domain: "recruitment",
			aggregateType: "candidate",
			eventTypes: [HUMAN_RESOURCES_CANDIDATE_CREATED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_CANDIDATE_UPDATE_PROFILE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_CANDIDATE_UPDATE_PROFILE,
		{
			domain: "recruitment",
			aggregateType: "candidate",
		},
	),
	[HUMAN_RESOURCES_COMMAND_CANDIDATE_WITHDRAW_CONSENT]:
		defineDomainEventEmission(
			HUMAN_RESOURCES_COMMAND_CANDIDATE_WITHDRAW_CONSENT,
			{
				domain: "recruitment",
				aggregateType: "candidate",
				eventTypes: [HUMAN_RESOURCES_CANDIDATE_CONSENT_WITHDRAWN_EVENT] as const,
			},
		),
	[HUMAN_RESOURCES_COMMAND_CANDIDATE_CHANGE_RETENTION]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_CANDIDATE_CHANGE_RETENTION,
		{
			domain: "recruitment",
			aggregateType: "candidate",
			eventTypes: [HUMAN_RESOURCES_CANDIDATE_RETENTION_CHANGED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_APPLICATION_CREATE]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_APPLICATION_CREATE,
		{
			domain: "recruitment",
			aggregateType: "application",
			eventTypes: [HUMAN_RESOURCES_APPLICATION_SUBMITTED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_APPLICATION_MOVE_TO_IN_REVIEW]:
		defineDomainEventEmission(
			HUMAN_RESOURCES_COMMAND_APPLICATION_MOVE_TO_IN_REVIEW,
			{
				domain: "recruitment",
				aggregateType: "application",
				eventTypes: [HUMAN_RESOURCES_APPLICATION_STAGE_CHANGED_EVENT] as const,
			},
		),
	[HUMAN_RESOURCES_COMMAND_APPLICATION_MOVE_TO_INTERVIEWING]:
		defineDomainEventEmission(
			HUMAN_RESOURCES_COMMAND_APPLICATION_MOVE_TO_INTERVIEWING,
			{
				domain: "recruitment",
				aggregateType: "application",
				eventTypes: [HUMAN_RESOURCES_APPLICATION_STAGE_CHANGED_EVENT] as const,
			},
		),
	[HUMAN_RESOURCES_COMMAND_APPLICATION_REJECT]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_APPLICATION_REJECT,
		{
			domain: "recruitment",
			aggregateType: "application",
			eventTypes: [HUMAN_RESOURCES_APPLICATION_REJECTED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_APPLICATION_WITHDRAW]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_APPLICATION_WITHDRAW,
		{
			domain: "recruitment",
			aggregateType: "application",
			eventTypes: [HUMAN_RESOURCES_APPLICATION_WITHDRAWN_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_INTERVIEW_SCHEDULE]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_INTERVIEW_SCHEDULE,
		{
			domain: "recruitment",
			aggregateType: "interview",
			eventTypes: [HUMAN_RESOURCES_INTERVIEW_SCHEDULED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_INTERVIEW_CANCEL]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_INTERVIEW_CANCEL,
		{
			domain: "recruitment",
			aggregateType: "interview",
		},
	),
	[HUMAN_RESOURCES_COMMAND_INTERVIEW_RECORD_EVALUATION]:
		defineDomainEventEmission(
			HUMAN_RESOURCES_COMMAND_INTERVIEW_RECORD_EVALUATION,
			{
				domain: "recruitment",
				aggregateType: "interview",
				eventTypes: [HUMAN_RESOURCES_INTERVIEW_COMPLETED_EVENT] as const,
			},
		),
	[HUMAN_RESOURCES_COMMAND_OFFER_CREATE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_OFFER_CREATE,
		{
			domain: "recruitment",
			aggregateType: "offer",
		},
	),
	[HUMAN_RESOURCES_COMMAND_OFFER_AMEND_DRAFT]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_OFFER_AMEND_DRAFT,
		{
			domain: "recruitment",
			aggregateType: "offer",
		},
	),
	[HUMAN_RESOURCES_COMMAND_OFFER_ISSUE]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_OFFER_ISSUE,
		{
			domain: "recruitment",
			aggregateType: "offer",
			eventTypes: [HUMAN_RESOURCES_OFFER_ISSUED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_OFFER_ACCEPT]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_OFFER_ACCEPT,
		{
			domain: "recruitment",
			aggregateType: "offer",
			eventTypes: [HUMAN_RESOURCES_OFFER_ACCEPTED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_OFFER_DECLINE]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_OFFER_DECLINE,
		{
			domain: "recruitment",
			aggregateType: "offer",
			eventTypes: [HUMAN_RESOURCES_OFFER_REJECTED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_OFFER_EXPIRE]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_OFFER_EXPIRE,
		{
			domain: "recruitment",
			aggregateType: "offer",
			eventTypes: [HUMAN_RESOURCES_OFFER_EXPIRED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_OFFER_WITHDRAW]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_OFFER_WITHDRAW,
		{
			domain: "recruitment",
			aggregateType: "offer",
			eventTypes: [HUMAN_RESOURCES_OFFER_WITHDRAWN_EVENT] as const,
		},
	),
} satisfies Record<
	HumanResourcesRecruitmentCommandId,
	HumanResourcesMutationEmissionDefinition
>;
