/** Canonical Time command emission classifications. */
import {
	HUMAN_RESOURCES_TIME_ATTENDANCE_CORRECTED_EVENT,
	HUMAN_RESOURCES_TIME_ATTENDANCE_RECORDED_EVENT,
	HUMAN_RESOURCES_TIME_EXCEPTION_CREATED_EVENT,
	HUMAN_RESOURCES_TIME_OVERTIME_APPROVED_EVENT,
	HUMAN_RESOURCES_TIME_PAYROLL_HANDOFF_READY_EVENT,
	HUMAN_RESOURCES_TIME_SCHEDULE_PUBLISHED_EVENT,
	HUMAN_RESOURCES_TIME_TIMESHEET_APPROVAL_STEP_RECORDED_EVENT,
	HUMAN_RESOURCES_TIME_TIMESHEET_LOCKED_EVENT,
	HUMAN_RESOURCES_TIME_TIMESHEET_REOPENED_EVENT,
	HUMAN_RESOURCES_TIME_TIMESHEET_SUBMITTED_EVENT,
	HUMAN_RESOURCES_TIMESHEET_APPROVED_EVENT,
} from "@afenda/events/schemas";

import {
	HUMAN_RESOURCES_COMMAND_ATTENDANCE_BREAK_WAIVER_APPROVE,
	HUMAN_RESOURCES_COMMAND_ATTENDANCE_EVENT_CORRECT,
	HUMAN_RESOURCES_COMMAND_ATTENDANCE_EVENT_RECORD,
	HUMAN_RESOURCES_COMMAND_ATTENDANCE_EVENT_VOID,
	HUMAN_RESOURCES_COMMAND_ATTENDANCE_EVENTS_IMPORT,
	HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_CREATE,
	HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_EXCUSE,
	HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_REJECT,
	HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_RESOLVE,
	HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_REVIEW,
	HUMAN_RESOURCES_COMMAND_ATTENDANCE_SESSION_RESOLVE,
	HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CALENDAR_ASSIGN,
	HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CALENDAR_END,
	HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_APPROVE,
	HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_CANCEL,
	HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_CREATE,
	HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_RECORD_ACTUAL,
	HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_REJECT,
	HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_VERIFY,
	HUMAN_RESOURCES_COMMAND_SHIFT_ACTIVATE,
	HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGN,
	HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGNMENT_CANCEL,
	HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGNMENT_CHANGE,
	HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGNMENT_COMPLETE,
	HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGNMENT_PUBLISH,
	HUMAN_RESOURCES_COMMAND_SHIFT_BREAK_ADD,
	HUMAN_RESOURCES_COMMAND_SHIFT_BREAK_REMOVE,
	HUMAN_RESOURCES_COMMAND_SHIFT_CREATE,
	HUMAN_RESOURCES_COMMAND_SHIFT_DEACTIVATE,
	HUMAN_RESOURCES_COMMAND_SHIFT_SUPERSEDE,
	HUMAN_RESOURCES_COMMAND_SHIFT_UPDATE,
	HUMAN_RESOURCES_COMMAND_TIME_APPROVAL_AUTHORITY_ASSIGN,
	HUMAN_RESOURCES_COMMAND_TIME_APPROVAL_AUTHORITY_END,
	HUMAN_RESOURCES_COMMAND_TIME_POLICY_ACTIVATE,
	HUMAN_RESOURCES_COMMAND_TIME_POLICY_ASSIGN,
	HUMAN_RESOURCES_COMMAND_TIME_POLICY_CREATE,
	HUMAN_RESOURCES_COMMAND_TIME_POLICY_SUPERSEDE,
	HUMAN_RESOURCES_COMMAND_TIMESHEET_APPROVE,
	HUMAN_RESOURCES_COMMAND_TIMESHEET_CREATE,
	HUMAN_RESOURCES_COMMAND_TIMESHEET_ENTRY_ADD,
	HUMAN_RESOURCES_COMMAND_TIMESHEET_ENTRY_REMOVE,
	HUMAN_RESOURCES_COMMAND_TIMESHEET_ENTRY_UPDATE,
	HUMAN_RESOURCES_COMMAND_TIMESHEET_GENERATE_ENTRIES,
	HUMAN_RESOURCES_COMMAND_TIMESHEET_LOCK,
	HUMAN_RESOURCES_COMMAND_TIMESHEET_REJECT,
	HUMAN_RESOURCES_COMMAND_TIMESHEET_REOPEN,
	HUMAN_RESOURCES_COMMAND_TIMESHEET_RETURN,
	HUMAN_RESOURCES_COMMAND_TIMESHEET_SUBMIT,
	HUMAN_RESOURCES_COMMAND_TIMESHEET_SUPERSEDE,
	HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_ARCHIVE,
	HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_CREATE,
	HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_DATE_OVERRIDE_ADD,
	HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_DATE_OVERRIDE_REMOVE,
	HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_HOLIDAY_ADD,
	HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_HOLIDAY_REMOVE,
	HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_SCOPE_ASSIGN,
	HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_SCOPE_END,
	HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_SUPERSEDE,
	HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_UPDATE,
	type HumanResourcesTimeCommandId,
} from "../../module-ids";

import {
	defineAuditOnlyEmission,
	defineDomainEventEmission,
} from "../define-emission";
import { inferEmissionMetadata } from "../infer-emission-metadata";
import type { HumanResourcesMutationEmissionDefinition } from "../types";

export const HUMAN_RESOURCES_TIME_EMISSIONS = {
	[HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_CREATE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_CREATE,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_CREATE),
		},
	),
	[HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_SUPERSEDE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_SUPERSEDE,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_SUPERSEDE),
		},
	),
	[HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_UPDATE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_UPDATE,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_UPDATE),
		},
	),
	[HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_ARCHIVE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_ARCHIVE,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_ARCHIVE),
		},
	),
	[HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_HOLIDAY_ADD]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_HOLIDAY_ADD,
		{
			...inferEmissionMetadata(
				HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_HOLIDAY_ADD,
			),
		},
	),
	[HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_HOLIDAY_REMOVE]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_HOLIDAY_REMOVE,
			{
				...inferEmissionMetadata(
					HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_HOLIDAY_REMOVE,
				),
			},
		),
	[HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_DATE_OVERRIDE_ADD]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_DATE_OVERRIDE_ADD,
			{
				...inferEmissionMetadata(
					HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_DATE_OVERRIDE_ADD,
				),
			},
		),
	[HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_DATE_OVERRIDE_REMOVE]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_DATE_OVERRIDE_REMOVE,
			{
				...inferEmissionMetadata(
					HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_DATE_OVERRIDE_REMOVE,
				),
			},
		),
	[HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CALENDAR_ASSIGN]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CALENDAR_ASSIGN,
		{
			...inferEmissionMetadata(
				HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CALENDAR_ASSIGN,
			),
		},
	),
	[HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CALENDAR_END]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CALENDAR_END,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CALENDAR_END),
		},
	),
	[HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_SCOPE_ASSIGN]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_SCOPE_ASSIGN,
		{
			...inferEmissionMetadata(
				HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_SCOPE_ASSIGN,
			),
		},
	),
	[HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_SCOPE_END]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_SCOPE_END,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_SCOPE_END),
		},
	),
	[HUMAN_RESOURCES_COMMAND_TIME_POLICY_CREATE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_TIME_POLICY_CREATE,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_TIME_POLICY_CREATE),
		},
	),
	[HUMAN_RESOURCES_COMMAND_TIME_POLICY_ACTIVATE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_TIME_POLICY_ACTIVATE,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_TIME_POLICY_ACTIVATE),
		},
	),
	[HUMAN_RESOURCES_COMMAND_TIME_POLICY_SUPERSEDE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_TIME_POLICY_SUPERSEDE,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_TIME_POLICY_SUPERSEDE),
		},
	),
	[HUMAN_RESOURCES_COMMAND_TIME_POLICY_ASSIGN]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_TIME_POLICY_ASSIGN,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_TIME_POLICY_ASSIGN),
		},
	),
	[HUMAN_RESOURCES_COMMAND_TIME_APPROVAL_AUTHORITY_ASSIGN]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_TIME_APPROVAL_AUTHORITY_ASSIGN,
			{
				...inferEmissionMetadata(
					HUMAN_RESOURCES_COMMAND_TIME_APPROVAL_AUTHORITY_ASSIGN,
				),
			},
		),
	[HUMAN_RESOURCES_COMMAND_TIME_APPROVAL_AUTHORITY_END]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_TIME_APPROVAL_AUTHORITY_END,
			{
				...inferEmissionMetadata(
					HUMAN_RESOURCES_COMMAND_TIME_APPROVAL_AUTHORITY_END,
				),
			},
		),
	[HUMAN_RESOURCES_COMMAND_SHIFT_CREATE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_SHIFT_CREATE,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_SHIFT_CREATE),
		},
	),
	[HUMAN_RESOURCES_COMMAND_SHIFT_SUPERSEDE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_SHIFT_SUPERSEDE,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_SHIFT_SUPERSEDE),
		},
	),
	[HUMAN_RESOURCES_COMMAND_SHIFT_UPDATE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_SHIFT_UPDATE,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_SHIFT_UPDATE),
		},
	),
	[HUMAN_RESOURCES_COMMAND_SHIFT_ACTIVATE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_SHIFT_ACTIVATE,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_SHIFT_ACTIVATE),
		},
	),
	[HUMAN_RESOURCES_COMMAND_SHIFT_DEACTIVATE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_SHIFT_DEACTIVATE,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_SHIFT_DEACTIVATE),
		},
	),
	[HUMAN_RESOURCES_COMMAND_SHIFT_BREAK_ADD]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_SHIFT_BREAK_ADD,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_SHIFT_BREAK_ADD),
		},
	),
	[HUMAN_RESOURCES_COMMAND_SHIFT_BREAK_REMOVE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_SHIFT_BREAK_REMOVE,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_SHIFT_BREAK_REMOVE),
		},
	),
	[HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGN]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGN,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGN),
		},
	),
	[HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGNMENT_PUBLISH]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGNMENT_PUBLISH,
		{
			...inferEmissionMetadata(
				HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGNMENT_PUBLISH,
			),
			eventTypes: [HUMAN_RESOURCES_TIME_SCHEDULE_PUBLISHED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGNMENT_CANCEL]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGNMENT_CANCEL,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGNMENT_CANCEL),
		},
	),
	[HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGNMENT_CHANGE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGNMENT_CHANGE,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGNMENT_CHANGE),
		},
	),
	[HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGNMENT_COMPLETE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGNMENT_COMPLETE,
		{
			...inferEmissionMetadata(
				HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGNMENT_COMPLETE,
			),
		},
	),
	[HUMAN_RESOURCES_COMMAND_ATTENDANCE_EVENT_RECORD]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_ATTENDANCE_EVENT_RECORD,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_ATTENDANCE_EVENT_RECORD),
			eventTypes: [HUMAN_RESOURCES_TIME_ATTENDANCE_RECORDED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_ATTENDANCE_EVENTS_IMPORT]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_ATTENDANCE_EVENTS_IMPORT,
		{
			...inferEmissionMetadata(
				HUMAN_RESOURCES_COMMAND_ATTENDANCE_EVENTS_IMPORT,
			),
		},
	),
	[HUMAN_RESOURCES_COMMAND_ATTENDANCE_EVENT_CORRECT]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_ATTENDANCE_EVENT_CORRECT,
		{
			...inferEmissionMetadata(
				HUMAN_RESOURCES_COMMAND_ATTENDANCE_EVENT_CORRECT,
			),
			eventTypes: [HUMAN_RESOURCES_TIME_ATTENDANCE_CORRECTED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_ATTENDANCE_EVENT_VOID]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_ATTENDANCE_EVENT_VOID,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_ATTENDANCE_EVENT_VOID),
		},
	),
	[HUMAN_RESOURCES_COMMAND_ATTENDANCE_SESSION_RESOLVE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_ATTENDANCE_SESSION_RESOLVE,
		{
			...inferEmissionMetadata(
				HUMAN_RESOURCES_COMMAND_ATTENDANCE_SESSION_RESOLVE,
			),
		},
	),
	[HUMAN_RESOURCES_COMMAND_ATTENDANCE_BREAK_WAIVER_APPROVE]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_ATTENDANCE_BREAK_WAIVER_APPROVE,
			{
				...inferEmissionMetadata(
					HUMAN_RESOURCES_COMMAND_ATTENDANCE_BREAK_WAIVER_APPROVE,
				),
			},
		),
	[HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_CREATE]:
		defineDomainEventEmission(
			HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_CREATE,
			{
				...inferEmissionMetadata(
					HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_CREATE,
				),
				eventTypes: [HUMAN_RESOURCES_TIME_EXCEPTION_CREATED_EVENT] as const,
			},
		),
	[HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_REVIEW]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_REVIEW,
			{
				...inferEmissionMetadata(
					HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_REVIEW,
				),
			},
		),
	[HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_EXCUSE]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_EXCUSE,
			{
				...inferEmissionMetadata(
					HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_EXCUSE,
				),
			},
		),
	[HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_REJECT]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_REJECT,
			{
				...inferEmissionMetadata(
					HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_REJECT,
				),
			},
		),
	[HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_RESOLVE]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_RESOLVE,
			{
				...inferEmissionMetadata(
					HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_RESOLVE,
				),
			},
		),
	[HUMAN_RESOURCES_COMMAND_TIMESHEET_CREATE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_TIMESHEET_CREATE,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_TIMESHEET_CREATE),
		},
	),
	[HUMAN_RESOURCES_COMMAND_TIMESHEET_GENERATE_ENTRIES]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_TIMESHEET_GENERATE_ENTRIES,
		{
			...inferEmissionMetadata(
				HUMAN_RESOURCES_COMMAND_TIMESHEET_GENERATE_ENTRIES,
			),
		},
	),
	[HUMAN_RESOURCES_COMMAND_TIMESHEET_ENTRY_ADD]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_TIMESHEET_ENTRY_ADD,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_TIMESHEET_ENTRY_ADD),
		},
	),
	[HUMAN_RESOURCES_COMMAND_TIMESHEET_ENTRY_UPDATE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_TIMESHEET_ENTRY_UPDATE,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_TIMESHEET_ENTRY_UPDATE),
		},
	),
	[HUMAN_RESOURCES_COMMAND_TIMESHEET_ENTRY_REMOVE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_TIMESHEET_ENTRY_REMOVE,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_TIMESHEET_ENTRY_REMOVE),
		},
	),
	[HUMAN_RESOURCES_COMMAND_TIMESHEET_SUBMIT]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_TIMESHEET_SUBMIT,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_TIMESHEET_SUBMIT),
			eventTypes: [HUMAN_RESOURCES_TIME_TIMESHEET_SUBMITTED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_TIMESHEET_RETURN]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_TIMESHEET_RETURN,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_TIMESHEET_RETURN),
		},
	),
	[HUMAN_RESOURCES_COMMAND_TIMESHEET_APPROVE]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_TIMESHEET_APPROVE,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_TIMESHEET_APPROVE),
			eventTypes: [
				HUMAN_RESOURCES_TIME_TIMESHEET_APPROVAL_STEP_RECORDED_EVENT,
				HUMAN_RESOURCES_TIMESHEET_APPROVED_EVENT,
			] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_TIMESHEET_REJECT]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_TIMESHEET_REJECT,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_TIMESHEET_REJECT),
		},
	),
	[HUMAN_RESOURCES_COMMAND_TIMESHEET_REOPEN]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_TIMESHEET_REOPEN,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_TIMESHEET_REOPEN),
			eventTypes: [HUMAN_RESOURCES_TIME_TIMESHEET_REOPENED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_TIMESHEET_LOCK]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_TIMESHEET_LOCK,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_TIMESHEET_LOCK),
			eventTypes: [
				HUMAN_RESOURCES_TIME_TIMESHEET_LOCKED_EVENT,
				HUMAN_RESOURCES_TIME_PAYROLL_HANDOFF_READY_EVENT,
			] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_TIMESHEET_SUPERSEDE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_TIMESHEET_SUPERSEDE,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_TIMESHEET_SUPERSEDE),
		},
	),
	[HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_CREATE]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_CREATE,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_CREATE),
		},
	),
	[HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_APPROVE]: defineDomainEventEmission(
		HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_APPROVE,
		{
			...inferEmissionMetadata(
				HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_APPROVE,
			),
			eventTypes: [HUMAN_RESOURCES_TIME_OVERTIME_APPROVED_EVENT] as const,
		},
	),
	[HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_REJECT]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_REJECT,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_REJECT),
		},
	),
	[HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_CANCEL]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_CANCEL,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_CANCEL),
		},
	),
	[HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_RECORD_ACTUAL]:
		defineAuditOnlyEmission(
			HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_RECORD_ACTUAL,
			{
				...inferEmissionMetadata(
					HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_RECORD_ACTUAL,
				),
			},
		),
	[HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_VERIFY]: defineAuditOnlyEmission(
		HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_VERIFY,
		{
			...inferEmissionMetadata(HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_VERIFY),
		},
	),
} satisfies Record<
	HumanResourcesTimeCommandId,
	HumanResourcesMutationEmissionDefinition
>;
