import type { PlatformPermissionCatalogRow } from "../platform-permission-catalog-reconciler";

export const ERP_PLATFORM_PERMISSIONS = [
	{
		code: "sales.pricing.read",
		module: "sales",
		description: "Read Sales price books and calculation traces",
		sensitive: false,
	},
	{
		code: "sales.pricing.manage",
		module: "sales",
		description: "Manage Sales price books and commercial conditions",
		sensitive: true,
	},
	{
		code: "sales.quotation.read",
		module: "sales",
		description: "Read Sales quotations",
		sensitive: false,
	},
	{
		code: "sales.quotation.create",
		module: "sales",
		description: "Create Sales quotations",
		sensitive: true,
	},
	{
		code: "sales.quotation.update",
		module: "sales",
		description: "Revise and transition Sales quotations",
		sensitive: true,
	},
	{
		code: "sales.quotation.approve",
		module: "sales",
		description: "Approve or reject Sales quotations",
		sensitive: true,
	},
	{
		code: "sales.order.create",
		module: "sales",
		description: "Create draft sales orders",
		sensitive: true,
	},
	{
		code: "sales.order.update",
		module: "sales",
		description: "Add or update lines on draft sales orders",
		sensitive: true,
	},
	{
		code: "sales.order.approve",
		module: "sales",
		description: "Approve Sales orders",
		sensitive: true,
	},
	{
		code: "sales.order.post",
		module: "sales",
		description: "Validate, confirm, and release Sales orders",
		sensitive: true,
	},
	{
		code: "sales.order.release",
		module: "sales",
		description: "Release approved Sales orders to fulfillment",
		sensitive: true,
	},
	{
		code: "sales.order.hold",
		module: "sales",
		description: "Place and resolve Sales-order holds",
		sensitive: true,
	},
	{
		code: "sales.order.cancel",
		module: "sales",
		description: "Cancel draft or posted sales orders",
		sensitive: true,
	},
	{
		code: "sales.order.close",
		module: "sales",
		description: "Close fulfilled or cancelled Sales orders",
		sensitive: true,
	},
	{
		code: "sales.order.read",
		module: "sales",
		description: "Read a single sales order by id",
		sensitive: false,
	},
	{
		code: "sales.order.list",
		module: "sales",
		description: "List organization sales orders",
		sensitive: false,
	},
	{
		code: "sales.return.read",
		module: "sales",
		description: "Read Sales return authorizations",
		sensitive: false,
	},
	{
		code: "sales.return.create",
		module: "sales",
		description: "Create Sales return authorizations",
		sensitive: true,
	},
	{
		code: "sales.return.approve",
		module: "sales",
		description: "Approve, reject, or close Sales return authorizations",
		sensitive: true,
	},
	{
		code: "sales.return.cancel",
		module: "sales",
		description: "Cancel Sales return authorizations",
		sensitive: true,
	},
	{
		code: "purchasing.order.create",
		module: "purchasing",
		description: "Create draft purchase orders",
		sensitive: true,
	},
	{
		code: "purchasing.order.update",
		module: "purchasing",
		description: "Add or update lines on draft purchase orders",
		sensitive: true,
	},
	{
		code: "purchasing.order.post",
		module: "purchasing",
		description: "Post draft purchase orders and freeze snapshots",
		sensitive: true,
	},
	{
		code: "purchasing.order.cancel",
		module: "purchasing",
		description: "Cancel draft purchase orders",
		sensitive: true,
	},
	{
		code: "purchasing.order.close",
		module: "purchasing",
		description:
			"Close posted purchase orders (terminate remaining commitment)",
		sensitive: true,
	},
	{
		code: "purchasing.order.read",
		module: "purchasing",
		description: "Read a single purchase order by id",
		sensitive: false,
	},
	{
		code: "purchasing.order.list",
		module: "purchasing",
		description: "List organization purchase orders",
		sensitive: false,
	},
	{
		code: "inventory.movement.create",
		module: "inventory",
		description: "Create draft stock movements and add lines",
		sensitive: true,
	},
	{
		code: "inventory.movement.post",
		module: "inventory",
		description: "Post stock movements and create compensating reversals",
		sensitive: true,
	},
	{
		code: "inventory.movement.cancel",
		module: "inventory",
		description: "Cancel draft stock movements",
		sensitive: true,
	},
	{
		code: "inventory.movement.read",
		module: "inventory",
		description: "Read and list organization stock movements",
		sensitive: false,
	},
	{
		code: "inventory.reservation.create",
		module: "inventory",
		description: "Create stock reservations",
		sensitive: true,
	},
	{
		code: "inventory.reservation.release",
		module: "inventory",
		description: "Release active stock reservations",
		sensitive: true,
	},
	{
		code: "inventory.availability.read",
		module: "inventory",
		description: "Read organization stock availability",
		sensitive: false,
	},
	{
		code: "inventory.adjustment.post",
		module: "inventory",
		description: "Create and post manual stock adjustments",
		sensitive: true,
	},
	{
		code: "receiving.receipt.read",
		module: "receiving",
		description: "Read organization goods receipts and discrepancies",
		sensitive: false,
	},
	{
		code: "receiving.receipt.create",
		module: "receiving",
		description: "Create draft goods receipts",
		sensitive: true,
	},
	{
		code: "receiving.receipt.update",
		module: "receiving",
		description: "Add and update lines on draft goods receipts",
		sensitive: true,
	},
	{
		code: "receiving.receipt.post",
		module: "receiving",
		description: "Post draft goods receipts to inventory",
		sensitive: true,
	},
	{
		code: "receiving.receipt.cancel",
		module: "receiving",
		description: "Cancel draft goods receipts",
		sensitive: true,
	},
	{
		code: "receiving.receipt.reverse",
		module: "receiving",
		description: "Reverse posted goods receipts with compensating documents",
		sensitive: true,
	},
	{
		code: "receiving.discrepancy.record",
		module: "receiving",
		description: "Record receiving discrepancies",
		sensitive: true,
	},
	{
		code: "receiving.discrepancy.resolve",
		module: "receiving",
		description: "Resolve receiving discrepancies",
		sensitive: true,
	},
	{
		code: "fulfillment.delivery.read",
		module: "fulfillment",
		description:
			"Read organization deliveries, picks, packs, and proof of delivery",
		sensitive: false,
	},
	{
		code: "fulfillment.delivery.create",
		module: "fulfillment",
		description: "Create draft deliveries",
		sensitive: true,
	},
	{
		code: "fulfillment.delivery.update",
		module: "fulfillment",
		description: "Add and update lines on draft deliveries",
		sensitive: true,
	},
	{
		code: "fulfillment.picking.confirm",
		module: "fulfillment",
		description: "Start and confirm picking operations",
		sensitive: true,
	},
	{
		code: "fulfillment.packing.confirm",
		module: "fulfillment",
		description: "Confirm packing operations",
		sensitive: true,
	},
	{
		code: "fulfillment.delivery.post",
		module: "fulfillment",
		description: "Post deliveries and issue inventory",
		sensitive: true,
	},
	{
		code: "fulfillment.delivery.cancel",
		module: "fulfillment",
		description: "Cancel draft, picking, or packed deliveries before post",
		sensitive: true,
	},
	{
		code: "fulfillment.pod.record",
		module: "fulfillment",
		description: "Record proof of delivery and mark as delivered",
		sensitive: true,
	},
	{
		code: "fulfillment.delivery.close",
		module: "fulfillment",
		description: "Close delivered deliveries",
		sensitive: true,
	},
	{
		code: "receivables.invoice.read",
		module: "receivables",
		description: "Read organization sales invoices",
		sensitive: false,
	},
	{
		code: "receivables.invoice.create",
		module: "receivables",
		description: "Create draft sales invoices",
		sensitive: true,
	},
	{
		code: "receivables.invoice.update",
		module: "receivables",
		description: "Update draft sales invoices and lines",
		sensitive: true,
	},
	{
		code: "receivables.invoice.post",
		module: "receivables",
		description: "Post sales invoices",
		sensitive: true,
	},
	{
		code: "receivables.invoice.cancel",
		module: "receivables",
		description: "Cancel draft sales invoices",
		sensitive: true,
	},
	{
		code: "receivables.invoice.close",
		module: "receivables",
		description: "Close fully settled sales invoices",
		sensitive: true,
	},
	{
		code: "receivables.credit_note.issue",
		module: "receivables",
		description: "Issue sales credit notes",
		sensitive: true,
	},
	{
		code: "receivables.receipt.apply",
		module: "receivables",
		description: "Apply posted customer receipts to invoices",
		sensitive: true,
	},
	{
		code: "receivables.receipt_application.reverse",
		module: "receivables",
		description: "Reverse customer receipt applications",
		sensitive: true,
	},
	{
		code: "receivables.balance.read",
		module: "receivables",
		description: "Read customer AR balances",
		sensitive: false,
	},
	{
		code: "receivables.aging.read",
		module: "receivables",
		description: "Read customer AR aging",
		sensitive: false,
	},
	{
		code: "payables.read",
		module: "payables",
		description:
			"Read organization supplier invoices, credit notes, matches, allocations, and balances",
		sensitive: false,
	},
	{
		code: "payables.manage",
		module: "payables",
		description:
			"Create, match, post, cancel, and allocate organization payables",
		sensitive: true,
	},
	{
		code: "payments.payment.read",
		module: "payments",
		description: "Read payments and their application instructions",
		sensitive: false,
	},
	{
		code: "payments.payment.create",
		module: "payments",
		description: "Create draft payments",
		sensitive: true,
	},
	{
		code: "payments.payment.update",
		module: "payments",
		description: "Update draft payments",
		sensitive: true,
	},
	{
		code: "payments.payment.post",
		module: "payments",
		description: "Post payments (settle money movement)",
		sensitive: true,
	},
	{
		code: "payments.payment.reverse",
		module: "payments",
		description: "Reverse posted payments",
		sensitive: true,
	},
	{
		code: "payments.refund.create",
		module: "payments",
		description: "Create refund instructions",
		sensitive: true,
	},
	{
		code: "payments.refund.post",
		module: "payments",
		description: "Post refunds",
		sensitive: true,
	},
	{
		code: "payments.transfer.create",
		module: "payments",
		description: "Create internal payment transfers",
		sensitive: true,
	},
	{
		code: "payments.transfer.post",
		module: "payments",
		description: "Post internal payment transfers",
		sensitive: true,
	},
	{
		code: "payments.application_instruction.manage",
		module: "payments",
		description: "Manage payment application instructions",
		sensitive: true,
	},
	{
		code: "payments.account.manage",
		module: "payments",
		description: "Manage payment accounts",
		sensitive: true,
	},
	{
		code: "payments.account.read",
		module: "payments",
		description: "Read payment accounts",
		sensitive: false,
	},
	{
		code: "payments.availability.read",
		module: "payments",
		description: "Read payment application availability",
		sensitive: false,
	},
	{
		code: "accounting.journal.read",
		module: "accounting",
		description: "Read organization journals and ledger postings",
		sensitive: false,
	},
	{
		code: "accounting.journal.create",
		module: "accounting",
		description: "Create draft journals and add journal lines",
		sensitive: true,
	},
	{
		code: "accounting.journal.update",
		module: "accounting",
		description: "Update draft journals and journal lines",
		sensitive: true,
	},
	{
		code: "accounting.journal.post",
		module: "accounting",
		description: "Post balanced draft journals to the ledger",
		sensitive: true,
	},
	{
		code: "accounting.journal.reverse",
		module: "accounting",
		description: "Reverse posted journals with compensating entries",
		sensitive: true,
	},
	{
		code: "accounting.trial_balance.read",
		module: "accounting",
		description: "Read organization trial balance",
		sensitive: false,
	},
	{
		code: "accounting.ledger.read",
		module: "accounting",
		description: "Read ledger account activity and source posting traces",
		sensitive: false,
	},
	{
		code: "accounting.period.read",
		module: "accounting",
		description: "Read organization accounting periods",
		sensitive: false,
	},
	{
		code: "accounting.period.open",
		module: "accounting",
		description: "Open new accounting periods",
		sensitive: true,
	},
	{
		code: "accounting.period.soft_close",
		module: "accounting",
		description: "Soft-close open accounting periods",
		sensitive: true,
	},
	{
		code: "accounting.period.close",
		module: "accounting",
		description: "Close soft-closed accounting periods",
		sensitive: true,
	},
	{
		code: "accounting.period.reopen",
		module: "accounting",
		description: "Reopen soft-closed or closed accounting periods",
		sensitive: true,
	},
	{
		code: "accounting.account.read",
		module: "accounting",
		description: "Read charts of accounts, ledger accounts, and role mappings",
		sensitive: false,
	},
	{
		code: "accounting.account.manage",
		module: "accounting",
		description:
			"Create and manage charts of accounts, ledger accounts, and role mappings",
		sensitive: true,
	},
	{
		code: "accounting.posting_rule.manage",
		module: "accounting",
		description: "Manage posting profiles and posting profile lines",
		sensitive: true,
	},
	{
		code: "accounting.exception.read",
		module: "accounting",
		description: "Read financial posting exceptions",
		sensitive: false,
	},
	{
		code: "accounting.exception.manage",
		module: "accounting",
		description: "Resolve and retry financial posting exceptions",
		sensitive: true,
	},
] as const satisfies readonly PlatformPermissionCatalogRow[];
