import type { PlatformPermissionCatalogRow } from "../platform-permission-catalog-reconciler";

export const MASTER_DATA_PLATFORM_PERMISSIONS = [
	{
		code: "master_data.read",
		module: "master_data",
		description: "Read organization master data (party, item, warehouse)",
		sensitive: false,
	},
	{
		code: "master_data.manage",
		module: "master_data",
		description: "Create and mutate organization master data",
		sensitive: true,
	},
	{
		code: "master_data.approve",
		module: "master_data",
		description: "Approve or reject master-data change requests (checker)",
		sensitive: true,
	},
	{
		code: "master_data.reference_read",
		module: "master_data",
		description: "Read platform reference values used by ERP master data",
		sensitive: false,
	},
	{
		code: "master_data.dimension_read",
		module: "master_data",
		description: "Read organization dimension masters",
		sensitive: false,
	},
	{
		code: "master_data.dimension_create",
		module: "master_data",
		description: "Create organization dimension masters",
		sensitive: true,
	},
	{
		code: "master_data.dimension_update",
		module: "master_data",
		description: "Update organization dimension masters",
		sensitive: true,
	},
	{
		code: "master_data.dimension_activate",
		module: "master_data",
		description: "Activate organization dimension masters",
		sensitive: true,
	},
	{
		code: "master_data.dimension_archive",
		module: "master_data",
		description: "Archive organization dimension masters",
		sensitive: true,
	},
	{
		code: "master_data.party_read",
		module: "master_data",
		description: "Read party masters and party extensions",
		sensitive: false,
	},
	{
		code: "master_data.party_create",
		module: "master_data",
		description: "Create party masters",
		sensitive: true,
	},
	{
		code: "master_data.party_update",
		module: "master_data",
		description: "Update party masters",
		sensitive: true,
	},
	{
		code: "master_data.party_suspend",
		module: "master_data",
		description: "Suspend party masters from operational use",
		sensitive: true,
	},
	{
		code: "master_data.item_read",
		module: "master_data",
		description: "Read item, item-group, template, and variant masters",
		sensitive: false,
	},
	{
		code: "master_data.item_create",
		module: "master_data",
		description: "Create item masters",
		sensitive: true,
	},
	{
		code: "master_data.item_update",
		module: "master_data",
		description: "Update item masters",
		sensitive: true,
	},
	{
		code: "master_data.item_suspend",
		module: "master_data",
		description: "Suspend item masters from operational use",
		sensitive: true,
	},
	{
		code: "master_data.item_extension_manage",
		module: "master_data",
		description:
			"Manage item groups, UoM conversions, barcodes, aliases, and item external IDs",
		sensitive: true,
	},
	{
		code: "master_data.warehouse_manage",
		module: "master_data",
		description: "Manage warehouse master identities",
		sensitive: true,
	},
	{
		code: "master_data.payment_term_manage",
		module: "master_data",
		description: "Manage payment-term masters",
		sensitive: true,
	},
	{
		code: "master_data.tax_registration_manage",
		module: "master_data",
		description: "Manage tax-registration masters",
		sensitive: true,
	},
	{
		code: "master_data.template_manage",
		module: "master_data",
		description: "Manage item templates and template attributes",
		sensitive: true,
	},
	{
		code: "master_data.variant_manage",
		module: "master_data",
		description: "Manage item variants and variant attribute values",
		sensitive: true,
	},
	{
		code: "master_data.change_request_create",
		module: "master_data",
		description: "Create controlled master-data change requests",
		sensitive: true,
	},
	{
		code: "master_data.change_request_submit",
		module: "master_data",
		description: "Submit controlled master-data change requests for review",
		sensitive: true,
	},
	{
		code: "master_data.change_request_approve",
		module: "master_data",
		description: "Approve controlled master-data change requests",
		sensitive: true,
	},
	{
		code: "master_data.change_request_apply",
		module: "master_data",
		description: "Apply approved master-data change requests",
		sensitive: true,
	},
	{
		code: "master_data.import_create",
		module: "master_data",
		description: "Create master-data import batches",
		sensitive: true,
	},
	{
		code: "master_data.import_validate",
		module: "master_data",
		description: "Validate master-data import batches",
		sensitive: true,
	},
	{
		code: "master_data.import_approve",
		module: "master_data",
		description: "Approve master-data import batches",
		sensitive: true,
	},
	{
		code: "master_data.import_apply",
		module: "master_data",
		description: "Apply approved master-data import batches",
		sensitive: true,
	},
	{
		code: "master_data.import_cancel",
		module: "master_data",
		description: "Cancel master-data import batches",
		sensitive: true,
	},
	{
		code: "master_data.search_rebuild",
		module: "master_data",
		description: "Rebuild master-data search projections",
		sensitive: true,
	},
	{
		code: "master_data.duplicate_review",
		module: "master_data",
		description: "Review master-data duplicate candidates",
		sensitive: true,
	},
	{
		code: "master_data.tax_registration_read",
		module: "master_data",
		description: "Read masked tax-registration projections",
		sensitive: false,
	},
	{
		code: "master_data.tax_registration_sensitive_read",
		module: "master_data",
		description: "Read unmasked tax-registration projections",
		sensitive: true,
	},
	{
		code: "master_data.party_contact_read",
		module: "master_data",
		description: "Read masked party-contact projections",
		sensitive: false,
	},
	{
		code: "master_data.party_contact_sensitive_read",
		module: "master_data",
		description: "Read unmasked party-contact projections",
		sensitive: true,
	},
	{
		code: "master_data.sensitive_external_id_read",
		module: "master_data",
		description: "Read sensitive external identifier values",
		sensitive: true,
	},
	{
		code: "master_data.party_activate",
		module: "master_data",
		description: "Activate party master records",
		sensitive: true,
	},
	{
		code: "master_data.party_inactivate",
		module: "master_data",
		description: "Inactivate party master records",
		sensitive: true,
	},
	{
		code: "master_data.party_block",
		module: "master_data",
		description: "Block party master records",
		sensitive: true,
	},
	{
		code: "master_data.party_unblock",
		module: "master_data",
		description: "Restore blocked party master records",
		sensitive: true,
	},
	{
		code: "master_data.party_retire",
		module: "master_data",
		description: "Retire party master records",
		sensitive: true,
	},
	{
		code: "master_data.party_archive",
		module: "master_data",
		description: "Archive party master records",
		sensitive: true,
	},
	{
		code: "master_data.party_merge",
		module: "master_data",
		description: "Merge duplicate party master records",
		sensitive: true,
	},
	{
		code: "master_data.item_activate",
		module: "master_data",
		description: "Activate item master records",
		sensitive: true,
	},
	{
		code: "master_data.item_inactivate",
		module: "master_data",
		description: "Inactivate item master records",
		sensitive: true,
	},
	{
		code: "master_data.item_block",
		module: "master_data",
		description: "Block item master records",
		sensitive: true,
	},
	{
		code: "master_data.item_unblock",
		module: "master_data",
		description: "Restore blocked item master records",
		sensitive: true,
	},
	{
		code: "master_data.item_retire",
		module: "master_data",
		description: "Retire item master records",
		sensitive: true,
	},
	{
		code: "master_data.item_archive",
		module: "master_data",
		description: "Archive item master records",
		sensitive: true,
	},
	{
		code: "master_data.item_group_activate",
		module: "master_data",
		description: "Activate item-group master records",
		sensitive: true,
	},
	{
		code: "master_data.item_group_inactivate",
		module: "master_data",
		description: "Inactivate item-group master records",
		sensitive: true,
	},
	{
		code: "master_data.item_group_archive",
		module: "master_data",
		description: "Archive item-group master records",
		sensitive: true,
	},
	{
		code: "master_data.warehouse_activate",
		module: "master_data",
		description: "Activate warehouse master records",
		sensitive: true,
	},
	{
		code: "master_data.warehouse_inactivate",
		module: "master_data",
		description: "Inactivate warehouse master records",
		sensitive: true,
	},
	{
		code: "master_data.warehouse_block",
		module: "master_data",
		description: "Block warehouse master records",
		sensitive: true,
	},
	{
		code: "master_data.warehouse_unblock",
		module: "master_data",
		description: "Restore blocked warehouse master records",
		sensitive: true,
	},
	{
		code: "master_data.warehouse_retire",
		module: "master_data",
		description: "Retire warehouse master records",
		sensitive: true,
	},
	{
		code: "master_data.warehouse_archive",
		module: "master_data",
		description: "Archive warehouse master records",
		sensitive: true,
	},
	{
		code: "master_data.payment_term_activate",
		module: "master_data",
		description: "Activate payment-term master records",
		sensitive: true,
	},
	{
		code: "master_data.payment_term_inactivate",
		module: "master_data",
		description: "Inactivate payment-term master records",
		sensitive: true,
	},
	{
		code: "master_data.payment_term_archive",
		module: "master_data",
		description: "Archive payment-term master records",
		sensitive: true,
	},
	{
		code: "master_data.tax_registration_activate",
		module: "master_data",
		description: "Activate tax-registration master records",
		sensitive: true,
	},
	{
		code: "master_data.tax_registration_revoke",
		module: "master_data",
		description: "Revoke tax-registration master records",
		sensitive: true,
	},
	{
		code: "master_data.tax_registration_archive",
		module: "master_data",
		description: "Archive tax-registration master records",
		sensitive: true,
	},
	{
		code: "master_data.tax_registration_restore",
		module: "master_data",
		description: "Restore tax-registration master records",
		sensitive: true,
	},
	{
		code: "master_data.item_template_activate",
		module: "master_data",
		description: "Activate item-template master records",
		sensitive: true,
	},
	{
		code: "master_data.item_template_inactivate",
		module: "master_data",
		description: "Inactivate item-template master records",
		sensitive: true,
	},
	{
		code: "master_data.item_template_retire",
		module: "master_data",
		description: "Retire item-template master records",
		sensitive: true,
	},
	{
		code: "master_data.item_variant_activate",
		module: "master_data",
		description: "Activate item-variant master records",
		sensitive: true,
	},
	{
		code: "master_data.item_variant_inactivate",
		module: "master_data",
		description: "Inactivate item-variant master records",
		sensitive: true,
	},
	{
		code: "master_data.item_variant_block",
		module: "master_data",
		description: "Block item-variant master records",
		sensitive: true,
	},
	{
		code: "master_data.item_variant_unblock",
		module: "master_data",
		description: "Restore blocked item-variant master records",
		sensitive: true,
	},
	{
		code: "master_data.item_variant_retire",
		module: "master_data",
		description: "Retire item-variant master records",
		sensitive: true,
	},
	{
		code: "master_data.item_variant_archive",
		module: "master_data",
		description: "Archive item-variant master records",
		sensitive: true,
	},
	{
		code: "master_data.party_role_manage",
		module: "master_data",
		description: "Manage party operational roles",
		sensitive: true,
	},
	{
		code: "master_data.party_address_manage",
		module: "master_data",
		description: "Manage party addresses and primary-address selection",
		sensitive: true,
	},
	{
		code: "master_data.party_contact_manage",
		module: "master_data",
		description: "Manage party contact endpoints",
		sensitive: true,
	},
	{
		code: "master_data.party_contact_verify",
		module: "master_data",
		description: "Verify or revoke verification of party contact endpoints",
		sensitive: true,
	},
	{
		code: "master_data.party_external_id_manage",
		module: "master_data",
		description: "Manage non-regulatory party external identifiers",
		sensitive: true,
	},
	{
		code: "master_data.party_external_id_regulatory_manage",
		module: "master_data",
		description:
			"Manage legal, tax, government, and regulatory party identifiers",
		sensitive: true,
	},
	{
		code: "master_data.party_relationship_manage",
		module: "master_data",
		description: "Manage ordinary party relationships",
		sensitive: true,
	},
	{
		code: "master_data.party_relationship_control_manage",
		module: "master_data",
		description: "Manage party ownership and corporate-control relationships",
		sensitive: true,
	},
	{
		code: "master_data.item_uom_manage",
		module: "master_data",
		description: "Manage item-specific UoM conversions and defaults",
		sensitive: true,
	},
	{
		code: "master_data.item_barcode_manage",
		module: "master_data",
		description: "Manage item barcodes and primary-barcode selection",
		sensitive: true,
	},
	{
		code: "master_data.item_external_id_manage",
		module: "master_data",
		description: "Manage item external identifiers",
		sensitive: true,
	},
	{
		code: "master_data.item_alias_manage",
		module: "master_data",
		description: "Manage searchable item aliases",
		sensitive: true,
	},
	{
		code: "master_data.warehouse_external_id_manage",
		module: "master_data",
		description: "Manage warehouse external identifiers",
		sensitive: true,
	},
	{
		code: "master_data.item_template_attribute_manage",
		module: "master_data",
		description: "Manage non-identity item-template attributes",
		sensitive: true,
	},
	{
		code: "master_data.item_template_option_manage",
		module: "master_data",
		description: "Manage item-template attribute options",
		sensitive: true,
	},
	{
		code: "master_data.item_variant_attribute_manage",
		module: "master_data",
		description: "Assign governed attribute values to item variants",
		sensitive: true,
	},
	{
		code: "master_data.item_variant_defining_attribute_manage",
		module: "master_data",
		description:
			"Manage identity-defining item-template and variant attributes",
		sensitive: true,
	},
] as const satisfies readonly PlatformPermissionCatalogRow[];
