import type { PlatformPermissionCatalogRow } from "../platform-permission-catalog-reconciler";

export const WORKFORCE_PLATFORM_PERMISSIONS = [
	{
		code: "human-resources.employee.create",
		module: "human_resources",
		description: "Create employee records",
		sensitive: true,
	},
	{
		code: "human-resources.employee.read",
		module: "human_resources",
		description: "Read employee directory records",
		sensitive: false,
	},
	{
		code: "human-resources.employee.update",
		module: "human_resources",
		description: "Update employee records",
		sensitive: true,
	},
	{
		code: "human-resources.person.read",
		module: "human_resources",
		description: "Read person identity records",
		sensitive: true,
	},
	{
		code: "human-resources.person.manage",
		module: "human_resources",
		description: "Manage person identity records and names",
		sensitive: true,
	},
	{
		code: "human-resources.worker.read",
		module: "human_resources",
		description: "Read workforce participation records",
		sensitive: true,
	},
	{
		code: "human-resources.worker.manage",
		module: "human_resources",
		description: "Manage worker classification and lifecycle status",
		sensitive: true,
	},
	{
		code: "human-resources.personal-details.read",
		module: "human_resources",
		description: "Read authorized worker personal details",
		sensitive: true,
	},
	{
		code: "human-resources.personal-details.manage",
		module: "human_resources",
		description: "Manage worker contact, address, and personal facts",
		sensitive: true,
	},
	{
		code: "human-resources.sensitive-identifiers.read",
		module: "human_resources",
		description: "Read restricted statutory identifier projections",
		sensitive: true,
	},
	{
		code: "human-resources.sensitive-identifiers.manage",
		module: "human_resources",
		description: "Record, replace, and end statutory identifiers",
		sensitive: true,
	},
	{
		code: "human-resources.assignment.read",
		module: "human_resources",
		description: "Read employment assignment records",
		sensitive: false,
	},
	{
		code: "human-resources.assignment.manage",
		module: "human_resources",
		description: "Manage effective-dated employment assignments",
		sensitive: true,
	},
	{
		code: "human-resources.organization-context.read",
		module: "human_resources",
		description: "Resolve historical worker organization context",
		sensitive: false,
	},
	{
		code: "human-resources.reporting-line.manage",
		module: "human_resources",
		description: "Manage effective-dated assignment reporting relationships",
		sensitive: true,
	},
	{
		code: "human-resources.employment.manage",
		module: "human_resources",
		description: "Manage employment relationships and contracts",
		sensitive: true,
	},
	{
		code: "human-resources.organization.read",
		module: "human_resources",
		description:
			"Read organization structure (departments, jobs, positions, reporting lines)",
		sensitive: false,
	},
	{
		code: "human-resources.organization.manage",
		module: "human_resources",
		description:
			"Manage organization structure (departments, jobs, positions, reporting lines)",
		sensitive: true,
	},
	{
		code: "human-resources.requisition.create",
		module: "human_resources",
		description: "Create job requisitions",
		sensitive: true,
	},
	{
		code: "human-resources.candidate.manage",
		module: "human_resources",
		description: "Manage candidates and applications",
		sensitive: true,
	},
	{
		code: "human-resources.interview.read",
		module: "human_resources",
		description: "Read interviews and evaluation outcomes",
		sensitive: false,
	},
	{
		code: "human-resources.interview.record",
		module: "human_resources",
		description: "Record interviews and evaluations",
		sensitive: true,
	},
	{
		code: "human-resources.offer.approve",
		module: "human_resources",
		description: "Approve employment offers",
		sensitive: true,
	},
	{
		code: "human-resources.hire.orchestrate",
		module: "human_resources",
		description: "Orchestrate hire from accepted offer through onboarding",
		sensitive: true,
	},
	{
		code: "human-resources.onboarding.manage",
		module: "human_resources",
		description: "Manage onboarding cases and tasks",
		sensitive: true,
	},
	{
		code: "human-resources.offboarding.manage",
		module: "human_resources",
		description: "Manage offboarding cases and clearance",
		sensitive: true,
	},
	{
		code: "human-resources.leave-policy.read",
		module: "human_resources",
		description: "Read leave policies and eligibility rules",
		sensitive: false,
	},
	{
		code: "human-resources.leave-policy.manage",
		module: "human_resources",
		description: "Create and manage leave policies",
		sensitive: true,
	},
	{
		code: "human-resources.leave-entitlement.read",
		module: "human_resources",
		description: "Read leave entitlements and balances",
		sensitive: true,
	},
	{
		code: "human-resources.leave-entitlement.grant",
		module: "human_resources",
		description: "Grant, carry forward, and expire leave entitlements",
		sensitive: true,
	},
	{
		code: "human-resources.leave-entitlement.adjust",
		module: "human_resources",
		description: "Post manual leave entitlement adjustments",
		sensitive: true,
	},
	{
		code: "human-resources.leave-request.own",
		module: "human_resources",
		description: "Submit and manage own leave requests",
		sensitive: false,
	},
	{
		code: "human-resources.leave-request.approve-team",
		module: "human_resources",
		description: "Approve or reject team leave requests",
		sensitive: true,
	},
	{
		code: "human-resources.leave-request.backdate",
		module: "human_resources",
		description: "Submit backdated leave requests",
		sensitive: true,
	},
	{
		code: "human-resources.leave-request.sensitive-read",
		module: "human_resources",
		description: "Read sensitive leave policy and request data",
		sensitive: true,
	},
	{
		code: "human-resources.leave.handoff.read",
		module: "human_resources",
		description: "Read approved leave payroll handoff facts",
		sensitive: true,
	},
	{
		code: "human-resources.attendance.manage",
		module: "human_resources",
		description: "Manage attendance events and records",
		sensitive: true,
	},
	{
		code: "human-resources.time.calendar.read",
		module: "human_resources",
		description: "Read work calendars and assignments",
		sensitive: false,
	},
	{
		code: "human-resources.time.calendar.manage",
		module: "human_resources",
		description: "Manage work calendars, holidays, and assignments",
		sensitive: false,
	},
	{
		code: "human-resources.time.shift.read",
		module: "human_resources",
		description: "Read shift definitions",
		sensitive: false,
	},
	{
		code: "human-resources.time.shift.manage",
		module: "human_resources",
		description: "Manage shift definitions and breaks",
		sensitive: false,
	},
	{
		code: "human-resources.time.schedule.read",
		module: "human_resources",
		description: "Read employee schedules",
		sensitive: false,
	},
	{
		code: "human-resources.time.schedule.manage",
		module: "human_resources",
		description: "Assign and amend employee schedules",
		sensitive: false,
	},
	{
		code: "human-resources.time.schedule.publish",
		module: "human_resources",
		description: "Publish employee schedules",
		sensitive: false,
	},
	{
		code: "human-resources.time.attendance.self.record",
		module: "human_resources",
		description: "Record own attendance clock events",
		sensitive: true,
	},
	{
		code: "human-resources.time.attendance.read",
		module: "human_resources",
		description: "Read attendance events and sessions",
		sensitive: true,
	},
	{
		code: "human-resources.time.attendance.correct",
		module: "human_resources",
		description: "Correct and void attendance events",
		sensitive: true,
	},
	{
		code: "human-resources.time.attendance.manage",
		module: "human_resources",
		description: "Record supervisor-entered attendance on behalf of employees",
		sensitive: true,
	},
	{
		code: "human-resources.time.exception.read",
		module: "human_resources",
		description: "Read attendance exceptions",
		sensitive: true,
	},
	{
		code: "human-resources.time.exception.resolve",
		module: "human_resources",
		description: "Resolve attendance exceptions",
		sensitive: true,
	},
	{
		code: "human-resources.time.timesheet.self.read",
		module: "human_resources",
		description: "Read own timesheets",
		sensitive: true,
	},
	{
		code: "human-resources.time.timesheet.self.edit",
		module: "human_resources",
		description: "Edit own draft timesheets",
		sensitive: true,
	},
	{
		code: "human-resources.time.timesheet.submit",
		module: "human_resources",
		description: "Submit timesheets for approval",
		sensitive: true,
	},
	{
		code: "human-resources.time.timesheet.read",
		module: "human_resources",
		description: "Read team and organization timesheets",
		sensitive: true,
	},
	{
		code: "human-resources.time.timesheet.approve",
		module: "human_resources",
		description: "Approve, return, or reject employee timesheets (manager/HR)",
		sensitive: true,
	},
	{
		code: "human-resources.time.timesheet.reopen",
		module: "human_resources",
		description: "Reopen approved timesheets under control",
		sensitive: true,
	},
	{
		code: "human-resources.time.timesheet.lock",
		module: "human_resources",
		description: "Lock timesheets for payroll handoff",
		sensitive: true,
	},
	{
		code: "human-resources.time.overtime.request",
		module: "human_resources",
		description: "Request overtime",
		sensitive: true,
	},
	{
		code: "human-resources.time.overtime.read",
		module: "human_resources",
		description: "Read overtime requests",
		sensitive: true,
	},
	{
		code: "human-resources.time.overtime.approve",
		module: "human_resources",
		description: "Approve overtime requests",
		sensitive: true,
	},
	{
		code: "human-resources.time.handoff.read",
		module: "human_resources",
		description: "Read approved time payroll handoff facts",
		sensitive: true,
	},
	{
		code: "human-resources.performance.manage",
		module: "human_resources",
		description: "Manage performance cycles, goals, and reviews",
		sensitive: true,
	},
	{
		code: "human-resources.performance.own.read",
		module: "human_resources",
		description:
			"Read own performance goals and reviews without confidential fields",
		sensitive: true,
	},
	{
		code: "human-resources.performance.goal.own.manage",
		module: "human_resources",
		description:
			"Create and manage own employee-proposed performance goals and progress",
		sensitive: true,
	},
	{
		code: "human-resources.performance.manager.manage",
		module: "human_resources",
		description: "Manage team performance goals, assessments, and approvals",
		sensitive: true,
	},
	{
		code: "human-resources.performance.improvement-plan.manage",
		module: "human_resources",
		description: "Manage performance improvement plans and checkpoints",
		sensitive: true,
	},
	{
		code: "human-resources.performance.review.reopen",
		module: "human_resources",
		description: "Exceptionally reopen finalized performance reviews",
		sensitive: true,
	},
	{
		code: "human-resources.performance.confidential.read",
		module: "human_resources",
		description: "Read confidential performance ratings and comments",
		sensitive: true,
	},
	{
		code: "human-resources.learning.manage",
		module: "human_resources",
		description: "Manage learning programs and assignments",
		sensitive: true,
	},
	{
		code: "human-resources.certification.manage",
		module: "human_resources",
		description: "Manage employee certifications",
		sensitive: true,
	},
	{
		code: "human-resources.compensation.read",
		module: "human_resources",
		description: "Read compensation and benefits agreements",
		sensitive: true,
	},
	{
		code: "human-resources.compensation.manage",
		module: "human_resources",
		description: "Manage compensation agreements and reviews",
		sensitive: true,
	},
	{
		code: "human-resources.compensation-proposal.create",
		module: "human_resources",
		description: "Create compensation proposals for recruitment offers",
		sensitive: true,
	},
	{
		code: "human-resources.compensation-proposal.amend",
		module: "human_resources",
		description: "Amend draft compensation proposals",
		sensitive: true,
	},
	{
		code: "human-resources.compensation-proposal.approve",
		module: "human_resources",
		description: "Approve compensation proposals",
		sensitive: true,
	},
	{
		code: "human-resources.compensation-proposal.read",
		module: "human_resources",
		description: "Read compensation proposals",
		sensitive: true,
	},
	{
		code: "human-resources.benefits.manage",
		module: "human_resources",
		description: "Manage benefit plans and enrollments",
		sensitive: true,
	},
	{
		code: "human-resources.employee-case.open",
		module: "human_resources",
		description: "Open confidential employee-relations cases",
		sensitive: true,
	},
	{
		code: "human-resources.employee-case.assigned.read",
		module: "human_resources",
		description: "Read employee cases assigned to the actor",
		sensitive: true,
	},
	{
		code: "human-resources.employee-case.investigate",
		module: "human_resources",
		description: "Investigate employee-relations cases",
		sensitive: true,
	},
	{
		code: "human-resources.employee-case.finding",
		module: "human_resources",
		description: "Record employee-relations case findings",
		sensitive: true,
	},
	{
		code: "human-resources.employee-case.action.approve",
		module: "human_resources",
		description: "Recommend and approve employee-relations case actions",
		sensitive: true,
	},
	{
		code: "human-resources.employee-case.appeal",
		module: "human_resources",
		description: "Record and resolve employee-relations appeals",
		sensitive: true,
	},
	{
		code: "human-resources.employee-case.exceptional.admin",
		module: "human_resources",
		description: "Exceptional employee-relations case administration",
		sensitive: true,
	},
	{
		code: "human-resources.workforce-plan.read",
		module: "human_resources",
		description: "Read workforce and headcount plans",
		sensitive: false,
	},
	{
		code: "human-resources.workforce-plan.prepare",
		module: "human_resources",
		description: "Prepare workforce and headcount plans",
		sensitive: false,
	},
	{
		code: "human-resources.workforce-plan.approve",
		module: "human_resources",
		description: "Approve workforce and headcount plans",
		sensitive: true,
	},
	{
		code: "human-resources.headcount.reserve",
		module: "human_resources",
		description: "Reserve headcount against approved plans",
		sensitive: false,
	},
	{
		code: "human-resources.headcount.exceptional-adjust",
		module: "human_resources",
		description: "Exceptional headcount capacity adjustments",
		sensitive: true,
	},
	{
		code: "human-resources.document-requirement.manage",
		module: "human_resources",
		description: "Manage document requirements",
		sensitive: true,
	},
	{
		code: "human-resources.employee-document.own.read",
		module: "human_resources",
		description: "Read own employee documents",
		sensitive: true,
	},
	{
		code: "human-resources.employee-document.own.register",
		module: "human_resources",
		description: "Register own employee documents",
		sensitive: true,
	},
	{
		code: "human-resources.employee-document.verify",
		module: "human_resources",
		description: "Verify employee documents",
		sensitive: true,
	},
	{
		code: "human-resources.work-eligibility.verify",
		module: "human_resources",
		description: "Verify work eligibility records",
		sensitive: true,
	},
	{
		code: "human-resources.compliance.administer",
		module: "human_resources",
		description:
			"Administer compliance summaries and org-wide compliance reads",
		sensitive: true,
	},
	{
		code: "human-resources.identity-document.sensitive.read",
		module: "human_resources",
		description: "Read sensitive identity document fields",
		sensitive: true,
	},
	{
		code: "human-resources.policy-acknowledgement.administer",
		module: "human_resources",
		description: "Administer policy acknowledgement requirements",
		sensitive: true,
	},
	{
		code: "human-resources.competency.read",
		module: "human_resources",
		description: "Read competency definitions and mappings",
		sensitive: false,
	},
	{
		code: "human-resources.competency.manage",
		module: "human_resources",
		description: "Create, update, retire competencies and job mappings",
		sensitive: false,
	},
	{
		code: "human-resources.competency.assess",
		module: "human_resources",
		description: "Record and supersede employee competency assessments",
		sensitive: true,
	},
	{
		code: "human-resources.career-plan.own.read",
		module: "human_resources",
		description: "Read own career plans and actions",
		sensitive: false,
	},
	{
		code: "human-resources.career-plan.manage",
		module: "human_resources",
		description: "Manage career plans, actions, and talent pools",
		sensitive: true,
	},
	{
		code: "human-resources.talent.admin",
		module: "human_resources",
		description: "Administer talent profiles and talent pools",
		sensitive: true,
	},
	{
		code: "human-resources.talent.profile.sensitive.read",
		module: "human_resources",
		description: "Read confidential talent profile classifications",
		sensitive: true,
	},
	{
		code: "human-resources.succession.admin",
		module: "human_resources",
		description: "Administer succession plans and candidates",
		sensitive: true,
	},
	{
		code: "human-resources.succession.executive.read",
		module: "human_resources",
		description: "Read succession plan coverage and candidate readiness",
		sensitive: true,
	},
	{
		code: "human-resources.privacy.export",
		module: "human_resources",
		description: "Export human-resources subject data for privacy requests",
		sensitive: true,
	},
	{
		code: "human-resources.privacy.anonymize.evaluate",
		module: "human_resources",
		description: "Evaluate human-resources anonymization eligibility",
		sensitive: true,
	},
	{
		code: "human-resources.privacy.retention.evaluate",
		module: "human_resources",
		description: "Evaluate human-resources retention policies for a subject",
		sensitive: true,
	},
	{
		code: "human-resources.privacy.legal-hold.manage",
		module: "human_resources",
		description: "Place and release human-resources legal holds",
		sensitive: true,
	},
	{
		code: "human-resources.privacy.anonymize.execute",
		module: "human_resources",
		description: "Execute human-resources subject anonymization",
		sensitive: true,
	},
	{
		code: "human-resources.reliability.operate",
		module: "human_resources",
		description:
			"Replay Human Resources reliability dead letters and acknowledge connector work",
		sensitive: true,
	},
	{
		code: "human-resources.connector-cursor.manage",
		module: "human_resources",
		description: "Repair Human Resources connector cursor checkpoints",
		sensitive: true,
	},
	{
		code: "payroll.setup.manage",
		module: "payroll",
		description: "Manage payroll calendars, pay groups, and rules",
		sensitive: true,
	},
	{
		code: "payroll.input.manage",
		module: "payroll",
		description: "Manage payroll period inputs and adjustments",
		sensitive: true,
	},
	{
		code: "payroll.run.create",
		module: "payroll",
		description: "Create payroll runs",
		sensitive: true,
	},
	{
		code: "payroll.run.calculate",
		module: "payroll",
		description: "Calculate payroll runs",
		sensitive: true,
	},
	{
		code: "payroll.run.review",
		module: "payroll",
		description: "Review payroll run results and exceptions",
		sensitive: true,
	},
	{
		code: "payroll.run.finalize",
		module: "payroll",
		description: "Finalize payroll runs",
		sensitive: true,
	},
	{
		code: "payroll.run.reverse",
		module: "payroll",
		description: "Reverse finalized payroll runs",
		sensitive: true,
	},
	{
		code: "payroll.payslip.read-own",
		module: "payroll",
		description: "Read own payslips",
		sensitive: false,
	},
	{
		code: "payroll.payslip.read-all",
		module: "payroll",
		description: "Read all organization payslips",
		sensitive: true,
	},
	{
		code: "payroll.reconciliation.manage",
		module: "payroll",
		description: "Manage payroll reconciliation",
		sensitive: true,
	},
] as const satisfies readonly PlatformPermissionCatalogRow[];
