import "server-only";

export {
	archivePayrollCalendar,
	archivePayrollDeductionRule,
	archivePayrollEarningRule,
	archivePayrollPayGroup,
	archivePayrollStatutoryRule,
	calculatePayrollRun,
	closePayrollPeriod,
	createPayrollCalendar,
	createPayrollDeductionRule,
	createPayrollEarningRule,
	createPayrollEmployeeAssignment,
	createPayrollPayGroup,
	createPayrollPeriod,
	createPayrollRecurringDeduction,
	createPayrollRecurringEarning,
	createPayrollRun,
	createPayrollStatutoryRule,
	createPayrollVariableInput,
	finalizePayrollRun,
	getOwnPayrollPayslip,
	getPayrollCalendar,
	getPayrollDeductionRule,
	getPayrollEarningRule,
	getPayrollEmployeeAssignment,
	getPayrollPayGroup,
	getPayrollPayslip,
	getPayrollPeriod,
	getPayrollRun,
	getPayrollStatutoryRule,
	getPayrollVariableInput,
	ingestApprovedPayrollHandoff,
	listPayrollCalendars,
	listPayrollExceptionsForRun,
	listPayrollPayGroups,
	listPayrollPeriods,
	listPayrollReconciliationsForRun,
	recordPayrollException,
	recordPayrollReconciliation,
	resolvePayrollReconciliation,
	reversePayrollRun,
	supersedePayrollDeductionRule,
	supersedePayrollEarningRule,
	supersedePayrollStatutoryRule,
	updatePayrollCalendar,
	updatePayrollDeductionRule,
	updatePayrollEarningRule,
	updatePayrollPayGroup,
	updatePayrollPeriod,
	updatePayrollStatutoryRule,
} from "./facade/capabilities";
export {
	createPayrollCapabilityOptions,
	type PayrollCapabilityOptions,
} from "./facade/context";
export type {
	PayrollAuthorizationCapability,
	PayrollCapabilityComposition,
	PayrollWorkforceCapability,
} from "./facade/contracts";
export {
	createFixedPayrollClock,
	createJurisdictionPayrollCurrency,
	createRegistryPayrollStatutory,
	createSystemPayrollClock,
} from "./facade/system-capabilities";
export { PAYROLL_PLATFORM_EVENT_DISPATCHER_ID } from "./kernel/emissions/emission-registry";
export type {
	PayrollClockCapability,
	PayrollCurrencyCapability,
	PayrollStatutoryCapability,
} from "./kernel/execution/capability-ports";
export {
	PAYROLL_PERMISSION_CODES,
	PAYROLL_PERMISSION_INPUT_MANAGE,
	PAYROLL_PERMISSION_PAYSLIP_READ_ALL,
	PAYROLL_PERMISSION_PAYSLIP_READ_OWN,
	PAYROLL_PERMISSION_RECONCILIATION_MANAGE,
	PAYROLL_PERMISSION_RUN_CALCULATE,
	PAYROLL_PERMISSION_RUN_CREATE,
	PAYROLL_PERMISSION_RUN_FINALIZE,
	PAYROLL_PERMISSION_RUN_REVERSE,
	PAYROLL_PERMISSION_RUN_REVIEW,
	PAYROLL_PERMISSION_SETUP_MANAGE,
} from "./kernel/execution/permissions";
