import "server-only";

export {
	applyRetroToPeriod,
	archivePayrollCalendar,
	archivePayrollDeductionRule,
	archivePayrollEarningRule,
	archivePayrollPayGroup,
	archivePayrollStatutoryRule,
	calculateFinalSettlement,
	calculatePayrollRun,
	calculateRetroDifference,
	claimDuePayrollJobWork,
	closePayrollPeriod,
	createPayrollCalendar,
	createPayrollDeductionRule,
	createPayrollEarningRule,
	createPayrollEmployeeAssignment,
	createPayrollPayGroup,
	createPayrollPeriod,
	createPayrollRecurringDeduction,
	createPayrollRecurringEarning,
	createPayrollRun,
	createPayrollStatutoryRule,
	createPayrollVariableInput,
	enqueuePayrollCalculationJob,
	executePayrollJobWork,
	expirePayrollRetention,
	finalizeFinalSettlement,
	finalizePayrollRun,
	getOwnPayrollPayslip,
	getPayrollCalendar,
	getPayrollDeductionRule,
	getPayrollEarningRule,
	getPayrollEmployeeAssignment,
	getPayrollJob,
	getPayrollPayGroup,
	getPayrollPayslip,
	getPayrollPeriod,
	getPayrollRun,
	getPayrollStatutoryRule,
	getPayrollVariableInput,
	ingestApprovedPayrollHandoff,
	initiateFinalSettlement,
	issueFinalSettlementStatement,
	liftPayrollRestriction,
	listPayrollCalendars,
	listPayrollDeadLetters,
	listPayrollExceptionsForRun,
	listPayrollPayGroups,
	listPayrollPeriods,
	listPayrollReconciliationsForRun,
	listRetroItems,
	projectPayrollFields,
	queueRetroItem,
	recordPaymentSettlement,
	recordPayrollException,
	recordPayrollReconciliation,
	recordPayrollRetentionEvidence,
	recordPostingConfirmation,
	replayPayrollDeadLetter,
	resolvePayrollReconciliation,
	resolveReconciliationDiscrepancy,
	respondToPayrollSubjectAccess,
	restrictPayrollSubject,
	reversePayrollRun,
	supersedePayrollDeductionRule,
	supersedePayrollEarningRule,
	supersedePayrollStatutoryRule,
	updatePayrollCalendar,
	updatePayrollDeductionRule,
	updatePayrollEarningRule,
	updatePayrollPayGroup,
	updatePayrollPeriod,
	updatePayrollStatutoryRule,
} from "./facade/capabilities";
export {
	createPayrollCapabilityOptions,
	type PayrollCapabilityOptions,
} from "./facade/context";
export type {
	PayrollAuthorizationCapability,
	PayrollCapabilityComposition,
	PayrollPrivacyCapability,
	PayrollWorkforceCapability,
} from "./facade/contracts";
export {
	createFixedPayrollClock,
	createJurisdictionPayrollCurrency,
	createRegistryPayrollStatutory,
	createSystemPayrollClock,
} from "./facade/system-capabilities";
export {
	PAYROLL_FINAL_SETTLEMENT_LINE_KINDS,
	PAYROLL_FINAL_SETTLEMENT_STATUSES,
	type PayrollFinalSettlement,
	type PayrollFinalSettlementFacts,
	type PayrollFinalSettlementLine,
	type PayrollFinalSettlementLineKind,
	type PayrollFinalSettlementRecovery,
	type PayrollFinalSettlementStatement,
	type PayrollFinalSettlementStatus,
	type PayrollFinalSettlementTotals,
	type PayrollFinalSettlementView,
} from "./features/final-settlement/contract";
export type {
	PayrollJob,
	PayrollJobChunkExecutorPort,
	PayrollJobDeadLetter,
	PayrollJobEmployeeDirectoryPort,
	PayrollJobWorkItem,
} from "./features/payroll-jobs/contract";
export {
	PAYROLL_RETENTION_CLASSIFICATIONS,
	type PayrollPrivacyPort,
	type PayrollPrivacyRequestContext,
	type PayrollProjectedFields,
	type PayrollRetentionClassification,
	type PayrollRetentionEvidence,
	type PayrollSubjectAccessExport,
} from "./features/privacy/contract";
export {
	PAYROLL_RETRO_CORRECTION_KINDS,
	PAYROLL_RETRO_STATUSES,
	type PayrollRetroCorrection,
	type PayrollRetroCorrectionKind,
	type PayrollRetroDifference,
	type PayrollRetroDifferenceLine,
	type PayrollRetroDifferenceTotals,
	type PayrollRetroItem,
	type PayrollRetroItemView,
	type PayrollRetroLine,
	type PayrollRetroStatus,
} from "./features/retro-pay/contract";
export { parsePayrollDisbursementReference } from "./features/settlement-ingress/parse-payroll-disbursement-reference";
export { PAYROLL_PLATFORM_EVENT_DISPATCHER_ID } from "./kernel/emissions/emission-registry";
export type {
	PayrollClockCapability,
	PayrollCurrencyCapability,
	PayrollStatutoryCapability,
} from "./kernel/execution/capability-ports";
export {
	PAYROLL_PERMISSION_CODES,
	PAYROLL_PERMISSION_INPUT_MANAGE,
	PAYROLL_PERMISSION_PAYSLIP_READ_ALL,
	PAYROLL_PERMISSION_PAYSLIP_READ_OWN,
	PAYROLL_PERMISSION_RECONCILIATION_MANAGE,
	PAYROLL_PERMISSION_RUN_CALCULATE,
	PAYROLL_PERMISSION_RUN_CREATE,
	PAYROLL_PERMISSION_RUN_FINALIZE,
	PAYROLL_PERMISSION_RUN_REVERSE,
	PAYROLL_PERMISSION_RUN_REVIEW,
	PAYROLL_PERMISSION_SETUP_MANAGE,
} from "./kernel/execution/permissions";
