/**
 * ARCH-023 hard tenant roots after domain wipe.
 * Every table has `organization_id … NOT NULL` — CI: `pnpm audit:tenancy-nulls`.
 */

import {
	accountingPeriod,
	accountRoleMapping,
	chartOfAccount,
	financialPostingException,
	journal,
	journalLine,
	ledgerAccount,
	ledgerPosting,
	postingProfile,
	postingProfileLine,
	sourcePostingLink,
} from "./schema/accounting";
import {
	caAuthorityMandate,
	caCompanyActivity,
	caCompanyFinancialYear,
	caCompanyIdentifier,
	caCompanyJurisdictionProfile,
	caCompanyLegalFormHistory,
	caCompanyName,
	caCompanyStatusHistory,
	caConflictDisclosure,
	caEstablishmentStatusHistory,
	caGovernanceBody,
	caGovernanceMeeting,
	caGovernanceMembership,
	caLegalCompany,
	caLegalEstablishment,
	caMeetingNotice,
	caMeetingParticipant,
	caMeetingQuorumResult,
	caMeetingVote,
	caMutationReceipt,
	caOfficerAppointment,
	caOfficerDeclaration,
	caOfficerDisqualification,
	caOfficerQualification,
	caPremise,
	caRegisteredAddress,
	caResolution,
	caResolutionAction,
	caStatutoryOffice,
} from "./schema/corporate-administration";
import {
	delivery,
	deliveryLine,
	deliveryPack,
	deliveryPick,
	proofOfDelivery,
} from "./schema/fulfillment";
import {
	hrAllowanceEntitlement,
	hrAttendanceAdjustment,
	hrAttendanceBreakWaiverDecision,
	hrAttendanceEvent,
	hrAttendanceException,
	hrAttendanceImportBatch,
	hrAttendanceImportError,
	hrAttendanceSession,
	hrBenefitEligibility,
	hrBenefitEnrollment,
	hrBenefitEnrollmentDependent,
	hrBenefitPlan,
	hrBonusEligibility,
	hrBulkExportArtifactChunk,
	hrBulkExportJob,
	hrBulkImportAudit,
	hrBulkImportCheckpoint,
	hrBulkImportErrorArtifact,
	hrBulkImportJob,
	hrBulkImportJobRow,
	hrCandidate,
	hrCandidateApplication,
	hrCandidateApplicationStatusHistory,
	hrCareerPlan,
	hrCareerPlanAction,
	hrClearance,
	hrCompensationGrade,
	hrCompensationGradeProgressionRule,
	hrCompensationProposal,
	hrCompensationReview,
	hrCompensationReviewCycle,
	hrCompetency,
	hrCompetencyAssessment,
	hrConnectorCursor,
	hrDepartment,
	hrDepartmentStructureVersion,
	hrDevelopmentPlan,
	hrDocumentRequirement,
	hrEmployee,
	hrEmployeeCase,
	hrEmployeeCaseAction,
	hrEmployeeCaseAppeal,
	hrEmployeeCaseEvent,
	hrEmployeeCertification,
	hrEmployeeCompensation,
	hrEmployeeDocument,
	hrEmployment,
	hrEmploymentCalendarAssignment,
	hrEmploymentConfirmation,
	hrEmploymentContract,
	hrEmploymentMovement,
	hrEmploymentOffer,
	hrEmploymentStatusHistory,
	hrExitInterview,
	hrHeadcountPlan,
	hrHeadcountPlanLine,
	hrHeadcountReservation,
	hrHireAttempt,
	hrInterview,
	hrInterviewEvaluation,
	hrJob,
	hrJobCompetency,
	hrJobDefinitionVersion,
	hrJobRequisition,
	hrLearningAssessment,
	hrLearningAssignment,
	hrLearningAttendance,
	hrLearningCompletion,
	hrLearningCourse,
	hrLearningProgram,
	hrLearningSession,
	hrLeaveAdjustment,
	hrLeaveApprovalDecision,
	hrLeaveEntitlement,
	hrLeavePolicy,
	hrLeavePolicyEligibility,
	hrLeaveRequest,
	hrLeaveRequestSegment,
	hrOffboardingAccessRevocation,
	hrOffboardingCase,
	hrOffboardingPayrollHandoff,
	hrOffboardingTask,
	hrOnboardingAccessHandoff,
	hrOnboardingCase,
	hrOnboardingEquipmentHandoff,
	hrOnboardingOrientation,
	hrOnboardingTask,
	hrOvertimeApproval,
	hrOvertimeRequest,
	hrPayrollHandoffDelivery,
	hrPerformanceAssessment,
	hrPerformanceCycle,
	hrPerformanceCycleEligibility,
	hrPerformanceCycleParticipant,
	hrPerformanceCycleReviewPeriod,
	hrPerformanceGoal,
	hrPerformanceGoalProgress,
	hrPerformanceImprovementCheckpoint,
	hrPerformanceImprovementPlan,
	hrPerformanceReview,
	hrPerformanceReviewParticipant,
	hrPerson,
	hrPersonContact,
	hrPersonIdentifier,
	hrPersonIdentityVersion,
	hrPolicyAcknowledgement,
	hrPosition,
	hrPositionDefinitionVersion,
	hrProbationAssessment,
	hrProbationReview,
	hrReliabilityDeadLetter,
	hrReliabilityWorkItem,
	hrReportingLine,
	hrSalaryBand,
	hrShift,
	hrShiftAssignment,
	hrShiftAssignmentSegment,
	hrShiftBreak,
	hrSuccessionCandidate,
	hrSuccessionPlan,
	hrTalentCriticalRoleReadiness,
	hrTalentPool,
	hrTalentPoolMember,
	hrTalentProfile,
	hrTalentProfileAssessment,
	hrTalentProfileMobility,
	hrTermination,
	hrTimeApprovalAuthorityAssignment,
	hrTimePolicy,
	hrTimePolicyAssignment,
	hrTimesheet,
	hrTimesheetApprovalDecision,
	hrTimesheetEntry,
	hrUserEmployee,
	hrWorkAssignment,
	hrWorkCalendar,
	hrWorkCalendarHoliday,
	hrWorkCalendarScopeAssignment,
	hrWorkEligibility,
	hrWorker,
	hrWorkerClassificationVersion,
} from "./schema/human-resources";
import {
	stockBalance,
	stockLedgerEntry,
	stockMovement,
	stockMovementLine,
	stockReservation,
} from "./schema/inventory";
import {
	mdChangeRequest,
	mdImportBatch,
	mdImportBatchRow,
	mdItem,
	mdItemAlias,
	mdItemBarcode,
	mdItemExternalId,
	mdItemGroup,
	mdItemTemplate,
	mdItemTemplateAttribute,
	mdItemTemplateAttributeOption,
	mdItemUom,
	mdItemVariant,
	mdItemVariantAttributeValue,
	mdItemVariantAttributeValueOption,
	mdOrganizationDimension,
	mdParty,
	mdPartyAddress,
	mdPartyContact,
	mdPartyExternalId,
	mdPartyRelationship,
	mdPartyRole,
	mdPaymentTerm,
	mdTaxRegistration,
	mdWarehouse,
	mdWarehouseExternalId,
} from "./schema/master-data";
import {
	supplierAllocation,
	supplierBalanceProjection,
	supplierCreditNote,
	supplierCreditNoteLine,
	supplierInvoice,
	supplierInvoiceLine,
	threeWayMatchResult,
} from "./schema/payables";
import {
	payment,
	paymentAccount,
	paymentAllocation,
	paymentDeduction,
	paymentMethod,
	paymentProvider,
	paymentProviderEvent,
	paymentReversal,
	paymentToken,
	paymentTransaction,
	paymentTransactionCapture,
	paymentTransactionRefund,
} from "./schema/payments";
import {
	payrollAcceptedHandoff,
	payrollAdjustment,
	payrollCalendar,
	payrollDeductionRule,
	payrollEarningRule,
	payrollEmployeeAssignment,
	payrollException,
	payrollPayGroup,
	payrollPayslip,
	payrollPeriod,
	payrollReconciliation,
	payrollRecurringDeduction,
	payrollRecurringEarning,
	payrollResultLine,
	payrollRuleFinalizedUsage,
	payrollRun,
	payrollRunEmployee,
	payrollStatutoryResult,
	payrollStatutoryRule,
	payrollVariableInput,
} from "./schema/payroll";
import {
	platformAuditLog,
	platformDomainEvent,
	platformNotification,
	platformRbacAudit,
	platformRoleAssignment,
	platformSearchDocument,
	platformWorkItem,
	platformWorkItemActivity,
} from "./schema/platform";
import { purchaseOrder, purchaseOrderLine } from "./schema/purchasing";
import {
	customerAllocation,
	customerBalanceProjection,
	salesCreditNote,
	salesInvoice,
	salesInvoiceLine,
} from "./schema/receivables";
import {
	goodsReceipt,
	goodsReceiptLine,
	receivingDiscrepancy,
} from "./schema/receiving";
import {
	salesOrder,
	salesOrderHold,
	salesOrderLine,
	salesOrderSchedule,
	salesPriceBook,
	salesPriceBookEntry,
	salesQuotation,
	salesQuotationLine,
	salesReturnAuthorization,
	salesReturnAuthorizationLine,
} from "./schema/sales";

/**
 * Single hard-tenant root registry.
 *
 * Each entry binds the trusted SQL table name used by operations audits to its
 * Drizzle table reference used by compile-time and schema-contract checks.
 */
export const HARD_TENANT_ROOT_ENTRIES = [
	["platform_role_assignment", platformRoleAssignment],
	["platform_rbac_audit", platformRbacAudit],
	["platform_audit_log", platformAuditLog],
	["platform_search_document", platformSearchDocument],
	["platform_notification", platformNotification],
	["platform_domain_event", platformDomainEvent],
	["platform_work_item", platformWorkItem],
	["platform_work_item_activity", platformWorkItemActivity],
	["ca_mutation_receipt", caMutationReceipt],
	["ca_legal_company", caLegalCompany],
	["ca_company_jurisdiction_profile", caCompanyJurisdictionProfile],
	["ca_company_name", caCompanyName],
	["ca_company_status_history", caCompanyStatusHistory],
	["ca_company_legal_form_history", caCompanyLegalFormHistory],
	["ca_company_identifier", caCompanyIdentifier],
	["ca_company_financial_year", caCompanyFinancialYear],
	["ca_company_activity", caCompanyActivity],
	["ca_legal_establishment", caLegalEstablishment],
	["ca_establishment_status_history", caEstablishmentStatusHistory],
	["ca_registered_address", caRegisteredAddress],
	["ca_premise", caPremise],
	["ca_governance_body", caGovernanceBody],
	["ca_governance_membership", caGovernanceMembership],
	["ca_statutory_office", caStatutoryOffice],
	["ca_officer_appointment", caOfficerAppointment],
	["ca_officer_qualification", caOfficerQualification],
	["ca_officer_declaration", caOfficerDeclaration],
	["ca_officer_disqualification", caOfficerDisqualification],
	["ca_conflict_disclosure", caConflictDisclosure],
	["ca_governance_meeting", caGovernanceMeeting],
	["ca_meeting_notice", caMeetingNotice],
	["ca_meeting_participant", caMeetingParticipant],
	["ca_meeting_quorum_result", caMeetingQuorumResult],
	["ca_meeting_vote", caMeetingVote],
	["ca_resolution", caResolution],
	["ca_resolution_action", caResolutionAction],
	["ca_authority_mandate", caAuthorityMandate],
	["md_party", mdParty],
	["md_organization_dimension", mdOrganizationDimension],
	["md_item_group", mdItemGroup],
	["md_item", mdItem],
	["md_warehouse", mdWarehouse],
	["md_payment_term", mdPaymentTerm],
	["md_tax_registration", mdTaxRegistration],
	["md_party_role", mdPartyRole],
	["md_party_address", mdPartyAddress],
	["md_party_contact", mdPartyContact],
	["md_party_external_id", mdPartyExternalId],
	["md_party_relationship", mdPartyRelationship],
	["md_item_uom", mdItemUom],
	["md_item_barcode", mdItemBarcode],
	["md_item_external_id", mdItemExternalId],
	["md_item_alias", mdItemAlias],
	["md_warehouse_external_id", mdWarehouseExternalId],
	["md_item_template", mdItemTemplate],
	["md_item_template_attribute", mdItemTemplateAttribute],
	["md_item_template_attribute_option", mdItemTemplateAttributeOption],
	["md_item_variant", mdItemVariant],
	["md_item_variant_attribute_value", mdItemVariantAttributeValue],
	["md_item_variant_attribute_value_option", mdItemVariantAttributeValueOption],
	["md_change_request", mdChangeRequest],
	["md_import_batch", mdImportBatch],
	["md_import_batch_row", mdImportBatchRow],
	["sales_order", salesOrder],
	["sales_order_line", salesOrderLine],
	["sales_order_schedule", salesOrderSchedule],
	["sales_order_hold", salesOrderHold],
	["sales_price_book", salesPriceBook],
	["sales_price_book_entry", salesPriceBookEntry],
	["sales_quotation", salesQuotation],
	["sales_quotation_line", salesQuotationLine],
	["sales_return_authorization", salesReturnAuthorization],
	["sales_return_authorization_line", salesReturnAuthorizationLine],
	["purchase_order", purchaseOrder],
	["purchase_order_line", purchaseOrderLine],
	["sales_invoice", salesInvoice],
	["sales_invoice_line", salesInvoiceLine],
	["sales_credit_note", salesCreditNote],
	["customer_allocation", customerAllocation],
	["customer_balance_projection", customerBalanceProjection],
	["supplier_invoice", supplierInvoice],
	["supplier_invoice_line", supplierInvoiceLine],
	["supplier_credit_note", supplierCreditNote],
	["supplier_credit_note_line", supplierCreditNoteLine],
	["supplier_allocation", supplierAllocation],
	["three_way_match_result", threeWayMatchResult],
	["supplier_balance_projection", supplierBalanceProjection],
	["payment_account", paymentAccount],
	["payment_method", paymentMethod],
	["payment", payment],
	["payment_allocation", paymentAllocation],
	["payment_deduction", paymentDeduction],
	["payment_reversal", paymentReversal],
	["payment_provider", paymentProvider],
	["payment_token", paymentToken],
	["payment_transaction", paymentTransaction],
	["payment_transaction_capture", paymentTransactionCapture],
	["payment_transaction_refund", paymentTransactionRefund],
	["payment_provider_event", paymentProviderEvent],
	["payroll_calendar", payrollCalendar],
	["payroll_pay_group", payrollPayGroup],
	["payroll_period", payrollPeriod],
	["payroll_employee_assignment", payrollEmployeeAssignment],
	["payroll_earning_rule", payrollEarningRule],
	["payroll_deduction_rule", payrollDeductionRule],
	["payroll_statutory_rule", payrollStatutoryRule],
	["payroll_recurring_earning", payrollRecurringEarning],
	["payroll_recurring_deduction", payrollRecurringDeduction],
	["payroll_variable_input", payrollVariableInput],
	["payroll_run", payrollRun],
	["payroll_run_employee", payrollRunEmployee],
	["payroll_result_line", payrollResultLine],
	["payroll_statutory_result", payrollStatutoryResult],
	["payroll_exception", payrollException],
	["payroll_payslip", payrollPayslip],
	["payroll_adjustment", payrollAdjustment],
	["payroll_reconciliation", payrollReconciliation],
	["payroll_accepted_handoff", payrollAcceptedHandoff],
	["payroll_rule_finalized_usage", payrollRuleFinalizedUsage],
	["stock_movement", stockMovement],
	["stock_movement_line", stockMovementLine],
	["stock_balance", stockBalance],
	["stock_ledger_entry", stockLedgerEntry],
	["stock_reservation", stockReservation],
	["goods_receipt", goodsReceipt],
	["goods_receipt_line", goodsReceiptLine],
	["receiving_discrepancy", receivingDiscrepancy],
	["delivery", delivery],
	["delivery_line", deliveryLine],
	["delivery_pick", deliveryPick],
	["delivery_pack", deliveryPack],
	["proof_of_delivery", proofOfDelivery],
	["journal", journal],
	["journal_line", journalLine],
	["ledger_posting", ledgerPosting],
	["accounting_period", accountingPeriod],
	["chart_of_account", chartOfAccount],
	["ledger_account", ledgerAccount],
	["account_role_mapping", accountRoleMapping],
	["posting_profile", postingProfile],
	["posting_profile_line", postingProfileLine],
	["source_posting_link", sourcePostingLink],
	["financial_posting_exception", financialPostingException],
	["hr_person", hrPerson],
	["hr_person_contact", hrPersonContact],
	["hr_person_identifier", hrPersonIdentifier],
	["hr_person_identity_version", hrPersonIdentityVersion],
	["hr_employee", hrEmployee],
	["hr_worker", hrWorker],
	["hr_worker_classification_version", hrWorkerClassificationVersion],
	["hr_employment", hrEmployment],
	["hr_employment_status_history", hrEmploymentStatusHistory],
	["hr_employment_contract", hrEmploymentContract],
	["hr_work_assignment", hrWorkAssignment],
	["hr_department", hrDepartment],
	["hr_department_structure_version", hrDepartmentStructureVersion],
	["hr_job", hrJob],
	["hr_job_definition_version", hrJobDefinitionVersion],
	["hr_position", hrPosition],
	["hr_position_definition_version", hrPositionDefinitionVersion],
	["hr_reporting_line", hrReportingLine],
	["hr_employment_movement", hrEmploymentMovement],
	["hr_job_requisition", hrJobRequisition],
	["hr_candidate", hrCandidate],
	["hr_candidate_application", hrCandidateApplication],
	[
		"hr_candidate_application_status_history",
		hrCandidateApplicationStatusHistory,
	],
	["hr_interview", hrInterview],
	["hr_interview_evaluation", hrInterviewEvaluation],
	["hr_employment_offer", hrEmploymentOffer],
	["hr_hire_attempt", hrHireAttempt],
	["hr_onboarding_case", hrOnboardingCase],
	["hr_onboarding_task", hrOnboardingTask],
	["hr_onboarding_orientation", hrOnboardingOrientation],
	["hr_onboarding_equipment_handoff", hrOnboardingEquipmentHandoff],
	["hr_onboarding_access_handoff", hrOnboardingAccessHandoff],
	["hr_probation_review", hrProbationReview],
	["hr_probation_assessment", hrProbationAssessment],
	["hr_employment_confirmation", hrEmploymentConfirmation],
	["hr_termination", hrTermination],
	["hr_offboarding_case", hrOffboardingCase],
	["hr_offboarding_task", hrOffboardingTask],
	["hr_exit_interview", hrExitInterview],
	["hr_clearance", hrClearance],
	["hr_offboarding_access_revocation", hrOffboardingAccessRevocation],
	["hr_offboarding_payroll_handoff", hrOffboardingPayrollHandoff],
	["hr_learning_course", hrLearningCourse],
	["hr_learning_program", hrLearningProgram],
	["hr_learning_session", hrLearningSession],
	["hr_learning_assignment", hrLearningAssignment],
	["hr_learning_attendance", hrLearningAttendance],
	["hr_learning_assessment", hrLearningAssessment],
	["hr_learning_completion", hrLearningCompletion],
	["hr_employee_certification", hrEmployeeCertification],
	["hr_development_plan", hrDevelopmentPlan],
	["hr_compensation_grade", hrCompensationGrade],
	["hr_salary_band", hrSalaryBand],
	[
		"hr_compensation_grade_progression_rule",
		hrCompensationGradeProgressionRule,
	],
	["hr_employee_compensation", hrEmployeeCompensation],
	["hr_allowance_entitlement", hrAllowanceEntitlement],
	["hr_bonus_eligibility", hrBonusEligibility],
	["hr_benefit_plan", hrBenefitPlan],
	["hr_benefit_eligibility", hrBenefitEligibility],
	["hr_benefit_enrollment", hrBenefitEnrollment],
	["hr_benefit_enrollment_dependent", hrBenefitEnrollmentDependent],
	["hr_compensation_review_cycle", hrCompensationReviewCycle],
	["hr_compensation_review", hrCompensationReview],
	["hr_compensation_proposal", hrCompensationProposal],
	["hr_leave_policy", hrLeavePolicy],
	["hr_leave_policy_eligibility", hrLeavePolicyEligibility],
	["hr_leave_entitlement", hrLeaveEntitlement],
	["hr_leave_adjustment", hrLeaveAdjustment],
	["hr_leave_request", hrLeaveRequest],
	["hr_leave_request_segment", hrLeaveRequestSegment],
	["hr_leave_approval_decision", hrLeaveApprovalDecision],
	["hr_performance_cycle", hrPerformanceCycle],
	["hr_performance_cycle_participant", hrPerformanceCycleParticipant],
	["hr_performance_cycle_review_period", hrPerformanceCycleReviewPeriod],
	["hr_performance_cycle_eligibility", hrPerformanceCycleEligibility],
	["hr_performance_goal", hrPerformanceGoal],
	["hr_performance_goal_progress", hrPerformanceGoalProgress],
	["hr_performance_review", hrPerformanceReview],
	["hr_performance_review_participant", hrPerformanceReviewParticipant],
	["hr_performance_assessment", hrPerformanceAssessment],
	["hr_performance_improvement_plan", hrPerformanceImprovementPlan],
	["hr_performance_improvement_checkpoint", hrPerformanceImprovementCheckpoint],
	["hr_competency", hrCompetency],
	["hr_job_competency", hrJobCompetency],
	["hr_competency_assessment", hrCompetencyAssessment],
	["hr_talent_profile", hrTalentProfile],
	["hr_talent_profile_assessment", hrTalentProfileAssessment],
	["hr_talent_profile_mobility", hrTalentProfileMobility],
	["hr_talent_critical_role_readiness", hrTalentCriticalRoleReadiness],
	["hr_talent_pool", hrTalentPool],
	["hr_talent_pool_member", hrTalentPoolMember],
	["hr_career_plan", hrCareerPlan],
	["hr_career_plan_action", hrCareerPlanAction],
	["hr_succession_plan", hrSuccessionPlan],
	["hr_succession_candidate", hrSuccessionCandidate],
	["hr_headcount_plan", hrHeadcountPlan],
	["hr_headcount_plan_line", hrHeadcountPlanLine],
	["hr_headcount_reservation", hrHeadcountReservation],
	["hr_employee_case", hrEmployeeCase],
	["hr_employee_case_event", hrEmployeeCaseEvent],
	["hr_employee_case_action", hrEmployeeCaseAction],
	["hr_employee_case_appeal", hrEmployeeCaseAppeal],
	["hr_document_requirement", hrDocumentRequirement],
	["hr_employee_document", hrEmployeeDocument],
	["hr_work_eligibility", hrWorkEligibility],
	["hr_policy_acknowledgement", hrPolicyAcknowledgement],
	["hr_payroll_handoff_delivery", hrPayrollHandoffDelivery],
	["hr_bulk_import_checkpoint", hrBulkImportCheckpoint],
	["hr_bulk_import_audit", hrBulkImportAudit],
	["hr_bulk_import_error_artifact", hrBulkImportErrorArtifact],
	["hr_bulk_export_artifact_chunk", hrBulkExportArtifactChunk],
	["hr_bulk_export_job", hrBulkExportJob],
	["hr_bulk_import_job", hrBulkImportJob],
	["hr_bulk_import_job_row", hrBulkImportJobRow],
	["hr_user_employee", hrUserEmployee],
	["hr_reliability_work_item", hrReliabilityWorkItem],
	["hr_reliability_dead_letter", hrReliabilityDeadLetter],
	["hr_connector_cursor", hrConnectorCursor],
	["hr_work_calendar", hrWorkCalendar],
	["hr_work_calendar_holiday", hrWorkCalendarHoliday],
	["hr_employment_calendar_assignment", hrEmploymentCalendarAssignment],
	["hr_work_calendar_scope_assignment", hrWorkCalendarScopeAssignment],
	["hr_shift", hrShift],
	["hr_shift_break", hrShiftBreak],
	["hr_shift_assignment", hrShiftAssignment],
	["hr_shift_assignment_segment", hrShiftAssignmentSegment],
	["hr_attendance_event", hrAttendanceEvent],
	["hr_attendance_session", hrAttendanceSession],
	["hr_attendance_break_waiver_decision", hrAttendanceBreakWaiverDecision],
	["hr_attendance_exception", hrAttendanceException],
	["hr_attendance_adjustment", hrAttendanceAdjustment],
	["hr_attendance_import_batch", hrAttendanceImportBatch],
	["hr_attendance_import_error", hrAttendanceImportError],
	["hr_time_policy", hrTimePolicy],
	["hr_time_policy_assignment", hrTimePolicyAssignment],
	["hr_time_approval_authority_assignment", hrTimeApprovalAuthorityAssignment],
	["hr_timesheet", hrTimesheet],
	["hr_timesheet_approval_decision", hrTimesheetApprovalDecision],
	["hr_timesheet_entry", hrTimesheetEntry],
	["hr_overtime_request", hrOvertimeRequest],
	["hr_overtime_approval", hrOvertimeApproval],
] as const;

export type HardTenantRootTableName =
	(typeof HARD_TENANT_ROOT_ENTRIES)[number][0];

export type HardTenantRootTable = (typeof HARD_TENANT_ROOT_ENTRIES)[number][1];

export const HARD_TENANT_ROOT_TABLE_NAMES: readonly HardTenantRootTableName[] =
	HARD_TENANT_ROOT_ENTRIES.map(([name]) => name);

export const HARD_TENANT_ROOT_TABLES: Readonly<
	Record<HardTenantRootTableName, HardTenantRootTable>
> = Object.fromEntries(HARD_TENANT_ROOT_ENTRIES);
