/**
 * Human Resources semantic error codes — package authority.
 * Platform `Result` uses `@afenda/errors` ErrorCode; attach these via details.humanResourcesCode.
 */

export const HUMAN_RESOURCES_ERROR_INVALID_INPUT =
	"human_resources.invalid_input" as const;
export const HUMAN_RESOURCES_ERROR_UNAUTHORIZED =
	"human_resources.unauthorized" as const;
export const HUMAN_RESOURCES_ERROR_FORBIDDEN =
	"human_resources.forbidden" as const;
export const HUMAN_RESOURCES_ERROR_NOT_FOUND =
	"human_resources.not_found" as const;
export const HUMAN_RESOURCES_ERROR_CONFLICT =
	"human_resources.conflict" as const;
export const HUMAN_RESOURCES_ERROR_DUPLICATE =
	"human_resources.duplicate" as const;
export const HUMAN_RESOURCES_ERROR_INVALID_STATE_TRANSITION =
	"human_resources.invalid_state_transition" as const;
export const HUMAN_RESOURCES_ERROR_STALE_VERSION =
	"human_resources.stale_version" as const;
export const HUMAN_RESOURCES_ERROR_CROSS_ORGANIZATION_REFERENCE =
	"human_resources.cross_organization_reference" as const;
export const HUMAN_RESOURCES_ERROR_DEPENDENCY_UNAVAILABLE =
	"human_resources.dependency_unavailable" as const;
export const HUMAN_RESOURCES_ERROR_PERSISTENCE_FAILURE =
	"human_resources.persistence_failure" as const;
export const HUMAN_RESOURCES_ERROR_PERSON_NOT_FOUND =
	"human_resources.person_not_found" as const;
export const HUMAN_RESOURCES_ERROR_WORKER_NOT_FOUND =
	"human_resources.worker_not_found" as const;
export const HUMAN_RESOURCES_ERROR_EMPLOYMENT_NOT_FOUND =
	"human_resources.employment_not_found" as const;
export const HUMAN_RESOURCES_ERROR_ASSIGNMENT_NOT_FOUND =
	"human_resources.assignment_not_found" as const;
export const HUMAN_RESOURCES_ERROR_DIRECTORY_REFERENCE_NOT_FOUND =
	"human_resources.directory_reference_not_found" as const;
export const HUMAN_RESOURCES_ERROR_DIRECTORY_REFERENCE_INACTIVE =
	"human_resources.directory_reference_inactive" as const;
export const HUMAN_RESOURCES_ERROR_EFFECTIVE_DATE_CONFLICT =
	"human_resources.effective_date_conflict" as const;
export const HUMAN_RESOURCES_ERROR_EFFECTIVE_RANGE_OVERLAP =
	"human_resources.effective_range_overlap" as const;
export const HUMAN_RESOURCES_ERROR_MULTIPLE_PRIMARY_ASSIGNMENTS =
	"human_resources.multiple_primary_assignments" as const;
export const HUMAN_RESOURCES_ERROR_NO_DETERMINISTIC_ASSIGNMENT =
	"human_resources.no_deterministic_assignment" as const;
export const HUMAN_RESOURCES_ERROR_ASSIGNMENT_OUTSIDE_EMPLOYMENT_RANGE =
	"human_resources.assignment_outside_employment_range" as const;
export const HUMAN_RESOURCES_ERROR_REPORTING_SELF_REFERENCE =
	"human_resources.reporting_self_reference" as const;
export const HUMAN_RESOURCES_ERROR_REPORTING_CYCLE =
	"human_resources.reporting_cycle" as const;
export const HUMAN_RESOURCES_ERROR_MANAGER_ASSIGNMENT_NOT_EFFECTIVE =
	"human_resources.manager_assignment_not_effective" as const;
export const HUMAN_RESOURCES_ERROR_REHIRE_REQUIRES_ENDED_EMPLOYMENT =
	"human_resources.rehire_requires_ended_employment" as const;
export const HUMAN_RESOURCES_ERROR_INCOMPATIBLE_WORKER_TYPE =
	"human_resources.incompatible_worker_type" as const;
export const HUMAN_RESOURCES_ERROR_SENSITIVE_FIELD_ACCESS_DENIED =
	"human_resources.sensitive_field_access_denied" as const;
export const HUMAN_RESOURCES_ERROR_CONCURRENCY_CONFLICT =
	"human_resources.concurrency_conflict" as const;

export const HUMAN_RESOURCES_ERROR_CODES = {
	INVALID_INPUT: HUMAN_RESOURCES_ERROR_INVALID_INPUT,
	UNAUTHORIZED: HUMAN_RESOURCES_ERROR_UNAUTHORIZED,
	FORBIDDEN: HUMAN_RESOURCES_ERROR_FORBIDDEN,
	NOT_FOUND: HUMAN_RESOURCES_ERROR_NOT_FOUND,
	CONFLICT: HUMAN_RESOURCES_ERROR_CONFLICT,
	DUPLICATE: HUMAN_RESOURCES_ERROR_DUPLICATE,
	INVALID_STATE_TRANSITION: HUMAN_RESOURCES_ERROR_INVALID_STATE_TRANSITION,
	STALE_VERSION: HUMAN_RESOURCES_ERROR_STALE_VERSION,
	CROSS_ORGANIZATION_REFERENCE:
		HUMAN_RESOURCES_ERROR_CROSS_ORGANIZATION_REFERENCE,
	DEPENDENCY_UNAVAILABLE: HUMAN_RESOURCES_ERROR_DEPENDENCY_UNAVAILABLE,
	PERSISTENCE_FAILURE: HUMAN_RESOURCES_ERROR_PERSISTENCE_FAILURE,
	PERSON_NOT_FOUND: HUMAN_RESOURCES_ERROR_PERSON_NOT_FOUND,
	WORKER_NOT_FOUND: HUMAN_RESOURCES_ERROR_WORKER_NOT_FOUND,
	EMPLOYMENT_NOT_FOUND: HUMAN_RESOURCES_ERROR_EMPLOYMENT_NOT_FOUND,
	ASSIGNMENT_NOT_FOUND: HUMAN_RESOURCES_ERROR_ASSIGNMENT_NOT_FOUND,
	DIRECTORY_REFERENCE_NOT_FOUND:
		HUMAN_RESOURCES_ERROR_DIRECTORY_REFERENCE_NOT_FOUND,
	DIRECTORY_REFERENCE_INACTIVE:
		HUMAN_RESOURCES_ERROR_DIRECTORY_REFERENCE_INACTIVE,
	EFFECTIVE_DATE_CONFLICT: HUMAN_RESOURCES_ERROR_EFFECTIVE_DATE_CONFLICT,
	EFFECTIVE_RANGE_OVERLAP: HUMAN_RESOURCES_ERROR_EFFECTIVE_RANGE_OVERLAP,
	MULTIPLE_PRIMARY_ASSIGNMENTS:
		HUMAN_RESOURCES_ERROR_MULTIPLE_PRIMARY_ASSIGNMENTS,
	NO_DETERMINISTIC_ASSIGNMENT:
		HUMAN_RESOURCES_ERROR_NO_DETERMINISTIC_ASSIGNMENT,
	ASSIGNMENT_OUTSIDE_EMPLOYMENT_RANGE:
		HUMAN_RESOURCES_ERROR_ASSIGNMENT_OUTSIDE_EMPLOYMENT_RANGE,
	REPORTING_SELF_REFERENCE: HUMAN_RESOURCES_ERROR_REPORTING_SELF_REFERENCE,
	REPORTING_CYCLE: HUMAN_RESOURCES_ERROR_REPORTING_CYCLE,
	MANAGER_ASSIGNMENT_NOT_EFFECTIVE:
		HUMAN_RESOURCES_ERROR_MANAGER_ASSIGNMENT_NOT_EFFECTIVE,
	REHIRE_REQUIRES_ENDED_EMPLOYMENT:
		HUMAN_RESOURCES_ERROR_REHIRE_REQUIRES_ENDED_EMPLOYMENT,
	INCOMPATIBLE_WORKER_TYPE: HUMAN_RESOURCES_ERROR_INCOMPATIBLE_WORKER_TYPE,
	SENSITIVE_FIELD_ACCESS_DENIED:
		HUMAN_RESOURCES_ERROR_SENSITIVE_FIELD_ACCESS_DENIED,
	CONCURRENCY_CONFLICT: HUMAN_RESOURCES_ERROR_CONCURRENCY_CONFLICT,
} as const;

export const HUMAN_RESOURCES_ERROR_CODE_LIST = [
	HUMAN_RESOURCES_ERROR_INVALID_INPUT,
	HUMAN_RESOURCES_ERROR_UNAUTHORIZED,
	HUMAN_RESOURCES_ERROR_FORBIDDEN,
	HUMAN_RESOURCES_ERROR_NOT_FOUND,
	HUMAN_RESOURCES_ERROR_CONFLICT,
	HUMAN_RESOURCES_ERROR_DUPLICATE,
	HUMAN_RESOURCES_ERROR_INVALID_STATE_TRANSITION,
	HUMAN_RESOURCES_ERROR_STALE_VERSION,
	HUMAN_RESOURCES_ERROR_CROSS_ORGANIZATION_REFERENCE,
	HUMAN_RESOURCES_ERROR_DEPENDENCY_UNAVAILABLE,
	HUMAN_RESOURCES_ERROR_PERSISTENCE_FAILURE,
	HUMAN_RESOURCES_ERROR_PERSON_NOT_FOUND,
	HUMAN_RESOURCES_ERROR_WORKER_NOT_FOUND,
	HUMAN_RESOURCES_ERROR_EMPLOYMENT_NOT_FOUND,
	HUMAN_RESOURCES_ERROR_ASSIGNMENT_NOT_FOUND,
	HUMAN_RESOURCES_ERROR_DIRECTORY_REFERENCE_NOT_FOUND,
	HUMAN_RESOURCES_ERROR_DIRECTORY_REFERENCE_INACTIVE,
	HUMAN_RESOURCES_ERROR_EFFECTIVE_DATE_CONFLICT,
	HUMAN_RESOURCES_ERROR_EFFECTIVE_RANGE_OVERLAP,
	HUMAN_RESOURCES_ERROR_MULTIPLE_PRIMARY_ASSIGNMENTS,
	HUMAN_RESOURCES_ERROR_NO_DETERMINISTIC_ASSIGNMENT,
	HUMAN_RESOURCES_ERROR_ASSIGNMENT_OUTSIDE_EMPLOYMENT_RANGE,
	HUMAN_RESOURCES_ERROR_REPORTING_SELF_REFERENCE,
	HUMAN_RESOURCES_ERROR_REPORTING_CYCLE,
	HUMAN_RESOURCES_ERROR_MANAGER_ASSIGNMENT_NOT_EFFECTIVE,
	HUMAN_RESOURCES_ERROR_REHIRE_REQUIRES_ENDED_EMPLOYMENT,
	HUMAN_RESOURCES_ERROR_INCOMPATIBLE_WORKER_TYPE,
	HUMAN_RESOURCES_ERROR_SENSITIVE_FIELD_ACCESS_DENIED,
	HUMAN_RESOURCES_ERROR_CONCURRENCY_CONFLICT,
] as const;

export type HumanResourcesErrorCode =
	(typeof HUMAN_RESOURCES_ERROR_CODE_LIST)[number];

export function humanResourcesErrorDetails(
	humanResourcesCode: HumanResourcesErrorCode,
): { humanResourcesCode: HumanResourcesErrorCode } {
	return { humanResourcesCode };
}
