import "server-only";

export type {
	HumanResourcesAuthorizationPort,
	HumanResourcesPermission,
} from "./authorization";
export {
	type HumanResourcesAssignmentId,
	type HumanResourcesDepartmentId,
	type HumanResourcesEmployeeId,
	type HumanResourcesEmploymentContractId,
	type HumanResourcesEmploymentId,
	type HumanResourcesJobId,
	type HumanResourcesPositionId,
	type HumanResourcesReportingLineId,
	humanResourcesAssignmentIdSchema,
	humanResourcesDepartmentIdSchema,
	humanResourcesEmployeeIdSchema,
	humanResourcesEmploymentContractIdSchema,
	humanResourcesEmploymentIdSchema,
	humanResourcesJobIdSchema,
	humanResourcesPositionIdSchema,
	humanResourcesReportingLineIdSchema,
	parseHumanResourcesAssignmentId,
	parseHumanResourcesDepartmentId,
	parseHumanResourcesEmployeeId,
	parseHumanResourcesEmploymentContractId,
	parseHumanResourcesEmploymentId,
	parseHumanResourcesJobId,
	parseHumanResourcesPositionId,
	parseHumanResourcesReportingLineId,
} from "./brands";
export type { HumanResourcesCommandOptions } from "./command-options";
export {
	createAssignment,
	endAssignment,
	getAssignment,
} from "./core/assignment";
export {
	createEmployee,
	getEmployeeById,
	listEmployees,
	updateEmployee,
} from "./core/employee";
export {
	amendEmployment,
	createEmployment,
	getEmployment,
} from "./core/employment";
export {
	createEmploymentContract,
	getEmploymentContract,
} from "./core/employment-contract";
export {
	HUMAN_RESOURCES_ERROR_CODE_LIST,
	HUMAN_RESOURCES_ERROR_CODES,
	HUMAN_RESOURCES_ERROR_CONFLICT,
	HUMAN_RESOURCES_ERROR_CROSS_ORGANIZATION_REFERENCE,
	HUMAN_RESOURCES_ERROR_DEPENDENCY_UNAVAILABLE,
	HUMAN_RESOURCES_ERROR_DUPLICATE,
	HUMAN_RESOURCES_ERROR_FORBIDDEN,
	HUMAN_RESOURCES_ERROR_INVALID_INPUT,
	HUMAN_RESOURCES_ERROR_INVALID_STATE_TRANSITION,
	HUMAN_RESOURCES_ERROR_NOT_FOUND,
	HUMAN_RESOURCES_ERROR_PERSISTENCE_FAILURE,
	HUMAN_RESOURCES_ERROR_STALE_VERSION,
	HUMAN_RESOURCES_ERROR_UNAUTHORIZED,
	type HumanResourcesErrorCode,
	humanResourcesErrorDetails,
} from "./error-codes";
export {
	HUMAN_RESOURCES_COMMAND_ASSIGNMENT_CREATE,
	HUMAN_RESOURCES_COMMAND_ASSIGNMENT_END,
	HUMAN_RESOURCES_COMMAND_DEPARTMENT_ACTIVATE,
	HUMAN_RESOURCES_COMMAND_DEPARTMENT_ARCHIVE,
	HUMAN_RESOURCES_COMMAND_DEPARTMENT_CREATE,
	HUMAN_RESOURCES_COMMAND_DEPARTMENT_UPDATE,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_CREATE,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_UPDATE,
	HUMAN_RESOURCES_COMMAND_EMPLOYMENT_AMEND,
	HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CONTRACT_CREATE,
	HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CREATE,
	HUMAN_RESOURCES_COMMAND_IDS,
	HUMAN_RESOURCES_COMMAND_JOB_ACTIVATE,
	HUMAN_RESOURCES_COMMAND_JOB_ARCHIVE,
	HUMAN_RESOURCES_COMMAND_JOB_CREATE,
	HUMAN_RESOURCES_COMMAND_JOB_UPDATE,
	HUMAN_RESOURCES_COMMAND_POSITION_ACTIVATE,
	HUMAN_RESOURCES_COMMAND_POSITION_CLOSE,
	HUMAN_RESOURCES_COMMAND_POSITION_CREATE,
	HUMAN_RESOURCES_COMMAND_POSITION_FREEZE,
	HUMAN_RESOURCES_COMMAND_POSITION_UPDATE,
	HUMAN_RESOURCES_COMMAND_REPORTING_LINE_ASSIGN_PRIMARY,
	HUMAN_RESOURCES_COMMAND_REPORTING_LINE_CLOSE,
	HUMAN_RESOURCES_COMMAND_REPORTING_LINE_REPLACE_PRIMARY,
	HUMAN_RESOURCES_QUERY_ASSIGNMENT_GET,
	HUMAN_RESOURCES_QUERY_DEPARTMENT_GET,
	HUMAN_RESOURCES_QUERY_DEPARTMENT_LIST,
	HUMAN_RESOURCES_QUERY_EMPLOYEE_GET,
	HUMAN_RESOURCES_QUERY_EMPLOYEE_LIST,
	HUMAN_RESOURCES_QUERY_EMPLOYMENT_CONTRACT_GET,
	HUMAN_RESOURCES_QUERY_EMPLOYMENT_GET,
	HUMAN_RESOURCES_QUERY_IDS,
	HUMAN_RESOURCES_QUERY_JOB_GET,
	HUMAN_RESOURCES_QUERY_JOB_LIST,
	HUMAN_RESOURCES_QUERY_ORGANIZATION_TREE,
	HUMAN_RESOURCES_QUERY_POSITION_GET,
	HUMAN_RESOURCES_QUERY_POSITION_LIST,
	HUMAN_RESOURCES_QUERY_REPORTING_LINE_LIST_DIRECT_REPORTS,
	HUMAN_RESOURCES_QUERY_REPORTING_LINE_RESOLVE_PRIMARY_MANAGER,
	type HumanResourcesCommandId,
	type HumanResourcesQueryId,
} from "./module-ids";
export {
	activateDepartment,
	archiveDepartment,
	createDepartment,
	getDepartment,
	getOrganizationTree,
	listDepartments,
	updateDepartment,
} from "./organization/department";
export {
	activateJob,
	archiveJob,
	createJob,
	getJob,
	listJobs,
	updateJob,
} from "./organization/job";
export {
	activatePosition,
	closePosition,
	createPosition,
	freezePosition,
	getPosition,
	listPositions,
	updatePosition,
} from "./organization/position";
export {
	assignPrimaryReportingLine,
	closeReportingLine,
	listDirectReports,
	replacePrimaryReportingLine,
	resolvePrimaryManager,
} from "./organization/reporting-line";
export {
	HUMAN_RESOURCES_PERMISSION_ATTENDANCE_MANAGE,
	HUMAN_RESOURCES_PERMISSION_BENEFITS_MANAGE,
	HUMAN_RESOURCES_PERMISSION_CANDIDATE_MANAGE,
	HUMAN_RESOURCES_PERMISSION_CERTIFICATION_MANAGE,
	HUMAN_RESOURCES_PERMISSION_CODES,
	HUMAN_RESOURCES_PERMISSION_COMPENSATION_MANAGE,
	HUMAN_RESOURCES_PERMISSION_COMPENSATION_READ,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CREATE,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_READ,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_UPDATE,
	HUMAN_RESOURCES_PERMISSION_EMPLOYMENT_MANAGE,
	HUMAN_RESOURCES_PERMISSION_INTERVIEW_RECORD,
	HUMAN_RESOURCES_PERMISSION_LEARNING_MANAGE,
	HUMAN_RESOURCES_PERMISSION_LEAVE_APPROVE,
	HUMAN_RESOURCES_PERMISSION_LEAVE_REQUEST,
	HUMAN_RESOURCES_PERMISSION_OFFBOARDING_MANAGE,
	HUMAN_RESOURCES_PERMISSION_OFFER_APPROVE,
	HUMAN_RESOURCES_PERMISSION_ONBOARDING_MANAGE,
	HUMAN_RESOURCES_PERMISSION_ORGANIZATION_MANAGE,
	HUMAN_RESOURCES_PERMISSION_ORGANIZATION_READ,
	HUMAN_RESOURCES_PERMISSION_PERFORMANCE_MANAGE,
	HUMAN_RESOURCES_PERMISSION_REQUISITION_CREATE,
	HUMAN_RESOURCES_PERMISSION_TIMESHEET_APPROVE,
} from "./permissions";
export type {
	AuditFactPort,
	MutationPorts,
	OutboxPort,
} from "./ports";
export {
	type AmendEmploymentInput,
	type AssignPrimaryReportingLineInput,
	amendEmploymentInputSchema,
	assignPrimaryReportingLineInputSchema,
	type CloseReportingLineInput,
	type CreateAssignmentInput,
	type CreateDepartmentInput,
	type CreateEmployeeInput,
	type CreateEmploymentContractInput,
	type CreateEmploymentInput,
	type CreateJobInput,
	type CreatePositionInput,
	closeReportingLineInputSchema,
	createAssignmentInputSchema,
	createDepartmentInputSchema,
	createEmployeeInputSchema,
	createEmploymentContractInputSchema,
	createEmploymentInputSchema,
	createJobInputSchema,
	createPositionInputSchema,
	type EndAssignmentInput,
	endAssignmentInputSchema,
	type GetAssignmentInput,
	type GetDepartmentInput,
	type GetEmployeeByIdInput,
	type GetEmploymentContractInput,
	type GetEmploymentInput,
	type GetJobInput,
	type GetPositionInput,
	getAssignmentInputSchema,
	getDepartmentInputSchema,
	getEmployeeByIdInputSchema,
	getEmploymentContractInputSchema,
	getEmploymentInputSchema,
	getJobInputSchema,
	getPositionInputSchema,
	type HumanResourcesMutationContext,
	type HumanResourcesTenantContext,
	humanResourcesActorUserIdSchema,
	humanResourcesCorrelationIdSchema,
	humanResourcesExpectedVersionSchema,
	humanResourcesIdempotencyKeySchema,
	humanResourcesMutationContextSchema,
	humanResourcesOrganizationIdSchema,
	humanResourcesTenantContextSchema,
	type ListDepartmentsInput,
	type ListDirectReportsInput,
	type ListEmployeesInput,
	type ListJobsInput,
	type ListPositionsInput,
	listDepartmentsInputSchema,
	listDirectReportsInputSchema,
	listEmployeesInputSchema,
	listJobsInputSchema,
	listPositionsInputSchema,
	type OrganizationTreeInput,
	organizationTreeInputSchema,
	type ReplacePrimaryReportingLineInput,
	type ResolvePrimaryManagerInput,
	replacePrimaryReportingLineInputSchema,
	resolvePrimaryManagerInputSchema,
	type UpdateDepartmentInput,
	type UpdateEmployeeInput,
	type UpdateJobInput,
	type UpdatePositionInput,
	updateDepartmentInputSchema,
	updateEmployeeInputSchema,
	updateJobInputSchema,
	updatePositionInputSchema,
} from "./schemas";
export type {
	DepartmentStatus,
	EmploymentStatus,
	JobStatus,
	PositionStatus,
	ReportingRelationshipKind,
} from "./shared/employment-status";
export {
	DEPARTMENT_STATUSES,
	EMPLOYMENT_STATUSES,
	JOB_STATUSES,
	POSITION_STATUSES,
	REPORTING_RELATIONSHIP_KINDS,
} from "./shared/employment-status";
export type {
	Department,
	Employee,
	EmployeeListPage,
	Employment,
	EmploymentContract,
	Job,
	OrganizationTreeNode,
	OrganizationTreePage,
	Position,
	ReportingLine,
	WorkAssignment,
} from "./types";
