import "server-only";

export type {
	HumanResourcesAuthorizationPort,
	HumanResourcesPermission,
} from "./authorization";
export {
	type HumanResourcesEmployeeId,
	humanResourcesEmployeeIdSchema,
} from "./brands";
export type { HumanResourcesCommandOptions } from "./command-options";
export { createEmployee, getEmployeeById } from "./core/employee";
export {
	HUMAN_RESOURCES_ERROR_CODE_LIST,
	HUMAN_RESOURCES_ERROR_CODES,
	HUMAN_RESOURCES_ERROR_EMPLOYEE_DUPLICATE,
	HUMAN_RESOURCES_ERROR_EMPLOYEE_NOT_FOUND,
	HUMAN_RESOURCES_ERROR_FORBIDDEN,
	HUMAN_RESOURCES_ERROR_IDEMPOTENCY_CONFLICT,
	HUMAN_RESOURCES_ERROR_INVALID_STATE_TRANSITION,
	HUMAN_RESOURCES_ERROR_PERSISTENCE_FAILURE,
	HUMAN_RESOURCES_ERROR_UNAUTHORIZED,
	HUMAN_RESOURCES_ERROR_VALIDATION,
	HUMAN_RESOURCES_ERROR_VERSION_CONFLICT,
	type HumanResourcesErrorCode,
	humanResourcesErrorDetails,
} from "./error-codes";
export {
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_CREATE,
	HUMAN_RESOURCES_COMMAND_IDS,
	HUMAN_RESOURCES_QUERY_EMPLOYEE_GET,
	HUMAN_RESOURCES_QUERY_IDS,
	type HumanResourcesCommandId,
	type HumanResourcesQueryId,
} from "./module-ids";
export {
	HUMAN_RESOURCES_PERMISSION_ATTENDANCE_MANAGE,
	HUMAN_RESOURCES_PERMISSION_BENEFITS_MANAGE,
	HUMAN_RESOURCES_PERMISSION_CANDIDATE_MANAGE,
	HUMAN_RESOURCES_PERMISSION_CERTIFICATION_MANAGE,
	HUMAN_RESOURCES_PERMISSION_CODES,
	HUMAN_RESOURCES_PERMISSION_COMPENSATION_MANAGE,
	HUMAN_RESOURCES_PERMISSION_COMPENSATION_READ,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CREATE,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_READ,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_UPDATE,
	HUMAN_RESOURCES_PERMISSION_EMPLOYMENT_MANAGE,
	HUMAN_RESOURCES_PERMISSION_INTERVIEW_RECORD,
	HUMAN_RESOURCES_PERMISSION_LEARNING_MANAGE,
	HUMAN_RESOURCES_PERMISSION_LEAVE_APPROVE,
	HUMAN_RESOURCES_PERMISSION_LEAVE_REQUEST,
	HUMAN_RESOURCES_PERMISSION_OFFBOARDING_MANAGE,
	HUMAN_RESOURCES_PERMISSION_OFFER_APPROVE,
	HUMAN_RESOURCES_PERMISSION_ONBOARDING_MANAGE,
	HUMAN_RESOURCES_PERMISSION_PERFORMANCE_MANAGE,
	HUMAN_RESOURCES_PERMISSION_REQUISITION_CREATE,
	HUMAN_RESOURCES_PERMISSION_TIMESHEET_APPROVE,
} from "./permissions";
export type {
	AuditFactPort,
	MutationPorts,
	OutboxPort,
} from "./ports";
export {
	type CreateEmployeeInput,
	createEmployeeInputSchema,
	type GetEmployeeByIdInput,
	getEmployeeByIdInputSchema,
	type HumanResourcesMutationContext,
	type HumanResourcesTenantContext,
	humanResourcesActorUserIdSchema,
	humanResourcesCorrelationIdSchema,
	humanResourcesExpectedVersionSchema,
	humanResourcesIdempotencyKeySchema,
	humanResourcesMutationContextSchema,
	humanResourcesOrganizationIdSchema,
	humanResourcesTenantContextSchema,
} from "./schemas";
export type { Employee } from "./types";
