/**
 * Human Resources permission codes — ERP-owned; must stay aligned with
 * `@afenda/db` PLATFORM_PERMISSION_V1 (human-resources.*).
 */

export const HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CREATE =
	"human-resources.employee.create" as const;
export const HUMAN_RESOURCES_PERMISSION_EMPLOYEE_READ =
	"human-resources.employee.read" as const;
export const HUMAN_RESOURCES_PERMISSION_EMPLOYEE_UPDATE =
	"human-resources.employee.update" as const;
export const HUMAN_RESOURCES_PERMISSION_PERSON_READ =
	"human-resources.person.read" as const;
export const HUMAN_RESOURCES_PERMISSION_PERSON_MANAGE =
	"human-resources.person.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_WORKER_READ =
	"human-resources.worker.read" as const;
export const HUMAN_RESOURCES_PERMISSION_WORKER_MANAGE =
	"human-resources.worker.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_PERSONAL_DETAILS_READ =
	"human-resources.personal-details.read" as const;
export const HUMAN_RESOURCES_PERMISSION_PERSONAL_DETAILS_MANAGE =
	"human-resources.personal-details.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_SENSITIVE_IDENTIFIERS_READ =
	"human-resources.sensitive-identifiers.read" as const;
export const HUMAN_RESOURCES_PERMISSION_SENSITIVE_IDENTIFIERS_MANAGE =
	"human-resources.sensitive-identifiers.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_ASSIGNMENT_READ =
	"human-resources.assignment.read" as const;
export const HUMAN_RESOURCES_PERMISSION_ASSIGNMENT_MANAGE =
	"human-resources.assignment.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_ORGANIZATION_CONTEXT_READ =
	"human-resources.organization-context.read" as const;
export const HUMAN_RESOURCES_PERMISSION_REPORTING_LINE_MANAGE =
	"human-resources.reporting-line.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_EMPLOYMENT_MANAGE =
	"human-resources.employment.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_ORGANIZATION_READ =
	"human-resources.organization.read" as const;
export const HUMAN_RESOURCES_PERMISSION_ORGANIZATION_MANAGE =
	"human-resources.organization.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_REQUISITION_CREATE =
	"human-resources.requisition.create" as const;
export const HUMAN_RESOURCES_PERMISSION_CANDIDATE_MANAGE =
	"human-resources.candidate.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_INTERVIEW_RECORD =
	"human-resources.interview.record" as const;
export const HUMAN_RESOURCES_PERMISSION_OFFER_APPROVE =
	"human-resources.offer.approve" as const;
export const HUMAN_RESOURCES_PERMISSION_ONBOARDING_MANAGE =
	"human-resources.onboarding.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_OFFBOARDING_MANAGE =
	"human-resources.offboarding.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_LEAVE_POLICY_READ =
	"human-resources.leave-policy.read" as const;
export const HUMAN_RESOURCES_PERMISSION_LEAVE_POLICY_MANAGE =
	"human-resources.leave-policy.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_LEAVE_ENTITLEMENT_READ =
	"human-resources.leave-entitlement.read" as const;
export const HUMAN_RESOURCES_PERMISSION_LEAVE_ENTITLEMENT_GRANT =
	"human-resources.leave-entitlement.grant" as const;
export const HUMAN_RESOURCES_PERMISSION_LEAVE_ENTITLEMENT_ADJUST =
	"human-resources.leave-entitlement.adjust" as const;
export const HUMAN_RESOURCES_PERMISSION_LEAVE_REQUEST_OWN =
	"human-resources.leave-request.own" as const;
export const HUMAN_RESOURCES_PERMISSION_LEAVE_REQUEST_APPROVE_TEAM =
	"human-resources.leave-request.approve-team" as const;
export const HUMAN_RESOURCES_PERMISSION_LEAVE_REQUEST_BACKDATE =
	"human-resources.leave-request.backdate" as const;
export const HUMAN_RESOURCES_PERMISSION_LEAVE_REQUEST_SENSITIVE_READ =
	"human-resources.leave-request.sensitive-read" as const;
export const HUMAN_RESOURCES_PERMISSION_ATTENDANCE_MANAGE =
	"human-resources.attendance.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_TIME_CALENDAR_READ =
	"human-resources.time.calendar.read" as const;
export const HUMAN_RESOURCES_PERMISSION_TIME_CALENDAR_MANAGE =
	"human-resources.time.calendar.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_TIME_SHIFT_READ =
	"human-resources.time.shift.read" as const;
export const HUMAN_RESOURCES_PERMISSION_TIME_SHIFT_MANAGE =
	"human-resources.time.shift.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_TIME_SCHEDULE_READ =
	"human-resources.time.schedule.read" as const;
export const HUMAN_RESOURCES_PERMISSION_TIME_SCHEDULE_MANAGE =
	"human-resources.time.schedule.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_TIME_SCHEDULE_PUBLISH =
	"human-resources.time.schedule.publish" as const;
export const HUMAN_RESOURCES_PERMISSION_TIME_ATTENDANCE_SELF_RECORD =
	"human-resources.time.attendance.self.record" as const;
export const HUMAN_RESOURCES_PERMISSION_TIME_ATTENDANCE_READ =
	"human-resources.time.attendance.read" as const;
export const HUMAN_RESOURCES_PERMISSION_TIME_ATTENDANCE_CORRECT =
	"human-resources.time.attendance.correct" as const;
export const HUMAN_RESOURCES_PERMISSION_TIME_ATTENDANCE_MANAGE =
	"human-resources.time.attendance.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_TIME_EXCEPTION_READ =
	"human-resources.time.exception.read" as const;
export const HUMAN_RESOURCES_PERMISSION_TIME_EXCEPTION_RESOLVE =
	"human-resources.time.exception.resolve" as const;
export const HUMAN_RESOURCES_PERMISSION_TIME_TIMESHEET_SELF_READ =
	"human-resources.time.timesheet.self.read" as const;
export const HUMAN_RESOURCES_PERMISSION_TIME_TIMESHEET_SELF_EDIT =
	"human-resources.time.timesheet.self.edit" as const;
export const HUMAN_RESOURCES_PERMISSION_TIME_TIMESHEET_SUBMIT =
	"human-resources.time.timesheet.submit" as const;
export const HUMAN_RESOURCES_PERMISSION_TIME_TIMESHEET_READ =
	"human-resources.time.timesheet.read" as const;
export const HUMAN_RESOURCES_PERMISSION_TIME_TIMESHEET_APPROVE =
	"human-resources.time.timesheet.approve" as const;
export const HUMAN_RESOURCES_PERMISSION_TIME_TIMESHEET_REOPEN =
	"human-resources.time.timesheet.reopen" as const;
export const HUMAN_RESOURCES_PERMISSION_TIME_TIMESHEET_LOCK =
	"human-resources.time.timesheet.lock" as const;
export const HUMAN_RESOURCES_PERMISSION_TIME_OVERTIME_REQUEST =
	"human-resources.time.overtime.request" as const;
export const HUMAN_RESOURCES_PERMISSION_TIME_OVERTIME_READ =
	"human-resources.time.overtime.read" as const;
export const HUMAN_RESOURCES_PERMISSION_TIME_OVERTIME_APPROVE =
	"human-resources.time.overtime.approve" as const;
export const HUMAN_RESOURCES_PERMISSION_TIME_HANDOFF_READ =
	"human-resources.time.handoff.read" as const;
export const HUMAN_RESOURCES_PERMISSION_PERFORMANCE_MANAGE =
	"human-resources.performance.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_PERFORMANCE_OWN_READ =
	"human-resources.performance.own.read" as const;
export const HUMAN_RESOURCES_PERMISSION_PERFORMANCE_MANAGER_MANAGE =
	"human-resources.performance.manager.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_PERFORMANCE_IMPROVEMENT_PLAN_MANAGE =
	"human-resources.performance.improvement-plan.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_PERFORMANCE_REVIEW_REOPEN =
	"human-resources.performance.review.reopen" as const;
export const HUMAN_RESOURCES_PERMISSION_PERFORMANCE_CONFIDENTIAL_READ =
	"human-resources.performance.confidential.read" as const;
export const HUMAN_RESOURCES_PERMISSION_LEARNING_MANAGE =
	"human-resources.learning.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_CERTIFICATION_MANAGE =
	"human-resources.certification.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_COMPENSATION_READ =
	"human-resources.compensation.read" as const;
export const HUMAN_RESOURCES_PERMISSION_COMPENSATION_MANAGE =
	"human-resources.compensation.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_BENEFITS_MANAGE =
	"human-resources.benefits.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_OPEN =
	"human-resources.employee-case.open" as const;
export const HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_ASSIGNED_READ =
	"human-resources.employee-case.assigned.read" as const;
export const HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_INVESTIGATE =
	"human-resources.employee-case.investigate" as const;
export const HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_FINDING =
	"human-resources.employee-case.finding" as const;
export const HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_ACTION_APPROVE =
	"human-resources.employee-case.action.approve" as const;
export const HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_APPEAL =
	"human-resources.employee-case.appeal" as const;
export const HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_EXCEPTIONAL_ADMIN =
	"human-resources.employee-case.exceptional.admin" as const;
export const HUMAN_RESOURCES_PERMISSION_WORKFORCE_PLAN_READ =
	"human-resources.workforce-plan.read" as const;
export const HUMAN_RESOURCES_PERMISSION_WORKFORCE_PLAN_PREPARE =
	"human-resources.workforce-plan.prepare" as const;
export const HUMAN_RESOURCES_PERMISSION_WORKFORCE_PLAN_APPROVE =
	"human-resources.workforce-plan.approve" as const;
export const HUMAN_RESOURCES_PERMISSION_HEADCOUNT_RESERVE =
	"human-resources.headcount.reserve" as const;
export const HUMAN_RESOURCES_PERMISSION_HEADCOUNT_EXCEPTIONAL_ADJUST =
	"human-resources.headcount.exceptional-adjust" as const;
export const HUMAN_RESOURCES_PERMISSION_DOCUMENT_REQUIREMENT_MANAGE =
	"human-resources.document-requirement.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_EMPLOYEE_DOCUMENT_OWN_READ =
	"human-resources.employee-document.own.read" as const;
export const HUMAN_RESOURCES_PERMISSION_EMPLOYEE_DOCUMENT_OWN_REGISTER =
	"human-resources.employee-document.own.register" as const;
export const HUMAN_RESOURCES_PERMISSION_EMPLOYEE_DOCUMENT_VERIFY =
	"human-resources.employee-document.verify" as const;
export const HUMAN_RESOURCES_PERMISSION_WORK_ELIGIBILITY_VERIFY =
	"human-resources.work-eligibility.verify" as const;
export const HUMAN_RESOURCES_PERMISSION_COMPLIANCE_ADMINISTER =
	"human-resources.compliance.administer" as const;
export const HUMAN_RESOURCES_PERMISSION_IDENTITY_DOCUMENT_SENSITIVE_READ =
	"human-resources.identity-document.sensitive.read" as const;
export const HUMAN_RESOURCES_PERMISSION_POLICY_ACKNOWLEDGEMENT_ADMINISTER =
	"human-resources.policy-acknowledgement.administer" as const;
export const HUMAN_RESOURCES_PERMISSION_COMPETENCY_READ =
	"human-resources.competency.read" as const;
export const HUMAN_RESOURCES_PERMISSION_COMPETENCY_MANAGE =
	"human-resources.competency.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_COMPETENCY_ASSESS =
	"human-resources.competency.assess" as const;
export const HUMAN_RESOURCES_PERMISSION_CAREER_PLAN_OWN_READ =
	"human-resources.career-plan.own.read" as const;
export const HUMAN_RESOURCES_PERMISSION_CAREER_PLAN_MANAGE =
	"human-resources.career-plan.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_TALENT_ADMIN =
	"human-resources.talent.admin" as const;
export const HUMAN_RESOURCES_PERMISSION_TALENT_PROFILE_SENSITIVE_READ =
	"human-resources.talent.profile.sensitive.read" as const;
export const HUMAN_RESOURCES_PERMISSION_SUCCESSION_ADMIN =
	"human-resources.succession.admin" as const;
export const HUMAN_RESOURCES_PERMISSION_SUCCESSION_EXECUTIVE_READ =
	"human-resources.succession.executive.read" as const;

export const HUMAN_RESOURCES_PERMISSION_CODES = [
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CREATE,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_READ,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_UPDATE,
	HUMAN_RESOURCES_PERMISSION_PERSON_READ,
	HUMAN_RESOURCES_PERMISSION_PERSON_MANAGE,
	HUMAN_RESOURCES_PERMISSION_WORKER_READ,
	HUMAN_RESOURCES_PERMISSION_WORKER_MANAGE,
	HUMAN_RESOURCES_PERMISSION_PERSONAL_DETAILS_READ,
	HUMAN_RESOURCES_PERMISSION_PERSONAL_DETAILS_MANAGE,
	HUMAN_RESOURCES_PERMISSION_SENSITIVE_IDENTIFIERS_READ,
	HUMAN_RESOURCES_PERMISSION_SENSITIVE_IDENTIFIERS_MANAGE,
	HUMAN_RESOURCES_PERMISSION_ASSIGNMENT_READ,
	HUMAN_RESOURCES_PERMISSION_ASSIGNMENT_MANAGE,
	HUMAN_RESOURCES_PERMISSION_ORGANIZATION_CONTEXT_READ,
	HUMAN_RESOURCES_PERMISSION_REPORTING_LINE_MANAGE,
	HUMAN_RESOURCES_PERMISSION_EMPLOYMENT_MANAGE,
	HUMAN_RESOURCES_PERMISSION_ORGANIZATION_READ,
	HUMAN_RESOURCES_PERMISSION_ORGANIZATION_MANAGE,
	HUMAN_RESOURCES_PERMISSION_REQUISITION_CREATE,
	HUMAN_RESOURCES_PERMISSION_CANDIDATE_MANAGE,
	HUMAN_RESOURCES_PERMISSION_INTERVIEW_RECORD,
	HUMAN_RESOURCES_PERMISSION_OFFER_APPROVE,
	HUMAN_RESOURCES_PERMISSION_ONBOARDING_MANAGE,
	HUMAN_RESOURCES_PERMISSION_OFFBOARDING_MANAGE,
	HUMAN_RESOURCES_PERMISSION_LEAVE_POLICY_READ,
	HUMAN_RESOURCES_PERMISSION_LEAVE_POLICY_MANAGE,
	HUMAN_RESOURCES_PERMISSION_LEAVE_ENTITLEMENT_READ,
	HUMAN_RESOURCES_PERMISSION_LEAVE_ENTITLEMENT_GRANT,
	HUMAN_RESOURCES_PERMISSION_LEAVE_ENTITLEMENT_ADJUST,
	HUMAN_RESOURCES_PERMISSION_LEAVE_REQUEST_OWN,
	HUMAN_RESOURCES_PERMISSION_LEAVE_REQUEST_APPROVE_TEAM,
	HUMAN_RESOURCES_PERMISSION_LEAVE_REQUEST_BACKDATE,
	HUMAN_RESOURCES_PERMISSION_LEAVE_REQUEST_SENSITIVE_READ,
	HUMAN_RESOURCES_PERMISSION_ATTENDANCE_MANAGE,
	HUMAN_RESOURCES_PERMISSION_TIME_CALENDAR_READ,
	HUMAN_RESOURCES_PERMISSION_TIME_CALENDAR_MANAGE,
	HUMAN_RESOURCES_PERMISSION_TIME_SHIFT_READ,
	HUMAN_RESOURCES_PERMISSION_TIME_SHIFT_MANAGE,
	HUMAN_RESOURCES_PERMISSION_TIME_SCHEDULE_READ,
	HUMAN_RESOURCES_PERMISSION_TIME_SCHEDULE_MANAGE,
	HUMAN_RESOURCES_PERMISSION_TIME_SCHEDULE_PUBLISH,
	HUMAN_RESOURCES_PERMISSION_TIME_ATTENDANCE_SELF_RECORD,
	HUMAN_RESOURCES_PERMISSION_TIME_ATTENDANCE_READ,
	HUMAN_RESOURCES_PERMISSION_TIME_ATTENDANCE_CORRECT,
	HUMAN_RESOURCES_PERMISSION_TIME_ATTENDANCE_MANAGE,
	HUMAN_RESOURCES_PERMISSION_TIME_EXCEPTION_READ,
	HUMAN_RESOURCES_PERMISSION_TIME_EXCEPTION_RESOLVE,
	HUMAN_RESOURCES_PERMISSION_TIME_TIMESHEET_SELF_READ,
	HUMAN_RESOURCES_PERMISSION_TIME_TIMESHEET_SELF_EDIT,
	HUMAN_RESOURCES_PERMISSION_TIME_TIMESHEET_SUBMIT,
	HUMAN_RESOURCES_PERMISSION_TIME_TIMESHEET_READ,
	HUMAN_RESOURCES_PERMISSION_TIME_TIMESHEET_APPROVE,
	HUMAN_RESOURCES_PERMISSION_TIME_TIMESHEET_REOPEN,
	HUMAN_RESOURCES_PERMISSION_TIME_TIMESHEET_LOCK,
	HUMAN_RESOURCES_PERMISSION_TIME_OVERTIME_REQUEST,
	HUMAN_RESOURCES_PERMISSION_TIME_OVERTIME_READ,
	HUMAN_RESOURCES_PERMISSION_TIME_OVERTIME_APPROVE,
	HUMAN_RESOURCES_PERMISSION_TIME_HANDOFF_READ,
	HUMAN_RESOURCES_PERMISSION_PERFORMANCE_MANAGE,
	HUMAN_RESOURCES_PERMISSION_PERFORMANCE_OWN_READ,
	HUMAN_RESOURCES_PERMISSION_PERFORMANCE_MANAGER_MANAGE,
	HUMAN_RESOURCES_PERMISSION_PERFORMANCE_IMPROVEMENT_PLAN_MANAGE,
	HUMAN_RESOURCES_PERMISSION_PERFORMANCE_REVIEW_REOPEN,
	HUMAN_RESOURCES_PERMISSION_PERFORMANCE_CONFIDENTIAL_READ,
	HUMAN_RESOURCES_PERMISSION_LEARNING_MANAGE,
	HUMAN_RESOURCES_PERMISSION_CERTIFICATION_MANAGE,
	HUMAN_RESOURCES_PERMISSION_COMPENSATION_READ,
	HUMAN_RESOURCES_PERMISSION_COMPENSATION_MANAGE,
	HUMAN_RESOURCES_PERMISSION_BENEFITS_MANAGE,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_OPEN,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_ASSIGNED_READ,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_INVESTIGATE,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_FINDING,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_ACTION_APPROVE,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_APPEAL,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_EXCEPTIONAL_ADMIN,
	HUMAN_RESOURCES_PERMISSION_WORKFORCE_PLAN_READ,
	HUMAN_RESOURCES_PERMISSION_WORKFORCE_PLAN_PREPARE,
	HUMAN_RESOURCES_PERMISSION_WORKFORCE_PLAN_APPROVE,
	HUMAN_RESOURCES_PERMISSION_HEADCOUNT_RESERVE,
	HUMAN_RESOURCES_PERMISSION_HEADCOUNT_EXCEPTIONAL_ADJUST,
	HUMAN_RESOURCES_PERMISSION_DOCUMENT_REQUIREMENT_MANAGE,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_DOCUMENT_OWN_READ,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_DOCUMENT_OWN_REGISTER,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_DOCUMENT_VERIFY,
	HUMAN_RESOURCES_PERMISSION_WORK_ELIGIBILITY_VERIFY,
	HUMAN_RESOURCES_PERMISSION_COMPLIANCE_ADMINISTER,
	HUMAN_RESOURCES_PERMISSION_IDENTITY_DOCUMENT_SENSITIVE_READ,
	HUMAN_RESOURCES_PERMISSION_POLICY_ACKNOWLEDGEMENT_ADMINISTER,
	HUMAN_RESOURCES_PERMISSION_COMPETENCY_READ,
	HUMAN_RESOURCES_PERMISSION_COMPETENCY_MANAGE,
	HUMAN_RESOURCES_PERMISSION_COMPETENCY_ASSESS,
	HUMAN_RESOURCES_PERMISSION_CAREER_PLAN_OWN_READ,
	HUMAN_RESOURCES_PERMISSION_CAREER_PLAN_MANAGE,
	HUMAN_RESOURCES_PERMISSION_TALENT_ADMIN,
	HUMAN_RESOURCES_PERMISSION_TALENT_PROFILE_SENSITIVE_READ,
	HUMAN_RESOURCES_PERMISSION_SUCCESSION_ADMIN,
	HUMAN_RESOURCES_PERMISSION_SUCCESSION_EXECUTIVE_READ,
] as const;
