import type { HumanResourcesCommandOptions } from "./command-options";
import {
	acceptOffer as acceptOfferInternal,
	accrueLeaveEntitlement as accrueLeaveEntitlementInternal,
	acknowledgeCareerPlan as acknowledgeCareerPlanInternal,
	acknowledgeImprovementPlan as acknowledgeImprovementPlanInternal,
	acknowledgePerformanceReview as acknowledgePerformanceReviewInternal,
	acknowledgePolicy as acknowledgePolicyInternal,
	activateCourse as activateCourseInternal,
	activateDepartment as activateDepartmentInternal,
	activateEmployeeCompensation as activateEmployeeCompensationInternal,
	activateJob as activateJobInternal,
	activatePerformanceGoal as activatePerformanceGoalInternal,
	activatePosition as activatePositionInternal,
	activateShift as activateShiftInternal,
	activateTimePolicy as activateTimePolicyInternal,
	addBenefitEnrollmentDependent as addBenefitEnrollmentDependentInternal,
	addCalendarDateOverride as addCalendarDateOverrideInternal,
	addCareerPlanAction as addCareerPlanActionInternal,
	addCycleParticipant as addCycleParticipantInternal,
	addDelegatedReviewer as addDelegatedReviewerInternal,
	addEmployeeCaseEvidenceReference as addEmployeeCaseEvidenceReferenceInternal,
	addEmployeeCaseParticipant as addEmployeeCaseParticipantInternal,
	addHeadcountPlanLine as addHeadcountPlanLineInternal,
	addPersonContact as addPersonContactInternal,
	addPersonIdentifier as addPersonIdentifierInternal,
	addShiftBreak as addShiftBreakInternal,
	addTimesheetEntry as addTimesheetEntryInternal,
	addWorkCalendarHoliday as addWorkCalendarHolidayInternal,
	adjustLeaveEntitlement as adjustLeaveEntitlementInternal,
	alignPerformanceGoal as alignPerformanceGoalInternal,
	amendCompensationProposal as amendCompensationProposalInternal,
	amendEmployeeCompensation as amendEmployeeCompensationInternal,
	amendEmploymentContract as amendEmploymentContractInternal,
	amendEmployment as amendEmploymentInternal,
	amendImprovementPlan as amendImprovementPlanInternal,
	amendLeaveRequest as amendLeaveRequestInternal,
	amendOfferDraft as amendOfferDraftInternal,
	amendRequisition as amendRequisitionInternal,
	anonymizeCandidate as anonymizeCandidateInternal,
	anonymizeHumanResourcesSubject as anonymizeHumanResourcesSubjectInternal,
	applyApprovedCompensationResult as applyApprovedCompensationResultInternal,
	approveAttendanceBreakWaiver as approveAttendanceBreakWaiverInternal,
	approveCompensationProposal as approveCompensationProposalInternal,
	approveEmployeeCaseAction as approveEmployeeCaseActionInternal,
	approveEmployeeCompensation as approveEmployeeCompensationInternal,
	approveHeadcountPlan as approveHeadcountPlanInternal,
	approveLeaveRequest as approveLeaveRequestInternal,
	approveOffer as approveOfferInternal,
	approveOvertimeRequest as approveOvertimeRequestInternal,
	approvePerformanceGoal as approvePerformanceGoalInternal,
	approveRequisition as approveRequisitionInternal,
	approveSuccessionCandidate as approveSuccessionCandidateInternal,
	approveTalentPoolMember as approveTalentPoolMemberInternal,
	approveTermination as approveTerminationInternal,
	approveTimesheet as approveTimesheetInternal,
	archiveBenefitPlan as archiveBenefitPlanInternal,
	archiveCompensationGrade as archiveCompensationGradeInternal,
	archiveCompensationGradeProgressionRule as archiveCompensationGradeProgressionRuleInternal,
	archiveCourse as archiveCourseInternal,
	archiveDepartment as archiveDepartmentInternal,
	archiveJob as archiveJobInternal,
	archiveLeavePolicy as archiveLeavePolicyInternal,
	archiveSalaryBand as archiveSalaryBandInternal,
	archiveTalentProfile as archiveTalentProfileInternal,
	archiveWorkCalendar as archiveWorkCalendarInternal,
	assembleApprovedPayrollHandoff as assembleApprovedPayrollHandoffInternal,
	assessEmployeeCompetency as assessEmployeeCompetencyInternal,
	assessSuccessionReadiness as assessSuccessionReadinessInternal,
	assignEmployeeCaseOwner as assignEmployeeCaseOwnerInternal,
	assignEmploymentCalendar as assignEmploymentCalendarInternal,
	assignHiringManager as assignHiringManagerInternal,
	assignInterviewInterviewer as assignInterviewInterviewerInternal,
	assignLearning as assignLearningInternal,
	assignPrimaryReportingLine as assignPrimaryReportingLineInternal,
	assignSessionInstructor as assignSessionInstructorInternal,
	assignShift as assignShiftInternal,
	assignTimeApprovalAuthority as assignTimeApprovalAuthorityInternal,
	assignTimePolicy as assignTimePolicyInternal,
	assignWorkCalendarScope as assignWorkCalendarScopeInternal,
	calibratePerformanceReview as calibratePerformanceReviewInternal,
	cancelApprovedLeaveRequest as cancelApprovedLeaveRequestInternal,
	cancelBenefitEnrollment as cancelBenefitEnrollmentInternal,
	cancelCompensationReviewCycle as cancelCompensationReviewCycleInternal,
	cancelImprovementPlan as cancelImprovementPlanInternal,
	cancelInterview as cancelInterviewInternal,
	cancelOvertimeRequest as cancelOvertimeRequestInternal,
	cancelPerformanceCycle as cancelPerformanceCycleInternal,
	cancelPerformanceGoal as cancelPerformanceGoalInternal,
	cancelRequisition as cancelRequisitionInternal,
	cancelSession as cancelSessionInternal,
	cancelShiftAssignment as cancelShiftAssignmentInternal,
	carryForwardLeaveEntitlement as carryForwardLeaveEntitlementInternal,
	changeCandidateRetention as changeCandidateRetentionInternal,
	changeShiftAssignment as changeShiftAssignmentInternal,
	changeWorkerStatus as changeWorkerStatusInternal,
	changeWorkerType as changeWorkerTypeInternal,
	closeCareerPlan as closeCareerPlanInternal,
	closeCompensationReviewCycle as closeCompensationReviewCycleInternal,
	closeEmployeeCase as closeEmployeeCaseInternal,
	closeHeadcountPlan as closeHeadcountPlanInternal,
	closeImprovementPlanUnsuccessful as closeImprovementPlanUnsuccessfulInternal,
	closePerformanceCycle as closePerformanceCycleInternal,
	closePerformanceGoal as closePerformanceGoalInternal,
	closePosition as closePositionInternal,
	closeReportingLine as closeReportingLineInternal,
	closeRequisition as closeRequisitionInternal,
	closeSuccessionPlan as closeSuccessionPlanInternal,
	closeTalentPool as closeTalentPoolInternal,
	closeWorkEligibility as closeWorkEligibilityInternal,
	completeCareerPlanAction as completeCareerPlanActionInternal,
	completeImprovementPlan as completeImprovementPlanInternal,
	completeOffboarding as completeOffboardingInternal,
	completeOffboardingTask as completeOffboardingTaskInternal,
	completeOnboarding as completeOnboardingInternal,
	completeOnboardingTask as completeOnboardingTaskInternal,
	completeSession as completeSessionInternal,
	completeShiftAssignment as completeShiftAssignmentInternal,
	confirmEmployment as confirmEmploymentInternal,
	confirmTalentProfileAssessment as confirmTalentProfileAssessmentInternal,
	consumeHeadcountReservation as consumeHeadcountReservationInternal,
	correctAttendanceEvent as correctAttendanceEventInternal,
	correctEmployeeCompensation as correctEmployeeCompensationInternal,
	correctEmploymentContract as correctEmploymentContractInternal,
	correctEmployment as correctEmploymentInternal,
	createApplication as createApplicationInternal,
	createAssignment as createAssignmentInternal,
	createAttendanceException as createAttendanceExceptionInternal,
	createBenefitPlan as createBenefitPlanInternal,
	createCandidate as createCandidateInternal,
	createCareerPlan as createCareerPlanInternal,
	createCompensationGrade as createCompensationGradeInternal,
	createCompensationGradeProgressionRule as createCompensationGradeProgressionRuleInternal,
	createCompensationProposal as createCompensationProposalInternal,
	createCompensationReviewCycle as createCompensationReviewCycleInternal,
	createCompensationReviewDraft as createCompensationReviewDraftInternal,
	createCompetency as createCompetencyInternal,
	createCourse as createCourseInternal,
	createDepartment as createDepartmentInternal,
	createDocumentRequirement as createDocumentRequirementInternal,
	createDraftLeaveRequest as createDraftLeaveRequestInternal,
	createDraftRequisition as createDraftRequisitionInternal,
	createEmployeeCompensation as createEmployeeCompensationInternal,
	createEmployee as createEmployeeInternal,
	createEmploymentContract as createEmploymentContractInternal,
	createEmployment as createEmploymentInternal,
	createHeadcountPlan as createHeadcountPlanInternal,
	createImprovementPlan as createImprovementPlanInternal,
	createJob as createJobInternal,
	createLeavePolicy as createLeavePolicyInternal,
	createOffer as createOfferInternal,
	createOvertimeRequest as createOvertimeRequestInternal,
	createPerformanceCycle as createPerformanceCycleInternal,
	createPerformanceGoal as createPerformanceGoalInternal,
	createPerson as createPersonInternal,
	createPosition as createPositionInternal,
	createSalaryBand as createSalaryBandInternal,
	createSession as createSessionInternal,
	createShift as createShiftInternal,
	createSuccessionPlan as createSuccessionPlanInternal,
	createTalentPool as createTalentPoolInternal,
	createTalentProfile as createTalentProfileInternal,
	createTimePolicy as createTimePolicyInternal,
	createTimesheet as createTimesheetInternal,
	createWorkCalendar as createWorkCalendarInternal,
	createWorker as createWorkerInternal,
	deactivateShift as deactivateShiftInternal,
	declineOffer as declineOfferInternal,
	detectCandidateDuplicates as detectCandidateDuplicatesInternal,
	detectComplianceExpiryOperations as detectComplianceExpiryOperationsInternal,
	detectPersonDuplicates as detectPersonDuplicatesInternal,
	endAssignment as endAssignmentInternal,
	endBenefitEnrollmentDependent as endBenefitEnrollmentDependentInternal,
	endBenefitEnrollment as endBenefitEnrollmentInternal,
	endEmployeeCompensation as endEmployeeCompensationInternal,
	endEmploymentContract as endEmploymentContractInternal,
	endTimeApprovalAuthorityAssignment as endTimeApprovalAuthorityAssignmentInternal,
	endWorkCalendarAssignment as endWorkCalendarAssignmentInternal,
	endWorkCalendarScopeAssignment as endWorkCalendarScopeAssignmentInternal,
	enrolAssignment as enrolAssignmentInternal,
	enrolBenefit as enrolBenefitInternal,
	enrollEligibleCycleParticipants as enrollEligibleCycleParticipantsInternal,
	evaluateHumanResourcesAnonymization as evaluateHumanResourcesAnonymizationInternal,
	evaluateHumanResourcesRetention as evaluateHumanResourcesRetentionInternal,
	excuseAttendanceException as excuseAttendanceExceptionInternal,
	expireCertification as expireCertificationInternal,
	expireCompetencyAssessment as expireCompetencyAssessmentInternal,
	expireLeaveEntitlement as expireLeaveEntitlementInternal,
	expireOffer as expireOfferInternal,
	exportHumanResourcesSubjectData as exportHumanResourcesSubjectDataInternal,
	extendProbation as extendProbationInternal,
	finalizeCompensationReview as finalizeCompensationReviewInternal,
	finalizePerformanceReview as finalizePerformanceReviewInternal,
	finalizeTermination as finalizeTerminationInternal,
	findSalaryBandByGradeAndCurrencyAsOf as findSalaryBandByGradeAndCurrencyAsOfInternal,
	freezePosition as freezePositionInternal,
	generateTimesheetEntries as generateTimesheetEntriesInternal,
	getApplication as getApplicationInternal,
	getApprovedCompensationHandoff as getApprovedCompensationHandoffInternal,
	getApprovedHeadcountPlan as getApprovedHeadcountPlanInternal,
	getApprovedLeaveHandoff as getApprovedLeaveHandoffInternal,
	getApprovedTimeHandoff as getApprovedTimeHandoffInternal,
	getAssignmentAsOf as getAssignmentAsOfInternal,
	getAssignment as getAssignmentInternal,
	getAttendanceEvent as getAttendanceEventInternal,
	getAttendanceException as getAttendanceExceptionInternal,
	getAttendanceSession as getAttendanceSessionInternal,
	getBenefitPlanEligibility as getBenefitPlanEligibilityInternal,
	getCandidate as getCandidateInternal,
	getCareerPlanById as getCareerPlanByIdInternal,
	getCertification as getCertificationInternal,
	getClearanceByOffboardingCase as getClearanceByOffboardingCaseInternal,
	getCompensationGrade as getCompensationGradeInternal,
	getCompensationGradeProgressionRule as getCompensationGradeProgressionRuleInternal,
	getCompensationProposal as getCompensationProposalInternal,
	getCompensationReviewCycle as getCompensationReviewCycleInternal,
	getCompensationReview as getCompensationReviewInternal,
	getCompetencyById as getCompetencyByIdInternal,
	getCompletion as getCompletionInternal,
	getCourse as getCourseInternal,
	getCurrentEmploymentContract as getCurrentEmploymentContractInternal,
	getDailyAttendanceSummary as getDailyAttendanceSummaryInternal,
	getDepartmentAsOf as getDepartmentAsOfInternal,
	getDepartment as getDepartmentInternal,
	getEmployeeById as getEmployeeByIdInternal,
	getEmployeeCaseById as getEmployeeCaseByIdInternal,
	getEmployeeCaseOutcome as getEmployeeCaseOutcomeInternal,
	getEmployeeCaseTimeline as getEmployeeCaseTimelineInternal,
	getEmployeeCompensation as getEmployeeCompensationInternal,
	getEmployeeCompetencyProfile as getEmployeeCompetencyProfileInternal,
	getEmployeeComplianceSummary as getEmployeeComplianceSummaryInternal,
	getEmployeeDocument as getEmployeeDocumentInternal,
	getEmployeePerformanceHistory as getEmployeePerformanceHistoryInternal,
	getEmployeeProfile as getEmployeeProfileInternal,
	getEmployeeRelationsHistoryByEmployee as getEmployeeRelationsHistoryByEmployeeInternal,
	getEmployeeWorkEligibility as getEmployeeWorkEligibilityInternal,
	getEmploymentAsOf as getEmploymentAsOfInternal,
	getEmploymentConfirmation as getEmploymentConfirmationInternal,
	getEmploymentContractAsOf as getEmploymentContractAsOfInternal,
	getEmploymentContract as getEmploymentContractInternal,
	getEmployment as getEmploymentInternal,
	getHeadcountAvailability as getHeadcountAvailabilityInternal,
	getHeadcountPlanById as getHeadcountPlanByIdInternal,
	getHumanResourcesPrivacyCase as getHumanResourcesPrivacyCaseInternal,
	getImprovementPlanById as getImprovementPlanByIdInternal,
	getInterviewEvaluation as getInterviewEvaluationInternal,
	getInterview as getInterviewInternal,
	getJobAsOf as getJobAsOfInternal,
	getJob as getJobInternal,
	getLearningAssignment as getLearningAssignmentInternal,
	getLearningAttendance as getLearningAttendanceInternal,
	getLeaveBalance as getLeaveBalanceInternal,
	getLeaveEntitlement as getLeaveEntitlementInternal,
	getLeavePolicy as getLeavePolicyInternal,
	getLeaveRequest as getLeaveRequestInternal,
	getOffboardingAccessRevocationByCase as getOffboardingAccessRevocationByCaseInternal,
	getOffboardingCase as getOffboardingCaseInternal,
	getOffboardingPayrollHandoffByCase as getOffboardingPayrollHandoffByCaseInternal,
	getOffer as getOfferInternal,
	getOnboardingAccessHandoffByCase as getOnboardingAccessHandoffByCaseInternal,
	getOnboardingCase as getOnboardingCaseInternal,
	getOnboardingEquipmentHandoffByCase as getOnboardingEquipmentHandoffByCaseInternal,
	getOnboardingOrientationByCase as getOnboardingOrientationByCaseInternal,
	getOrganizationTreeAsOf as getOrganizationTreeAsOfInternal,
	getOrganizationTree as getOrganizationTreeInternal,
	getOvertimeRequest as getOvertimeRequestInternal,
	getPerformanceCycleById as getPerformanceCycleByIdInternal,
	getPerformanceCycleEligibility as getPerformanceCycleEligibilityInternal,
	getPerformanceGoalById as getPerformanceGoalByIdInternal,
	getPerformanceReviewById as getPerformanceReviewByIdInternal,
	getPersonAsOf as getPersonAsOfInternal,
	getPersonById as getPersonByIdInternal,
	getPolicyAcknowledgementStatus as getPolicyAcknowledgementStatusInternal,
	getPositionAsOf as getPositionAsOfInternal,
	getPosition as getPositionInternal,
	getPositionOccupancyAsOf as getPositionOccupancyAsOfInternal,
	getPositionSuccessionCoverage as getPositionSuccessionCoverageInternal,
	getProbationReview as getProbationReviewInternal,
	getRecruitmentHeadcountHandoff as getRecruitmentHeadcountHandoffInternal,
	getRequisition as getRequisitionInternal,
	getSalaryBand as getSalaryBandInternal,
	getScheduledShiftForEmployeeDate as getScheduledShiftForEmployeeDateInternal,
	getSession as getSessionInternal,
	getShiftAssignment as getShiftAssignmentInternal,
	getShift as getShiftInternal,
	getSuccessionPlanById as getSuccessionPlanByIdInternal,
	getTalentProfileByEmployee as getTalentProfileByEmployeeInternal,
	getTermination as getTerminationInternal,
	getTimePolicy as getTimePolicyInternal,
	getTimesheetForEmployeePeriod as getTimesheetForEmployeePeriodInternal,
	getTimesheet as getTimesheetInternal,
	getTimesheetTotals as getTimesheetTotalsInternal,
	getWorkCalendar as getWorkCalendarInternal,
	getWorkerAsOf as getWorkerAsOfInternal,
	getWorkerById as getWorkerByIdInternal,
	getWorkforcePlanVariance as getWorkforcePlanVarianceInternal,
	grantLeaveEntitlement as grantLeaveEntitlementInternal,
	hireEmployment as hireEmploymentInternal,
	hireFromAcceptedOffer as hireFromAcceptedOfferInternal,
	importAttendanceEvents as importAttendanceEventsInternal,
	issueCertification as issueCertificationInternal,
	issueInterimEmployeeMeasure as issueInterimEmployeeMeasureInternal,
	issueOffer as issueOfferInternal,
	issuePolicyAcknowledgementRequirement as issuePolicyAcknowledgementRequirementInternal,
	listActiveImprovementPlans as listActiveImprovementPlansInternal,
	listApplicationStatusHistory as listApplicationStatusHistoryInternal,
	listApplications as listApplicationsInternal,
	listAttendanceAdjustments as listAttendanceAdjustmentsInternal,
	listAttendanceBreakWaiverDecisions as listAttendanceBreakWaiverDecisionsInternal,
	listAttendanceEvents as listAttendanceEventsInternal,
	listAttendanceExceptions as listAttendanceExceptionsInternal,
	listAttendanceSessions as listAttendanceSessionsInternal,
	listCandidates as listCandidatesInternal,
	listCasesAssignedToActor as listCasesAssignedToActorInternal,
	listCertifications as listCertificationsInternal,
	listCompensationGradeProgressionRulesFromGrade as listCompensationGradeProgressionRulesFromGradeInternal,
	listCompensationGrades as listCompensationGradesInternal,
	listCompensationProposals as listCompensationProposalsInternal,
	listCompensationReviewCycles as listCompensationReviewCyclesInternal,
	listCompensationReviewsByEmployee as listCompensationReviewsByEmployeeInternal,
	listCompetencies as listCompetenciesInternal,
	listCompletions as listCompletionsInternal,
	listCourses as listCoursesInternal,
	listCriticalRoleReadiness as listCriticalRoleReadinessInternal,
	listCycleParticipants as listCycleParticipantsInternal,
	listDepartments as listDepartmentsInternal,
	listDirectReports as listDirectReportsInternal,
	listEligibleProgressionTargets as listEligibleProgressionTargetsInternal,
	listEmployeeCareerPlans as listEmployeeCareerPlansInternal,
	listEmployeeCases as listEmployeeCasesInternal,
	listEmployeeCompensationsByEmployee as listEmployeeCompensationsByEmployeeInternal,
	listEmployeeDocuments as listEmployeeDocumentsInternal,
	listEmployeeGoals as listEmployeeGoalsInternal,
	listEmployeePerformanceReviews as listEmployeePerformanceReviewsInternal,
	listEmployees as listEmployeesInternal,
	listEmployeesWithWorkEligibilityRisk as listEmployeesWithWorkEligibilityRiskInternal,
	listEmploymentContracts as listEmploymentContractsInternal,
	listEmploymentStatusHistory as listEmploymentStatusHistoryInternal,
	listExpiringCertifications as listExpiringCertificationsInternal,
	listExpiringEmployeeDocuments as listExpiringEmployeeDocumentsInternal,
	listGoalProgress as listGoalProgressInternal,
	listHeadcountPlans as listHeadcountPlansInternal,
	listHeadcountReservations as listHeadcountReservationsInternal,
	listImprovementPlanCheckpoints as listImprovementPlanCheckpointsInternal,
	listInterviews as listInterviewsInternal,
	listJobCompetencies as listJobCompetenciesInternal,
	listJobs as listJobsInternal,
	listLearningAssignments as listLearningAssignmentsInternal,
	listLearningAttendance as listLearningAttendanceInternal,
	listLeaveEntitlements as listLeaveEntitlementsInternal,
	listLeavePolicies as listLeavePoliciesInternal,
	listLeaveRequests as listLeaveRequestsInternal,
	listLocationSchedule as listLocationScheduleInternal,
	listMissingRequiredDocuments as listMissingRequiredDocumentsInternal,
	listOffboardingTasks as listOffboardingTasksInternal,
	listOffers as listOffersInternal,
	listOnboardingTasks as listOnboardingTasksInternal,
	listOpenEmployeeRelationsCases as listOpenEmployeeRelationsCasesInternal,
	listOutstandingPolicyAcknowledgements as listOutstandingPolicyAcknowledgementsInternal,
	listOverduePolicyAcknowledgements as listOverduePolicyAcknowledgementsInternal,
	listOvertimeRequests as listOvertimeRequestsInternal,
	listPendingApprovalLeaveRequests as listPendingApprovalLeaveRequestsInternal,
	listPendingOvertimeApprovals as listPendingOvertimeApprovalsInternal,
	listPerformanceCycleReviewPeriods as listPerformanceCycleReviewPeriodsInternal,
	listPerformanceCycles as listPerformanceCyclesInternal,
	listPersonContacts as listPersonContactsInternal,
	listPersonIdentifiers as listPersonIdentifiersInternal,
	listPositions as listPositionsInternal,
	listProbationAssessments as listProbationAssessmentsInternal,
	listProbationReviewsByEmployment as listProbationReviewsByEmploymentInternal,
	listRequisitions as listRequisitionsInternal,
	listReviewsPendingManagerAction as listReviewsPendingManagerActionInternal,
	listSalaryBandsByGrade as listSalaryBandsByGradeInternal,
	listSessions as listSessionsInternal,
	listShiftAssignmentSegments as listShiftAssignmentSegmentsInternal,
	listShiftAssignments as listShiftAssignmentsInternal,
	listShiftBreaks as listShiftBreaksInternal,
	listShifts as listShiftsInternal,
	listSuccessionCandidates as listSuccessionCandidatesInternal,
	listSuccessionPlans as listSuccessionPlansInternal,
	listTalentPoolMembers as listTalentPoolMembersInternal,
	listTalentProfileAssessments as listTalentProfileAssessmentsInternal,
	listTalentProfileMobility as listTalentProfileMobilityInternal,
	listTeamCalendarLeaveRequests as listTeamCalendarLeaveRequestsInternal,
	listTimesheetApprovalDecisions as listTimesheetApprovalDecisionsInternal,
	listTimesheetEntries as listTimesheetEntriesInternal,
	listTimesheets as listTimesheetsInternal,
	listUnresolvedAttendanceExceptions as listUnresolvedAttendanceExceptionsInternal,
	listWorkCalendarHolidays as listWorkCalendarHolidaysInternal,
	listWorkCalendars as listWorkCalendarsInternal,
	lockTimesheet as lockTimesheetInternal,
	mapCompetencyToJob as mapCompetencyToJobInternal,
	markEmployeeDocumentExpired as markEmployeeDocumentExpiredInternal,
	moveApplicationToInReview as moveApplicationToInReviewInternal,
	moveApplicationToInterviewing as moveApplicationToInterviewingInternal,
	nominateSuccessionCandidate as nominateSuccessionCandidateInternal,
	nominateTalentPoolMember as nominateTalentPoolMemberInternal,
	openCompensationReviewCycle as openCompensationReviewCycleInternal,
	openEmployeeCase as openEmployeeCaseInternal,
	openImprovementPlan as openImprovementPlanInternal,
	openPerformanceCycle as openPerformanceCycleInternal,
	openProbation as openProbationInternal,
	openRequisition as openRequisitionInternal,
	placeHumanResourcesLegalHold as placeHumanResourcesLegalHoldInternal,
	placeRequisitionOnHold as placeRequisitionOnHoldInternal,
	proposeTermination as proposeTerminationInternal,
	publishDocumentRequirement as publishDocumentRequirementInternal,
	publishLeavePolicy as publishLeavePolicyInternal,
	publishPerformanceCycle as publishPerformanceCycleInternal,
	publishShiftAssignment as publishShiftAssignmentInternal,
	reactivateEmployment as reactivateEmploymentInternal,
	recommendEmployeeCaseAction as recommendEmployeeCaseActionInternal,
	reconcileLeaveBalance as reconcileLeaveBalanceInternal,
	recordAttendanceEvent as recordAttendanceEventInternal,
	recordBreakEnd as recordBreakEndInternal,
	recordBreakStart as recordBreakStartInternal,
	recordClearance as recordClearanceInternal,
	recordClockIn as recordClockInInternal,
	recordClockOut as recordClockOutInternal,
	recordCompensationRecommendation as recordCompensationRecommendationInternal,
	recordCompletion as recordCompletionInternal,
	recordCriticalRoleReadiness as recordCriticalRoleReadinessInternal,
	recordEmployeeCaseAppeal as recordEmployeeCaseAppealInternal,
	recordEmployeeCaseEvent as recordEmployeeCaseEventInternal,
	recordEmployeeCaseFinding as recordEmployeeCaseFindingInternal,
	recordExitInterview as recordExitInterviewInternal,
	recordGoalProgress as recordGoalProgressInternal,
	recordImprovementCheckpoint as recordImprovementCheckpointInternal,
	recordInterviewEvaluation as recordInterviewEvaluationInternal,
	recordLearningAttendance as recordLearningAttendanceInternal,
	recordManualAttendance as recordManualAttendanceInternal,
	recordOffboardingAccessRevocation as recordOffboardingAccessRevocationInternal,
	recordOffboardingPayrollHandoff as recordOffboardingPayrollHandoffInternal,
	recordOnboardingAccessHandoff as recordOnboardingAccessHandoffInternal,
	recordOnboardingEquipmentHandoff as recordOnboardingEquipmentHandoffInternal,
	recordOnboardingOrientation as recordOnboardingOrientationInternal,
	recordOvertimeActual as recordOvertimeActualInternal,
	recordProbationAssessment as recordProbationAssessmentInternal,
	recordProbationOutcome as recordProbationOutcomeInternal,
	recordTalentProfileAssessment as recordTalentProfileAssessmentInternal,
	recordTalentProfileMobility as recordTalentProfileMobilityInternal,
	recordWorkEligibility as recordWorkEligibilityInternal,
	redactEmployeeCaseEvidenceReference as redactEmployeeCaseEvidenceReferenceInternal,
	registerEmployeeDocument as registerEmployeeDocumentInternal,
	rehireEmployment as rehireEmploymentInternal,
	rejectApplication as rejectApplicationInternal,
	rejectAttendanceException as rejectAttendanceExceptionInternal,
	rejectEmployeeDocument as rejectEmployeeDocumentInternal,
	rejectHeadcountPlan as rejectHeadcountPlanInternal,
	rejectLeaveRequest as rejectLeaveRequestInternal,
	rejectOvertimeRequest as rejectOvertimeRequestInternal,
	rejectPerformanceGoal as rejectPerformanceGoalInternal,
	rejectTimesheet as rejectTimesheetInternal,
	releaseHeadcountReservation as releaseHeadcountReservationInternal,
	releaseHumanResourcesLegalHold as releaseHumanResourcesLegalHoldInternal,
	removeCalendarDateOverride as removeCalendarDateOverrideInternal,
	removeCompetencyFromJob as removeCompetencyFromJobInternal,
	removeCycleParticipant as removeCycleParticipantInternal,
	removeHeadcountPlanLine as removeHeadcountPlanLineInternal,
	removeShiftBreak as removeShiftBreakInternal,
	removeSuccessionCandidate as removeSuccessionCandidateInternal,
	removeTalentPoolMember as removeTalentPoolMemberInternal,
	removeTimesheetEntry as removeTimesheetEntryInternal,
	removeWorkCalendarHoliday as removeWorkCalendarHolidayInternal,
	renewCertification as renewCertificationInternal,
	renewEmploymentContract as renewEmploymentContractInternal,
	renewWorkEligibility as renewWorkEligibilityInternal,
	reopenApplication as reopenApplicationInternal,
	reopenEmployeeCase as reopenEmployeeCaseInternal,
	reopenPerformanceReview as reopenPerformanceReviewInternal,
	reopenTimesheet as reopenTimesheetInternal,
	replacePrimaryReportingLine as replacePrimaryReportingLineInternal,
	reserveHeadcount as reserveHeadcountInternal,
	resolveApplicableLeavePolicy as resolveApplicableLeavePolicyInternal,
	resolveAttendanceException as resolveAttendanceExceptionInternal,
	resolveAttendanceSession as resolveAttendanceSessionInternal,
	resolveEmployeeCaseAppeal as resolveEmployeeCaseAppealInternal,
	resolveEmployeeOrgContextAsOf as resolveEmployeeOrgContextAsOfInternal,
	resolveEmployeeWorkCalendar as resolveEmployeeWorkCalendarInternal,
	resolveEmploymentCalendar as resolveEmploymentCalendarInternal,
	resolvePrimaryManager as resolvePrimaryManagerInternal,
	resolveTimePolicy as resolveTimePolicyInternal,
	retireCompetency as retireCompetencyInternal,
	retireDocumentRequirement as retireDocumentRequirementInternal,
	retirePersonContact as retirePersonContactInternal,
	retirePersonIdentifier as retirePersonIdentifierInternal,
	returnLeaveRequest as returnLeaveRequestInternal,
	returnPerformanceReviewForCorrection as returnPerformanceReviewForCorrectionInternal,
	returnTimesheet as returnTimesheetInternal,
	reviewAttendanceException as reviewAttendanceExceptionInternal,
	revokeCertification as revokeCertificationInternal,
	revokeEmployeeDocumentVerification as revokeEmployeeDocumentVerificationInternal,
	revokePolicyAcknowledgement as revokePolicyAcknowledgementInternal,
	scheduleEmployeeCompensationChange as scheduleEmployeeCompensationChangeInternal,
	scheduleInterview as scheduleInterviewInternal,
	setBenefitPlanEligibility as setBenefitPlanEligibilityInternal,
	setPerformanceCycleEligibility as setPerformanceCycleEligibilityInternal,
	setPerformanceCycleReviewPeriods as setPerformanceCycleReviewPeriodsInternal,
	setPersonPrivacyClassification as setPersonPrivacyClassificationInternal,
	startOffboarding as startOffboardingInternal,
	startOnboarding as startOnboardingInternal,
	startPerformanceReview as startPerformanceReviewInternal,
	startSession as startSessionInternal,
	submitDelegatedAssessment as submitDelegatedAssessmentInternal,
	submitHeadcountPlan as submitHeadcountPlanInternal,
	submitLeaveRequest as submitLeaveRequestInternal,
	submitManagerAssessment as submitManagerAssessmentInternal,
	submitPerformanceGoal as submitPerformanceGoalInternal,
	submitRequisition as submitRequisitionInternal,
	submitSelfAssessment as submitSelfAssessmentInternal,
	submitTimesheet as submitTimesheetInternal,
	supersedeCompetencyAssessment as supersedeCompetencyAssessmentInternal,
	supersedeEmploymentContract as supersedeEmploymentContractInternal,
	supersedeHeadcountPlan as supersedeHeadcountPlanInternal,
	supersedeLeavePolicy as supersedeLeavePolicyInternal,
	supersedePolicyAcknowledgementRequirement as supersedePolicyAcknowledgementRequirementInternal,
	supersedeSalaryBand as supersedeSalaryBandInternal,
	supersedeShift as supersedeShiftInternal,
	supersedeTimePolicy as supersedeTimePolicyInternal,
	supersedeTimesheet as supersedeTimesheetInternal,
	supersedeWorkCalendar as supersedeWorkCalendarInternal,
	suspendEmployment as suspendEmploymentInternal,
	suspendWorkEligibility as suspendWorkEligibilityInternal,
	terminateEmployment as terminateEmploymentInternal,
	transferAssignment as transferAssignmentInternal,
	updateBenefitPlan as updateBenefitPlanInternal,
	updateCandidateProfile as updateCandidateProfileInternal,
	updateCareerPlan as updateCareerPlanInternal,
	updateCompensationGrade as updateCompensationGradeInternal,
	updateCompetency as updateCompetencyInternal,
	updateCourse as updateCourseInternal,
	updateDepartment as updateDepartmentInternal,
	updateDocumentRequirement as updateDocumentRequirementInternal,
	updateEmployeeCaseClassification as updateEmployeeCaseClassificationInternal,
	updateEmployeeDocumentMetadata as updateEmployeeDocumentMetadataInternal,
	updateEmployee as updateEmployeeInternal,
	updateHeadcountPlan as updateHeadcountPlanInternal,
	updateHeadcountPlanLine as updateHeadcountPlanLineInternal,
	updateJob as updateJobInternal,
	updateLeavePolicy as updateLeavePolicyInternal,
	updatePerformanceCycle as updatePerformanceCycleInternal,
	updatePerformanceGoal as updatePerformanceGoalInternal,
	updatePersonContact as updatePersonContactInternal,
	updatePersonName as updatePersonNameInternal,
	updatePersonPreferredName as updatePersonPreferredNameInternal,
	updatePosition as updatePositionInternal,
	updateShift as updateShiftInternal,
	updateSuccessionPlan as updateSuccessionPlanInternal,
	updateTalentPool as updateTalentPoolInternal,
	updateTalentProfile as updateTalentProfileInternal,
	updateTimesheetEntry as updateTimesheetEntryInternal,
	updateWorkCalendar as updateWorkCalendarInternal,
	verifyEmployeeDocument as verifyEmployeeDocumentInternal,
	verifyOvertimeRequest as verifyOvertimeRequestInternal,
	verifyWorkEligibility as verifyWorkEligibilityInternal,
	voidAttendanceEvent as voidAttendanceEventInternal,
	waiveAssignment as waiveAssignmentInternal,
	waiveBenefit as waiveBenefitInternal,
	withdrawApplication as withdrawApplicationInternal,
	withdrawCandidateConsent as withdrawCandidateConsentInternal,
	withdrawLeaveRequest as withdrawLeaveRequestInternal,
	withdrawOffer as withdrawOfferInternal,
} from "./internal-api";
import {
	type HumanResourcesCapabilityOptions,
	resolveHumanResourcesCapabilityOptions,
} from "./public-execution-context";

function bindHumanResourcesCapability<TInput, TResult>(
	operation: (input: TInput, options: HumanResourcesCommandOptions) => TResult,
): (input: TInput, options: HumanResourcesCapabilityOptions) => TResult {
	return (input, options) =>
		operation(input, resolveHumanResourcesCapabilityOptions(options));
}

/** Permanent root operation facade; execution infrastructure stays internal. */
export const acceptOffer = bindHumanResourcesCapability(acceptOfferInternal);
export const accrueLeaveEntitlement = bindHumanResourcesCapability(
	accrueLeaveEntitlementInternal,
);
export const acknowledgeCareerPlan = bindHumanResourcesCapability(
	acknowledgeCareerPlanInternal,
);
export const acknowledgeImprovementPlan = bindHumanResourcesCapability(
	acknowledgeImprovementPlanInternal,
);
export const acknowledgePerformanceReview = bindHumanResourcesCapability(
	acknowledgePerformanceReviewInternal,
);
export const acknowledgePolicy = bindHumanResourcesCapability(
	acknowledgePolicyInternal,
);
export const activateCourse = bindHumanResourcesCapability(
	activateCourseInternal,
);
export const activateDepartment = bindHumanResourcesCapability(
	activateDepartmentInternal,
);
export const activateEmployeeCompensation = bindHumanResourcesCapability(
	activateEmployeeCompensationInternal,
);
export const activateJob = bindHumanResourcesCapability(activateJobInternal);
export const activatePerformanceGoal = bindHumanResourcesCapability(
	activatePerformanceGoalInternal,
);
export const activatePosition = bindHumanResourcesCapability(
	activatePositionInternal,
);
export const activateShift = bindHumanResourcesCapability(
	activateShiftInternal,
);
export const activateTimePolicy = bindHumanResourcesCapability(
	activateTimePolicyInternal,
);
export const addBenefitEnrollmentDependent = bindHumanResourcesCapability(
	addBenefitEnrollmentDependentInternal,
);
export const addCalendarDateOverride = bindHumanResourcesCapability(
	addCalendarDateOverrideInternal,
);
export const addCareerPlanAction = bindHumanResourcesCapability(
	addCareerPlanActionInternal,
);
export const addCycleParticipant = bindHumanResourcesCapability(
	addCycleParticipantInternal,
);
export const addDelegatedReviewer = bindHumanResourcesCapability(
	addDelegatedReviewerInternal,
);
export const addEmployeeCaseEvidenceReference = bindHumanResourcesCapability(
	addEmployeeCaseEvidenceReferenceInternal,
);
export const addEmployeeCaseParticipant = bindHumanResourcesCapability(
	addEmployeeCaseParticipantInternal,
);
export const addHeadcountPlanLine = bindHumanResourcesCapability(
	addHeadcountPlanLineInternal,
);
export const addPersonContact = bindHumanResourcesCapability(
	addPersonContactInternal,
);
export const addPersonIdentifier = bindHumanResourcesCapability(
	addPersonIdentifierInternal,
);
export const addShiftBreak = bindHumanResourcesCapability(
	addShiftBreakInternal,
);
export const addTimesheetEntry = bindHumanResourcesCapability(
	addTimesheetEntryInternal,
);
export const addWorkCalendarHoliday = bindHumanResourcesCapability(
	addWorkCalendarHolidayInternal,
);
export const adjustLeaveEntitlement = bindHumanResourcesCapability(
	adjustLeaveEntitlementInternal,
);
export const alignPerformanceGoal = bindHumanResourcesCapability(
	alignPerformanceGoalInternal,
);
export const amendCompensationProposal = bindHumanResourcesCapability(
	amendCompensationProposalInternal,
);
export const amendEmployeeCompensation = bindHumanResourcesCapability(
	amendEmployeeCompensationInternal,
);
export const amendEmployment = bindHumanResourcesCapability(
	amendEmploymentInternal,
);
export const amendEmploymentContract = bindHumanResourcesCapability(
	amendEmploymentContractInternal,
);
export const amendImprovementPlan = bindHumanResourcesCapability(
	amendImprovementPlanInternal,
);
export const amendLeaveRequest = bindHumanResourcesCapability(
	amendLeaveRequestInternal,
);
export const amendOfferDraft = bindHumanResourcesCapability(
	amendOfferDraftInternal,
);
export const amendRequisition = bindHumanResourcesCapability(
	amendRequisitionInternal,
);
export const anonymizeCandidate = bindHumanResourcesCapability(
	anonymizeCandidateInternal,
);
export const anonymizeHumanResourcesSubject = bindHumanResourcesCapability(
	anonymizeHumanResourcesSubjectInternal,
);
export const applyApprovedCompensationResult = bindHumanResourcesCapability(
	applyApprovedCompensationResultInternal,
);
export const approveAttendanceBreakWaiver = bindHumanResourcesCapability(
	approveAttendanceBreakWaiverInternal,
);
export const approveCompensationProposal = bindHumanResourcesCapability(
	approveCompensationProposalInternal,
);
export const approveEmployeeCaseAction = bindHumanResourcesCapability(
	approveEmployeeCaseActionInternal,
);
export const approveEmployeeCompensation = bindHumanResourcesCapability(
	approveEmployeeCompensationInternal,
);
export const approveHeadcountPlan = bindHumanResourcesCapability(
	approveHeadcountPlanInternal,
);
export const approveLeaveRequest = bindHumanResourcesCapability(
	approveLeaveRequestInternal,
);
export const approveOffer = bindHumanResourcesCapability(approveOfferInternal);
export const approveOvertimeRequest = bindHumanResourcesCapability(
	approveOvertimeRequestInternal,
);
export const approvePerformanceGoal = bindHumanResourcesCapability(
	approvePerformanceGoalInternal,
);
export const approveRequisition = bindHumanResourcesCapability(
	approveRequisitionInternal,
);
export const approveSuccessionCandidate = bindHumanResourcesCapability(
	approveSuccessionCandidateInternal,
);
export const approveTalentPoolMember = bindHumanResourcesCapability(
	approveTalentPoolMemberInternal,
);
export const approveTermination = bindHumanResourcesCapability(
	approveTerminationInternal,
);
export const approveTimesheet = bindHumanResourcesCapability(
	approveTimesheetInternal,
);
export const archiveBenefitPlan = bindHumanResourcesCapability(
	archiveBenefitPlanInternal,
);
export const archiveCompensationGrade = bindHumanResourcesCapability(
	archiveCompensationGradeInternal,
);
export const archiveCompensationGradeProgressionRule =
	bindHumanResourcesCapability(archiveCompensationGradeProgressionRuleInternal);
export const archiveCourse = bindHumanResourcesCapability(
	archiveCourseInternal,
);
export const archiveDepartment = bindHumanResourcesCapability(
	archiveDepartmentInternal,
);
export const archiveJob = bindHumanResourcesCapability(archiveJobInternal);
export const archiveLeavePolicy = bindHumanResourcesCapability(
	archiveLeavePolicyInternal,
);
export const archiveSalaryBand = bindHumanResourcesCapability(
	archiveSalaryBandInternal,
);
export const archiveTalentProfile = bindHumanResourcesCapability(
	archiveTalentProfileInternal,
);
export const archiveWorkCalendar = bindHumanResourcesCapability(
	archiveWorkCalendarInternal,
);
export const assembleApprovedPayrollHandoff = bindHumanResourcesCapability(
	assembleApprovedPayrollHandoffInternal,
);
export const assessEmployeeCompetency = bindHumanResourcesCapability(
	assessEmployeeCompetencyInternal,
);
export const assessSuccessionReadiness = bindHumanResourcesCapability(
	assessSuccessionReadinessInternal,
);
export const assignEmployeeCaseOwner = bindHumanResourcesCapability(
	assignEmployeeCaseOwnerInternal,
);
export const assignEmploymentCalendar = bindHumanResourcesCapability(
	assignEmploymentCalendarInternal,
);
export const assignHiringManager = bindHumanResourcesCapability(
	assignHiringManagerInternal,
);
export const assignInterviewInterviewer = bindHumanResourcesCapability(
	assignInterviewInterviewerInternal,
);
export const assignLearning = bindHumanResourcesCapability(
	assignLearningInternal,
);
export const assignPrimaryReportingLine = bindHumanResourcesCapability(
	assignPrimaryReportingLineInternal,
);
export const assignSessionInstructor = bindHumanResourcesCapability(
	assignSessionInstructorInternal,
);
export const assignShift = bindHumanResourcesCapability(assignShiftInternal);
export const assignTimeApprovalAuthority = bindHumanResourcesCapability(
	assignTimeApprovalAuthorityInternal,
);
export const assignTimePolicy = bindHumanResourcesCapability(
	assignTimePolicyInternal,
);
export const assignWorkCalendarScope = bindHumanResourcesCapability(
	assignWorkCalendarScopeInternal,
);
export const calibratePerformanceReview = bindHumanResourcesCapability(
	calibratePerformanceReviewInternal,
);
export const cancelApprovedLeaveRequest = bindHumanResourcesCapability(
	cancelApprovedLeaveRequestInternal,
);
export const cancelBenefitEnrollment = bindHumanResourcesCapability(
	cancelBenefitEnrollmentInternal,
);
export const cancelCompensationReviewCycle = bindHumanResourcesCapability(
	cancelCompensationReviewCycleInternal,
);
export const cancelImprovementPlan = bindHumanResourcesCapability(
	cancelImprovementPlanInternal,
);
export const cancelInterview = bindHumanResourcesCapability(
	cancelInterviewInternal,
);
export const cancelOvertimeRequest = bindHumanResourcesCapability(
	cancelOvertimeRequestInternal,
);
export const cancelPerformanceCycle = bindHumanResourcesCapability(
	cancelPerformanceCycleInternal,
);
export const cancelPerformanceGoal = bindHumanResourcesCapability(
	cancelPerformanceGoalInternal,
);
export const cancelRequisition = bindHumanResourcesCapability(
	cancelRequisitionInternal,
);
export const cancelSession = bindHumanResourcesCapability(
	cancelSessionInternal,
);
export const cancelShiftAssignment = bindHumanResourcesCapability(
	cancelShiftAssignmentInternal,
);
export const carryForwardLeaveEntitlement = bindHumanResourcesCapability(
	carryForwardLeaveEntitlementInternal,
);
export const changeCandidateRetention = bindHumanResourcesCapability(
	changeCandidateRetentionInternal,
);
export const changeShiftAssignment = bindHumanResourcesCapability(
	changeShiftAssignmentInternal,
);
export const changeWorkerStatus = bindHumanResourcesCapability(
	changeWorkerStatusInternal,
);
export const changeWorkerType = bindHumanResourcesCapability(
	changeWorkerTypeInternal,
);
export const closeCareerPlan = bindHumanResourcesCapability(
	closeCareerPlanInternal,
);
export const closeCompensationReviewCycle = bindHumanResourcesCapability(
	closeCompensationReviewCycleInternal,
);
export const closeEmployeeCase = bindHumanResourcesCapability(
	closeEmployeeCaseInternal,
);
export const closeHeadcountPlan = bindHumanResourcesCapability(
	closeHeadcountPlanInternal,
);
export const closeImprovementPlanUnsuccessful = bindHumanResourcesCapability(
	closeImprovementPlanUnsuccessfulInternal,
);
export const closePerformanceCycle = bindHumanResourcesCapability(
	closePerformanceCycleInternal,
);
export const closePerformanceGoal = bindHumanResourcesCapability(
	closePerformanceGoalInternal,
);
export const closePosition = bindHumanResourcesCapability(
	closePositionInternal,
);
export const closeReportingLine = bindHumanResourcesCapability(
	closeReportingLineInternal,
);
export const closeRequisition = bindHumanResourcesCapability(
	closeRequisitionInternal,
);
export const closeSuccessionPlan = bindHumanResourcesCapability(
	closeSuccessionPlanInternal,
);
export const closeTalentPool = bindHumanResourcesCapability(
	closeTalentPoolInternal,
);
export const closeWorkEligibility = bindHumanResourcesCapability(
	closeWorkEligibilityInternal,
);
export const completeCareerPlanAction = bindHumanResourcesCapability(
	completeCareerPlanActionInternal,
);
export const completeImprovementPlan = bindHumanResourcesCapability(
	completeImprovementPlanInternal,
);
export const completeOffboarding = bindHumanResourcesCapability(
	completeOffboardingInternal,
);
export const completeOffboardingTask = bindHumanResourcesCapability(
	completeOffboardingTaskInternal,
);
export const completeOnboarding = bindHumanResourcesCapability(
	completeOnboardingInternal,
);
export const completeOnboardingTask = bindHumanResourcesCapability(
	completeOnboardingTaskInternal,
);
export const completeSession = bindHumanResourcesCapability(
	completeSessionInternal,
);
export const completeShiftAssignment = bindHumanResourcesCapability(
	completeShiftAssignmentInternal,
);
export const confirmEmployment = bindHumanResourcesCapability(
	confirmEmploymentInternal,
);
export const confirmTalentProfileAssessment = bindHumanResourcesCapability(
	confirmTalentProfileAssessmentInternal,
);
export const consumeHeadcountReservation = bindHumanResourcesCapability(
	consumeHeadcountReservationInternal,
);
export const correctAttendanceEvent = bindHumanResourcesCapability(
	correctAttendanceEventInternal,
);
export const correctEmployeeCompensation = bindHumanResourcesCapability(
	correctEmployeeCompensationInternal,
);
export const correctEmployment = bindHumanResourcesCapability(
	correctEmploymentInternal,
);
export const correctEmploymentContract = bindHumanResourcesCapability(
	correctEmploymentContractInternal,
);
export const createApplication = bindHumanResourcesCapability(
	createApplicationInternal,
);
export const createAssignment = bindHumanResourcesCapability(
	createAssignmentInternal,
);
export const createAttendanceException = bindHumanResourcesCapability(
	createAttendanceExceptionInternal,
);
export const createBenefitPlan = bindHumanResourcesCapability(
	createBenefitPlanInternal,
);
export const createCandidate = bindHumanResourcesCapability(
	createCandidateInternal,
);
export const createCareerPlan = bindHumanResourcesCapability(
	createCareerPlanInternal,
);
export const createCompensationGrade = bindHumanResourcesCapability(
	createCompensationGradeInternal,
);
export const createCompensationGradeProgressionRule =
	bindHumanResourcesCapability(createCompensationGradeProgressionRuleInternal);
export const createCompensationProposal = bindHumanResourcesCapability(
	createCompensationProposalInternal,
);
export const createCompensationReviewCycle = bindHumanResourcesCapability(
	createCompensationReviewCycleInternal,
);
export const createCompensationReviewDraft = bindHumanResourcesCapability(
	createCompensationReviewDraftInternal,
);
export const createCompetency = bindHumanResourcesCapability(
	createCompetencyInternal,
);
export const createCourse = bindHumanResourcesCapability(createCourseInternal);
export const createDepartment = bindHumanResourcesCapability(
	createDepartmentInternal,
);
export const createDocumentRequirement = bindHumanResourcesCapability(
	createDocumentRequirementInternal,
);
export const createDraftLeaveRequest = bindHumanResourcesCapability(
	createDraftLeaveRequestInternal,
);
export const createDraftRequisition = bindHumanResourcesCapability(
	createDraftRequisitionInternal,
);
export const createEmployee = bindHumanResourcesCapability(
	createEmployeeInternal,
);
export const createEmployeeCompensation = bindHumanResourcesCapability(
	createEmployeeCompensationInternal,
);
export const createEmployment = bindHumanResourcesCapability(
	createEmploymentInternal,
);
export const createEmploymentContract = bindHumanResourcesCapability(
	createEmploymentContractInternal,
);
export const createHeadcountPlan = bindHumanResourcesCapability(
	createHeadcountPlanInternal,
);
export const createImprovementPlan = bindHumanResourcesCapability(
	createImprovementPlanInternal,
);
export const createJob = bindHumanResourcesCapability(createJobInternal);
export const createLeavePolicy = bindHumanResourcesCapability(
	createLeavePolicyInternal,
);
export const createOffer = bindHumanResourcesCapability(createOfferInternal);
export const createOvertimeRequest = bindHumanResourcesCapability(
	createOvertimeRequestInternal,
);
export const createPerformanceCycle = bindHumanResourcesCapability(
	createPerformanceCycleInternal,
);
export const createPerformanceGoal = bindHumanResourcesCapability(
	createPerformanceGoalInternal,
);
export const createPerson = bindHumanResourcesCapability(createPersonInternal);
export const createPosition = bindHumanResourcesCapability(
	createPositionInternal,
);
export const createSalaryBand = bindHumanResourcesCapability(
	createSalaryBandInternal,
);
export const createSession = bindHumanResourcesCapability(
	createSessionInternal,
);
export const createShift = bindHumanResourcesCapability(createShiftInternal);
export const createSuccessionPlan = bindHumanResourcesCapability(
	createSuccessionPlanInternal,
);
export const createTalentPool = bindHumanResourcesCapability(
	createTalentPoolInternal,
);
export const createTalentProfile = bindHumanResourcesCapability(
	createTalentProfileInternal,
);
export const createTimePolicy = bindHumanResourcesCapability(
	createTimePolicyInternal,
);
export const createTimesheet = bindHumanResourcesCapability(
	createTimesheetInternal,
);
export const createWorkCalendar = bindHumanResourcesCapability(
	createWorkCalendarInternal,
);
export const createWorker = bindHumanResourcesCapability(createWorkerInternal);
export const deactivateShift = bindHumanResourcesCapability(
	deactivateShiftInternal,
);
export const declineOffer = bindHumanResourcesCapability(declineOfferInternal);
export const detectCandidateDuplicates = bindHumanResourcesCapability(
	detectCandidateDuplicatesInternal,
);
export const detectComplianceExpiryOperations = bindHumanResourcesCapability(
	detectComplianceExpiryOperationsInternal,
);
export const detectPersonDuplicates = bindHumanResourcesCapability(
	detectPersonDuplicatesInternal,
);
export const endAssignment = bindHumanResourcesCapability(
	endAssignmentInternal,
);
export const endBenefitEnrollment = bindHumanResourcesCapability(
	endBenefitEnrollmentInternal,
);
export const endBenefitEnrollmentDependent = bindHumanResourcesCapability(
	endBenefitEnrollmentDependentInternal,
);
export const endEmployeeCompensation = bindHumanResourcesCapability(
	endEmployeeCompensationInternal,
);
export const endEmploymentContract = bindHumanResourcesCapability(
	endEmploymentContractInternal,
);
export const endTimeApprovalAuthorityAssignment = bindHumanResourcesCapability(
	endTimeApprovalAuthorityAssignmentInternal,
);
export const endWorkCalendarAssignment = bindHumanResourcesCapability(
	endWorkCalendarAssignmentInternal,
);
export const endWorkCalendarScopeAssignment = bindHumanResourcesCapability(
	endWorkCalendarScopeAssignmentInternal,
);
export const enrolAssignment = bindHumanResourcesCapability(
	enrolAssignmentInternal,
);
export const enrolBenefit = bindHumanResourcesCapability(enrolBenefitInternal);
export const enrollEligibleCycleParticipants = bindHumanResourcesCapability(
	enrollEligibleCycleParticipantsInternal,
);
export const evaluateHumanResourcesAnonymization = bindHumanResourcesCapability(
	evaluateHumanResourcesAnonymizationInternal,
);
export const evaluateHumanResourcesRetention = bindHumanResourcesCapability(
	evaluateHumanResourcesRetentionInternal,
);
export const excuseAttendanceException = bindHumanResourcesCapability(
	excuseAttendanceExceptionInternal,
);
export const expireCertification = bindHumanResourcesCapability(
	expireCertificationInternal,
);
export const expireCompetencyAssessment = bindHumanResourcesCapability(
	expireCompetencyAssessmentInternal,
);
export const expireLeaveEntitlement = bindHumanResourcesCapability(
	expireLeaveEntitlementInternal,
);
export const expireOffer = bindHumanResourcesCapability(expireOfferInternal);
export const exportHumanResourcesSubjectData = bindHumanResourcesCapability(
	exportHumanResourcesSubjectDataInternal,
);
export const extendProbation = bindHumanResourcesCapability(
	extendProbationInternal,
);
export const finalizeCompensationReview = bindHumanResourcesCapability(
	finalizeCompensationReviewInternal,
);
export const finalizePerformanceReview = bindHumanResourcesCapability(
	finalizePerformanceReviewInternal,
);
export const finalizeTermination = bindHumanResourcesCapability(
	finalizeTerminationInternal,
);
export const findSalaryBandByGradeAndCurrencyAsOf =
	bindHumanResourcesCapability(findSalaryBandByGradeAndCurrencyAsOfInternal);
export const freezePosition = bindHumanResourcesCapability(
	freezePositionInternal,
);
export const generateTimesheetEntries = bindHumanResourcesCapability(
	generateTimesheetEntriesInternal,
);
export const getApplication = bindHumanResourcesCapability(
	getApplicationInternal,
);
export const getApprovedCompensationHandoff = bindHumanResourcesCapability(
	getApprovedCompensationHandoffInternal,
);
export const getApprovedHeadcountPlan = bindHumanResourcesCapability(
	getApprovedHeadcountPlanInternal,
);
export const getApprovedLeaveHandoff = bindHumanResourcesCapability(
	getApprovedLeaveHandoffInternal,
);
export const getApprovedTimeHandoff = bindHumanResourcesCapability(
	getApprovedTimeHandoffInternal,
);
export const getAssignment = bindHumanResourcesCapability(
	getAssignmentInternal,
);
export const getAssignmentAsOf = bindHumanResourcesCapability(
	getAssignmentAsOfInternal,
);
export const getAttendanceEvent = bindHumanResourcesCapability(
	getAttendanceEventInternal,
);
export const getAttendanceException = bindHumanResourcesCapability(
	getAttendanceExceptionInternal,
);
export const getAttendanceSession = bindHumanResourcesCapability(
	getAttendanceSessionInternal,
);
export const getBenefitPlanEligibility = bindHumanResourcesCapability(
	getBenefitPlanEligibilityInternal,
);
export const getCandidate = bindHumanResourcesCapability(getCandidateInternal);
export const getCareerPlanById = bindHumanResourcesCapability(
	getCareerPlanByIdInternal,
);
export const getCertification = bindHumanResourcesCapability(
	getCertificationInternal,
);
export const getClearanceByOffboardingCase = bindHumanResourcesCapability(
	getClearanceByOffboardingCaseInternal,
);
export const getCompensationGrade = bindHumanResourcesCapability(
	getCompensationGradeInternal,
);
export const getCompensationGradeProgressionRule = bindHumanResourcesCapability(
	getCompensationGradeProgressionRuleInternal,
);
export const getCompensationProposal = bindHumanResourcesCapability(
	getCompensationProposalInternal,
);
export const getCompensationReview = bindHumanResourcesCapability(
	getCompensationReviewInternal,
);
export const getCompensationReviewCycle = bindHumanResourcesCapability(
	getCompensationReviewCycleInternal,
);
export const getCompetencyById = bindHumanResourcesCapability(
	getCompetencyByIdInternal,
);
export const getCompletion = bindHumanResourcesCapability(
	getCompletionInternal,
);
export const getCourse = bindHumanResourcesCapability(getCourseInternal);
export const getCurrentEmploymentContract = bindHumanResourcesCapability(
	getCurrentEmploymentContractInternal,
);
export const getDailyAttendanceSummary = bindHumanResourcesCapability(
	getDailyAttendanceSummaryInternal,
);
export const getDepartment = bindHumanResourcesCapability(
	getDepartmentInternal,
);
export const getDepartmentAsOf = bindHumanResourcesCapability(
	getDepartmentAsOfInternal,
);
export const getEmployeeById = bindHumanResourcesCapability(
	getEmployeeByIdInternal,
);
export const getEmployeeCaseById = bindHumanResourcesCapability(
	getEmployeeCaseByIdInternal,
);
export const getEmployeeCaseOutcome = bindHumanResourcesCapability(
	getEmployeeCaseOutcomeInternal,
);
export const getEmployeeCaseTimeline = bindHumanResourcesCapability(
	getEmployeeCaseTimelineInternal,
);
export const getEmployeeCompensation = bindHumanResourcesCapability(
	getEmployeeCompensationInternal,
);
export const getEmployeeCompetencyProfile = bindHumanResourcesCapability(
	getEmployeeCompetencyProfileInternal,
);
export const getEmployeeComplianceSummary = bindHumanResourcesCapability(
	getEmployeeComplianceSummaryInternal,
);
export const getEmployeeDocument = bindHumanResourcesCapability(
	getEmployeeDocumentInternal,
);
export const getEmployeePerformanceHistory = bindHumanResourcesCapability(
	getEmployeePerformanceHistoryInternal,
);
export const getEmployeeProfile = bindHumanResourcesCapability(
	getEmployeeProfileInternal,
);
export const getEmployeeRelationsHistoryByEmployee =
	bindHumanResourcesCapability(getEmployeeRelationsHistoryByEmployeeInternal);
export const getEmployeeWorkEligibility = bindHumanResourcesCapability(
	getEmployeeWorkEligibilityInternal,
);
export const getEmployment = bindHumanResourcesCapability(
	getEmploymentInternal,
);
export const getEmploymentAsOf = bindHumanResourcesCapability(
	getEmploymentAsOfInternal,
);
export const getEmploymentConfirmation = bindHumanResourcesCapability(
	getEmploymentConfirmationInternal,
);
export const getEmploymentContract = bindHumanResourcesCapability(
	getEmploymentContractInternal,
);
export const getEmploymentContractAsOf = bindHumanResourcesCapability(
	getEmploymentContractAsOfInternal,
);
export const getHeadcountAvailability = bindHumanResourcesCapability(
	getHeadcountAvailabilityInternal,
);
export const getHeadcountPlanById = bindHumanResourcesCapability(
	getHeadcountPlanByIdInternal,
);
export const getHumanResourcesPrivacyCase = bindHumanResourcesCapability(
	getHumanResourcesPrivacyCaseInternal,
);
export const getImprovementPlanById = bindHumanResourcesCapability(
	getImprovementPlanByIdInternal,
);
export const getInterview = bindHumanResourcesCapability(getInterviewInternal);
export const getInterviewEvaluation = bindHumanResourcesCapability(
	getInterviewEvaluationInternal,
);
export const getJob = bindHumanResourcesCapability(getJobInternal);
export const getJobAsOf = bindHumanResourcesCapability(getJobAsOfInternal);
export const getLearningAssignment = bindHumanResourcesCapability(
	getLearningAssignmentInternal,
);
export const getLearningAttendance = bindHumanResourcesCapability(
	getLearningAttendanceInternal,
);
export const getLeaveBalance = bindHumanResourcesCapability(
	getLeaveBalanceInternal,
);
export const getLeaveEntitlement = bindHumanResourcesCapability(
	getLeaveEntitlementInternal,
);
export const getLeavePolicy = bindHumanResourcesCapability(
	getLeavePolicyInternal,
);
export const getLeaveRequest = bindHumanResourcesCapability(
	getLeaveRequestInternal,
);
export const getOffboardingAccessRevocationByCase =
	bindHumanResourcesCapability(getOffboardingAccessRevocationByCaseInternal);
export const getOffboardingCase = bindHumanResourcesCapability(
	getOffboardingCaseInternal,
);
export const getOffboardingPayrollHandoffByCase = bindHumanResourcesCapability(
	getOffboardingPayrollHandoffByCaseInternal,
);
export const getOffer = bindHumanResourcesCapability(getOfferInternal);
export const getOnboardingAccessHandoffByCase = bindHumanResourcesCapability(
	getOnboardingAccessHandoffByCaseInternal,
);
export const getOnboardingCase = bindHumanResourcesCapability(
	getOnboardingCaseInternal,
);
export const getOnboardingEquipmentHandoffByCase = bindHumanResourcesCapability(
	getOnboardingEquipmentHandoffByCaseInternal,
);
export const getOnboardingOrientationByCase = bindHumanResourcesCapability(
	getOnboardingOrientationByCaseInternal,
);
export const getOrganizationTree = bindHumanResourcesCapability(
	getOrganizationTreeInternal,
);
export const getOrganizationTreeAsOf = bindHumanResourcesCapability(
	getOrganizationTreeAsOfInternal,
);
export const getOvertimeRequest = bindHumanResourcesCapability(
	getOvertimeRequestInternal,
);
export const getPerformanceCycleById = bindHumanResourcesCapability(
	getPerformanceCycleByIdInternal,
);
export const getPerformanceCycleEligibility = bindHumanResourcesCapability(
	getPerformanceCycleEligibilityInternal,
);
export const getPerformanceGoalById = bindHumanResourcesCapability(
	getPerformanceGoalByIdInternal,
);
export const getPerformanceReviewById = bindHumanResourcesCapability(
	getPerformanceReviewByIdInternal,
);
export const getPersonAsOf = bindHumanResourcesCapability(
	getPersonAsOfInternal,
);
export const getPersonById = bindHumanResourcesCapability(
	getPersonByIdInternal,
);
export const getPolicyAcknowledgementStatus = bindHumanResourcesCapability(
	getPolicyAcknowledgementStatusInternal,
);
export const getPosition = bindHumanResourcesCapability(getPositionInternal);
export const getPositionAsOf = bindHumanResourcesCapability(
	getPositionAsOfInternal,
);
export const getPositionOccupancyAsOf = bindHumanResourcesCapability(
	getPositionOccupancyAsOfInternal,
);
export const getPositionSuccessionCoverage = bindHumanResourcesCapability(
	getPositionSuccessionCoverageInternal,
);
export const getProbationReview = bindHumanResourcesCapability(
	getProbationReviewInternal,
);
export const getRecruitmentHeadcountHandoff = bindHumanResourcesCapability(
	getRecruitmentHeadcountHandoffInternal,
);
export const getRequisition = bindHumanResourcesCapability(
	getRequisitionInternal,
);
export const getSalaryBand = bindHumanResourcesCapability(
	getSalaryBandInternal,
);
export const getScheduledShiftForEmployeeDate = bindHumanResourcesCapability(
	getScheduledShiftForEmployeeDateInternal,
);
export const getSession = bindHumanResourcesCapability(getSessionInternal);
export const getShift = bindHumanResourcesCapability(getShiftInternal);
export const getShiftAssignment = bindHumanResourcesCapability(
	getShiftAssignmentInternal,
);
export const getSuccessionPlanById = bindHumanResourcesCapability(
	getSuccessionPlanByIdInternal,
);
export const getTalentProfileByEmployee = bindHumanResourcesCapability(
	getTalentProfileByEmployeeInternal,
);
export const getTermination = bindHumanResourcesCapability(
	getTerminationInternal,
);
export const getTimePolicy = bindHumanResourcesCapability(
	getTimePolicyInternal,
);
export const getTimesheet = bindHumanResourcesCapability(getTimesheetInternal);
export const getTimesheetForEmployeePeriod = bindHumanResourcesCapability(
	getTimesheetForEmployeePeriodInternal,
);
export const getTimesheetTotals = bindHumanResourcesCapability(
	getTimesheetTotalsInternal,
);
export const getWorkCalendar = bindHumanResourcesCapability(
	getWorkCalendarInternal,
);
export const getWorkerAsOf = bindHumanResourcesCapability(
	getWorkerAsOfInternal,
);
export const getWorkerById = bindHumanResourcesCapability(
	getWorkerByIdInternal,
);
export const getWorkforcePlanVariance = bindHumanResourcesCapability(
	getWorkforcePlanVarianceInternal,
);
export const grantLeaveEntitlement = bindHumanResourcesCapability(
	grantLeaveEntitlementInternal,
);
export const hireEmployment = bindHumanResourcesCapability(
	hireEmploymentInternal,
);
export const hireFromAcceptedOffer = bindHumanResourcesCapability(
	hireFromAcceptedOfferInternal,
);
export const importAttendanceEvents = bindHumanResourcesCapability(
	importAttendanceEventsInternal,
);
export const issueCertification = bindHumanResourcesCapability(
	issueCertificationInternal,
);
export const issueInterimEmployeeMeasure = bindHumanResourcesCapability(
	issueInterimEmployeeMeasureInternal,
);
export const issueOffer = bindHumanResourcesCapability(issueOfferInternal);
export const issuePolicyAcknowledgementRequirement =
	bindHumanResourcesCapability(issuePolicyAcknowledgementRequirementInternal);
export const listActiveImprovementPlans = bindHumanResourcesCapability(
	listActiveImprovementPlansInternal,
);
export const listApplicationStatusHistory = bindHumanResourcesCapability(
	listApplicationStatusHistoryInternal,
);
export const listApplications = bindHumanResourcesCapability(
	listApplicationsInternal,
);
export const listAttendanceAdjustments = bindHumanResourcesCapability(
	listAttendanceAdjustmentsInternal,
);
export const listAttendanceBreakWaiverDecisions = bindHumanResourcesCapability(
	listAttendanceBreakWaiverDecisionsInternal,
);
export const listAttendanceEvents = bindHumanResourcesCapability(
	listAttendanceEventsInternal,
);
export const listAttendanceExceptions = bindHumanResourcesCapability(
	listAttendanceExceptionsInternal,
);
export const listAttendanceSessions = bindHumanResourcesCapability(
	listAttendanceSessionsInternal,
);
export const listCandidates = bindHumanResourcesCapability(
	listCandidatesInternal,
);
export const listCasesAssignedToActor = bindHumanResourcesCapability(
	listCasesAssignedToActorInternal,
);
export const listCertifications = bindHumanResourcesCapability(
	listCertificationsInternal,
);
export const listCompensationGradeProgressionRulesFromGrade =
	bindHumanResourcesCapability(
		listCompensationGradeProgressionRulesFromGradeInternal,
	);
export const listCompensationGrades = bindHumanResourcesCapability(
	listCompensationGradesInternal,
);
export const listCompensationProposals = bindHumanResourcesCapability(
	listCompensationProposalsInternal,
);
export const listCompensationReviewCycles = bindHumanResourcesCapability(
	listCompensationReviewCyclesInternal,
);
export const listCompensationReviewsByEmployee = bindHumanResourcesCapability(
	listCompensationReviewsByEmployeeInternal,
);
export const listCompetencies = bindHumanResourcesCapability(
	listCompetenciesInternal,
);
export const listCompletions = bindHumanResourcesCapability(
	listCompletionsInternal,
);
export const listCourses = bindHumanResourcesCapability(listCoursesInternal);
export const listCriticalRoleReadiness = bindHumanResourcesCapability(
	listCriticalRoleReadinessInternal,
);
export const listCycleParticipants = bindHumanResourcesCapability(
	listCycleParticipantsInternal,
);
export const listDepartments = bindHumanResourcesCapability(
	listDepartmentsInternal,
);
export const listDirectReports = bindHumanResourcesCapability(
	listDirectReportsInternal,
);
export const listEligibleProgressionTargets = bindHumanResourcesCapability(
	listEligibleProgressionTargetsInternal,
);
export const listEmployeeCareerPlans = bindHumanResourcesCapability(
	listEmployeeCareerPlansInternal,
);
export const listEmployeeCases = bindHumanResourcesCapability(
	listEmployeeCasesInternal,
);
export const listEmployeeCompensationsByEmployee = bindHumanResourcesCapability(
	listEmployeeCompensationsByEmployeeInternal,
);
export const listEmployeeDocuments = bindHumanResourcesCapability(
	listEmployeeDocumentsInternal,
);
export const listEmployeeGoals = bindHumanResourcesCapability(
	listEmployeeGoalsInternal,
);
export const listEmployeePerformanceReviews = bindHumanResourcesCapability(
	listEmployeePerformanceReviewsInternal,
);
export const listEmployees = bindHumanResourcesCapability(
	listEmployeesInternal,
);
export const listEmployeesWithWorkEligibilityRisk =
	bindHumanResourcesCapability(listEmployeesWithWorkEligibilityRiskInternal);
export const listEmploymentContracts = bindHumanResourcesCapability(
	listEmploymentContractsInternal,
);
export const listEmploymentStatusHistory = bindHumanResourcesCapability(
	listEmploymentStatusHistoryInternal,
);
export const listExpiringCertifications = bindHumanResourcesCapability(
	listExpiringCertificationsInternal,
);
export const listExpiringEmployeeDocuments = bindHumanResourcesCapability(
	listExpiringEmployeeDocumentsInternal,
);
export const listGoalProgress = bindHumanResourcesCapability(
	listGoalProgressInternal,
);
export const listHeadcountPlans = bindHumanResourcesCapability(
	listHeadcountPlansInternal,
);
export const listHeadcountReservations = bindHumanResourcesCapability(
	listHeadcountReservationsInternal,
);
export const listImprovementPlanCheckpoints = bindHumanResourcesCapability(
	listImprovementPlanCheckpointsInternal,
);
export const listInterviews = bindHumanResourcesCapability(
	listInterviewsInternal,
);
export const listJobCompetencies = bindHumanResourcesCapability(
	listJobCompetenciesInternal,
);
export const listJobs = bindHumanResourcesCapability(listJobsInternal);
export const listLearningAssignments = bindHumanResourcesCapability(
	listLearningAssignmentsInternal,
);
export const listLearningAttendance = bindHumanResourcesCapability(
	listLearningAttendanceInternal,
);
export const listLeaveEntitlements = bindHumanResourcesCapability(
	listLeaveEntitlementsInternal,
);
export const listLeavePolicies = bindHumanResourcesCapability(
	listLeavePoliciesInternal,
);
export const listLeaveRequests = bindHumanResourcesCapability(
	listLeaveRequestsInternal,
);
export const listLocationSchedule = bindHumanResourcesCapability(
	listLocationScheduleInternal,
);
export const listMissingRequiredDocuments = bindHumanResourcesCapability(
	listMissingRequiredDocumentsInternal,
);
export const listOffboardingTasks = bindHumanResourcesCapability(
	listOffboardingTasksInternal,
);
export const listOffers = bindHumanResourcesCapability(listOffersInternal);
export const listOnboardingTasks = bindHumanResourcesCapability(
	listOnboardingTasksInternal,
);
export const listOpenEmployeeRelationsCases = bindHumanResourcesCapability(
	listOpenEmployeeRelationsCasesInternal,
);
export const listOutstandingPolicyAcknowledgements =
	bindHumanResourcesCapability(listOutstandingPolicyAcknowledgementsInternal);
export const listOverduePolicyAcknowledgements = bindHumanResourcesCapability(
	listOverduePolicyAcknowledgementsInternal,
);
export const listOvertimeRequests = bindHumanResourcesCapability(
	listOvertimeRequestsInternal,
);
export const listPendingApprovalLeaveRequests = bindHumanResourcesCapability(
	listPendingApprovalLeaveRequestsInternal,
);
export const listPendingOvertimeApprovals = bindHumanResourcesCapability(
	listPendingOvertimeApprovalsInternal,
);
export const listPerformanceCycleReviewPeriods = bindHumanResourcesCapability(
	listPerformanceCycleReviewPeriodsInternal,
);
export const listPerformanceCycles = bindHumanResourcesCapability(
	listPerformanceCyclesInternal,
);
export const listPersonContacts = bindHumanResourcesCapability(
	listPersonContactsInternal,
);
export const listPersonIdentifiers = bindHumanResourcesCapability(
	listPersonIdentifiersInternal,
);
export const listPositions = bindHumanResourcesCapability(
	listPositionsInternal,
);
export const listProbationAssessments = bindHumanResourcesCapability(
	listProbationAssessmentsInternal,
);
export const listProbationReviewsByEmployment = bindHumanResourcesCapability(
	listProbationReviewsByEmploymentInternal,
);
export const listRequisitions = bindHumanResourcesCapability(
	listRequisitionsInternal,
);
export const listReviewsPendingManagerAction = bindHumanResourcesCapability(
	listReviewsPendingManagerActionInternal,
);
export const listSalaryBandsByGrade = bindHumanResourcesCapability(
	listSalaryBandsByGradeInternal,
);
export const listSessions = bindHumanResourcesCapability(listSessionsInternal);
export const listShiftAssignmentSegments = bindHumanResourcesCapability(
	listShiftAssignmentSegmentsInternal,
);
export const listShiftAssignments = bindHumanResourcesCapability(
	listShiftAssignmentsInternal,
);
export const listShiftBreaks = bindHumanResourcesCapability(
	listShiftBreaksInternal,
);
export const listShifts = bindHumanResourcesCapability(listShiftsInternal);
export const listSuccessionCandidates = bindHumanResourcesCapability(
	listSuccessionCandidatesInternal,
);
export const listSuccessionPlans = bindHumanResourcesCapability(
	listSuccessionPlansInternal,
);
export const listTalentPoolMembers = bindHumanResourcesCapability(
	listTalentPoolMembersInternal,
);
export const listTalentProfileAssessments = bindHumanResourcesCapability(
	listTalentProfileAssessmentsInternal,
);
export const listTalentProfileMobility = bindHumanResourcesCapability(
	listTalentProfileMobilityInternal,
);
export const listTeamCalendarLeaveRequests = bindHumanResourcesCapability(
	listTeamCalendarLeaveRequestsInternal,
);
export const listTimesheetApprovalDecisions = bindHumanResourcesCapability(
	listTimesheetApprovalDecisionsInternal,
);
export const listTimesheetEntries = bindHumanResourcesCapability(
	listTimesheetEntriesInternal,
);
export const listTimesheets = bindHumanResourcesCapability(
	listTimesheetsInternal,
);
export const listUnresolvedAttendanceExceptions = bindHumanResourcesCapability(
	listUnresolvedAttendanceExceptionsInternal,
);
export const listWorkCalendarHolidays = bindHumanResourcesCapability(
	listWorkCalendarHolidaysInternal,
);
export const listWorkCalendars = bindHumanResourcesCapability(
	listWorkCalendarsInternal,
);
export const lockTimesheet = bindHumanResourcesCapability(
	lockTimesheetInternal,
);
export const mapCompetencyToJob = bindHumanResourcesCapability(
	mapCompetencyToJobInternal,
);
export const markEmployeeDocumentExpired = bindHumanResourcesCapability(
	markEmployeeDocumentExpiredInternal,
);
export const moveApplicationToInReview = bindHumanResourcesCapability(
	moveApplicationToInReviewInternal,
);
export const moveApplicationToInterviewing = bindHumanResourcesCapability(
	moveApplicationToInterviewingInternal,
);
export const nominateSuccessionCandidate = bindHumanResourcesCapability(
	nominateSuccessionCandidateInternal,
);
export const nominateTalentPoolMember = bindHumanResourcesCapability(
	nominateTalentPoolMemberInternal,
);
export const openCompensationReviewCycle = bindHumanResourcesCapability(
	openCompensationReviewCycleInternal,
);
export const openEmployeeCase = bindHumanResourcesCapability(
	openEmployeeCaseInternal,
);
export const openImprovementPlan = bindHumanResourcesCapability(
	openImprovementPlanInternal,
);
export const openPerformanceCycle = bindHumanResourcesCapability(
	openPerformanceCycleInternal,
);
export const openProbation = bindHumanResourcesCapability(
	openProbationInternal,
);
export const openRequisition = bindHumanResourcesCapability(
	openRequisitionInternal,
);
export const placeHumanResourcesLegalHold = bindHumanResourcesCapability(
	placeHumanResourcesLegalHoldInternal,
);
export const placeRequisitionOnHold = bindHumanResourcesCapability(
	placeRequisitionOnHoldInternal,
);
export const proposeTermination = bindHumanResourcesCapability(
	proposeTerminationInternal,
);
export const publishDocumentRequirement = bindHumanResourcesCapability(
	publishDocumentRequirementInternal,
);
export const publishLeavePolicy = bindHumanResourcesCapability(
	publishLeavePolicyInternal,
);
export const publishPerformanceCycle = bindHumanResourcesCapability(
	publishPerformanceCycleInternal,
);
export const publishShiftAssignment = bindHumanResourcesCapability(
	publishShiftAssignmentInternal,
);
export const reactivateEmployment = bindHumanResourcesCapability(
	reactivateEmploymentInternal,
);
export const recommendEmployeeCaseAction = bindHumanResourcesCapability(
	recommendEmployeeCaseActionInternal,
);
export const reconcileLeaveBalance = bindHumanResourcesCapability(
	reconcileLeaveBalanceInternal,
);
export const recordAttendanceEvent = bindHumanResourcesCapability(
	recordAttendanceEventInternal,
);
export const recordBreakEnd = bindHumanResourcesCapability(
	recordBreakEndInternal,
);
export const recordBreakStart = bindHumanResourcesCapability(
	recordBreakStartInternal,
);
export const recordClearance = bindHumanResourcesCapability(
	recordClearanceInternal,
);
export const recordClockIn = bindHumanResourcesCapability(
	recordClockInInternal,
);
export const recordClockOut = bindHumanResourcesCapability(
	recordClockOutInternal,
);
export const recordCompensationRecommendation = bindHumanResourcesCapability(
	recordCompensationRecommendationInternal,
);
export const recordCompletion = bindHumanResourcesCapability(
	recordCompletionInternal,
);
export const recordCriticalRoleReadiness = bindHumanResourcesCapability(
	recordCriticalRoleReadinessInternal,
);
export const recordEmployeeCaseAppeal = bindHumanResourcesCapability(
	recordEmployeeCaseAppealInternal,
);
export const recordEmployeeCaseEvent = bindHumanResourcesCapability(
	recordEmployeeCaseEventInternal,
);
export const recordEmployeeCaseFinding = bindHumanResourcesCapability(
	recordEmployeeCaseFindingInternal,
);
export const recordExitInterview = bindHumanResourcesCapability(
	recordExitInterviewInternal,
);
export const recordGoalProgress = bindHumanResourcesCapability(
	recordGoalProgressInternal,
);
export const recordImprovementCheckpoint = bindHumanResourcesCapability(
	recordImprovementCheckpointInternal,
);
export const recordInterviewEvaluation = bindHumanResourcesCapability(
	recordInterviewEvaluationInternal,
);
export const recordLearningAttendance = bindHumanResourcesCapability(
	recordLearningAttendanceInternal,
);
export const recordManualAttendance = bindHumanResourcesCapability(
	recordManualAttendanceInternal,
);
export const recordOffboardingAccessRevocation = bindHumanResourcesCapability(
	recordOffboardingAccessRevocationInternal,
);
export const recordOffboardingPayrollHandoff = bindHumanResourcesCapability(
	recordOffboardingPayrollHandoffInternal,
);
export const recordOnboardingAccessHandoff = bindHumanResourcesCapability(
	recordOnboardingAccessHandoffInternal,
);
export const recordOnboardingEquipmentHandoff = bindHumanResourcesCapability(
	recordOnboardingEquipmentHandoffInternal,
);
export const recordOnboardingOrientation = bindHumanResourcesCapability(
	recordOnboardingOrientationInternal,
);
export const recordOvertimeActual = bindHumanResourcesCapability(
	recordOvertimeActualInternal,
);
export const recordProbationAssessment = bindHumanResourcesCapability(
	recordProbationAssessmentInternal,
);
export const recordProbationOutcome = bindHumanResourcesCapability(
	recordProbationOutcomeInternal,
);
export const recordTalentProfileAssessment = bindHumanResourcesCapability(
	recordTalentProfileAssessmentInternal,
);
export const recordTalentProfileMobility = bindHumanResourcesCapability(
	recordTalentProfileMobilityInternal,
);
export const recordWorkEligibility = bindHumanResourcesCapability(
	recordWorkEligibilityInternal,
);
export const redactEmployeeCaseEvidenceReference = bindHumanResourcesCapability(
	redactEmployeeCaseEvidenceReferenceInternal,
);
export const registerEmployeeDocument = bindHumanResourcesCapability(
	registerEmployeeDocumentInternal,
);
export const rehireEmployment = bindHumanResourcesCapability(
	rehireEmploymentInternal,
);
export const rejectApplication = bindHumanResourcesCapability(
	rejectApplicationInternal,
);
export const rejectAttendanceException = bindHumanResourcesCapability(
	rejectAttendanceExceptionInternal,
);
export const rejectEmployeeDocument = bindHumanResourcesCapability(
	rejectEmployeeDocumentInternal,
);
export const rejectHeadcountPlan = bindHumanResourcesCapability(
	rejectHeadcountPlanInternal,
);
export const rejectLeaveRequest = bindHumanResourcesCapability(
	rejectLeaveRequestInternal,
);
export const rejectOvertimeRequest = bindHumanResourcesCapability(
	rejectOvertimeRequestInternal,
);
export const rejectPerformanceGoal = bindHumanResourcesCapability(
	rejectPerformanceGoalInternal,
);
export const rejectTimesheet = bindHumanResourcesCapability(
	rejectTimesheetInternal,
);
export const releaseHeadcountReservation = bindHumanResourcesCapability(
	releaseHeadcountReservationInternal,
);
export const releaseHumanResourcesLegalHold = bindHumanResourcesCapability(
	releaseHumanResourcesLegalHoldInternal,
);
export const removeCalendarDateOverride = bindHumanResourcesCapability(
	removeCalendarDateOverrideInternal,
);
export const removeCompetencyFromJob = bindHumanResourcesCapability(
	removeCompetencyFromJobInternal,
);
export const removeCycleParticipant = bindHumanResourcesCapability(
	removeCycleParticipantInternal,
);
export const removeHeadcountPlanLine = bindHumanResourcesCapability(
	removeHeadcountPlanLineInternal,
);
export const removeShiftBreak = bindHumanResourcesCapability(
	removeShiftBreakInternal,
);
export const removeSuccessionCandidate = bindHumanResourcesCapability(
	removeSuccessionCandidateInternal,
);
export const removeTalentPoolMember = bindHumanResourcesCapability(
	removeTalentPoolMemberInternal,
);
export const removeTimesheetEntry = bindHumanResourcesCapability(
	removeTimesheetEntryInternal,
);
export const removeWorkCalendarHoliday = bindHumanResourcesCapability(
	removeWorkCalendarHolidayInternal,
);
export const renewCertification = bindHumanResourcesCapability(
	renewCertificationInternal,
);
export const renewEmploymentContract = bindHumanResourcesCapability(
	renewEmploymentContractInternal,
);
export const renewWorkEligibility = bindHumanResourcesCapability(
	renewWorkEligibilityInternal,
);
export const reopenApplication = bindHumanResourcesCapability(
	reopenApplicationInternal,
);
export const reopenEmployeeCase = bindHumanResourcesCapability(
	reopenEmployeeCaseInternal,
);
export const reopenPerformanceReview = bindHumanResourcesCapability(
	reopenPerformanceReviewInternal,
);
export const reopenTimesheet = bindHumanResourcesCapability(
	reopenTimesheetInternal,
);
export const replacePrimaryReportingLine = bindHumanResourcesCapability(
	replacePrimaryReportingLineInternal,
);
export const reserveHeadcount = bindHumanResourcesCapability(
	reserveHeadcountInternal,
);
export const resolveApplicableLeavePolicy = bindHumanResourcesCapability(
	resolveApplicableLeavePolicyInternal,
);
export const resolveAttendanceException = bindHumanResourcesCapability(
	resolveAttendanceExceptionInternal,
);
export const resolveAttendanceSession = bindHumanResourcesCapability(
	resolveAttendanceSessionInternal,
);
export const resolveEmployeeCaseAppeal = bindHumanResourcesCapability(
	resolveEmployeeCaseAppealInternal,
);
export const resolveEmployeeOrgContextAsOf = bindHumanResourcesCapability(
	resolveEmployeeOrgContextAsOfInternal,
);
export const resolveEmployeeWorkCalendar = bindHumanResourcesCapability(
	resolveEmployeeWorkCalendarInternal,
);
export const resolveEmploymentCalendar = bindHumanResourcesCapability(
	resolveEmploymentCalendarInternal,
);
export const resolvePrimaryManager = bindHumanResourcesCapability(
	resolvePrimaryManagerInternal,
);
export const resolveTimePolicy = bindHumanResourcesCapability(
	resolveTimePolicyInternal,
);
export const retireCompetency = bindHumanResourcesCapability(
	retireCompetencyInternal,
);
export const retireDocumentRequirement = bindHumanResourcesCapability(
	retireDocumentRequirementInternal,
);
export const retirePersonContact = bindHumanResourcesCapability(
	retirePersonContactInternal,
);
export const retirePersonIdentifier = bindHumanResourcesCapability(
	retirePersonIdentifierInternal,
);
export const returnLeaveRequest = bindHumanResourcesCapability(
	returnLeaveRequestInternal,
);
export const returnPerformanceReviewForCorrection =
	bindHumanResourcesCapability(returnPerformanceReviewForCorrectionInternal);
export const returnTimesheet = bindHumanResourcesCapability(
	returnTimesheetInternal,
);
export const reviewAttendanceException = bindHumanResourcesCapability(
	reviewAttendanceExceptionInternal,
);
export const revokeCertification = bindHumanResourcesCapability(
	revokeCertificationInternal,
);
export const revokeEmployeeDocumentVerification = bindHumanResourcesCapability(
	revokeEmployeeDocumentVerificationInternal,
);
export const revokePolicyAcknowledgement = bindHumanResourcesCapability(
	revokePolicyAcknowledgementInternal,
);
export const scheduleEmployeeCompensationChange = bindHumanResourcesCapability(
	scheduleEmployeeCompensationChangeInternal,
);
export const scheduleInterview = bindHumanResourcesCapability(
	scheduleInterviewInternal,
);
export const setBenefitPlanEligibility = bindHumanResourcesCapability(
	setBenefitPlanEligibilityInternal,
);
export const setPerformanceCycleEligibility = bindHumanResourcesCapability(
	setPerformanceCycleEligibilityInternal,
);
export const setPerformanceCycleReviewPeriods = bindHumanResourcesCapability(
	setPerformanceCycleReviewPeriodsInternal,
);
export const setPersonPrivacyClassification = bindHumanResourcesCapability(
	setPersonPrivacyClassificationInternal,
);
export const startOffboarding = bindHumanResourcesCapability(
	startOffboardingInternal,
);
export const startOnboarding = bindHumanResourcesCapability(
	startOnboardingInternal,
);
export const startPerformanceReview = bindHumanResourcesCapability(
	startPerformanceReviewInternal,
);
export const startSession = bindHumanResourcesCapability(startSessionInternal);
export const submitDelegatedAssessment = bindHumanResourcesCapability(
	submitDelegatedAssessmentInternal,
);
export const submitHeadcountPlan = bindHumanResourcesCapability(
	submitHeadcountPlanInternal,
);
export const submitLeaveRequest = bindHumanResourcesCapability(
	submitLeaveRequestInternal,
);
export const submitManagerAssessment = bindHumanResourcesCapability(
	submitManagerAssessmentInternal,
);
export const submitPerformanceGoal = bindHumanResourcesCapability(
	submitPerformanceGoalInternal,
);
export const submitRequisition = bindHumanResourcesCapability(
	submitRequisitionInternal,
);
export const submitSelfAssessment = bindHumanResourcesCapability(
	submitSelfAssessmentInternal,
);
export const submitTimesheet = bindHumanResourcesCapability(
	submitTimesheetInternal,
);
export const supersedeCompetencyAssessment = bindHumanResourcesCapability(
	supersedeCompetencyAssessmentInternal,
);
export const supersedeEmploymentContract = bindHumanResourcesCapability(
	supersedeEmploymentContractInternal,
);
export const supersedeHeadcountPlan = bindHumanResourcesCapability(
	supersedeHeadcountPlanInternal,
);
export const supersedeLeavePolicy = bindHumanResourcesCapability(
	supersedeLeavePolicyInternal,
);
export const supersedePolicyAcknowledgementRequirement =
	bindHumanResourcesCapability(
		supersedePolicyAcknowledgementRequirementInternal,
	);
export const supersedeSalaryBand = bindHumanResourcesCapability(
	supersedeSalaryBandInternal,
);
export const supersedeShift = bindHumanResourcesCapability(
	supersedeShiftInternal,
);
export const supersedeTimePolicy = bindHumanResourcesCapability(
	supersedeTimePolicyInternal,
);
export const supersedeTimesheet = bindHumanResourcesCapability(
	supersedeTimesheetInternal,
);
export const supersedeWorkCalendar = bindHumanResourcesCapability(
	supersedeWorkCalendarInternal,
);
export const suspendEmployment = bindHumanResourcesCapability(
	suspendEmploymentInternal,
);
export const suspendWorkEligibility = bindHumanResourcesCapability(
	suspendWorkEligibilityInternal,
);
export const terminateEmployment = bindHumanResourcesCapability(
	terminateEmploymentInternal,
);
export const transferAssignment = bindHumanResourcesCapability(
	transferAssignmentInternal,
);
export const updateBenefitPlan = bindHumanResourcesCapability(
	updateBenefitPlanInternal,
);
export const updateCandidateProfile = bindHumanResourcesCapability(
	updateCandidateProfileInternal,
);
export const updateCareerPlan = bindHumanResourcesCapability(
	updateCareerPlanInternal,
);
export const updateCompensationGrade = bindHumanResourcesCapability(
	updateCompensationGradeInternal,
);
export const updateCompetency = bindHumanResourcesCapability(
	updateCompetencyInternal,
);
export const updateCourse = bindHumanResourcesCapability(updateCourseInternal);
export const updateDepartment = bindHumanResourcesCapability(
	updateDepartmentInternal,
);
export const updateDocumentRequirement = bindHumanResourcesCapability(
	updateDocumentRequirementInternal,
);
export const updateEmployee = bindHumanResourcesCapability(
	updateEmployeeInternal,
);
export const updateEmployeeCaseClassification = bindHumanResourcesCapability(
	updateEmployeeCaseClassificationInternal,
);
export const updateEmployeeDocumentMetadata = bindHumanResourcesCapability(
	updateEmployeeDocumentMetadataInternal,
);
export const updateHeadcountPlan = bindHumanResourcesCapability(
	updateHeadcountPlanInternal,
);
export const updateHeadcountPlanLine = bindHumanResourcesCapability(
	updateHeadcountPlanLineInternal,
);
export const updateJob = bindHumanResourcesCapability(updateJobInternal);
export const updateLeavePolicy = bindHumanResourcesCapability(
	updateLeavePolicyInternal,
);
export const updatePerformanceCycle = bindHumanResourcesCapability(
	updatePerformanceCycleInternal,
);
export const updatePerformanceGoal = bindHumanResourcesCapability(
	updatePerformanceGoalInternal,
);
export const updatePersonContact = bindHumanResourcesCapability(
	updatePersonContactInternal,
);
export const updatePersonName = bindHumanResourcesCapability(
	updatePersonNameInternal,
);
export const updatePersonPreferredName = bindHumanResourcesCapability(
	updatePersonPreferredNameInternal,
);
export const updatePosition = bindHumanResourcesCapability(
	updatePositionInternal,
);
export const updateShift = bindHumanResourcesCapability(updateShiftInternal);
export const updateSuccessionPlan = bindHumanResourcesCapability(
	updateSuccessionPlanInternal,
);
export const updateTalentPool = bindHumanResourcesCapability(
	updateTalentPoolInternal,
);
export const updateTalentProfile = bindHumanResourcesCapability(
	updateTalentProfileInternal,
);
export const updateTimesheetEntry = bindHumanResourcesCapability(
	updateTimesheetEntryInternal,
);
export const updateWorkCalendar = bindHumanResourcesCapability(
	updateWorkCalendarInternal,
);
export const verifyEmployeeDocument = bindHumanResourcesCapability(
	verifyEmployeeDocumentInternal,
);
export const verifyOvertimeRequest = bindHumanResourcesCapability(
	verifyOvertimeRequestInternal,
);
export const verifyWorkEligibility = bindHumanResourcesCapability(
	verifyWorkEligibilityInternal,
);
export const voidAttendanceEvent = bindHumanResourcesCapability(
	voidAttendanceEventInternal,
);
export const waiveAssignment = bindHumanResourcesCapability(
	waiveAssignmentInternal,
);
export const waiveBenefit = bindHumanResourcesCapability(waiveBenefitInternal);
export const withdrawApplication = bindHumanResourcesCapability(
	withdrawApplicationInternal,
);
export const withdrawCandidateConsent = bindHumanResourcesCapability(
	withdrawCandidateConsentInternal,
);
export const withdrawLeaveRequest = bindHumanResourcesCapability(
	withdrawLeaveRequestInternal,
);
export const withdrawOffer = bindHumanResourcesCapability(
	withdrawOfferInternal,
);
