import {
	PAYROLL_ASSIGNMENT_COMMANDS,
	PAYROLL_ASSIGNMENT_QUERIES,
} from "../../features/employee-assignments/operation-registry";
import {
	PAYROLL_FINAL_SETTLEMENT_COMMANDS,
	PAYROLL_FINAL_SETTLEMENT_QUERIES,
} from "../../features/final-settlement/operation-registry";
import {
	PAYROLL_JOB_COMMANDS,
	PAYROLL_JOB_QUERIES,
} from "../../features/payroll-jobs/operation-registry";
import {
	PAYROLL_RUN_COMMANDS,
	PAYROLL_RUN_QUERIES,
} from "../../features/payroll-runs/operation-registry";
import {
	PAYROLL_SETUP_COMMANDS,
	PAYROLL_SETUP_QUERIES,
} from "../../features/payroll-setup/operation-registry";
import { PAYROLL_PAYSLIP_QUERIES } from "../../features/payslips/operation-registry";
import {
	PAYROLL_PRIVACY_COMMANDS,
	PAYROLL_PRIVACY_QUERIES,
} from "../../features/privacy/operation-registry";
import {
	PAYROLL_RECONCILIATION_COMMANDS,
	PAYROLL_RECONCILIATION_QUERIES,
} from "../../features/reconciliation/operation-registry";
import {
	PAYROLL_RETRO_COMMANDS,
	PAYROLL_RETRO_QUERIES,
} from "../../features/retro-pay/operation-registry";
import { PAYROLL_SETTLEMENT_INGRESS_COMMANDS } from "../../features/settlement-ingress/operation-registry";
import {
	PAYROLL_STATUTORY_FILING_COMMANDS,
	PAYROLL_STATUTORY_FILING_QUERIES,
} from "../../features/statutory-filings/operation-registry";
import {
	PAYROLL_VARIABLE_INPUT_COMMANDS,
	PAYROLL_VARIABLE_INPUT_QUERIES,
} from "../../features/variable-inputs/operation-registry";
import { PAYROLL_WORKFORCE_INGRESS_COMMANDS } from "../../features/workforce-ingress/operation-registry";
import type { PayrollPermission } from "../execution/permissions";
import { composePayrollOperationRegistries } from "./define-registry";

// Fail-closed cross-feature validation (duplicate ids/public names throw).
composePayrollOperationRegistries(
	PAYROLL_SETUP_COMMANDS,
	PAYROLL_ASSIGNMENT_COMMANDS,
	PAYROLL_VARIABLE_INPUT_COMMANDS,
	PAYROLL_RUN_COMMANDS,
	PAYROLL_RECONCILIATION_COMMANDS,
	PAYROLL_SETTLEMENT_INGRESS_COMMANDS,
	PAYROLL_PRIVACY_COMMANDS,
	PAYROLL_JOB_COMMANDS,
	PAYROLL_RETRO_COMMANDS,
	PAYROLL_FINAL_SETTLEMENT_COMMANDS,
	PAYROLL_STATUTORY_FILING_COMMANDS,
	PAYROLL_WORKFORCE_INGRESS_COMMANDS,
	PAYROLL_SETUP_QUERIES,
	PAYROLL_ASSIGNMENT_QUERIES,
	PAYROLL_VARIABLE_INPUT_QUERIES,
	PAYROLL_RUN_QUERIES,
	PAYROLL_PAYSLIP_QUERIES,
	PAYROLL_PRIVACY_QUERIES,
	PAYROLL_JOB_QUERIES,
	PAYROLL_RECONCILIATION_QUERIES,
	PAYROLL_RETRO_QUERIES,
	PAYROLL_FINAL_SETTLEMENT_QUERIES,
	PAYROLL_STATUTORY_FILING_QUERIES,
);

/** Canonical Payroll operation identity, composed from feature registries. */
export const PAYROLL_OPERATION_DEFINITIONS = {
	...PAYROLL_SETUP_COMMANDS,
	...PAYROLL_ASSIGNMENT_COMMANDS,
	...PAYROLL_VARIABLE_INPUT_COMMANDS,
	...PAYROLL_RUN_COMMANDS,
	...PAYROLL_RECONCILIATION_COMMANDS,
	...PAYROLL_SETTLEMENT_INGRESS_COMMANDS,
	...PAYROLL_PRIVACY_COMMANDS,
	...PAYROLL_JOB_COMMANDS,
	...PAYROLL_RETRO_COMMANDS,
	...PAYROLL_FINAL_SETTLEMENT_COMMANDS,
	...PAYROLL_STATUTORY_FILING_COMMANDS,
	...PAYROLL_WORKFORCE_INGRESS_COMMANDS,
	...PAYROLL_SETUP_QUERIES,
	...PAYROLL_ASSIGNMENT_QUERIES,
	...PAYROLL_VARIABLE_INPUT_QUERIES,
	...PAYROLL_RUN_QUERIES,
	...PAYROLL_PAYSLIP_QUERIES,
	...PAYROLL_PRIVACY_QUERIES,
	...PAYROLL_JOB_QUERIES,
	...PAYROLL_RECONCILIATION_QUERIES,
	...PAYROLL_RETRO_QUERIES,
	...PAYROLL_FINAL_SETTLEMENT_QUERIES,
	...PAYROLL_STATUTORY_FILING_QUERIES,
} as const;

type PayrollOperation =
	(typeof PAYROLL_OPERATION_DEFINITIONS)[keyof typeof PAYROLL_OPERATION_DEFINITIONS];
type PayrollCommandOperation = Extract<PayrollOperation, { kind: "command" }>;
type PayrollQueryOperation = Extract<PayrollOperation, { kind: "query" }>;

const operationDefinitions = Object.values(PAYROLL_OPERATION_DEFINITIONS);
for (const definition of operationDefinitions) {
	Object.freeze(definition);
}
Object.freeze(PAYROLL_OPERATION_DEFINITIONS);

const operationIds = new Set(operationDefinitions.map(({ id }) => id));
if (operationIds.size !== operationDefinitions.length) {
	throw new Error("Payroll operation IDs must be unique");
}

const commandDefinitions = operationDefinitions.filter(
	(definition): definition is PayrollCommandOperation =>
		definition.kind === "command",
);
const queryDefinitions = operationDefinitions.filter(
	(definition): definition is PayrollQueryOperation =>
		definition.kind === "query",
);

function projectAuthorization<
	TDefinition extends {
		readonly id: string;
		readonly permission: PayrollPermission;
	},
>(definitions: readonly TDefinition[]) {
	return Object.freeze(
		Object.fromEntries(
			definitions.map(({ id, permission }) => [id, permission]),
		),
	) as Readonly<Record<TDefinition["id"], PayrollPermission>>;
}

export type PayrollCommandId = PayrollCommandOperation["id"];
export type PayrollQueryId = PayrollQueryOperation["id"];

export const PAYROLL_COMMAND_IDS = Object.freeze(
	commandDefinitions.map(({ id }) => id),
);
export const PAYROLL_QUERY_IDS = Object.freeze(
	queryDefinitions.map(({ id }) => id),
);
export const PAYROLL_COMMAND_AUTHORIZATION =
	projectAuthorization(commandDefinitions);
export const PAYROLL_QUERY_AUTHORIZATION =
	projectAuthorization(queryDefinitions);

export const PAYROLL_COMMAND_SETUP_CALENDAR_CREATE =
	PAYROLL_OPERATION_DEFINITIONS.createCalendar.id;
export const PAYROLL_COMMAND_SETUP_CALENDAR_UPDATE =
	PAYROLL_OPERATION_DEFINITIONS.updateCalendar.id;
export const PAYROLL_COMMAND_SETUP_CALENDAR_ARCHIVE =
	PAYROLL_OPERATION_DEFINITIONS.archiveCalendar.id;
export const PAYROLL_COMMAND_SETUP_PAY_GROUP_CREATE =
	PAYROLL_OPERATION_DEFINITIONS.createPayGroup.id;
export const PAYROLL_COMMAND_SETUP_PAY_GROUP_UPDATE =
	PAYROLL_OPERATION_DEFINITIONS.updatePayGroup.id;
export const PAYROLL_COMMAND_SETUP_PAY_GROUP_ARCHIVE =
	PAYROLL_OPERATION_DEFINITIONS.archivePayGroup.id;
export const PAYROLL_COMMAND_SETUP_PERIOD_CREATE =
	PAYROLL_OPERATION_DEFINITIONS.createPeriod.id;
export const PAYROLL_COMMAND_SETUP_PERIOD_UPDATE =
	PAYROLL_OPERATION_DEFINITIONS.updatePeriod.id;
export const PAYROLL_COMMAND_SETUP_PERIOD_CLOSE =
	PAYROLL_OPERATION_DEFINITIONS.closePeriod.id;
export const PAYROLL_COMMAND_SETUP_PERIOD_LOCK_INPUTS =
	PAYROLL_OPERATION_DEFINITIONS.lockPeriodInputs.id;
export const PAYROLL_COMMAND_SETUP_EARNING_RULE_CREATE =
	PAYROLL_OPERATION_DEFINITIONS.createEarningRule.id;
export const PAYROLL_COMMAND_SETUP_EARNING_RULE_UPDATE =
	PAYROLL_OPERATION_DEFINITIONS.updateEarningRule.id;
export const PAYROLL_COMMAND_SETUP_EARNING_RULE_ARCHIVE =
	PAYROLL_OPERATION_DEFINITIONS.archiveEarningRule.id;
export const PAYROLL_COMMAND_SETUP_EARNING_RULE_SUPERSEDE =
	PAYROLL_OPERATION_DEFINITIONS.supersedeEarningRule.id;
export const PAYROLL_COMMAND_SETUP_DEDUCTION_RULE_CREATE =
	PAYROLL_OPERATION_DEFINITIONS.createDeductionRule.id;
export const PAYROLL_COMMAND_SETUP_DEDUCTION_RULE_UPDATE =
	PAYROLL_OPERATION_DEFINITIONS.updateDeductionRule.id;
export const PAYROLL_COMMAND_SETUP_DEDUCTION_RULE_ARCHIVE =
	PAYROLL_OPERATION_DEFINITIONS.archiveDeductionRule.id;
export const PAYROLL_COMMAND_SETUP_DEDUCTION_RULE_SUPERSEDE =
	PAYROLL_OPERATION_DEFINITIONS.supersedeDeductionRule.id;
export const PAYROLL_COMMAND_SETUP_STATUTORY_RULE_CREATE =
	PAYROLL_OPERATION_DEFINITIONS.createStatutoryRule.id;
export const PAYROLL_COMMAND_SETUP_STATUTORY_RULE_UPDATE =
	PAYROLL_OPERATION_DEFINITIONS.updateStatutoryRule.id;
export const PAYROLL_COMMAND_SETUP_STATUTORY_RULE_ARCHIVE =
	PAYROLL_OPERATION_DEFINITIONS.archiveStatutoryRule.id;
export const PAYROLL_COMMAND_SETUP_STATUTORY_RULE_SUPERSEDE =
	PAYROLL_OPERATION_DEFINITIONS.supersedeStatutoryRule.id;
export const PAYROLL_COMMAND_ASSIGNMENT_CREATE =
	PAYROLL_OPERATION_DEFINITIONS.createAssignment.id;
export const PAYROLL_COMMAND_ASSIGNMENT_RECURRING_EARNING_CREATE =
	PAYROLL_OPERATION_DEFINITIONS.createRecurringEarning.id;
export const PAYROLL_COMMAND_ASSIGNMENT_RECURRING_DEDUCTION_CREATE =
	PAYROLL_OPERATION_DEFINITIONS.createRecurringDeduction.id;
export const PAYROLL_COMMAND_INPUT_VARIABLE_CREATE =
	PAYROLL_OPERATION_DEFINITIONS.createVariableInput.id;
export const PAYROLL_COMMAND_RUN_CREATE =
	PAYROLL_OPERATION_DEFINITIONS.createRun.id;
export const PAYROLL_COMMAND_RUN_CALCULATE =
	PAYROLL_OPERATION_DEFINITIONS.calculateRun.id;
export const PAYROLL_COMMAND_RUN_FINALIZE =
	PAYROLL_OPERATION_DEFINITIONS.finalizeRun.id;
export const PAYROLL_COMMAND_RUN_REVERSE =
	PAYROLL_OPERATION_DEFINITIONS.reverseRun.id;
export const PAYROLL_COMMAND_RECONCILIATION_RECORD =
	PAYROLL_OPERATION_DEFINITIONS.recordReconciliation.id;
export const PAYROLL_COMMAND_RECONCILIATION_RESOLVE =
	PAYROLL_OPERATION_DEFINITIONS.resolveReconciliation.id;
export const PAYROLL_COMMAND_SETTLEMENT_PAYMENT_RECORD =
	PAYROLL_OPERATION_DEFINITIONS.recordPaymentSettlement.id;
export const PAYROLL_COMMAND_SETTLEMENT_POSTING_RECORD =
	PAYROLL_OPERATION_DEFINITIONS.recordPostingConfirmation.id;
export const PAYROLL_COMMAND_SETTLEMENT_DISCREPANCY_RESOLVE =
	PAYROLL_OPERATION_DEFINITIONS.resolveReconciliationDiscrepancy.id;
export const PAYROLL_COMMAND_WORKFORCE_INGEST =
	PAYROLL_OPERATION_DEFINITIONS.ingestApprovedPayrollHandoff.id;
export const PAYROLL_COMMAND_PRIVACY_RESTRICTION_PLACE =
	PAYROLL_OPERATION_DEFINITIONS.restrictPayrollSubject.id;
export const PAYROLL_COMMAND_PRIVACY_RESTRICTION_LIFT =
	PAYROLL_OPERATION_DEFINITIONS.liftPayrollRestriction.id;
export const PAYROLL_COMMAND_PRIVACY_RETENTION_RECORD =
	PAYROLL_OPERATION_DEFINITIONS.recordPayrollRetentionEvidence.id;
export const PAYROLL_COMMAND_PRIVACY_RETENTION_EXPIRE =
	PAYROLL_OPERATION_DEFINITIONS.expirePayrollRetention.id;
export const PAYROLL_COMMAND_JOB_CALCULATION_ENQUEUE =
	PAYROLL_OPERATION_DEFINITIONS.enqueuePayrollCalculationJob.id;
export const PAYROLL_COMMAND_JOB_WORK_CLAIM =
	PAYROLL_OPERATION_DEFINITIONS.claimDuePayrollJobWork.id;
export const PAYROLL_COMMAND_JOB_WORK_EXECUTE =
	PAYROLL_OPERATION_DEFINITIONS.executePayrollJobWork.id;
export const PAYROLL_COMMAND_JOB_DEAD_LETTER_REPLAY =
	PAYROLL_OPERATION_DEFINITIONS.replayPayrollDeadLetter.id;

export const PAYROLL_COMMAND_RETRO_ITEM_QUEUE =
	PAYROLL_OPERATION_DEFINITIONS.queueRetroItem.id;
export const PAYROLL_COMMAND_RETRO_DIFFERENCE_CALCULATE =
	PAYROLL_OPERATION_DEFINITIONS.calculateRetroDifference.id;
export const PAYROLL_COMMAND_RETRO_PERIOD_APPLY =
	PAYROLL_OPERATION_DEFINITIONS.applyRetroToPeriod.id;
export const PAYROLL_COMMAND_FINAL_SETTLEMENT_INITIATE =
	PAYROLL_OPERATION_DEFINITIONS.initiateFinalSettlement.id;
export const PAYROLL_COMMAND_FINAL_SETTLEMENT_CALCULATE =
	PAYROLL_OPERATION_DEFINITIONS.calculateFinalSettlement.id;
export const PAYROLL_COMMAND_FINAL_SETTLEMENT_FINALIZE =
	PAYROLL_OPERATION_DEFINITIONS.finalizeFinalSettlement.id;
export const PAYROLL_QUERY_FINAL_SETTLEMENT_STATEMENT_READ_OWN =
	PAYROLL_OPERATION_DEFINITIONS.readOwnFinalSettlementStatement.id;
export const PAYROLL_QUERY_FINAL_SETTLEMENT_STATEMENT_READ_ALL =
	PAYROLL_OPERATION_DEFINITIONS.readAllFinalSettlementStatements.id;
export const PAYROLL_COMMAND_STATUTORY_FILING_GENERATE =
	PAYROLL_OPERATION_DEFINITIONS.generateStatutoryFiling.id;
export const PAYROLL_COMMAND_STATUTORY_FILING_ANNUAL_GENERATE =
	PAYROLL_OPERATION_DEFINITIONS.generateAnnualStatement.id;
export const PAYROLL_COMMAND_STATUTORY_FILING_EVIDENCE_SEAL =
	PAYROLL_OPERATION_DEFINITIONS.sealFilingEvidence.id;
export const PAYROLL_QUERY_STATUTORY_FILING_OBLIGATION_LIST =
	PAYROLL_OPERATION_DEFINITIONS.listFilingObligations.id;

export const PAYROLL_QUERY_SETUP_CALENDAR_GET =
	PAYROLL_OPERATION_DEFINITIONS.getCalendar.id;
export const PAYROLL_QUERY_SETUP_CALENDAR_LIST =
	PAYROLL_OPERATION_DEFINITIONS.listCalendars.id;
export const PAYROLL_QUERY_SETUP_PAY_GROUP_GET =
	PAYROLL_OPERATION_DEFINITIONS.getPayGroup.id;
export const PAYROLL_QUERY_SETUP_PAY_GROUP_LIST =
	PAYROLL_OPERATION_DEFINITIONS.listPayGroups.id;
export const PAYROLL_QUERY_SETUP_PERIOD_GET =
	PAYROLL_OPERATION_DEFINITIONS.getPeriod.id;
export const PAYROLL_QUERY_SETUP_PERIOD_LIST =
	PAYROLL_OPERATION_DEFINITIONS.listPeriods.id;
export const PAYROLL_QUERY_SETUP_EARNING_RULE_GET =
	PAYROLL_OPERATION_DEFINITIONS.getEarningRule.id;
export const PAYROLL_QUERY_SETUP_DEDUCTION_RULE_GET =
	PAYROLL_OPERATION_DEFINITIONS.getDeductionRule.id;
export const PAYROLL_QUERY_SETUP_STATUTORY_RULE_GET =
	PAYROLL_OPERATION_DEFINITIONS.getStatutoryRule.id;
export const PAYROLL_QUERY_ASSIGNMENT_GET =
	PAYROLL_OPERATION_DEFINITIONS.getAssignment.id;
export const PAYROLL_QUERY_INPUT_VARIABLE_GET =
	PAYROLL_OPERATION_DEFINITIONS.getVariableInput.id;
export const PAYROLL_QUERY_RUN_GET = PAYROLL_OPERATION_DEFINITIONS.getRun.id;
export const PAYROLL_QUERY_PAYSLIP_READ_OWN =
	PAYROLL_OPERATION_DEFINITIONS.readOwnPayslip.id;
export const PAYROLL_QUERY_PAYSLIP_READ_ALL =
	PAYROLL_OPERATION_DEFINITIONS.readAllPayslips.id;
export const PAYROLL_QUERY_RECONCILIATION_LIST =
	PAYROLL_OPERATION_DEFINITIONS.listReconciliations.id;
export const PAYROLL_QUERY_PRIVACY_FIELDS_PROJECT =
	PAYROLL_OPERATION_DEFINITIONS.projectPayrollFields.id;
export const PAYROLL_QUERY_PRIVACY_SUBJECT_ACCESS =
	PAYROLL_OPERATION_DEFINITIONS.respondToPayrollSubjectAccess.id;
export const PAYROLL_QUERY_JOB_GET =
	PAYROLL_OPERATION_DEFINITIONS.getPayrollJob.id;
export const PAYROLL_QUERY_JOB_DEAD_LETTER_LIST =
	PAYROLL_OPERATION_DEFINITIONS.listPayrollDeadLetters.id;
export const PAYROLL_QUERY_RETRO_ITEM_LIST =
	PAYROLL_OPERATION_DEFINITIONS.listRetroItems.id;
