/**
 * Domain failure reasons mapped onto `@afenda/errors` Result codes.
 * Do not expand `@afenda/errors` ERROR_CODES. Use `details.errorCode` for the
 * stable master-data taxonomy and `details.reason` for legacy/internal detail.
 */
export const MASTER_DATA_ERROR_CODES = [
	"MASTER_DATA_INVALID_INPUT",
	"MASTER_DATA_NOT_FOUND",
	"MASTER_DATA_ALREADY_EXISTS",
	"MASTER_DATA_VERSION_CONFLICT",
	"MASTER_DATA_INVALID_STATE",
	"MASTER_DATA_CODE_CONFLICT",
	"MASTER_DATA_EXTERNAL_ID_CONFLICT",
	"MASTER_DATA_CROSS_ORGANIZATION_ACCESS",
	"MASTER_DATA_PERMISSION_DENIED",
	"MASTER_DATA_REFERENCE_NOT_FOUND",
	"MASTER_DATA_DEPENDENCY_EXISTS",
	"MASTER_DATA_DUPLICATE_CANDIDATE",
	"MASTER_DATA_CHANGE_REQUEST_REQUIRED",
	"MASTER_DATA_IMPORT_NOT_APPROVED",
	"MASTER_DATA_IMPORT_ROW_INVALID",
	"MASTER_DATA_IDEMPOTENCY_CONFLICT",
	"MASTER_DATA_MERGE_NOT_ALLOWED",
] as const;

export type MasterDataErrorCode = (typeof MASTER_DATA_ERROR_CODES)[number];

export const MASTER_REASONS = [
	"MASTER_NOT_FOUND",
	"MASTER_CODE_CONFLICT",
	"MASTER_EXTERNAL_ID_CONFLICT",
	"MASTER_RELATIONSHIP_CYCLE",
	"MASTER_DUPLICATE",
	"MASTER_VERSION_CONFLICT",
	"MASTER_INVALID_STATE",
	"MASTER_FINAL_ACTIVE_ROLE",
	"MASTER_DEPENDENCY_BLOCKED",
	"MASTER_CROSS_ORG_REFERENCE",
	"MASTER_INVALID_UOM_CONVERSION",
	"MASTER_INVALID_BARCODE",
	"MASTER_VALIDATION_FAILED",
	"MASTER_VALIDITY_OVERLAP",
	"MASTER_CHANGE_REQUEST_REQUIRED",
	"MASTER_CHANGE_REQUEST_INVALID",
	"MASTER_MAKER_CHECKER_VIOLATION",
	"MASTER_PERMISSION_DENIED",
	"MASTER_DEPENDENCY_UNAVAILABLE",
	"MASTER_IMPORT_NOT_APPROVED",
	"MASTER_IDEMPOTENT_REPLAY",
	"MASTER_IMPORT_IDEMPOTENT_REPLAY",
	"MASTER_IDEMPOTENCY_CONFLICT",
	"MASTER_EFFECTIVE_RANGE_OVERLAP",
	"MASTER_PERSISTENCE_FAILURE",
	"MASTER_DIMENSION_AMBIGUOUS",
	"MASTER_DIMENSION_NOT_EFFECTIVE",
] as const;

export type MasterReason = (typeof MASTER_REASONS)[number];

export const MASTER_REASON_TO_ERROR_CODE = {
	MASTER_NOT_FOUND: "MASTER_DATA_NOT_FOUND",
	MASTER_CODE_CONFLICT: "MASTER_DATA_CODE_CONFLICT",
	MASTER_EXTERNAL_ID_CONFLICT: "MASTER_DATA_EXTERNAL_ID_CONFLICT",
	MASTER_RELATIONSHIP_CYCLE: "MASTER_DATA_MERGE_NOT_ALLOWED",
	MASTER_DUPLICATE: "MASTER_DATA_DUPLICATE_CANDIDATE",
	MASTER_VERSION_CONFLICT: "MASTER_DATA_VERSION_CONFLICT",
	MASTER_INVALID_STATE: "MASTER_DATA_INVALID_STATE",
	MASTER_FINAL_ACTIVE_ROLE: "MASTER_DATA_INVALID_STATE",
	MASTER_DEPENDENCY_BLOCKED: "MASTER_DATA_DEPENDENCY_EXISTS",
	MASTER_CROSS_ORG_REFERENCE: "MASTER_DATA_CROSS_ORGANIZATION_ACCESS",
	MASTER_INVALID_UOM_CONVERSION: "MASTER_DATA_INVALID_INPUT",
	MASTER_INVALID_BARCODE: "MASTER_DATA_INVALID_INPUT",
	MASTER_VALIDATION_FAILED: "MASTER_DATA_INVALID_INPUT",
	MASTER_VALIDITY_OVERLAP: "MASTER_DATA_INVALID_STATE",
	MASTER_CHANGE_REQUEST_REQUIRED: "MASTER_DATA_CHANGE_REQUEST_REQUIRED",
	MASTER_CHANGE_REQUEST_INVALID: "MASTER_DATA_INVALID_STATE",
	MASTER_MAKER_CHECKER_VIOLATION: "MASTER_DATA_PERMISSION_DENIED",
	MASTER_PERMISSION_DENIED: "MASTER_DATA_PERMISSION_DENIED",
	MASTER_DEPENDENCY_UNAVAILABLE: "MASTER_DATA_INVALID_STATE",
	MASTER_IMPORT_NOT_APPROVED: "MASTER_DATA_IMPORT_NOT_APPROVED",
	MASTER_IDEMPOTENT_REPLAY: "MASTER_DATA_ALREADY_EXISTS",
	MASTER_IMPORT_IDEMPOTENT_REPLAY: "MASTER_DATA_ALREADY_EXISTS",
	MASTER_IDEMPOTENCY_CONFLICT: "MASTER_DATA_IDEMPOTENCY_CONFLICT",
	MASTER_EFFECTIVE_RANGE_OVERLAP: "MASTER_DATA_INVALID_STATE",
	MASTER_PERSISTENCE_FAILURE: "MASTER_DATA_INVALID_STATE",
	MASTER_DIMENSION_AMBIGUOUS: "MASTER_DATA_INVALID_STATE",
	MASTER_DIMENSION_NOT_EFFECTIVE: "MASTER_DATA_INVALID_STATE",
} as const satisfies Record<MasterReason, MasterDataErrorCode>;

export function masterDataErrorCodeForReason(
	reason: MasterReason,
): MasterDataErrorCode {
	return MASTER_REASON_TO_ERROR_CODE[reason];
}

export function masterDataErrorCodeForFailureDetails(
	details: MasterFailureDetails,
): MasterDataErrorCode {
	if (details.errorCode !== undefined) {
		return details.errorCode;
	}
	if (details.platformReferenceReason === "MASTER_DATA_REFERENCE_NOT_FOUND") {
		return "MASTER_DATA_REFERENCE_NOT_FOUND";
	}
	if (details.governanceCode === "MASTER_DATA_IMPORT_VALIDATION_FAILED") {
		return "MASTER_DATA_IMPORT_ROW_INVALID";
	}
	if (
		details.governanceCode === "MASTER_DATA_GOVERNANCE_MERGE_NOT_AUTHORIZED"
	) {
		return "MASTER_DATA_MERGE_NOT_ALLOWED";
	}
	return masterDataErrorCodeForReason(details.reason);
}

export type MasterFailureDetails = {
	reason: MasterReason;
	errorCode?: MasterDataErrorCode;
	fieldErrors?: Record<string, string[] | undefined>;
	[key: string]: unknown;
};
