import "server-only";

export { corporateAdministrationModuleManifest } from "./composition/module.manifest";
export * from "./features/company/index";
export type * from "./features/establishments/index";
export {
	activateLegalEstablishment,
	activateLegalEstablishmentInputSchema,
	assertNoRegisteredAddressOverlap,
	closeLegalEstablishment,
	closeLegalEstablishmentInputSchema,
	endPremise,
	endPremiseInputSchema,
	establishmentStatusHistorySchema,
	findRegisteredAddressAsOf,
	findRegisteredAddressAsOfInputSchema,
	getLegalEstablishment,
	getLegalEstablishmentInputSchema,
	legalEstablishmentSchema,
	legalEstablishmentStatusSchema,
	legalEstablishmentTypeSchema,
	listLegalEstablishmentsAsOf,
	listLegalEstablishmentsAsOfInputSchema,
	listPremisesAsOf,
	listPremisesAsOfInputSchema,
	matchesEstablishmentAsOf,
	normalizeEstablishmentRegistrationIdentifier,
	premiseSchema,
	premiseTypeSchema,
	registeredAddressSchema,
	registeredAddressTypeSchema,
	registerLegalEstablishment,
	registerLegalEstablishmentInputSchema,
	registerPremise,
	registerPremiseInputSchema,
	resolveEstablishmentStatusAsOf,
	setRegisteredAddress,
	setRegisteredAddressInputSchema,
	statutoryAddressSnapshotSchema,
	suspendLegalEstablishment,
	suspendLegalEstablishmentInputSchema,
	updateLegalEstablishment,
	updateLegalEstablishmentInputSchema,
	validateEstablishmentChronology,
	validateEstablishmentStatusTransition,
	visibleAtKnownTime,
} from "./features/establishments/index";
export type * from "./features/governance/index";
export {
	amendGovernanceBody,
	amendGovernanceBodyInputSchema,
	appointGovernanceMember,
	appointGovernanceMemberInputSchema,
	assertNoGovernanceMembershipConflict,
	changeGovernanceMembership,
	changeGovernanceMembershipInputSchema,
	createGovernanceBody,
	createGovernanceBodyInputSchema,
	endGovernanceMembership,
	endGovernanceMembershipInputSchema,
	getGovernanceBody,
	getGovernanceBodyInputSchema,
	governanceBodyMatchesAsOf,
	governanceBodySchema,
	governanceBodyStatusSchema,
	governanceBodyTypeSchema,
	governanceMemberKindSchema,
	governanceMembershipMatchesAsOf,
	governanceMembershipRoleSchema,
	governanceMembershipSchema,
	governanceMembershipStatusSchema,
	governanceVotingEntitlementSchema,
	listGovernanceBodiesAsOf,
	listGovernanceBodiesAsOfInputSchema,
	listGovernanceMembershipsAsOf,
	listGovernanceMembershipsAsOfInputSchema,
	normalizeGovernanceBodyCode,
	retireGovernanceBody,
	retireGovernanceBodyInputSchema,
	validateMembershipWithinBody,
} from "./features/governance/index";
export type * from "./features/meetings/index";
export {
	adjournMeeting,
	adjournMeetingInputSchema,
	calculateMeetingQuorum,
	canCloseMeeting,
	closeMeeting,
	closeMeetingInputSchema,
	datePart,
	getGovernanceMeeting,
	getGovernanceMeetingInputSchema,
	getMeetingAttendance,
	getMeetingAttendanceInputSchema,
	getMeetingQuorumStatus,
	getMeetingQuorumStatusInputSchema,
	governanceMeetingListPageSchema,
	governanceMeetingProcedureTypeSchema,
	governanceMeetingSchema,
	governanceMeetingStatusSchema,
	hasNoticeSatisfied,
	isNoticeTimely,
	issueMeetingNotice,
	issueMeetingNoticeInputSchema,
	listGovernanceMeetings,
	listGovernanceMeetingsInputSchema,
	meetingNoticeSchema,
	meetingNoticeStatusSchema,
	meetingParticipantAttendanceStatusSchema,
	meetingParticipantSchema,
	meetingQuorumResultSchema,
	openMeeting,
	openMeetingInputSchema,
	quorumRuleSnapshotSchema,
	recordMeetingParticipant,
	recordMeetingParticipantInputSchema,
	recordNoticeDelivery,
	recordNoticeDeliveryInputSchema,
	recordQuorum,
	recordQuorumInputSchema,
	scheduleGovernanceMeeting,
	scheduleGovernanceMeetingInputSchema,
	waiveNotice,
	waiveNoticeInputSchema,
} from "./features/meetings/index";
export type * from "./features/officers/index";
export {
	amendOfficerAppointment,
	amendOfficerAppointmentInputSchema,
	appointOfficer,
	appointOfficerInputSchema,
	assertAppointmentWithinOffice,
	assertNoOfficerAppointmentConflict,
	assertOfficerQualificationCurrent,
	calculateOfficerEligibilityAsOf,
	calculateOfficerVacancyStatus,
	conflictDisclosureListPageSchema,
	conflictDisclosureSchema,
	conflictDisclosureStatusSchema,
	conflictMatterTypeSchema,
	defineStatutoryOffice,
	defineStatutoryOfficeInputSchema,
	discloseConflict,
	discloseConflictInputSchema,
	endOfficerDisqualification,
	endOfficerDisqualificationInputSchema,
	getOfficerAppointment,
	getOfficerAppointmentInputSchema,
	getOfficerEligibilityAsOf,
	getOfficerEligibilityAsOfInputSchema,
	getOfficerVacancyStatus,
	getOfficerVacancyStatusInputSchema,
	listActiveDisqualifications,
	listActiveDisqualificationsInputSchema,
	listConflictsForMatter,
	listConflictsForMatterInputSchema,
	listExpiringDeclarations,
	listExpiringDeclarationsInputSchema,
	listOfficersAsOf,
	listOfficersAsOfInputSchema,
	listRequiredStatutoryOffices,
	listRequiredStatutoryOfficesInputSchema,
	officerAppointingAuthorityTypeSchema,
	officerAppointmentMatchesAsOf,
	officerAppointmentMethodSchema,
	officerAppointmentSchema,
	officerAppointmentStatusSchema,
	officerDeclarationSchema,
	officerDeclarationStatusSchema,
	officerDeclarationTypeSchema,
	officerDisqualificationMatchesAsOf,
	officerDisqualificationSchema,
	officerDisqualificationStatusSchema,
	officerQualificationMatchesAsOf,
	officerQualificationSchema,
	officerQualificationVerificationStatusSchema,
	recordOfficerDeclaration,
	recordOfficerDeclarationInputSchema,
	recordOfficerDisqualification,
	recordOfficerDisqualificationInputSchema,
	recordOfficerQualification,
	recordOfficerQualificationInputSchema,
	recordRecusal,
	recordRecusalInputSchema,
	removeOfficer,
	removeOfficerInputSchema,
	resignOfficer,
	resignOfficerInputSchema,
	statutoryOfficeMatchesAsOf,
	statutoryOfficeSchema,
	statutoryOfficeStatusSchema,
	supersedeOfficerDeclaration,
	supersedeOfficerDeclarationInputSchema,
} from "./features/officers/index";
export type * from "./features/resolutions/index";
export {
	adoptResolution,
	adoptResolutionInputSchema,
	assignResolutionAction,
	assignResolutionActionInputSchema,
	calculateResolutionExecutionStatus,
	calculateVoteOutcome,
	completeResolutionAction,
	completeResolutionActionInputSchema,
	getResolution,
	getResolutionExecutionStatus,
	getResolutionExecutionStatusInputSchema,
	getResolutionInputSchema,
	isResolutionActionOverdue,
	listOverdueResolutionActions,
	listOverdueResolutionActionsInputSchema,
	listResolutionsAsOf,
	listResolutionsAsOfInputSchema,
	meetingVoteSchema,
	recordMeetingVote,
	recordMeetingVoteInputSchema,
	recordMinutesDocument,
	recordMinutesDocumentInputSchema,
	recordWrittenResolution,
	recordWrittenResolutionInputSchema,
	rejectResolution,
	rejectResolutionInputSchema,
	requiredVotesForThreshold,
	resolutionActionSchema,
	resolutionActionStatusSchema,
	resolutionApprovalBasisSchema,
	resolutionMatchesAsOf,
	resolutionSchema,
	resolutionStatusSchema,
	supersedeResolution,
	supersedeResolutionInputSchema,
	voteOutcomeSchema,
	voteThresholdTypeSchema,
} from "./features/resolutions/index";
export type {
	CorporateAdministrationApprovalDecision,
	CorporateAdministrationApprovalDecisionPort,
	CorporateAdministrationAuthorizationContext,
	CorporateAdministrationAuthorizationInput,
} from "./kernel/authorization/authorization";
export { corporateAdministrationPermissionFor } from "./kernel/authorization/authorization";
export type { CorporateAdministrationPermission } from "./kernel/authorization/permissions";
export { CORPORATE_ADMINISTRATION_PERMISSION_CODES } from "./kernel/authorization/permissions";
export type {
	CausationId,
	CommandFingerprint,
	CorporateAdministrationEventId,
	CorrelationId,
	IdempotencyKey,
	IdempotencyReservationToken,
	OrganizationId,
	UserId,
} from "./kernel/brands";
export {
	causationIdSchema,
	commandFingerprintSchema,
	companyLegalFormHistoryIdSchema,
	companyNameIdSchema,
	correlationIdSchema,
	eventIdSchema,
	governanceBodyIdSchema,
	governanceMembershipIdSchema,
	idempotencyKeySchema,
	idempotencyReservationTokenSchema,
	meetingVoteIdSchema,
	officerAppointmentIdSchema,
	officerQualificationIdSchema,
	organizationIdSchema,
	resolutionActionIdSchema,
	resolutionIdSchema,
	statutoryOfficeIdSchema,
	userIdSchema,
} from "./kernel/brands";
export type { CanonicalJsonValue } from "./kernel/canonical-json";
export { createCanonicalFingerprint } from "./kernel/canonical-json";
export type { CanonicalDate, CanonicalInstant } from "./kernel/dates";
export {
	canonicalDateSchema,
	canonicalInstantSchema,
	compareCanonicalDates,
	isCanonicalDate,
	toCanonicalInstant,
} from "./kernel/dates";
export type { CanonicalDecimal } from "./kernel/decimals";
export {
	canonicalDecimalSchema,
	decimalInputSchema,
	normalizeDecimalString,
} from "./kernel/decimals";
export type { EffectiveRange } from "./kernel/effective-range";
export {
	effectiveRangeContainsRange,
	effectiveRangeEndsBeforeOrAt,
	effectiveRangeSchema,
	effectiveRangeStartsAfter,
	effectiveRangesOverlap,
	isDateInEffectiveRange,
	isOpenEffectiveRange,
} from "./kernel/effective-range";
export type {
	CorporateAdministrationDomainEventEnvelope,
	CorporateAdministrationPendingEvent,
} from "./kernel/emissions/domain-events";
export { createCorporateAdministrationDomainEventEnvelope } from "./kernel/emissions/domain-events";
export type {
	CorporateAdministrationEventType,
	CreateCorporateAdministrationEventTypeInput,
} from "./kernel/emissions/event-types";
export {
	CORPORATE_ADMINISTRATION_EVENT_TYPES,
	corporateAdministrationEventTypeSchema,
	createCorporateAdministrationEventType,
} from "./kernel/emissions/event-types";
export type { CorporateAdministrationMutationTable } from "./kernel/emissions/mutation-tables";
export { CORPORATE_ADMINISTRATION_MUTATION_TABLES } from "./kernel/emissions/mutation-tables";
export type {
	CorporateAdministrationCommandFingerprintEnvelope,
	CorporateAdministrationCommandIdentity,
} from "./kernel/execution/command-identity";
export { createCorporateAdministrationCommandFingerprint } from "./kernel/execution/command-identity";
export type {
	CorporateAdministrationApprovalCommandOptions,
	CorporateAdministrationCommandOptions,
	CorporateAdministrationExecutionContext,
	CorporateAdministrationPaginatedQueryOptions,
	CorporateAdministrationQueryOptions,
} from "./kernel/execution/command-options";
export type {
	CorporateAdministrationErrorCode,
	CorporateAdministrationFailureDetails,
	CorporateAdministrationFailureMetadata,
} from "./kernel/execution/error-codes";
export {
	CORPORATE_ADMINISTRATION_ERROR_CODES,
	CORPORATE_ADMINISTRATION_RESULT_CODE_BY_REASON,
	corporateAdministrationErrorCodeSchema,
	corporateAdministrationErrorDetails,
	corporateAdministrationFailureDetailsSchema,
	corporateAdministrationFailureMetadataSchema,
	corporateAdministrationResultCode,
} from "./kernel/execution/error-codes";
export type {
	CorporateAdministrationIdempotencyBeginInput,
	CorporateAdministrationIdempotencyBeginOutcome,
	CorporateAdministrationIdempotencyCompletionInput,
	CorporateAdministrationIdempotencyPort,
	CorporateAdministrationIdempotencyReleaseInput,
	CorporateAdministrationIdempotencyScope,
} from "./kernel/execution/idempotency";
export type {
	ActivityClassificationResolution,
	ClockPort,
	CompatibilityResolution,
	CorporateAdministrationAuditFactInput,
	CorporateAdministrationAuditFactPort,
	CorporateAdministrationAuditOperationType,
	CorporateAdministrationAuditOutcome,
	CorporateAdministrationObservabilityPort,
	CorporateAdministrationOperationObservation,
	CorporateAdministrationOutboxPort,
	CorporateAdministrationRuntimePorts,
	CorporateAdministrationSafeAuditMetadataValue,
	CorporateAdministrationTransactionContext,
	CorporateAdministrationTransactionOutcome,
	CorporateAdministrationTransactionPort,
	CorporateAdministrationTransactionStatement,
	DocumentObjectPort,
	IdentifierAuthorityResolution,
	LegalFormReferenceResolution,
	MasterDataReconciliationPort,
	PartyReference,
	PartyReferencePort,
	ReferenceDataPort,
	ReferenceResolution,
	StatutoryNameReconciliationFact,
	TaxRegistrationReadModel,
	TaxRegistrationReadPort,
} from "./kernel/execution/ports";
export {
	CORPORATE_ADMINISTRATION_AUDIT_OPERATION_TYPES,
	CORPORATE_ADMINISTRATION_AUDIT_OUTCOMES,
	commitCorporateAdministrationTransaction,
	corporateAdministrationAuditFactInputSchema,
	corporateAdministrationSafeAuditMetadataSchema,
	createCorporateAdministrationRuntime,
	rollbackCorporateAdministrationTransaction,
} from "./kernel/execution/ports";
export type {
	NormalizedCode,
	NormalizedCodeValue,
} from "./kernel/normalization";
export {
	MAX_CORPORATE_ADMINISTRATION_CODE_LENGTH,
	normalizeCorporateAdministrationCode,
	normalizedCodeSchema,
} from "./kernel/normalization";
export type {
	CorporateAdministrationCommandId,
	CorporateAdministrationQueryId,
} from "./kernel/operations/module-ids";
export {
	CORPORATE_ADMINISTRATION_COMMAND_IDS,
	CORPORATE_ADMINISTRATION_MODULE_ID,
	CORPORATE_ADMINISTRATION_PACKAGE_NAME,
	CORPORATE_ADMINISTRATION_QUERY_IDS,
} from "./kernel/operations/module-ids";
export type {
	CursorPage,
	CursorPagination,
	OpaqueCursor,
} from "./kernel/pagination";
export {
	cursorPaginationSchema,
	DEFAULT_CURSOR_PAGE_SIZE,
	MAX_CURSOR_PAGE_SIZE,
	MAX_OPAQUE_CURSOR_LENGTH,
	opaqueCursorSchema,
} from "./kernel/pagination";
export { parseCorporateAdministrationInput } from "./kernel/validation/parse-input";
