import "server-only";

export {
	type CorporateAdministrationAuthorizationPort,
	requireCaCommandPermission,
	requireCaQueryPermission,
} from "./authorization";
export type { CorporateAdministrationCommandOptions } from "./command-options";
export {
	createCorporateDocument,
	createFilingObligation,
	createFilingSubmission,
	getCorporateDocument,
	getFilingObligation,
	getFilingSubmission,
	listCorporateDocuments,
	listFilingObligations,
	listFilingSubmissions,
} from "./documents-filings";
export {
	appointGovernanceMembership,
	appointOfficer,
	createGovernanceBody,
	getAuthorityMandate,
	getCompanyPremise,
	getGovernanceBody,
	getGovernanceMeeting,
	getGovernanceMembership,
	getOfficerAppointment,
	getResolution,
	grantAuthorityMandate,
	listAuthorityMandates,
	listCompanyPremises,
	listGovernanceBodies,
	listGovernanceMeetings,
	listGovernanceMemberships,
	listOfficerAppointments,
	listResolutions,
	recordGovernanceMeeting,
	recordResolution,
	registerCompanyPremise,
} from "./governance";
export {
	getAuthorityMandateAsOf,
	getCompanyPremiseAsOf,
	getGovernanceBodyAsOf,
	getGovernanceMeetingAsOf,
	getGovernanceMembershipAsOf,
	getOfficerAppointmentAsOf,
	getResolutionAsOf,
} from "./governance-as-of";
export {
	amendAuthorityMandate,
	amendOfficer,
	approveResolution,
	closeGovernanceMeeting,
	endGovernanceMembership,
	endOfficer,
	retireCompanyPremise,
	retireGovernanceBody,
	revokeAuthorityMandate,
	revokeResolution,
	updateCompanyPremise,
	updateGovernanceBody,
} from "./governance-lifecycle";
export {
	activateLegalCompany,
	addCompanyIdentifier,
	addCompanyName,
	archiveLegalCompany,
	createLegalCompany,
	dissolveLegalCompany,
	endCompanyName,
	getLegalCompany,
	getLegalCompanyAsOf,
	listCompanyIdentifiers,
	listCompanyNames,
	listCompanyStatusHistory,
	listLegalCompanies,
	retireCompanyIdentifier,
	suspendLegalCompany,
	updateCompanyIdentifier,
	updateLegalCompany,
} from "./legal-company";
export {
	createBankAccountRegistration,
	createBankMandate,
	createGroupControlRelationship,
	createLicencePermit,
	createMaterialAgreement,
	getBankAccountRegistration,
	getBankMandate,
	getGroupControlRelationship,
	getLicencePermit,
	getMaterialAgreement,
	listBankAccountRegistrations,
	listBankMandates,
	listGroupControlRelationships,
	listLicencePermits,
	listMaterialAgreements,
} from "./licences-banking";
export { corporateAdministrationModuleManifest } from "./module.manifest";
export { CA_COMMAND_IDS, CA_QUERY_IDS } from "./module-ids";
export {
	CA_PERMISSION_CODES,
	CA_PERMISSION_COMPANY_ACTIVATE,
	CA_PERMISSION_COMPANY_ARCHIVE,
	CA_PERMISSION_COMPANY_CREATE,
	CA_PERMISSION_COMPANY_DISSOLVE,
	CA_PERMISSION_COMPANY_IDENTIFIER_MANAGE,
	CA_PERMISSION_COMPANY_LIST,
	CA_PERMISSION_COMPANY_NAME_MANAGE,
	CA_PERMISSION_COMPANY_READ,
	CA_PERMISSION_COMPANY_SUSPEND,
	CA_PERMISSION_COMPANY_UPDATE,
	CA_PERMISSION_GOVERNANCE_MANAGE,
	CA_PERMISSION_GOVERNANCE_READ,
	CA_PERMISSION_PROPERTY_ASSETS_MANAGE,
	CA_PERMISSION_PROPERTY_ASSETS_READ,
	CA_PERMISSION_SHARE_CAPITAL_MANAGE,
	CA_PERMISSION_SHARE_CAPITAL_READ,
} from "./permissions";
export type {
	CorporateAdministrationMasterLookupPort,
	MutationPorts,
} from "./ports";
export {
	amendCharge,
	cancelInsurancePolicy,
	disposeCorporateAsset,
	disposeIntellectualProperty,
	disposeProperty,
	expireIntellectualProperty,
	getCharge,
	getCorporateAsset,
	getInsurancePolicy,
	getIntellectualProperty,
	getProperty,
	listCharges,
	listChargesAsOf,
	listCorporateAssets,
	listCorporateAssetsAsOf,
	listExpiringInsurancePolicies,
	listExpiringIntellectualProperty,
	listInsurancePolicies,
	listInsurancePoliciesAsOf,
	listIntellectualProperty,
	listIntellectualPropertyAsOf,
	listProperties,
	listPropertiesAsOf,
	registerCharge,
	registerCorporateAsset,
	registerInsurancePolicy,
	registerIntellectualProperty,
	registerProperty,
	releaseCharge,
	renewInsurancePolicy,
	renewIntellectualProperty,
	updateCorporateAsset,
	updateInsurancePolicy,
	updateIntellectualProperty,
	updateProperty,
	writeOffCorporateAsset,
} from "./property-assets";
export { ca4SubjectSchema } from "./property-assets-schemas";
export type {
	CaAuthorityMandate,
	CaAuthorityMandateDetail,
	CaAuthorityMandateHolder,
	CaCompanyIdentifier,
	CaCompanyName,
	CaCompanyPremise,
	CaCompanyStatus,
	CaCompanyStatusHistory,
	CaGovernanceBody,
	CaGovernanceMeeting,
	CaGovernanceMembership,
	CaLegalCompany,
	CaLegalCompanyDetail,
	CaOfficerAppointment,
	CaResolution,
} from "./schemas";
export { CA_COMPANY_STATUSES } from "./schemas";
export {
	listDueFilings,
	listOverdueFilings,
	searchCorporateRecords,
} from "./search-compliance";
export {
	createBeneficialOwnerDisclosure,
	createShareCertificate,
	createShareClass,
	createShareTransaction,
	getBeneficialOwnerDisclosure,
	getShareCertificate,
	getShareClass,
	getShareHoldingAsOf,
	getShareTransaction,
	listBeneficialOwnerDisclosures,
	listBeneficialOwnerDisclosuresAsOf,
	listShareCertificates,
	listShareClasses,
	listShareHoldingsAsOf,
	listShareTransactions,
} from "./share-capital";
export {
	cancelShareCertificate,
	closeShareClass,
	endBeneficialOwnerDisclosure,
	replaceShareCertificate,
	reverseShareTransaction,
	updateBeneficialOwnerDisclosure,
	updateShareClass,
} from "./share-capital-lifecycle";
export { createCorporateAdministrationRequestFingerprint } from "./shared/fingerprint";
export type {
	Ca4Subject,
	CaBankAccountRegistrationPublic,
	CaBankMandate,
	CaBeneficialOwnerDisclosure,
	CaCharge,
	CaChargeVariation,
	CaCorporateAsset,
	CaCorporateDocument,
	CaCorporateRecordSearchHit,
	CaFilingObligation,
	CaFilingSubmission,
	CaGroupControlRelationship,
	CaInsurancePolicy,
	CaInsurancePolicyRenewal,
	CaIntellectualPropertyRenewal,
	CaIntellectualPropertyRight,
	CaLicencePermit,
	CaMaterialAgreement,
	CaPropertyAssetMutationReceipt,
	CaPropertyHolding,
	CaShareCertificate,
	CaShareClass,
	CaShareHolding,
	CaShareTransaction,
	CaShareTransactionDetail,
} from "./slice-types";
