export const CORPORATE_ADMINISTRATION_MODULE_ID =
	"corporate-administration" as const;
export const CORPORATE_ADMINISTRATION_PACKAGE_NAME =
	"@afenda/corporate-administration" as const;

export const CORPORATE_ADMINISTRATION_COMMAND_IDS = [
	"registerLegalCompanyDraft",
	"updateLegalCompanyProfile",
	"addCompanyName",
	"supersedeCompanyName",
	"retireCompanyName",
	"setCompanyJurisdictionProfile",
	"supersedeCompanyJurisdictionProfile",
	"setCompanyLegalForm",
	"supersedeCompanyLegalForm",
	"registerCompanyIdentifier",
	"supersedeCompanyIdentifier",
	"retireCompanyIdentifier",
	"setCompanyFinancialYear",
	"registerCompanyActivity",
	"endCompanyActivity",
	"activateLegalCompany",
	"suspendLegalCompany",
	"markCompanyStruckOff",
	"enterLiquidation",
	"dissolveLegalCompany",
	"restoreLegalCompany",
	"archiveLegalCompany",
	"registerLegalEstablishment",
	"updateLegalEstablishment",
	"activateLegalEstablishment",
	"suspendLegalEstablishment",
	"closeLegalEstablishment",
	"setRegisteredAddress",
	"registerPremise",
	"endPremise",
	"createGovernanceBody",
	"amendGovernanceBody",
	"retireGovernanceBody",
	"appointGovernanceMember",
	"changeGovernanceMembership",
	"endGovernanceMembership",
	"defineStatutoryOffice",
	"appointOfficer",
	"amendOfficerAppointment",
	"recordOfficerQualification",
	"resignOfficer",
	"removeOfficer",
	"recordOfficerDeclaration",
	"supersedeOfficerDeclaration",
	"recordOfficerDisqualification",
	"endOfficerDisqualification",
	"discloseConflict",
	"recordRecusal",
	"scheduleGovernanceMeeting",
	"issueMeetingNotice",
	"recordNoticeDelivery",
	"waiveNotice",
	"recordMeetingParticipant",
	"openMeeting",
	"recordQuorum",
	"adjournMeeting",
	"closeMeeting",
	"recordMeetingVote",
	"adoptResolution",
	"rejectResolution",
	"recordWrittenResolution",
	"supersedeResolution",
	"assignResolutionAction",
	"completeResolutionAction",
	"recordMinutesDocument",
] as const;
export type CorporateAdministrationCommandId =
	(typeof CORPORATE_ADMINISTRATION_COMMAND_IDS)[number];
export const CORPORATE_ADMINISTRATION_QUERY_IDS = [
	"getLegalCompany",
	"listLegalCompanies",
	"listCompanyNames",
	"findCompanyNameAsOf",
	"findCompanyJurisdictionProfileAsOf",
	"findCompanyLegalFormAsOf",
	"listCompanyIdentifiers",
	"findCompanyIdentifierAsOf",
	"findCompanyFinancialYearAsOf",
	"listCompanyActivitiesAsOf",
	"findCompanyStatusAsOf",
	"listCompaniesByStatus",
	"getCompanyCompletenessForActivation",
	"getLegalCompanyTimeline",
	"getLegalEstablishment",
	"listLegalEstablishmentsAsOf",
	"findRegisteredAddressAsOf",
	"listPremisesAsOf",
	"getGovernanceBody",
	"listGovernanceBodiesAsOf",
	"listGovernanceMembershipsAsOf",
	"listRequiredStatutoryOffices",
	"listOfficersAsOf",
	"getOfficerAppointment",
	"getOfficerVacancyStatus",
	"getOfficerEligibilityAsOf",
	"listExpiringDeclarations",
	"listActiveDisqualifications",
	"listConflictsForMatter",
	"getGovernanceMeeting",
	"listGovernanceMeetings",
	"getMeetingAttendance",
	"getMeetingQuorumStatus",
	"getResolution",
	"listResolutionsAsOf",
	"getResolutionExecutionStatus",
	"listOverdueResolutionActions",
] as const;
export type CorporateAdministrationQueryId =
	(typeof CORPORATE_ADMINISTRATION_QUERY_IDS)[number];
