import type { AfendaModuleManifest } from "@afenda/db/module-manifest";

import {
	CORPORATE_ADMINISTRATION_MODULE_ID,
	CORPORATE_ADMINISTRATION_PACKAGE_NAME,
} from "./module-ids";
import { CORPORATE_ADMINISTRATION_MUTATION_TABLES } from "./mutation-tables";

/**
 * Corporate Administration greenfield module manifest.
 *
 * Declares infrastructure-only mutation ownership while the module remains
 * scaffolded. Runtime infrastructure (clock, transaction, idempotency) is not
 * an ERP module dependency and must not appear here. Optional integrations stay
 * empty until a later governed slice proves the relationship.
 */
export const corporateAdministrationModuleManifest = {
	id: CORPORATE_ADMINISTRATION_MODULE_ID,
	category: "erp",
	packageName: CORPORATE_ADMINISTRATION_PACKAGE_NAME,
	band: "R1-F",
	lifecycle: "scaffolded",
	activationMode: "organization_toggle",
	owns: {
		aggregates: [
			"legal_company",
			"legal_establishment",
			"premise",
			"governance_body",
			"governance_membership",
			"statutory_office",
			"officer_appointment",
			"officer_qualification",
			"officer_declaration",
			"officer_disqualification",
			"conflict_disclosure",
			"governance_meeting",
			"meeting_notice",
			"meeting_participant",
			"meeting_quorum_result",
			"meeting_vote",
			"resolution",
			"resolution_action",
		],
		commandNamespace: "corporate-administration",
		commands: [
			"registerLegalCompanyDraft",
			"updateLegalCompanyProfile",
			"addCompanyName",
			"supersedeCompanyName",
			"retireCompanyName",
			"setCompanyJurisdictionProfile",
			"supersedeCompanyJurisdictionProfile",
			"setCompanyLegalForm",
			"supersedeCompanyLegalForm",
			"registerCompanyIdentifier",
			"supersedeCompanyIdentifier",
			"retireCompanyIdentifier",
			"setCompanyFinancialYear",
			"registerCompanyActivity",
			"endCompanyActivity",
			"activateLegalCompany",
			"suspendLegalCompany",
			"markCompanyStruckOff",
			"enterLiquidation",
			"dissolveLegalCompany",
			"restoreLegalCompany",
			"archiveLegalCompany",
			"registerLegalEstablishment",
			"updateLegalEstablishment",
			"activateLegalEstablishment",
			"suspendLegalEstablishment",
			"closeLegalEstablishment",
			"setRegisteredAddress",
			"registerPremise",
			"endPremise",
			"createGovernanceBody",
			"amendGovernanceBody",
			"retireGovernanceBody",
			"appointGovernanceMember",
			"changeGovernanceMembership",
			"endGovernanceMembership",
			"defineStatutoryOffice",
			"appointOfficer",
			"amendOfficerAppointment",
			"recordOfficerQualification",
			"resignOfficer",
			"removeOfficer",
			"recordOfficerDeclaration",
			"supersedeOfficerDeclaration",
			"recordOfficerDisqualification",
			"endOfficerDisqualification",
			"discloseConflict",
			"recordRecusal",
			"scheduleGovernanceMeeting",
			"issueMeetingNotice",
			"recordNoticeDelivery",
			"waiveNotice",
			"recordMeetingParticipant",
			"openMeeting",
			"recordQuorum",
			"adjournMeeting",
			"closeMeeting",
			"recordMeetingVote",
			"adoptResolution",
			"rejectResolution",
			"recordWrittenResolution",
			"supersedeResolution",
			"assignResolutionAction",
			"completeResolutionAction",
			"recordMinutesDocument",
		],
		queryNamespace: "corporate-administration",
		queries: [
			"getLegalCompany",
			"listLegalCompanies",
			"listCompanyNames",
			"findCompanyNameAsOf",
			"findCompanyJurisdictionProfileAsOf",
			"findCompanyLegalFormAsOf",
			"listCompanyIdentifiers",
			"findCompanyIdentifierAsOf",
			"findCompanyFinancialYearAsOf",
			"listCompanyActivitiesAsOf",
			"findCompanyStatusAsOf",
			"listCompaniesByStatus",
			"getCompanyCompletenessForActivation",
			"getLegalCompanyTimeline",
			"getLegalEstablishment",
			"listLegalEstablishmentsAsOf",
			"findRegisteredAddressAsOf",
			"listPremisesAsOf",
			"getGovernanceBody",
			"listGovernanceBodiesAsOf",
			"listGovernanceMembershipsAsOf",
			"listRequiredStatutoryOffices",
			"listOfficersAsOf",
			"getOfficerAppointment",
			"getOfficerVacancyStatus",
			"getOfficerEligibilityAsOf",
			"listExpiringDeclarations",
			"listActiveDisqualifications",
			"listConflictsForMatter",
			"getGovernanceMeeting",
			"listGovernanceMeetings",
			"getMeetingAttendance",
			"getMeetingQuorumStatus",
			"getResolution",
			"listResolutionsAsOf",
			"getResolutionExecutionStatus",
			"listOverdueResolutionActions",
		],
	},
	persistence: {
		schemaOwner: "@afenda/db",
		mutationTables: [...CORPORATE_ADMINISTRATION_MUTATION_TABLES],
	},
	events: {
		namespace: "corporate_administration",
		emits: [
			"corporate_administration.legal_company.draft_registered.v1",
			"corporate_administration.legal_company.profile_updated.v1",
			"corporate_administration.legal_company.jurisdiction_profile_set.v1",
			"corporate_administration.legal_company.name_added.v1",
			"corporate_administration.legal_company.name_superseded.v1",
			"corporate_administration.legal_company.legal_form_changed.v1",
			"corporate_administration.legal_company.identifier_registered.v1",
			"corporate_administration.legal_company.financial_year_set.v1",
			"corporate_administration.legal_company.activity_registered.v1",
			"corporate_administration.legal_company.activated.v1",
			"corporate_administration.legal_company.suspended.v1",
			"corporate_administration.legal_company.struck_off_marked.v1",
			"corporate_administration.legal_company.liquidation_entered.v1",
			"corporate_administration.legal_company.dissolved.v1",
			"corporate_administration.legal_company.restored.v1",
			"corporate_administration.legal_company.archived.v1",
			"corporate_administration.legal_establishment.registered.v1",
			"corporate_administration.legal_establishment.updated.v1",
			"corporate_administration.legal_establishment.status_changed.v1",
			"corporate_administration.registered_address.set.v1",
			"corporate_administration.premise.registered.v1",
			"corporate_administration.premise.ended.v1",
			"corporate_administration.governance_body.created.v1",
			"corporate_administration.governance_body.amended.v1",
			"corporate_administration.governance_body.retired.v1",
			"corporate_administration.governance_membership.appointed.v1",
			"corporate_administration.governance_membership.changed.v1",
			"corporate_administration.governance_membership.ended.v1",
			"corporate_administration.statutory_office.defined.v1",
			"corporate_administration.officer.appointed.v1",
			"corporate_administration.officer.appointment_amended.v1",
			"corporate_administration.officer.qualification_recorded.v1",
			"corporate_administration.officer.resigned.v1",
			"corporate_administration.officer.removed.v1",
			"corporate_administration.officer.declaration_recorded.v1",
			"corporate_administration.officer.declaration_superseded.v1",
			"corporate_administration.officer.disqualified.v1",
			"corporate_administration.officer.disqualification_ended.v1",
			"corporate_administration.conflict.disclosed.v1",
			"corporate_administration.conflict.recusal_recorded.v1",
			"corporate_administration.governance_meeting.scheduled.v1",
			"corporate_administration.meeting_notice.issued.v1",
			"corporate_administration.meeting_notice.delivered.v1",
			"corporate_administration.meeting_notice.waived.v1",
			"corporate_administration.meeting_participant.recorded.v1",
			"corporate_administration.governance_meeting.opened.v1",
			"corporate_administration.governance_meeting.quorum_recorded.v1",
			"corporate_administration.governance_meeting.adjourned.v1",
			"corporate_administration.governance_meeting.closed.v1",
			"corporate_administration.meeting_vote.recorded.v1",
			"corporate_administration.resolution.adopted.v1",
			"corporate_administration.resolution.rejected.v1",
			"corporate_administration.resolution.superseded.v1",
			"corporate_administration.resolution.minutes_recorded.v1",
			"corporate_administration.resolution.action_assigned.v1",
			"corporate_administration.resolution.action_completed.v1",
		],
		consumes: [],
	},
	permissions: {
		namespace: "corporate_administration",
		codes: [
			"corporate_administration.company.read",
			"corporate_administration.company.manage",
			"corporate_administration.establishment.manage",
			"corporate_administration.governance.read",
			"corporate_administration.governance.manage",
			"corporate_administration.officer.read",
			"corporate_administration.officer.manage",
			"corporate_administration.officer_compliance.read",
			"corporate_administration.officer_compliance.manage",
			"corporate_administration.meeting.read",
			"corporate_administration.meeting.manage",
			"corporate_administration.resolution.read",
			"corporate_administration.resolution.manage",
		],
	},
	authorization: {
		commands: {
			registerLegalCompanyDraft: "corporate_administration.company.manage",
			updateLegalCompanyProfile: "corporate_administration.company.manage",
			addCompanyName: "corporate_administration.company.manage",
			supersedeCompanyName: "corporate_administration.company.manage",
			retireCompanyName: "corporate_administration.company.manage",
			setCompanyJurisdictionProfile: "corporate_administration.company.manage",
			supersedeCompanyJurisdictionProfile:
				"corporate_administration.company.manage",
			setCompanyLegalForm: "corporate_administration.company.manage",
			supersedeCompanyLegalForm: "corporate_administration.company.manage",
			registerCompanyIdentifier: "corporate_administration.company.manage",
			supersedeCompanyIdentifier: "corporate_administration.company.manage",
			retireCompanyIdentifier: "corporate_administration.company.manage",
			setCompanyFinancialYear: "corporate_administration.company.manage",
			registerCompanyActivity: "corporate_administration.company.manage",
			endCompanyActivity: "corporate_administration.company.manage",
			activateLegalCompany: "corporate_administration.company.manage",
			suspendLegalCompany: "corporate_administration.company.manage",
			markCompanyStruckOff: "corporate_administration.company.manage",
			enterLiquidation: "corporate_administration.company.manage",
			dissolveLegalCompany: "corporate_administration.company.manage",
			restoreLegalCompany: "corporate_administration.company.manage",
			archiveLegalCompany: "corporate_administration.company.manage",
			registerLegalEstablishment:
				"corporate_administration.establishment.manage",
			updateLegalEstablishment: "corporate_administration.establishment.manage",
			activateLegalEstablishment:
				"corporate_administration.establishment.manage",
			suspendLegalEstablishment:
				"corporate_administration.establishment.manage",
			closeLegalEstablishment: "corporate_administration.establishment.manage",
			setRegisteredAddress: "corporate_administration.establishment.manage",
			registerPremise: "corporate_administration.establishment.manage",
			endPremise: "corporate_administration.establishment.manage",
			createGovernanceBody: "corporate_administration.governance.manage",
			amendGovernanceBody: "corporate_administration.governance.manage",
			retireGovernanceBody: "corporate_administration.governance.manage",
			appointGovernanceMember: "corporate_administration.governance.manage",
			changeGovernanceMembership: "corporate_administration.governance.manage",
			endGovernanceMembership: "corporate_administration.governance.manage",
			defineStatutoryOffice: "corporate_administration.officer.manage",
			appointOfficer: "corporate_administration.officer.manage",
			amendOfficerAppointment: "corporate_administration.officer.manage",
			recordOfficerQualification: "corporate_administration.officer.manage",
			resignOfficer: "corporate_administration.officer.manage",
			removeOfficer: "corporate_administration.officer.manage",
			recordOfficerDeclaration:
				"corporate_administration.officer_compliance.manage",
			supersedeOfficerDeclaration:
				"corporate_administration.officer_compliance.manage",
			recordOfficerDisqualification:
				"corporate_administration.officer_compliance.manage",
			endOfficerDisqualification:
				"corporate_administration.officer_compliance.manage",
			discloseConflict: "corporate_administration.officer_compliance.manage",
			recordRecusal: "corporate_administration.officer_compliance.manage",
			scheduleGovernanceMeeting: "corporate_administration.meeting.manage",
			issueMeetingNotice: "corporate_administration.meeting.manage",
			recordNoticeDelivery: "corporate_administration.meeting.manage",
			waiveNotice: "corporate_administration.meeting.manage",
			recordMeetingParticipant: "corporate_administration.meeting.manage",
			openMeeting: "corporate_administration.meeting.manage",
			recordQuorum: "corporate_administration.meeting.manage",
			adjournMeeting: "corporate_administration.meeting.manage",
			closeMeeting: "corporate_administration.meeting.manage",
			recordMeetingVote: "corporate_administration.resolution.manage",
			adoptResolution: "corporate_administration.resolution.manage",
			rejectResolution: "corporate_administration.resolution.manage",
			recordWrittenResolution: "corporate_administration.resolution.manage",
			supersedeResolution: "corporate_administration.resolution.manage",
			assignResolutionAction: "corporate_administration.resolution.manage",
			completeResolutionAction: "corporate_administration.resolution.manage",
			recordMinutesDocument: "corporate_administration.resolution.manage",
		},
		queries: {
			getLegalCompany: "corporate_administration.company.read",
			listLegalCompanies: "corporate_administration.company.read",
			listCompanyNames: "corporate_administration.company.read",
			findCompanyNameAsOf: "corporate_administration.company.read",
			findCompanyJurisdictionProfileAsOf:
				"corporate_administration.company.read",
			findCompanyLegalFormAsOf: "corporate_administration.company.read",
			listCompanyIdentifiers: "corporate_administration.company.read",
			findCompanyIdentifierAsOf: "corporate_administration.company.read",
			findCompanyFinancialYearAsOf: "corporate_administration.company.read",
			listCompanyActivitiesAsOf: "corporate_administration.company.read",
			findCompanyStatusAsOf: "corporate_administration.company.read",
			listCompaniesByStatus: "corporate_administration.company.read",
			getCompanyCompletenessForActivation:
				"corporate_administration.company.read",
			getLegalCompanyTimeline: "corporate_administration.company.read",
			getLegalEstablishment: "corporate_administration.company.read",
			listLegalEstablishmentsAsOf: "corporate_administration.company.read",
			findRegisteredAddressAsOf: "corporate_administration.company.read",
			listPremisesAsOf: "corporate_administration.company.read",
			getGovernanceBody: "corporate_administration.governance.read",
			listGovernanceBodiesAsOf: "corporate_administration.governance.read",
			listGovernanceMembershipsAsOf: "corporate_administration.governance.read",
			listRequiredStatutoryOffices: "corporate_administration.officer.read",
			listOfficersAsOf: "corporate_administration.officer.read",
			getOfficerAppointment: "corporate_administration.officer.read",
			getOfficerVacancyStatus: "corporate_administration.officer.read",
			getOfficerEligibilityAsOf:
				"corporate_administration.officer_compliance.read",
			listExpiringDeclarations:
				"corporate_administration.officer_compliance.read",
			listActiveDisqualifications:
				"corporate_administration.officer_compliance.read",
			listConflictsForMatter:
				"corporate_administration.officer_compliance.read",
			getGovernanceMeeting: "corporate_administration.meeting.read",
			listGovernanceMeetings: "corporate_administration.meeting.read",
			getMeetingAttendance: "corporate_administration.meeting.read",
			getMeetingQuorumStatus: "corporate_administration.meeting.read",
			getResolution: "corporate_administration.resolution.read",
			listResolutionsAsOf: "corporate_administration.resolution.read",
			getResolutionExecutionStatus: "corporate_administration.resolution.read",
			listOverdueResolutionActions: "corporate_administration.resolution.read",
		},
	},
	moduleDependencies: {
		required: [],
	},
	optionalIntegratesWith: [],
} as const satisfies AfendaModuleManifest;
