export const CORPORATE_ADMINISTRATION_PERMISSION_CODES = [
	"corporate_administration.access",
	"corporate_administration.company.read",
	"corporate_administration.company.manage",
	"corporate_administration.company.activate",
	"corporate_administration.company.dissolve",
	"corporate_administration.establishment.manage",
	"corporate_administration.governance.read",
	"corporate_administration.governance.manage",
	"corporate_administration.officer.manage",
	"corporate_administration.meeting.manage",
	"corporate_administration.resolution.manage",
	"corporate_administration.authority.read",
	"corporate_administration.authority.manage",
	"corporate_administration.authority.publish",
	"corporate_administration.seal.manage",
	"corporate_administration.capital.read",
	"corporate_administration.capital.configure",
	"corporate_administration.capital.post",
	"corporate_administration.capital.reverse",
	"corporate_administration.ownership.read",
	"corporate_administration.ownership.manage",
	"corporate_administration.ubo.read",
	"corporate_administration.ubo.manage",
	"corporate_administration.ubo.attest",
	"corporate_administration.distribution.declare",
	"corporate_administration.assets.read",
	"corporate_administration.assets.manage",
	"corporate_administration.licence.manage",
	"corporate_administration.charge.manage",
	"corporate_administration.banking.read",
	"corporate_administration.banking.manage",
	"corporate_administration.bank_mandate.manage",
	"corporate_administration.group.read",
	"corporate_administration.group.manage",
	"corporate_administration.related_party.manage",
	"corporate_administration.agreement.manage",
	"corporate_administration.corporate_action.manage",
	"corporate_administration.corporate_action.approve_effect",
	"corporate_administration.document.read",
	"corporate_administration.document.manage",
	"corporate_administration.register.certify",
	"corporate_administration.compliance_rule.manage",
	"corporate_administration.filing.read",
	"corporate_administration.filing.manage",
	"corporate_administration.filing.waive",
	"corporate_administration.import.prepare",
	"corporate_administration.import.approve",
	"corporate_administration.import.apply",
	"corporate_administration.export",
	"corporate_administration.reconcile",
	"corporate_administration.sensitive_export",
	"corporate_administration.module_admin",
] as const;

export type CorporateAdministrationPermission =
	(typeof CORPORATE_ADMINISTRATION_PERMISSION_CODES)[number];
