import type {
	ComponentGovernance,
	ErpModuleId,
	GovernedComponentContract,
	UiCapabilityId,
	UiCatalog,
	UiComponentMetadata,
	UiEvidence,
	UiFamily,
	UiLayer,
	UiQualityProfileId,
	UiRenderMode,
	UiState,
	UiSurfaceProfileId,
	UiTokenFamilyId,
} from "./contract";
import { defineComponentGovernance, UI_QUALITY_PROFILE_IDS } from "./contract";
import {
	accordionContract,
	alertContract,
	alertDialogContract,
	asyncStateContract,
	avatarContract,
	badgeContract,
	breadcrumbContract,
	bulkActionBarContract,
	buttonContract,
	buttonGroupContract,
	calendarContract,
	cardContract,
	changeDiffContract,
	chartContract,
	checkboxContract,
	codeContract,
	collapsibleContract,
	columnVisibilityMenuContract,
	comboboxContract,
	commandContract,
	contextMenuContract,
	dataTableContract,
	datePickerContract,
	dateTimePickerContract,
	dialogContract,
	drawerContract,
	dropdownMenuContract,
	emptyContract,
	fieldContract,
	fileUploadContract,
	filterBarContract,
	formErrorContract,
	formFieldContract,
	hoverCardContract,
	inputContract,
	inputGroupContract,
	kbdContract,
	keyValueContract,
	labelContract,
	masterDetailContract,
	menubarContract,
	metricCardContract,
	nativeSelectContract,
	numericInputContract,
	pageHeaderContract,
	paginationContract,
	popoverContract,
	progressContract,
	radioGroupContract,
	resizableContract,
	savedViewSelectContract,
	scrollAreaContract,
	searchFieldContract,
	selectContract,
	separatorContract,
	sheetContract,
	sidebarContract,
	sidebarCookieContract,
	skeletonContract,
	sliderContract,
	sonnerContract,
	spinnerContract,
	statusBadgeContract,
	stepperContract,
	switchContract,
	tableContract,
	tabsContract,
	textareaContract,
	timelineContract,
	toggleContract,
	toggleGroupContract,
	toolbarContract,
	tooltipContract,
	treeViewContract,
} from "./contracts";

const CANDIDATE_GOVERNANCE = defineComponentGovernance({
	lifecycle: "candidate",
});

function candidateContractGovernance(
	contract: GovernedComponentContract,
): ComponentGovernance {
	return defineComponentGovernance({ lifecycle: "candidate", contract });
}

function approvedContractGovernance(
	contract: GovernedComponentContract,
): ComponentGovernance {
	return defineComponentGovernance({ lifecycle: "approved", contract });
}

export const componentGovernanceById: Readonly<
	Partial<Record<UiComponentMetadata["id"], ComponentGovernance>>
> = {
	"ui.accordion": candidateContractGovernance(accordionContract),
	"ui.alert-dialog": candidateContractGovernance(alertDialogContract),
	"ui.alert": candidateContractGovernance(alertContract),
	"ui.async-state": candidateContractGovernance(asyncStateContract),
	"ui.avatar": candidateContractGovernance(avatarContract),
	"ui.badge": candidateContractGovernance(badgeContract),
	"ui.breadcrumb": candidateContractGovernance(breadcrumbContract),
	"ui.bulk-action-bar": candidateContractGovernance(bulkActionBarContract),
	"ui.button-group": candidateContractGovernance(buttonGroupContract),
	"ui.button": candidateContractGovernance(buttonContract),
	"ui.calendar": candidateContractGovernance(calendarContract),
	"ui.card": candidateContractGovernance(cardContract),
	"ui.change-diff": candidateContractGovernance(changeDiffContract),
	"ui.chart": candidateContractGovernance(chartContract),
	"ui.checkbox": candidateContractGovernance(checkboxContract),
	"ui.code": candidateContractGovernance(codeContract),
	"ui.collapsible": candidateContractGovernance(collapsibleContract),
	"ui.column-visibility-menu": candidateContractGovernance(
		columnVisibilityMenuContract,
	),
	"ui.combobox": candidateContractGovernance(comboboxContract),
	"ui.command": candidateContractGovernance(commandContract),
	"ui.context-menu": candidateContractGovernance(contextMenuContract),
	"ui.data-table": candidateContractGovernance(dataTableContract),
	"ui.date-picker": candidateContractGovernance(datePickerContract),
	"ui.date-time-picker": candidateContractGovernance(dateTimePickerContract),
	"ui.dialog": candidateContractGovernance(dialogContract),
	"ui.dropdown-menu": candidateContractGovernance(dropdownMenuContract),
	"ui.drawer": candidateContractGovernance(drawerContract),
	"ui.empty": candidateContractGovernance(emptyContract),
	"ui.field": candidateContractGovernance(fieldContract),
	"ui.file-upload": candidateContractGovernance(fileUploadContract),
	"ui.filter-bar": candidateContractGovernance(filterBarContract),
	"ui.form-error": candidateContractGovernance(formErrorContract),
	"ui.form-field": candidateContractGovernance(formFieldContract),
	"ui.hover-card": candidateContractGovernance(hoverCardContract),
	"ui.input-group": candidateContractGovernance(inputGroupContract),
	"ui.input": candidateContractGovernance(inputContract),
	"ui.kbd": candidateContractGovernance(kbdContract),
	"ui.key-value": candidateContractGovernance(keyValueContract),
	"ui.label": candidateContractGovernance(labelContract),
	"ui.master-detail": candidateContractGovernance(masterDetailContract),
	"ui.menubar": candidateContractGovernance(menubarContract),
	"ui.metric-card": candidateContractGovernance(metricCardContract),
	"ui.native-select": candidateContractGovernance(nativeSelectContract),
	"ui.numeric-input": candidateContractGovernance(numericInputContract),
	"ui.page-header": candidateContractGovernance(pageHeaderContract),
	"ui.pagination": candidateContractGovernance(paginationContract),
	"ui.popover": candidateContractGovernance(popoverContract),
	"ui.progress": candidateContractGovernance(progressContract),
	"ui.radio-group": candidateContractGovernance(radioGroupContract),
	"ui.resizable": candidateContractGovernance(resizableContract),
	"ui.saved-view-select": candidateContractGovernance(savedViewSelectContract),
	"ui.scroll-area": candidateContractGovernance(scrollAreaContract),
	"ui.search-field": candidateContractGovernance(searchFieldContract),
	"ui.select": candidateContractGovernance(selectContract),
	"ui.separator": candidateContractGovernance(separatorContract),
	"ui.sheet": candidateContractGovernance(sheetContract),
	"ui.sidebar-cookie": candidateContractGovernance(sidebarCookieContract),
	"ui.sidebar": candidateContractGovernance(sidebarContract),
	"ui.skeleton": candidateContractGovernance(skeletonContract),
	"ui.slider": approvedContractGovernance(sliderContract),
	"ui.sonner": approvedContractGovernance(sonnerContract),
	"ui.spinner": approvedContractGovernance(spinnerContract),
	"ui.status-badge": approvedContractGovernance(statusBadgeContract),
	"ui.stepper": approvedContractGovernance(stepperContract),
	"ui.switch": candidateContractGovernance(switchContract),
	"ui.table": candidateContractGovernance(tableContract),
	"ui.tabs": candidateContractGovernance(tabsContract),
	"ui.textarea": candidateContractGovernance(textareaContract),
	"ui.timeline": candidateContractGovernance(timelineContract),
	"ui.toggle-group": candidateContractGovernance(toggleGroupContract),
	"ui.toggle": candidateContractGovernance(toggleContract),
	"ui.toolbar": candidateContractGovernance(toolbarContract),
	"ui.tooltip": candidateContractGovernance(tooltipContract),
	"ui.tree-view": candidateContractGovernance(treeViewContract),
};

export function getComponentGovernance(
	componentId: UiComponentMetadata["id"],
): ComponentGovernance {
	return componentGovernanceById[componentId] ?? CANDIDATE_GOVERNANCE;
}

const CONTRACT_TEST = "__tests__/consistency.test.ts";
const RSC_TEST = "__tests__/rsc-boundary.test.ts";
const BASELINE_INTERACTION_TEST = "__tests__/erp-baseline.interaction.test.tsx";
const AXE_TEST = "__tests__/a11y.axe.interaction.test.tsx";
const OVERLAY_TEST = "__tests__/overlays.interaction.test.tsx";
const CONTRAST_TEST = "__tests__/color-contrast.test.ts";

const evidenceByProfile = {
	"static-display": [
		{ kind: "contract", path: CONTRACT_TEST },
		{ kind: "rsc", path: RSC_TEST },
	],
	"interactive-control": [
		{ kind: "contract", path: CONTRACT_TEST },
		{ kind: "interaction", path: BASELINE_INTERACTION_TEST },
	],
	"form-control": [
		{ kind: "contract", path: CONTRACT_TEST },
		{ kind: "interaction", path: BASELINE_INTERACTION_TEST },
		{ kind: "axe", path: AXE_TEST },
	],
	"modal-overlay": [
		{ kind: "interaction", path: OVERLAY_TEST },
		{ kind: "axe", path: AXE_TEST },
	],
	"collection-navigation": [
		{ kind: "contract", path: CONTRACT_TEST },
		{ kind: "interaction", path: BASELINE_INTERACTION_TEST },
	],
	"async-data": [
		{ kind: "contract", path: CONTRACT_TEST },
		{ kind: "interaction", path: BASELINE_INTERACTION_TEST },
		{ kind: "axe", path: AXE_TEST },
	],
	"status-feedback": [
		{ kind: "contract", path: CONTRACT_TEST },
		{ kind: "contrast", path: CONTRAST_TEST },
		{ kind: "axe", path: AXE_TEST },
	],
	"workflow-history": [
		{ kind: "contract", path: CONTRACT_TEST },
		{ kind: "axe", path: AXE_TEST },
	],
	"data-visualization": [
		{ kind: "contract", path: CONTRACT_TEST },
		{ kind: "interaction", path: BASELINE_INTERACTION_TEST },
		{ kind: "axe", path: AXE_TEST },
	],
} satisfies Record<UiQualityProfileId, readonly UiEvidence[]>;

const statesByProfile = {
	"static-display": ["default"],
	"interactive-control": ["default", "hover", "focus-visible", "disabled"],
	"form-control": [
		"default",
		"focus-visible",
		"disabled",
		"invalid",
		"read-only",
	],
	"modal-overlay": ["default", "open", "focus-visible"],
	"collection-navigation": ["default", "focus-visible", "selected", "empty"],
	"async-data": ["loading", "empty", "filtered-empty", "error", "default"],
	"status-feedback": ["success", "warning", "info", "destructive"],
	"workflow-history": ["default", "success", "warning", "destructive"],
	"data-visualization": ["default", "loading", "empty"],
} satisfies Record<UiQualityProfileId, readonly UiState[]>;

interface ComponentDefinition {
	id: UiComponentMetadata["id"];
	sourceModule: UiComponentMetadata["sourceModule"];
	publicExports: readonly string[];
	variants?: UiComponentMetadata["variants"];
	sizes?: UiComponentMetadata["sizes"];
	layer: UiLayer;
	family: UiFamily;
	renderMode: UiRenderMode;
	capabilities: readonly UiCapabilityId[];
	qualityProfile: UiQualityProfileId;
	tokenFamilies?: readonly UiTokenFamilyId[];
}

function defineComponent(definition: ComponentDefinition): UiComponentMetadata {
	const governance = getComponentGovernance(definition.id);

	return {
		...definition,
		name: definition.id,
		qualityProfiles: [definition.qualityProfile],
		requiredStates: statesByProfile[definition.qualityProfile],
		tokenFamilies: definition.tokenFamilies ?? ["core-surface", "focus"],
		evidence: evidenceByProfile[definition.qualityProfile],
		governance,
		lifecycle: governance.lifecycle,
	};
}

const components = [
	defineComponent({
		id: "ui.accordion",
		sourceModule: "src/components/ui/accordion.tsx",
		publicExports: [
			"Accordion",
			"AccordionContent",
			"AccordionItem",
			"AccordionTrigger",
		],
		layer: "primitive",
		family: "layout",
		renderMode: "client",
		capabilities: ["ui.layout.disclosure"],
		qualityProfile: "interactive-control",
	}),
	defineComponent({
		id: "ui.alert-dialog",
		sourceModule: "src/components/ui/alert-dialog.tsx",
		publicExports: [
			"AlertDialog",
			"AlertDialogAction",
			"AlertDialogCancel",
			"AlertDialogContent",
			"AlertDialogDescription",
			"AlertDialogFooter",
			"AlertDialogHeader",
			"AlertDialogMedia",
			"AlertDialogOverlay",
			"AlertDialogPortal",
			"AlertDialogTitle",
			"AlertDialogTrigger",
		],
		sizes: ["default", "sm"],
		layer: "primitive",
		family: "overlays",
		renderMode: "client",
		capabilities: ["ui.overlay.modal"],
		qualityProfile: "modal-overlay",
	}),
	defineComponent({
		id: "ui.alert",
		sourceModule: "src/components/ui/alert.tsx",
		publicExports: ["Alert", "AlertDescription", "AlertTitle"],
		variants: ["default", "destructive"],
		layer: "primitive",
		family: "feedback",
		renderMode: "server-compatible",
		capabilities: ["ui.feedback.alert"],
		qualityProfile: "status-feedback",
		tokenFamilies: ["core-surface", "status"],
	}),
	defineComponent({
		id: "ui.avatar",
		sourceModule: "src/components/ui/avatar.tsx",
		publicExports: [
			"Avatar",
			"AvatarBadge",
			"AvatarFallback",
			"AvatarGroup",
			"AvatarGroupCount",
			"AvatarImage",
		],
		sizes: ["default", "sm", "lg"],
		layer: "primitive",
		family: "data",
		renderMode: "client",
		capabilities: ["ui.data.key-value"],
		qualityProfile: "static-display",
	}),
	defineComponent({
		id: "ui.badge",
		sourceModule: "src/components/ui/badge.tsx",
		publicExports: ["Badge", "badgeVariants"],
		variants: [
			"default",
			"secondary",
			"destructive",
			"outline",
			"ghost",
			"link",
		],
		layer: "primitive",
		family: "feedback",
		renderMode: "server-compatible",
		capabilities: ["ui.data.label"],
		qualityProfile: "status-feedback",
		tokenFamilies: ["core-surface", "status"],
	}),
	defineComponent({
		id: "ui.breadcrumb",
		sourceModule: "src/components/ui/breadcrumb.tsx",
		publicExports: [
			"Breadcrumb",
			"BreadcrumbEllipsis",
			"BreadcrumbItem",
			"BreadcrumbLink",
			"BreadcrumbList",
			"BreadcrumbPage",
			"BreadcrumbSeparator",
		],
		layer: "primitive",
		family: "navigation",
		renderMode: "server-compatible",
		capabilities: ["ui.navigation.breadcrumb"],
		qualityProfile: "static-display",
	}),
	defineComponent({
		id: "ui.button-group",
		sourceModule: "src/components/ui/button-group.tsx",
		publicExports: [
			"ButtonGroup",
			"ButtonGroupSeparator",
			"ButtonGroupText",
			"buttonGroupVariants",
		],
		variants: ["horizontal", "vertical"],
		layer: "primitive",
		family: "actions",
		renderMode: "server-compatible",
		capabilities: ["ui.action.group"],
		qualityProfile: "static-display",
	}),
	defineComponent({
		id: "ui.button",
		sourceModule: "src/components/ui/button.tsx",
		publicExports: ["Button", "buttonVariants"],
		variants: [
			"default",
			"destructive",
			"outline",
			"secondary",
			"ghost",
			"link",
		],
		sizes: [
			"default",
			"xs",
			"sm",
			"lg",
			"icon",
			"icon-xs",
			"icon-sm",
			"icon-lg",
		],
		layer: "primitive",
		family: "actions",
		renderMode: "server-compatible",
		capabilities: ["ui.action.trigger"],
		qualityProfile: "interactive-control",
	}),
	defineComponent({
		id: "ui.calendar",
		sourceModule: "src/components/ui/calendar.tsx",
		publicExports: ["Calendar", "CalendarProps"],
		variants: ["single", "range"],
		layer: "primitive",
		family: "forms",
		renderMode: "client",
		capabilities: ["ui.form.date"],
		qualityProfile: "form-control",
	}),
	defineComponent({
		id: "ui.card",
		sourceModule: "src/components/ui/card.tsx",
		publicExports: [
			"Card",
			"CardAction",
			"CardContent",
			"CardDescription",
			"CardFooter",
			"CardHeader",
			"CardTitle",
		],
		layer: "primitive",
		family: "layout",
		renderMode: "server-compatible",
		capabilities: ["ui.layout.section-heading"],
		qualityProfile: "static-display",
	}),
	defineComponent({
		id: "ui.checkbox",
		sourceModule: "src/components/ui/checkbox.tsx",
		publicExports: ["Checkbox"],
		layer: "primitive",
		family: "forms",
		renderMode: "client",
		capabilities: ["ui.form.boolean"],
		qualityProfile: "form-control",
	}),
	defineComponent({
		id: "ui.code",
		sourceModule: "src/components/ui/code.tsx",
		publicExports: ["Code"],
		layer: "primitive",
		family: "data",
		renderMode: "server-compatible",
		capabilities: ["ui.data.key-value"],
		qualityProfile: "static-display",
	}),
	defineComponent({
		id: "ui.collapsible",
		sourceModule: "src/components/ui/collapsible.tsx",
		publicExports: ["Collapsible", "CollapsibleContent", "CollapsibleTrigger"],
		layer: "primitive",
		family: "layout",
		renderMode: "client",
		capabilities: ["ui.layout.disclosure"],
		qualityProfile: "interactive-control",
	}),
	defineComponent({
		id: "ui.combobox",
		sourceModule: "src/components/ui/combobox.tsx",
		publicExports: ["Combobox", "ComboboxOption"],
		layer: "compound",
		family: "forms",
		renderMode: "client",
		capabilities: ["ui.form.search-choice"],
		qualityProfile: "form-control",
	}),
	defineComponent({
		id: "ui.command",
		sourceModule: "src/components/ui/command.tsx",
		publicExports: [
			"Command",
			"CommandDialog",
			"CommandEmpty",
			"CommandGroup",
			"CommandInput",
			"CommandItem",
			"CommandList",
			"CommandSeparator",
			"CommandShortcut",
		],
		layer: "primitive",
		family: "navigation",
		renderMode: "client",
		capabilities: ["ui.navigation.command"],
		qualityProfile: "collection-navigation",
	}),
	defineComponent({
		id: "ui.context-menu",
		sourceModule: "src/components/ui/context-menu.tsx",
		publicExports: [
			"ContextMenu",
			"ContextMenuCheckboxItem",
			"ContextMenuContent",
			"ContextMenuGroup",
			"ContextMenuItem",
			"ContextMenuLabel",
			"ContextMenuPortal",
			"ContextMenuRadioGroup",
			"ContextMenuRadioItem",
			"ContextMenuSeparator",
			"ContextMenuShortcut",
			"ContextMenuSub",
			"ContextMenuSubContent",
			"ContextMenuSubTrigger",
			"ContextMenuTrigger",
		],
		variants: ["default", "destructive"],
		layer: "primitive",
		family: "overlays",
		renderMode: "client",
		capabilities: ["ui.overlay.popover"],
		qualityProfile: "interactive-control",
	}),
	defineComponent({
		id: "ui.data-table",
		sourceModule: "src/components/ui/data-table.tsx",
		publicExports: [
			"DataTable",
			"DataTableColumn",
			"DataTableDensity",
			"DataTableProps",
			"pageWindow",
		],
		variants: ["comfortable", "compact"],
		layer: "compound",
		family: "data",
		renderMode: "client",
		capabilities: [
			"ui.data.table",
			"ui.data.filter",
			"ui.data.column-visibility",
			"ui.data.bulk-actions",
			"ui.feedback.async-state",
			"ui.navigation.pagination",
		],
		qualityProfile: "async-data",
		tokenFamilies: ["core-surface", "data", "control", "focus"],
	}),
	defineComponent({
		id: "ui.date-picker",
		sourceModule: "src/components/ui/date-picker.tsx",
		publicExports: [
			"DatePicker",
			"DatePickerProps",
			"DateRangePicker",
			"DateRangePickerProps",
			"DateRangeValue",
		],
		variants: ["single", "range"],
		layer: "compound",
		family: "forms",
		renderMode: "client",
		capabilities: ["ui.form.date", "ui.form.date-range"],
		qualityProfile: "form-control",
	}),
	defineComponent({
		id: "ui.dialog",
		sourceModule: "src/components/ui/dialog.tsx",
		publicExports: [
			"Dialog",
			"DialogClose",
			"DialogContent",
			"DialogDescription",
			"DialogFooter",
			"DialogHeader",
			"DialogOverlay",
			"DialogPortal",
			"DialogTitle",
			"DialogTrigger",
		],
		layer: "primitive",
		family: "overlays",
		renderMode: "client",
		capabilities: ["ui.overlay.modal"],
		qualityProfile: "modal-overlay",
	}),
	defineComponent({
		id: "ui.dropdown-menu",
		sourceModule: "src/components/ui/dropdown-menu.tsx",
		publicExports: [
			"DropdownMenu",
			"DropdownMenuCheckboxItem",
			"DropdownMenuContent",
			"DropdownMenuGroup",
			"DropdownMenuItem",
			"DropdownMenuLabel",
			"DropdownMenuPortal",
			"DropdownMenuRadioGroup",
			"DropdownMenuRadioItem",
			"DropdownMenuSeparator",
			"DropdownMenuShortcut",
			"DropdownMenuSub",
			"DropdownMenuSubContent",
			"DropdownMenuSubTrigger",
			"DropdownMenuTrigger",
		],
		variants: ["default", "destructive"],
		layer: "primitive",
		family: "overlays",
		renderMode: "client",
		capabilities: ["ui.overlay.popover"],
		qualityProfile: "interactive-control",
	}),
	defineComponent({
		id: "ui.drawer",
		sourceModule: "src/components/ui/drawer.tsx",
		publicExports: [
			"Drawer",
			"DrawerClose",
			"DrawerContent",
			"DrawerDescription",
			"DrawerFooter",
			"DrawerHeader",
			"DrawerOverlay",
			"DrawerPortal",
			"DrawerTitle",
			"DrawerTrigger",
		],
		layer: "primitive",
		family: "overlays",
		renderMode: "client",
		capabilities: ["ui.overlay.drawer"],
		qualityProfile: "modal-overlay",
	}),
	defineComponent({
		id: "ui.empty",
		sourceModule: "src/components/ui/empty.tsx",
		publicExports: ["Empty", "emptyVariants"],
		sizes: ["sm", "md", "lg"],
		layer: "compound",
		family: "feedback",
		renderMode: "client",
		capabilities: ["ui.feedback.async-state"],
		qualityProfile: "async-data",
	}),
	defineComponent({
		id: "ui.field",
		sourceModule: "src/components/ui/field.tsx",
		publicExports: [
			"Field",
			"FieldContent",
			"FieldDescription",
			"FieldError",
			"FieldGroup",
			"FieldLabel",
			"FieldLegend",
			"FieldSeparator",
			"FieldSet",
			"FieldTitle",
		],
		variants: ["vertical", "horizontal", "responsive", "legend", "label"],
		layer: "primitive",
		family: "forms",
		renderMode: "client",
		capabilities: ["ui.form.field"],
		qualityProfile: "form-control",
	}),
	defineComponent({
		id: "ui.form-error",
		sourceModule: "src/components/ui/form-error.tsx",
		publicExports: ["FormError", "formErrorVariants"],
		variants: ["default", "warning", "info"],
		sizes: ["sm", "md", "lg"],
		layer: "compound",
		family: "feedback",
		renderMode: "client",
		capabilities: ["ui.feedback.alert"],
		qualityProfile: "status-feedback",
		tokenFamilies: ["status", "focus"],
	}),
	defineComponent({
		id: "ui.form-field",
		sourceModule: "src/components/ui/form-field.tsx",
		publicExports: ["FormField", "FormInput", "FormTextarea"],
		layer: "compound",
		family: "forms",
		renderMode: "client",
		capabilities: ["ui.form.field", "ui.form.text", "ui.form.multiline"],
		qualityProfile: "form-control",
	}),
	defineComponent({
		id: "ui.hover-card",
		sourceModule: "src/components/ui/hover-card.tsx",
		publicExports: ["HoverCard", "HoverCardContent", "HoverCardTrigger"],
		layer: "primitive",
		family: "overlays",
		renderMode: "client",
		capabilities: ["ui.overlay.popover"],
		qualityProfile: "interactive-control",
	}),
	defineComponent({
		id: "ui.input-group",
		sourceModule: "src/components/ui/input-group.tsx",
		publicExports: [
			"InputGroup",
			"InputGroupAddon",
			"InputGroupButton",
			"InputGroupInput",
			"InputGroupText",
			"InputGroupTextarea",
		],
		variants: ["inline-start", "inline-end", "block-start", "block-end"],
		sizes: ["xs", "sm", "icon-xs", "icon-sm"],
		layer: "compound",
		family: "forms",
		renderMode: "client",
		capabilities: ["ui.form.text", "ui.form.multiline"],
		qualityProfile: "form-control",
	}),
	defineComponent({
		id: "ui.input",
		sourceModule: "src/components/ui/input.tsx",
		publicExports: ["Input"],
		layer: "primitive",
		family: "forms",
		renderMode: "server-compatible",
		capabilities: ["ui.form.text"],
		qualityProfile: "form-control",
	}),
	defineComponent({
		id: "ui.kbd",
		sourceModule: "src/components/ui/kbd.tsx",
		publicExports: ["Kbd", "KbdGroup"],
		layer: "primitive",
		family: "data",
		renderMode: "server-compatible",
		capabilities: ["ui.navigation.command"],
		qualityProfile: "static-display",
	}),
	defineComponent({
		id: "ui.key-value",
		sourceModule: "src/components/ui/key-value.tsx",
		publicExports: ["KeyValue", "KeyValueList", "keyValueVariants"],
		variants: ["vertical", "horizontal", "inline"],
		sizes: ["sm", "md", "lg"],
		layer: "compound",
		family: "data",
		renderMode: "client",
		capabilities: ["ui.data.key-value"],
		qualityProfile: "interactive-control",
	}),
	defineComponent({
		id: "ui.label",
		sourceModule: "src/components/ui/label.tsx",
		publicExports: ["Label"],
		layer: "primitive",
		family: "forms",
		renderMode: "client",
		capabilities: ["ui.form.field"],
		qualityProfile: "form-control",
	}),
	defineComponent({
		id: "ui.metric-card",
		sourceModule: "src/components/ui/metric-card.tsx",
		publicExports: ["MetricCard", "MetricGrid", "trendVariants"],
		variants: ["up", "down", "neutral"],
		layer: "compound",
		family: "analytics",
		renderMode: "client",
		capabilities: ["ui.data.metric"],
		qualityProfile: "data-visualization",
		tokenFamilies: ["core-surface", "status", "chart"],
	}),
	defineComponent({
		id: "ui.menubar",
		sourceModule: "src/components/ui/menubar.tsx",
		publicExports: [
			"Menubar",
			"MenubarCheckboxItem",
			"MenubarContent",
			"MenubarGroup",
			"MenubarItem",
			"MenubarLabel",
			"MenubarMenu",
			"MenubarPortal",
			"MenubarRadioGroup",
			"MenubarRadioItem",
			"MenubarSeparator",
			"MenubarShortcut",
			"MenubarSub",
			"MenubarSubContent",
			"MenubarSubTrigger",
			"MenubarTrigger",
		],
		variants: ["default", "destructive"],
		layer: "primitive",
		family: "navigation",
		renderMode: "client",
		capabilities: ["ui.navigation.command", "ui.overlay.popover"],
		qualityProfile: "collection-navigation",
	}),
	defineComponent({
		id: "ui.native-select",
		sourceModule: "src/components/ui/native-select.tsx",
		publicExports: [
			"NativeSelect",
			"NativeSelectOptGroup",
			"NativeSelectOption",
		],
		sizes: ["default", "sm"],
		layer: "primitive",
		family: "forms",
		renderMode: "server-compatible",
		capabilities: ["ui.form.choice"],
		qualityProfile: "form-control",
	}),
	defineComponent({
		id: "ui.pagination",
		sourceModule: "src/components/ui/pagination.tsx",
		publicExports: [
			"Pagination",
			"PaginationContent",
			"PaginationEllipsis",
			"PaginationItem",
			"PaginationLink",
			"PaginationNext",
			"PaginationPrevious",
		],
		layer: "primitive",
		family: "navigation",
		renderMode: "server-compatible",
		capabilities: ["ui.navigation.pagination"],
		qualityProfile: "collection-navigation",
	}),
	defineComponent({
		id: "ui.popover",
		sourceModule: "src/components/ui/popover.tsx",
		publicExports: [
			"Popover",
			"PopoverAnchor",
			"PopoverContent",
			"PopoverDescription",
			"PopoverHeader",
			"PopoverTitle",
			"PopoverTrigger",
		],
		layer: "primitive",
		family: "overlays",
		renderMode: "client",
		capabilities: ["ui.overlay.popover"],
		qualityProfile: "interactive-control",
	}),
	defineComponent({
		id: "ui.progress",
		sourceModule: "src/components/ui/progress.tsx",
		publicExports: ["Progress"],
		layer: "primitive",
		family: "feedback",
		renderMode: "client",
		capabilities: ["ui.feedback.async-state"],
		qualityProfile: "async-data",
	}),
	defineComponent({
		id: "ui.radio-group",
		sourceModule: "src/components/ui/radio-group.tsx",
		publicExports: ["RadioGroup", "RadioGroupItem"],
		layer: "primitive",
		family: "forms",
		renderMode: "client",
		capabilities: ["ui.form.choice"],
		qualityProfile: "form-control",
	}),
	defineComponent({
		id: "ui.resizable",
		sourceModule: "src/components/ui/resizable.tsx",
		publicExports: ["ResizableHandle", "ResizablePanel", "ResizablePanelGroup"],
		layer: "primitive",
		family: "layout",
		renderMode: "client",
		capabilities: ["ui.layout.master-detail"],
		qualityProfile: "interactive-control",
	}),
	defineComponent({
		id: "ui.scroll-area",
		sourceModule: "src/components/ui/scroll-area.tsx",
		publicExports: ["ScrollArea", "ScrollBar"],
		layer: "primitive",
		family: "layout",
		renderMode: "client",
		capabilities: ["ui.layout.master-detail"],
		qualityProfile: "interactive-control",
	}),
	defineComponent({
		id: "ui.select",
		sourceModule: "src/components/ui/select.tsx",
		publicExports: [
			"Select",
			"SelectContent",
			"SelectGroup",
			"SelectItem",
			"SelectLabel",
			"SelectScrollDownButton",
			"SelectScrollUpButton",
			"SelectSeparator",
			"SelectTrigger",
			"SelectValue",
		],
		sizes: ["default", "sm"],
		layer: "primitive",
		family: "forms",
		renderMode: "client",
		capabilities: ["ui.form.choice"],
		qualityProfile: "form-control",
	}),
	defineComponent({
		id: "ui.separator",
		sourceModule: "src/components/ui/separator.tsx",
		publicExports: ["Separator"],
		layer: "primitive",
		family: "layout",
		renderMode: "client",
		capabilities: ["ui.layout.section-heading"],
		qualityProfile: "static-display",
	}),
	defineComponent({
		id: "ui.sheet",
		sourceModule: "src/components/ui/sheet.tsx",
		publicExports: [
			"Sheet",
			"SheetClose",
			"SheetContent",
			"SheetDescription",
			"SheetFooter",
			"SheetHeader",
			"SheetTitle",
			"SheetTrigger",
		],
		layer: "primitive",
		family: "overlays",
		renderMode: "client",
		capabilities: ["ui.overlay.drawer"],
		qualityProfile: "modal-overlay",
	}),
	defineComponent({
		id: "ui.sidebar-cookie",
		sourceModule: "src/components/ui/sidebar-cookie.ts",
		publicExports: ["SIDEBAR_COOKIE_MAX_AGE", "SIDEBAR_COOKIE_NAME"],
		layer: "foundation",
		family: "navigation",
		renderMode: "server-compatible",
		capabilities: ["ui.navigation.workspace"],
		qualityProfile: "static-display",
	}),
	defineComponent({
		id: "ui.sidebar",
		sourceModule: "src/components/ui/sidebar.tsx",
		publicExports: [
			"Sidebar",
			"SidebarContent",
			"SidebarFooter",
			"SidebarGroup",
			"SidebarGroupAction",
			"SidebarGroupContent",
			"SidebarGroupLabel",
			"SidebarHeader",
			"SidebarInput",
			"SidebarInset",
			"SidebarMenu",
			"SidebarMenuAction",
			"SidebarMenuBadge",
			"SidebarMenuButton",
			"SidebarMenuItem",
			"SidebarMenuSkeleton",
			"SidebarMenuSub",
			"SidebarMenuSubButton",
			"SidebarMenuSubItem",
			"SidebarProvider",
			"SidebarRail",
			"SidebarSeparator",
			"SidebarTrigger",
			"useSidebar",
		],
		variants: ["sidebar", "floating", "inset", "default", "outline"],
		sizes: ["default", "sm", "lg"],
		layer: "compound",
		family: "navigation",
		renderMode: "client",
		capabilities: ["ui.navigation.workspace"],
		qualityProfile: "collection-navigation",
	}),
	defineComponent({
		id: "ui.skeleton",
		sourceModule: "src/components/ui/skeleton.tsx",
		publicExports: ["Skeleton"],
		layer: "primitive",
		family: "feedback",
		renderMode: "server-compatible",
		capabilities: ["ui.feedback.async-state"],
		qualityProfile: "static-display",
	}),
	defineComponent({
		id: "ui.slider",
		sourceModule: "src/components/ui/slider.tsx",
		publicExports: ["Slider"],
		layer: "primitive",
		family: "forms",
		renderMode: "client",
		capabilities: ["ui.form.numeric"],
		qualityProfile: "form-control",
	}),
	defineComponent({
		id: "ui.sonner",
		sourceModule: "src/components/ui/sonner.tsx",
		publicExports: ["Toaster"],
		layer: "primitive",
		family: "feedback",
		renderMode: "client",
		capabilities: ["ui.feedback.toast"],
		qualityProfile: "status-feedback",
		tokenFamilies: ["core-surface", "status"],
	}),
	defineComponent({
		id: "ui.spinner",
		sourceModule: "src/components/ui/spinner.tsx",
		publicExports: ["Spinner", "spinnerVariants"],
		variants: ["default", "secondary", "destructive"],
		sizes: ["sm", "md", "lg", "xl"],
		layer: "primitive",
		family: "feedback",
		renderMode: "client",
		capabilities: ["ui.feedback.async-state"],
		qualityProfile: "async-data",
	}),
	defineComponent({
		id: "ui.status-badge",
		sourceModule: "src/components/ui/status-badge.tsx",
		publicExports: ["StatusBadge", "statusBadgeVariants"],
		variants: ["success", "pending", "error", "warning", "inactive", "active"],
		sizes: ["sm", "md", "lg"],
		layer: "compound",
		family: "feedback",
		renderMode: "client",
		capabilities: ["ui.feedback.status"],
		qualityProfile: "status-feedback",
		tokenFamilies: ["status", "focus"],
	}),
	defineComponent({
		id: "ui.switch",
		sourceModule: "src/components/ui/switch.tsx",
		publicExports: ["Switch"],
		sizes: ["default", "sm"],
		layer: "primitive",
		family: "forms",
		renderMode: "client",
		capabilities: ["ui.form.boolean"],
		qualityProfile: "form-control",
	}),
	defineComponent({
		id: "ui.table",
		sourceModule: "src/components/ui/table.tsx",
		publicExports: [
			"Table",
			"TableBody",
			"TableCaption",
			"TableCell",
			"TableFooter",
			"TableHead",
			"TableHeader",
			"TableRow",
		],
		layer: "primitive",
		family: "data",
		renderMode: "client",
		capabilities: ["ui.data.table"],
		qualityProfile: "static-display",
		tokenFamilies: ["core-surface", "data"],
	}),
	defineComponent({
		id: "ui.tabs",
		sourceModule: "src/components/ui/tabs.tsx",
		publicExports: [
			"Tabs",
			"TabsContent",
			"TabsList",
			"TabsTrigger",
			"tabsListVariants",
		],
		variants: ["default", "line"],
		layer: "primitive",
		family: "navigation",
		renderMode: "client",
		capabilities: ["ui.navigation.tabs"],
		qualityProfile: "collection-navigation",
	}),
	defineComponent({
		id: "ui.textarea",
		sourceModule: "src/components/ui/textarea.tsx",
		publicExports: ["Textarea"],
		layer: "primitive",
		family: "forms",
		renderMode: "server-compatible",
		capabilities: ["ui.form.multiline"],
		qualityProfile: "form-control",
	}),
	defineComponent({
		id: "ui.toggle-group",
		sourceModule: "src/components/ui/toggle-group.tsx",
		publicExports: ["ToggleGroup", "ToggleGroupItem"],
		variants: ["default", "outline"],
		sizes: ["default", "sm", "lg"],
		layer: "primitive",
		family: "actions",
		renderMode: "client",
		capabilities: ["ui.action.group"],
		qualityProfile: "interactive-control",
	}),
	defineComponent({
		id: "ui.toggle",
		sourceModule: "src/components/ui/toggle.tsx",
		publicExports: ["Toggle", "toggleVariants"],
		variants: ["default", "outline"],
		sizes: ["default", "sm", "lg"],
		layer: "primitive",
		family: "actions",
		renderMode: "client",
		capabilities: ["ui.action.trigger"],
		qualityProfile: "interactive-control",
	}),
	defineComponent({
		id: "ui.tooltip",
		sourceModule: "src/components/ui/tooltip.tsx",
		publicExports: [
			"Tooltip",
			"TooltipContent",
			"TooltipProvider",
			"TooltipTrigger",
		],
		layer: "primitive",
		family: "overlays",
		renderMode: "client",
		capabilities: ["ui.overlay.popover"],
		qualityProfile: "interactive-control",
	}),
	defineComponent({
		id: "ui.async-state",
		sourceModule: "src/components/ui/async-state.tsx",
		publicExports: ["AsyncState"],
		variants: ["loading", "empty", "filtered-empty", "error", "ready"],
		layer: "compound",
		family: "feedback",
		renderMode: "server-compatible",
		capabilities: ["ui.feedback.async-state"],
		qualityProfile: "async-data",
	}),
	defineComponent({
		id: "ui.bulk-action-bar",
		sourceModule: "src/components/ui/bulk-action-bar.tsx",
		publicExports: ["BulkActionBar"],
		layer: "compound",
		family: "data",
		renderMode: "server-compatible",
		capabilities: ["ui.data.bulk-actions"],
		qualityProfile: "static-display",
	}),
	defineComponent({
		id: "ui.change-diff",
		sourceModule: "src/components/ui/change-diff.tsx",
		publicExports: ["ChangeDiff", "ChangeDiffRow"],
		layer: "compound",
		family: "workflow",
		renderMode: "server-compatible",
		capabilities: ["ui.workflow.diff"],
		qualityProfile: "workflow-history",
		tokenFamilies: ["core-surface", "status"],
	}),
	defineComponent({
		id: "ui.chart",
		sourceModule: "src/components/ui/chart.tsx",
		publicExports: [
			"ChartConfig",
			"ChartContainer",
			"ChartLegend",
			"ChartLegendContent",
			"ChartStyle",
			"ChartTooltip",
			"ChartTooltipContent",
		],
		layer: "compound",
		family: "analytics",
		renderMode: "client",
		capabilities: ["ui.analytics.chart"],
		qualityProfile: "data-visualization",
		tokenFamilies: ["chart", "core-surface", "focus"],
	}),
	defineComponent({
		id: "ui.column-visibility-menu",
		sourceModule: "src/components/ui/column-visibility-menu.tsx",
		publicExports: ["ColumnVisibilityMenu", "ColumnVisibilityOption"],
		layer: "compound",
		family: "data",
		renderMode: "client",
		capabilities: ["ui.data.column-visibility"],
		qualityProfile: "interactive-control",
	}),
	defineComponent({
		id: "ui.date-time-picker",
		sourceModule: "src/components/ui/date-time-picker.tsx",
		publicExports: ["DateTimePicker", "DateTimePickerProps"],
		layer: "compound",
		family: "forms",
		renderMode: "client",
		capabilities: ["ui.form.datetime"],
		qualityProfile: "form-control",
	}),
	defineComponent({
		id: "ui.file-upload",
		sourceModule: "src/components/ui/file-upload.tsx",
		publicExports: [
			"AttachmentList",
			"AttachmentListProps",
			"FileUpload",
			"FileUploadProps",
			"UiAttachment",
		],
		variants: ["single", "multiple"],
		layer: "compound",
		family: "forms",
		renderMode: "client",
		capabilities: ["ui.form.file"],
		qualityProfile: "form-control",
	}),
	defineComponent({
		id: "ui.filter-bar",
		sourceModule: "src/components/ui/filter-bar.tsx",
		publicExports: ["FilterBar", "FilterBarActions", "FilterBarGroup"],
		layer: "compound",
		family: "data",
		renderMode: "server-compatible",
		capabilities: ["ui.data.filter"],
		qualityProfile: "static-display",
	}),
	defineComponent({
		id: "ui.master-detail",
		sourceModule: "src/components/ui/master-detail.tsx",
		publicExports: [
			"MasterDetail",
			"MasterDetailPrimary",
			"MasterDetailSecondary",
		],
		layer: "pattern",
		family: "layout",
		renderMode: "client",
		capabilities: ["ui.layout.master-detail"],
		qualityProfile: "interactive-control",
	}),
	defineComponent({
		id: "ui.numeric-input",
		sourceModule: "src/components/ui/numeric-input.tsx",
		publicExports: [
			"MoneyInput",
			"NumberInput",
			"NumericInputProps",
			"PercentInput",
			"QuantityInput",
		],
		layer: "compound",
		family: "forms",
		renderMode: "client",
		capabilities: [
			"ui.form.numeric",
			"ui.form.money",
			"ui.form.quantity",
			"ui.form.percent",
		],
		qualityProfile: "form-control",
	}),
	defineComponent({
		id: "ui.page-header",
		sourceModule: "src/components/ui/page-header.tsx",
		publicExports: [
			"EntityHeader",
			"PageHeader",
			"PageHeaderActions",
			"PageHeaderDescription",
			"PageHeaderHeading",
			"SectionHeader",
		],
		layer: "compound",
		family: "layout",
		renderMode: "server-compatible",
		capabilities: [
			"ui.layout.page-heading",
			"ui.layout.section-heading",
			"ui.layout.entity-heading",
		],
		qualityProfile: "static-display",
	}),
	defineComponent({
		id: "ui.saved-view-select",
		sourceModule: "src/components/ui/saved-view-select.tsx",
		publicExports: ["SavedViewOption", "SavedViewSelect"],
		layer: "compound",
		family: "data",
		renderMode: "client",
		capabilities: ["ui.data.saved-view"],
		qualityProfile: "form-control",
	}),
	defineComponent({
		id: "ui.search-field",
		sourceModule: "src/components/ui/search-field.tsx",
		publicExports: ["SearchField"],
		layer: "compound",
		family: "forms",
		renderMode: "client",
		capabilities: ["ui.data.filter", "ui.form.text"],
		qualityProfile: "form-control",
	}),
	defineComponent({
		id: "ui.stepper",
		sourceModule: "src/components/ui/stepper.tsx",
		publicExports: ["Stepper", "StepperStep"],
		layer: "compound",
		family: "workflow",
		renderMode: "server-compatible",
		capabilities: ["ui.workflow.stepper"],
		qualityProfile: "workflow-history",
		tokenFamilies: ["core-surface", "status"],
	}),
	defineComponent({
		id: "ui.timeline",
		sourceModule: "src/components/ui/timeline.tsx",
		publicExports: [
			"AuditTrail",
			"AuditTrailEntry",
			"Timeline",
			"TimelineEntry",
		],
		layer: "compound",
		family: "workflow",
		renderMode: "server-compatible",
		capabilities: ["ui.workflow.timeline", "ui.workflow.audit"],
		qualityProfile: "workflow-history",
		tokenFamilies: ["core-surface", "status"],
	}),
	defineComponent({
		id: "ui.toolbar",
		sourceModule: "src/components/ui/toolbar.tsx",
		publicExports: ["Toolbar", "ToolbarGroup", "ToolbarSeparator"],
		layer: "compound",
		family: "layout",
		renderMode: "server-compatible",
		capabilities: ["ui.layout.toolbar"],
		qualityProfile: "static-display",
	}),
	defineComponent({
		id: "ui.tree-view",
		sourceModule: "src/components/ui/tree-view.tsx",
		publicExports: ["TreeNode", "TreeView"],
		layer: "compound",
		family: "data",
		renderMode: "client",
		capabilities: ["ui.data.tree"],
		qualityProfile: "collection-navigation",
	}),
] satisfies readonly UiComponentMetadata[];

function capability(input: {
	id: UiCapabilityId;
	family: UiFamily;
	description: string;
	providers: readonly UiComponentMetadata["id"][];
}) {
	return { ...input, lifecycle: "verified" } as const;
}

const capabilities = [
	capability({
		id: "ui.foundation.theme",
		family: "layout",
		description: "Shared light and dark semantic theme.",
		providers: ["ui.card"],
	}),
	capability({
		id: "ui.foundation.status",
		family: "feedback",
		description: "Accessible ERP status roles and pairings.",
		providers: ["ui.status-badge", "ui.alert"],
	}),
	capability({
		id: "ui.action.trigger",
		family: "actions",
		description: "Accessible action trigger.",
		providers: ["ui.button", "ui.toggle"],
	}),
	capability({
		id: "ui.action.group",
		family: "actions",
		description: "Related action grouping.",
		providers: ["ui.button-group", "ui.toggle-group"],
	}),
	capability({
		id: "ui.form.field",
		family: "forms",
		description: "Label, help, required, and error association.",
		providers: ["ui.field", "ui.form-field"],
	}),
	capability({
		id: "ui.form.text",
		family: "forms",
		description: "Single-line text entry.",
		providers: ["ui.input", "ui.form-field", "ui.search-field"],
	}),
	capability({
		id: "ui.form.multiline",
		family: "forms",
		description: "Multi-line text entry.",
		providers: ["ui.textarea", "ui.form-field"],
	}),
	capability({
		id: "ui.form.boolean",
		family: "forms",
		description: "Boolean choice controls.",
		providers: ["ui.checkbox", "ui.switch"],
	}),
	capability({
		id: "ui.form.choice",
		family: "forms",
		description: "Bounded single or multiple choice.",
		providers: ["ui.select", "ui.native-select", "ui.radio-group"],
	}),
	capability({
		id: "ui.form.search-choice",
		family: "forms",
		description: "Searchable controlled choice.",
		providers: ["ui.combobox"],
	}),
	capability({
		id: "ui.form.date",
		family: "forms",
		description: "Date selection.",
		providers: ["ui.calendar", "ui.date-picker"],
	}),
	capability({
		id: "ui.form.date-range",
		family: "forms",
		description: "Date range selection.",
		providers: ["ui.date-picker"],
	}),
	capability({
		id: "ui.form.datetime",
		family: "forms",
		description: "Date and time selection without transport policy.",
		providers: ["ui.date-time-picker"],
	}),
	capability({
		id: "ui.form.numeric",
		family: "forms",
		description: "Locale-aware numeric entry.",
		providers: ["ui.numeric-input", "ui.slider"],
	}),
	capability({
		id: "ui.form.money",
		family: "forms",
		description: "Currency-labelled decimal entry.",
		providers: ["ui.numeric-input"],
	}),
	capability({
		id: "ui.form.quantity",
		family: "forms",
		description: "Unit-labelled quantity entry.",
		providers: ["ui.numeric-input"],
	}),
	capability({
		id: "ui.form.percent",
		family: "forms",
		description: "Percentage entry.",
		providers: ["ui.numeric-input"],
	}),
	capability({
		id: "ui.form.file",
		family: "forms",
		description: "Transport-neutral file selection and attachment display.",
		providers: ["ui.file-upload"],
	}),
	capability({
		id: "ui.data.table",
		family: "data",
		description: "Controlled ERP tabular presentation and interaction.",
		providers: ["ui.table", "ui.data-table"],
	}),
	capability({
		id: "ui.data.filter",
		family: "data",
		description: "Search and structured filter composition.",
		providers: ["ui.filter-bar", "ui.search-field", "ui.data-table"],
	}),
	capability({
		id: "ui.data.saved-view",
		family: "data",
		description:
			"Controlled saved-view selection without persistence ownership.",
		providers: ["ui.saved-view-select"],
	}),
	capability({
		id: "ui.data.column-visibility",
		family: "data",
		description: "Controlled table column visibility.",
		providers: ["ui.column-visibility-menu", "ui.data-table"],
	}),
	capability({
		id: "ui.data.bulk-actions",
		family: "data",
		description: "Selection-aware bulk action presentation.",
		providers: ["ui.bulk-action-bar", "ui.data-table"],
	}),
	capability({
		id: "ui.data.tree",
		family: "data",
		description: "Keyboard-operable hierarchy presentation.",
		providers: ["ui.tree-view"],
	}),
	capability({
		id: "ui.data.key-value",
		family: "data",
		description: "Dense record detail presentation.",
		providers: ["ui.key-value"],
	}),
	capability({
		id: "ui.data.label",
		family: "data",
		description:
			"Compact categorical, attribute, and non-authoritative metadata labels.",
		providers: ["ui.badge"],
	}),
	capability({
		id: "ui.data.metric",
		family: "analytics",
		description: "Metric cards and responsive metric groups.",
		providers: ["ui.metric-card"],
	}),
	capability({
		id: "ui.navigation.workspace",
		family: "navigation",
		description: "Responsive ERP workspace navigation.",
		providers: ["ui.sidebar"],
	}),
	capability({
		id: "ui.navigation.breadcrumb",
		family: "navigation",
		description: "Hierarchical route context.",
		providers: ["ui.breadcrumb"],
	}),
	capability({
		id: "ui.navigation.tabs",
		family: "navigation",
		description: "Related view navigation.",
		providers: ["ui.tabs"],
	}),
	capability({
		id: "ui.navigation.pagination",
		family: "navigation",
		description: "Controlled paged collection navigation.",
		providers: ["ui.pagination", "ui.data-table"],
	}),
	capability({
		id: "ui.navigation.command",
		family: "navigation",
		description: "Keyboard-first command discovery.",
		providers: ["ui.command", "ui.kbd", "ui.menubar"],
	}),
	capability({
		id: "ui.overlay.modal",
		family: "overlays",
		description: "Modal and destructive confirmation flows.",
		providers: ["ui.dialog", "ui.alert-dialog"],
	}),
	capability({
		id: "ui.overlay.drawer",
		family: "overlays",
		description: "Task-focused side sheet and gesture-aware drawer surfaces.",
		providers: ["ui.sheet", "ui.drawer"],
	}),
	capability({
		id: "ui.overlay.popover",
		family: "overlays",
		description: "Anchored transient content and menus.",
		providers: [
			"ui.popover",
			"ui.dropdown-menu",
			"ui.context-menu",
			"ui.menubar",
			"ui.tooltip",
			"ui.hover-card",
		],
	}),
	capability({
		id: "ui.feedback.alert",
		family: "feedback",
		description: "Inline notice and form feedback.",
		providers: ["ui.alert", "ui.form-error"],
	}),
	capability({
		id: "ui.feedback.toast",
		family: "feedback",
		description: "Transient application notification.",
		providers: ["ui.sonner"],
	}),
	capability({
		id: "ui.feedback.async-state",
		family: "feedback",
		description: "Loading, empty, filtered-empty, error, and ready states.",
		providers: [
			"ui.async-state",
			"ui.empty",
			"ui.spinner",
			"ui.skeleton",
			"ui.progress",
			"ui.data-table",
		],
	}),
	capability({
		id: "ui.feedback.status",
		family: "feedback",
		description: "Accessible lifecycle and health status display.",
		providers: ["ui.status-badge"],
	}),
	capability({
		id: "ui.workflow.stepper",
		family: "workflow",
		description: "Ordered workflow progress.",
		providers: ["ui.stepper"],
	}),
	capability({
		id: "ui.workflow.timeline",
		family: "workflow",
		description: "Chronological workflow history.",
		providers: ["ui.timeline"],
	}),
	capability({
		id: "ui.workflow.audit",
		family: "workflow",
		description: "Actor and event audit presentation.",
		providers: ["ui.timeline"],
	}),
	capability({
		id: "ui.workflow.diff",
		family: "workflow",
		description: "Before-and-after value comparison.",
		providers: ["ui.change-diff"],
	}),
	capability({
		id: "ui.analytics.chart",
		family: "analytics",
		description: "Accessible token-driven chart composition.",
		providers: ["ui.chart"],
	}),
	capability({
		id: "ui.layout.page-heading",
		family: "layout",
		description: "Consistent page identity and actions.",
		providers: ["ui.page-header"],
	}),
	capability({
		id: "ui.layout.section-heading",
		family: "layout",
		description: "Consistent section identity and actions.",
		providers: ["ui.page-header", "ui.card"],
	}),
	capability({
		id: "ui.layout.entity-heading",
		family: "layout",
		description: "Record identity, metadata, and status.",
		providers: ["ui.page-header"],
	}),
	capability({
		id: "ui.layout.toolbar",
		family: "layout",
		description: "Responsive related-control grouping.",
		providers: ["ui.toolbar"],
	}),
	capability({
		id: "ui.layout.master-detail",
		family: "layout",
		description: "Responsive master-detail workspace.",
		providers: ["ui.master-detail", "ui.resizable", "ui.scroll-area"],
	}),
	capability({
		id: "ui.layout.disclosure",
		family: "layout",
		description: "Progressive disclosure of secondary content.",
		providers: ["ui.accordion", "ui.collapsible"],
	}),
];

const qualityProfiles = UI_QUALITY_PROFILE_IDS.map((id) => ({
	id,
	requiredStates: statesByProfile[id],
	requiredEvidence: evidenceByProfile[id].map((item) => item.kind),
}));

const surfaceProfiles = [
	{
		id: "workspace-shell",
		capabilities: [
			"ui.navigation.workspace",
			"ui.navigation.breadcrumb",
			"ui.layout.page-heading",
		],
	},
	{
		id: "dashboard-metrics",
		capabilities: [
			"ui.data.metric",
			"ui.analytics.chart",
			"ui.feedback.async-state",
		],
	},
	{
		id: "record-list",
		capabilities: [
			"ui.data.table",
			"ui.data.filter",
			"ui.navigation.pagination",
			"ui.feedback.async-state",
		],
	},
	{
		id: "record-detail",
		capabilities: [
			"ui.layout.entity-heading",
			"ui.data.key-value",
			"ui.feedback.status",
		],
	},
	{
		id: "record-editor",
		capabilities: [
			"ui.form.field",
			"ui.form.text",
			"ui.form.choice",
			"ui.overlay.drawer",
			"ui.feedback.alert",
		],
	},
	{
		id: "transaction-lines",
		capabilities: [
			"ui.data.table",
			"ui.form.numeric",
			"ui.form.money",
			"ui.form.quantity",
		],
	},
	{
		id: "search-filtering",
		capabilities: [
			"ui.data.filter",
			"ui.data.saved-view",
			"ui.data.column-visibility",
		],
	},
	{
		id: "bulk-operations",
		capabilities: [
			"ui.data.bulk-actions",
			"ui.feedback.async-state",
			"ui.overlay.modal",
		],
	},
	{
		id: "lifecycle-workflow",
		capabilities: [
			"ui.workflow.stepper",
			"ui.workflow.timeline",
			"ui.feedback.status",
		],
	},
	{
		id: "approval-workflow",
		capabilities: [
			"ui.workflow.timeline",
			"ui.workflow.diff",
			"ui.overlay.modal",
			"ui.feedback.status",
		],
	},
	{
		id: "audit-history",
		capabilities: ["ui.workflow.audit", "ui.workflow.diff", "ui.data.filter"],
	},
	{
		id: "documents-attachments",
		capabilities: ["ui.form.file", "ui.feedback.async-state"],
	},
	{
		id: "hierarchical-data",
		capabilities: ["ui.data.tree", "ui.layout.master-detail"],
	},
	{
		id: "analytics-charts",
		capabilities: ["ui.analytics.chart", "ui.data.metric"],
	},
	{
		id: "async-permission-states",
		capabilities: [
			"ui.feedback.async-state",
			"ui.feedback.alert",
			"ui.action.trigger",
		],
	},
] as const;

const COMMON_PROFILES = [
	"workspace-shell",
	"record-list",
	"record-detail",
	"record-editor",
	"search-filtering",
	"lifecycle-workflow",
	"audit-history",
	"async-permission-states",
] as const satisfies readonly UiSurfaceProfileId[];

const TRANSACTION_PROFILES = [
	...COMMON_PROFILES,
	"dashboard-metrics",
	"transaction-lines",
	"bulk-operations",
	"documents-attachments",
	"analytics-charts",
] as const satisfies readonly UiSurfaceProfileId[];

const GOVERNED_PROFILES = [
	...COMMON_PROFILES,
	"dashboard-metrics",
	"approval-workflow",
	"bulk-operations",
	"documents-attachments",
	"hierarchical-data",
	"analytics-charts",
] as const satisfies readonly UiSurfaceProfileId[];

function moduleCoverage(
	moduleId: ErpModuleId,
	profiles: readonly UiSurfaceProfileId[],
) {
	return { moduleId, profiles };
}

const moduleCoverageEntries = [
	moduleCoverage("accounting", TRANSACTION_PROFILES),
	moduleCoverage("corporate-administration", GOVERNED_PROFILES),
	moduleCoverage("fulfillment", TRANSACTION_PROFILES),
	moduleCoverage("human-resources", GOVERNED_PROFILES),
	moduleCoverage("inventory", [...TRANSACTION_PROFILES, "hierarchical-data"]),
	moduleCoverage("master-data", GOVERNED_PROFILES),
	moduleCoverage("payables", TRANSACTION_PROFILES),
	moduleCoverage("payments", TRANSACTION_PROFILES),
	moduleCoverage("payroll", [...TRANSACTION_PROFILES, "approval-workflow"]),
	moduleCoverage("purchasing", [...TRANSACTION_PROFILES, "approval-workflow"]),
	moduleCoverage("receivables", TRANSACTION_PROFILES),
	moduleCoverage("receiving", TRANSACTION_PROFILES),
	moduleCoverage("sales", TRANSACTION_PROFILES),
];

export const UI_SYSTEM_CATALOG = {
	baseline: {
		id: "erp-ui-v1",
		version: 1,
		state: "locked",
		lockedOn: "2026-07-28",
	},
	components,
	capabilities,
	qualityProfiles,
	surfaceProfiles,
	moduleCoverage: moduleCoverageEntries,
	tokenFamilies: [
		{
			id: "core-surface",
			variables: [
				"--background",
				"--foreground",
				"--card",
				"--card-foreground",
				"--popover",
				"--popover-foreground",
				"--border",
				"--muted",
				"--muted-foreground",
			],
			requiredThemes: "both",
		},
		{
			id: "status",
			variables: [
				"--success-subtle",
				"--success-subtle-foreground",
				"--success-border",
				"--warning-subtle",
				"--warning-subtle-foreground",
				"--warning-border",
				"--info-subtle",
				"--info-subtle-foreground",
				"--info-border",
				"--destructive-subtle",
				"--destructive-subtle-foreground",
				"--destructive-border",
			],
			requiredThemes: "both",
		},
		{
			id: "data",
			variables: [
				"--table-row-hover",
				"--table-stripe",
				"--surface-sunken",
				"--surface-raised",
			],
			requiredThemes: "both",
		},
		{
			id: "control",
			variables: [
				"--control-fill",
				"--control-fill-hover",
				"--control-fill-strong",
				"--control-height",
				"--control-height-sm",
			],
			requiredThemes: "both",
		},
		{
			id: "focus",
			variables: [
				"--ring-focus",
				"--ring-destructive-focus",
				"--ring-destructive-focus-strong",
			],
			requiredThemes: "both",
		},
		{
			id: "chart",
			variables: [
				"--chart-1",
				"--chart-2",
				"--chart-3",
				"--chart-4",
				"--chart-5",
			],
			requiredThemes: "both",
		},
		{
			id: "motion",
			variables: [
				"--duration-instant",
				"--duration-fast",
				"--duration-normal",
				"--duration-slow",
				"--ease-standard",
				"--ease-enter",
				"--ease-exit",
			],
			requiredThemes: "both",
		},
	],
} satisfies UiCatalog;
